### ISSUE TITLE
adding advection and diffusion kernel bugs in parcels 2.2.2

### ISSUE THREAD

**Issue by HandmannP** [OceanParcels/parcels#1004]
I am trying to run experiments with uniform diffusion - using the DiffusionUniformKh kernel wich is
supposed to be usable with an advection kernel of my choice - though it gives me a type error:

 pset.execute(AdvectionRK4 + DiffusionUniformKh,
runtime=timedelta(days=365*adv_time),
dt=timedelta(minutes=dt*run_dir),

TypeError: unsupported operand type(s) for +: 'function' and 'function'

Am I using it wrong? Do you have an Idea how to make it work?

**Comment by reint-fischer** [comment]
Hi @HandmannP,

If you want to concatenate kernels, at least one of the functions has to be loaded as a kernel:
```
kernels = pset.Kernel(AdvectionRK4) + DiffusionUniformKh
pset.execute(kernels,
                     runtime=timedelta(days=365adv_time),
                     dt=timedelta(minutes=dtrun_dir)
```

**Comment by HandmannP** [comment]
@reint-fischer Thanks so much - this did the trick!
