### ISSUE TITLE
How can I index the previous timestep's latitude and longitude

### ISSUE THREAD

**Issue by hkhirsh** [OceanParcels/parcels#1019]
I am trying to write an unbeaching kernel that will essentially "bounce" a particle back to it's previous position then advect it using a different (alongshore) velocity field. Is there a way to index the previous longitude and latitude so I can reset the coordinates? 

particle.lon = #index previous longitude here
particle.lat = #index previous latitude here

I've been playing with indexing U and V using xi, yi, zi, and ti, but there doesn't seem to be a way to find a straightforward way to index coordinates inside a kernel.

**Comment by reint-fischer** [comment]
Hi @hkhirsh,

If you create a subclass of a `JITParticle` or `ScipyParticle` like in `In[26]` of [this tutorial](https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/parcels_tutorial.ipynb), you can add a `Variable` like `prev_lat` and `prev_lon`:
```
class UnbeachingParticle(JITParticle):
    prev_lat = Variable('prev_lat', initial=0., to_write=False)  
    prev_lon = Variable('prev_lon', initial=0., to_write=False)  
```
You can then store the coordinates before advecting in a kernel using 
```
particle.prev_lat = particle.lat
particle.prev_lon = particle.lon
```
The array of particle variables is created after the simulation by combining the output written at different timesteps and therefore not available within the simulation.

Does this answer your question?

**Comment by hkhirsh** [comment]
Hi @reint-fischer, 

Thank you! I think this did answer my question. I was able to store the coordinates in my advection kernel (before advecting) then call on them in a "bounce" kernel in order to send particles back to their previous position. 

It seems I have another unbeaching issue now. I can tell that the "bounce" and "unbeaching" kernels are working because I no longer have particles stuck in the middle of my landmass (Guam) or passing over/through the landmass entirely. But it looks like particles build up on the landward side of the outermost "land" cells. This doesn't make sense to me because my beaching detection kernel should be recognizing those positions as zero velocity and tagging the particles to bounce back out. 
![Screen Shot 2021-04-29 at 3 50 00 PM](https://user-images.githubusercontent.com/79546530/116633133-94242d80-a90d-11eb-9669-9b8bcb845227.png)

My kernel logic is as follows: 
1. Advection (any non-beached particle advects for one timestep)
2. Diffusion (any particle that has advected now diffuses)
3. BeachTesting (identified beached particles if u=0.00 and v=0.00)
4. Bounce (beached particles are returned to their previous coordinates)
5. UnbeachAlongshore (particles that were bounced now advect using a new velocity field where I have modified the cells closest to land so that particles advect with a longshore current. Basically if the particles are close enough to land to beach with the original velocity field then I replace the original advection with a new advection step that uses a velocity field that redirects particles alongshore).

I'm new to both Python and OceanParcels, so I apologize if I'm missing something really straightforward! 

Thank you for your help with the "bounce" to the previous coordinates!

**Comment by daanreijnders** [comment]
From the figure you show, I think it has to do with testing when the particle is on land. Whether you're on land is now tested using u=0 **_and_** v=0, but depending on your type of Arakawa grid, the interpolation may cause velocities to be nonzero even when you're already on land. You could try to construct a new 2D stationary field corresponding to a land mask. If you then use nearest-neighbor interpolation specifically on that land mask field, you will have a more accurate test of whether you're on land. When adding a field, you can individually pass an `interp_method` argument and set that to `nearest` for your mask.

**Comment by CKehl** [comment]
I agree with @reint-fischer here - recently created a script for some training data for my MSc student where I needed to skip-out the on-land particles, and the most robust coming out was the particle.prev_lat <-> particle.lat and particle.prev_lon <-> particle.lon check.

"""
class TemporalParticles_JIT(JITParticle):
    valid = Variable('valid', dtype=np.int32, initial=-1, to_write=True)
    age = Variable('age', dtype=np.float64, initial=0.0, to_write=True)
    pre_lon = Variable('pre_lon', dtype=np.float32, initial=0., to_write=False)
    pre_lat = Variable('pre_lat', dtype=np.float32, initial=0., to_write=False)

class TemporalParticles_SciPy(ScipyParticle):
    valid = Variable('valid', dtype=np.int32, initial=-1, to_write=True)
    age = Variable('age', dtype=np.float64, initial=0.0, to_write=True)
    pre_lon = Variable('pre_lon', dtype=np.float32, initial=0., to_write=False)
    pre_lat = Variable('pre_lat', dtype=np.float32, initial=0., to_write=False)

def TemporalAging(particle, fieldset, time):
    if particle.state == StateCode.Evaluate:
        particle.age = particle.age + math.fabs(particle.dt)

def validate(particle, fieldset, time):
    if particle.valid < 0:
        particle.pre_lon = particle.lon
        particle.pre_lat = particle.lat
        if (math.isnan(particle.time) == True):
            particle.valid = 0
        else:
            particle.valid = 1
    else:
        if ((particle.lon == particle.pre_lon) and (particle.lat == particle.pre_lat)):
            particle.valid = 0
        else:
            if(math.isnan(particle.time) == True):
                particle.valid = 0
            else:
                particle.valid = 1
        particle.pre_lon = particle.lon
        particle.pre_lat = particle.lat
"""

That's the actual function I used.

@daanreijnders (u==0, v==0) may also work, but it's really hard to track what xarray does or how it converts the *fill value* in the file to array values in the numpy array accessed by Parcels. As long as that conversion is not clear to me, I'd personally refrain from assuming (u==0, v==0) on land.
