### ISSUE TITLE
Parcels with multiple files and different S-levels for U, V and W speeds

### ISSUE THREAD

**Issue by mathildecha** [OceanParcels/parcels#1024]
Hello,

We are trying to use Parcels with the output of the French hydrodynamic model MARS (Ifremer).
I send you herewith a small example of output and tested code.
We want to simulate the dispersion of oyster larvae in Polynesian lagoons.
The Mars model uses an Arakawa C grid identical to Nemo.
It uses sigma levels, whose depths vary in time according to XE(sea surface height).
The U and V velocities are on 50 sigma levels (mid layer sigma); and the W velocities are on 51 sigmaW levels (interface sigma) which frames the 50 sigma.
Moreover, as the files are very large, we cut them with several files every 100 time steps (for a first test).
We have several questions: 

1/ It seems that we should have the same number of sigma levels for U, V and W in Parcels. We have 2 ideas for this:
- use the 50 sigma levels of U and V, and interpolate the W values on these 50 sigma levels.
or
-use directly the sigma levels of W without the bottom level (we have seen this on the forum), and use directly all the variables U, V and W without modifying them. (but is this a problem for U and V?).
What do you think about it?

In the following link, I give a Mars output, to which I have added 2 variables: the depths of the 50 sigma levels for U and V (Zsigma) and the W velocities interpolated on these levels (Winterp).
https://we.tl/t-94s8hUiLSn

2/ As we have several files and sigma levels that vary with time, we used the tutorial "timevaryingdepthdimensions.ipynb" and we manage to run it:  code attached. 
(Otherwise, if we use the other examples, we get an error: "Vertically adaptive meshes not implemented for from_netcdf()".
Does this code seem correct to you ?
We notice that the fieldset.U.grid.depth.shape has unexpected dimensions over time, but this does not seem to be a problem in the results.

3/ Does parcels manage the case where a particle meets a high point (reef, coast, pinnacles)?
Does parcels manage the case where a particle rises and risks exceeding the water surface?

Thank you very much for your answer !
[parcels_github2.txt](https://github.com/OceanParcels/parcels/files/6424856/parcels_github2.txt)

**Comment by reint-fischer** [comment]
Hi @mathildecha ,

those are some good questions! 

1. The standard vertical discretization [parcels assumes for C grids](https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/tutorial_nemo_3D.ipynb) is with the w-value associated with a cell at the top of the cell, so your second suggestion (without the bottom level) works best with the current implementation. Interpolation invalidates the assumed vertical discretization and is therefore discouraged. I think this extra layer of W-depths is worth looking into/implementing correctly, so I might have a look at this: feel free to share ideas or suggestions!
2. The timevarying depth dimensions should work, but I do not use them myself and I don't have the time unfortunately to check if your code executes correctly. Maybe you can get involved in [this discussion](https://github.com/OceanParcels/parcels/discussions/1021) to see what others have done? 
3. I believe there are many cases is time-varying sigma grids in which these cases occur. To my knowledge parcels does not manage these and you might want to check for these cases in your kernels and/or use recovery kernels. Maybe @cjongedijk can comment on this when she is back?

Hope this helps,

**Comment by mathildecha** [comment]
Hello,
Thank you very much for your answer and these elements, which help us to progress!
My apologies for the delay in answering! 
Concerning point 1: We start with the second suggestion, and we define the fieldset with sigma-W levels (without the bottom level).

But in our Mars model outputs, the U and V velocities are defined on sigma-U levels; which are located between 2 sigma-W levels. 
So we do not explicitly integrate these sigma-U levels in the fieldset in the code. And we wonder if this may create a bias for U and V.

Does Parcels implicitly take into account the fact that U and V are defined on sigma-U levels, different from sigma-W?

Thanks again for your answers, they are very helpful!
Best regards,
Mathilde Chauveau

**Comment by reint-fischer** [comment]
Hi @mathildecha,

Yes, when using one of `FieldSet.from_c_grid_dataset()`, `FieldSet.from_nemo()` or `FieldSet.from_netcdf(interp_method='cgrid_velocity')`, parcels requires only the coordinates of [the f-points in the horizontal](https://www.nemo-ocean.eu/doc/node19.html) and the sigma-W level in the vertical and will place the velocities on the correct faces of the cell.

For a more detailed explanation, you can maybe look at [this tutorial](https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/documentation_indexing.ipynb) and the paper by Delandmeter and Sebille 2019: https://gmd.copernicus.org/articles/12/3571/2019/gmd-12-3571-2019.html

**Comment by mathildecha** [comment]
Hi Reint-Fischer,
Thank you very much for your answer, that's great !
Mathilde
