### ISSUE TITLE
Issue with non-uniform diffusivity?

### ISSUE THREAD

**Issue by nordam** [OceanParcels/parcels#1028]
I wonder if there isn't an issue in the code for horizontal diffusion with non-uniform diffusivity? It might be that I have just misunderstood the code, but I couldn't make sense of the following:

```
    Kxp1 = fieldset.Kh_zonal[time, particle.depth, particle.lat, particle.lon + fieldset.dres]
    Kxm1 = fieldset.Kh_zonal[time, particle.depth, particle.lat, particle.lon - fieldset.dres]
    dKdx = (Kxp1 - Kxm1) / (2 * fieldset.dres)
    ax = fieldset.U[time, particle.depth, particle.lat, particle.lon] + dKdx
```

From these lines, it first looks like ```fieldset.dres``` should have the same units as ```particle.lon``` (longitude, I assume?), but the variable ```dKdx``` is supposed to have the same units as ```fieldset.U``` (meters per second, I assume). To me it looks like this cannot be consistent.

This applies to the functions ```AdvectionDiffusionM1``` and ```AdvectionDiffusionEM```.

**Comment by erikvansebille** [comment]
HI @nordam, thanks for the question. The point is that, if `mesh='spherical'`, then  `Kh_zonal` and `Kh_meridional` are 'under the hood' automatically converted from m/s to deg/s. So in that case `fieldset.dres` should also be in degrees. 

See also the tutorial at https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/tutorial_unitconverters.ipynb
