### ISSUE TITLE
Random walk due to vertical diffusivity

### ISSUE THREAD

**Issue by charlotteclubley** [OceanParcels/parcels#1033]
In the current version of Parcels, is there a method for implementing random walk due to vertical diffusivity? I am working with NEMO AMM7 data and have the necessary vertical diffusivity values but have been unable to find a way of implementing them so far.

Thanks for your help

**Comment by reint-fischer** [comment]
Hi @charlotteclubley,

A random walk can definitely be implemented in a kernel. [This study](https://aslopubs.onlinelibrary.wiley.com/doi/abs/10.4319/lom.2004.2.289) by Ross and Sharples 2004 shows a nice way to implement the random walk. In parcels, you can add the diffusivity field to your `FieldSet` and a random number generator is available as `ParcelsRandom`, i.e. you can import it as:
`from parcels import ParcelsRandom`

The challenge currently is the derivative needed in Eq. 1 from Ross and Sharples. There is development of this in PR #979 , but this is not finished yet. The easiest solution is to compute the derivatives of the entire diffusivity field in preprocessing and load those as another `Field`.

Let me know if that helps!
