### ISSUE TITLE
ParcelsRandom expovariate in JIT

### ISSUE THREAD

**Issue by reint-fischer** [OceanParcels/parcels#1040]
Hi all,

Federica Guerrini discovered that `ParcelsRandom.expovariate(1/10)` gives infinity in JIT. In Scipy, it works as is supposed to. I am not sure how the ParcelsRandom package works in JIT. Can anyone comment on this?

**Comment by erikvansebille** [comment]
Could it be because `1/10=0` in an integer division? What if you try `ParcelsRandom.expovariate(1./10)` or even `ParcelsRandom.expovariate(0.1)`?

**Comment by reint-fischer** [comment]
Yes, that was it, thanks :)
