### ISSUE TITLE
Warning "sh: None: command not found" when running JIT without MPI libraries installed

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/parcels#1054]
I recently installed a clean conda/developer version of Parcels, and saw that on every compilation of a JIT Kernel, I would get a (non-fatal) warning `sh: None: command not found` in the terminal. 

This disappeared after I also installed `mpi4py`, suggesting that it is a `MPI = None` statement somewhere in the code that triggers this warning. I checked basekernel.py, but couldn't find any place there where this warning is triggered

Again, the warning itself doesn't seem particularly problematic (Parcels still works as expected), but it would be good to fix this so other users are not confused too, like I was.

**Comment by goldford** [comment]
I get the same warning but good to know it still should run.
