### ISSUE TITLE
Handle State, Operation and Error codes in InteractionKernels

### ISSUE THREAD

**Issue by CKehl** [OceanParcels/parcels#1056]
The execute loop of InteractionKernels currently does not handle State/Operation codes that signify an error or edge case. It only reports a warning. It does not use the State-/OperationCode system as regular Kernels do, and it does not manipulate time, as this will interfere with the execution of regular kernels. Some thought has to be given to the way to handle these inner-kernel-workings in InteractionKernels.

**Comment by erikvansebille** [comment]
Since Interaction Particles is a bit of a niche feature for now; I am closing this Issue until others report that this is actually a problem for them
