### ISSUE TITLE
Implement InteractionKernels for JIT on SoA

### ISSUE THREAD

**Issue by CKehl** [OceanParcels/parcels#1057]
extend InteractionKernel functionality by making it work in a Kernel-generated, C-jit environment.
Benchmark first changes where only the kernel execution is integrated in JIT.
If benchmark says neighbourhood parsing is the bottleneck, think about how to fasten it - but avoid recode it all in JIT itself.

(specific subtasks still to be done)

**Comment by erikvansebille** [comment]
This is beyond scope for now, so closing this Issue
