### ISSUE TITLE
grid.from_netcdf does not efficiently allocate memory for models with many time snapshots

### ISSUE THREAD

**Issue by erikvansebille** [OceanPARCELS/parcels#106]
The filebuffer currently used does not appear to be very efficient when a model has a large number of time snapshots. 

Take for example the Globcurrent data. Running `memory_profiler` on it shows that if all files are used (i.e. `'U': "examples/GlobCurrent_example_data/20*.nc"`) then the total memory footprint of the `grid` is 12.5 MiB.

However, if only the January data is read in (i.e. `'U': "examples/GlobCurrent_example_data/200201*.nc"`), then the total memory footprint of the `grid` is 2.5 MiB.

This becomes more problematic with much larger grids. For example the 0.1 degree global OFES grid (3600 \* 1800 grid points in each snapshot) takes 70 MiB for one snapshot, but if the filebuffer is given 10 snapshots it require 512 MiB. And if it given 73 snapshots (a year's worth, at 3-day interval), the memory footprint of `grid` is 5,075 MiB.

For Parcels to be useful for long experiments on large grids, it needs to be smarter with memory allocation. For example the CMS always has only three consecutive snapshots of the velocity fields in memory, and shifts them through as `time` runs forward.

**Comment by Jacketless** [comment]
A somewhat related issue which I am coming up against increasingly is that of loading multiple netCDF files that contain the same variable across different time periods.

Many times long time-series of high resolution variable data are split up into separate files, e.g. by month, day etc. When these are on a computing cluster, it's not really appropriate to stitch them together using NCO tools into new (and enormous) netcdfs.

It would be neat if multiple files could be specified to PARCELS during grid creating/additions, and multiple instances of the same variable were stitched together in the time dimension. Not too complicated an addition, but possibly fiddly to do. What's the best approach for this?

**Comment by erikvansebille** [comment]
Hi @Jacketless, maybe I misunderstand, but isn't the wildcard operator `*` what you are after? See e.g. the `examples/example_globcurrent.py` script. The code that handles this is in the `from_netcdf` classmethod in `grid.py` (line 106).

Let me know if this fixes your issue with multiple netCDF files, or if you want something else

**Comment by Jacketless** [comment]
Apologies for my slow reply, this week has been very busy with PI meetings and prep for the Nouméa visit.

@erikvansebille You're absolutely right, PARCELS does already have this functionality. Sorry about that. I have not yet had a chance to try it out, but it should work fine.
If we can slice only the layers we are interested in from netcdfs that we then load into memory, in most cases we should be able to keep the memory footprint in reasonable territory even for long-ish runs.

**Comment by erikvansebille** [comment]
Slicing layers is indeed a feature I'd like to add in the near future. See also #75. If you have any thoughts on how to go about, it would be great to hear them there!

**Comment by erikvansebille** [comment]
Fixed in #155
