### ISSUE TITLE
Implement MPI support for InteractionKernels

### ISSUE THREAD

**Issue by CKehl** [OceanParcels/parcels#1060]
Particle-particle interaction does currently not work with MPI. That is mainly because particles interacting with one another potentially or probably occupy different processors. Hence, they would find each other as neighbours, and they can't communicate. This neighbourhood parse would need to be adapted - perhaps manage or 'house' particles centralized (?) - to communicated neighbourhood searches across processors. Also, lots of unidirectional message passing communication would need to be done between 2 processors housing interacting particles. Quite a very trick undertaking ...

(subtasks still to-be-determined)

**Comment by erikvansebille** [comment]
This is beyond scope for now, so closing this Issue
