### ISSUE TITLE
Expand tests to cases for interaction kernels

### ISSUE THREAD

**Issue by CKehl** [OceanParcels/parcels#1061]
Expand tests to cases for interaction kernels that are also expected to fail.

The tests that are currently implemented mainly test scenarios that are expected to succeed (and not so much edge cases or expected failures). Coverage is therefore currently around ~65%. For full integration in master it would probably be advisable to expand this a bit.

(subtasks still to-be-done)

**Comment by erikvansebille** [comment]
Until more users request this, I'm going to close for now as not planned. Particle Interaction is still too small a niche for Parcels to warrant the development effort for this Issue for now
