### ISSUE TITLE
Jupyter notebook examples for InteractionKernel

### ISSUE THREAD

**Issue by CKehl** [OceanParcels/parcels#1062]
Create a good, illustrative example Jupyter notebook (in collaboration with @fedeguerr @pdnooteboom and @mikaelk ) demonstrating the interaction kernel usage, as well as including the following things:
- execution order matters: regular kernel + manipulate -> regular kernel + manipulate -> ... -> [interaction kernel -> check execution -> apply interaction changes] -> [interaction kernel -> check execution -> apply interaction changes] ...
- performance benchmarks and conclusions
- limitations of particle-particle interaction

(subtasks still to-be-done)

**Comment by erikvansebille** [comment]
I think this is fixed (for now) with the https://docs.oceanparcels.org/en/latest/examples/tutorial_interaction.html tutorial, which most users seem to be able to work with well
