### ISSUE TITLE
problem with time-varying sigma levels / particles stopping

### ISSUE THREAD

**Issue by mathildecha** [OceanParcels/parcels#1065]
Hello,
I'm trying to run parcels with time-varying sigma levels (due to the tide).
I had originally written a parcels code using the tutorial "timevaryingdepthdimensions.ipynb" like this:

variables = { 'U': 'UZ',
              V': 'VZ',
              'W':'w_adapt',      
              depth_w': 'ZsigmaG_w'}

dimensions = { 'U': { 'lon': 'longitude_f', 'lat': 'latitude_f', 'depth': 'not_yet_set', 'time': 'time'},
              'V': {'lon': 'longitude_f', 'lat': 'latitude_f', 'depth': 'not_yet_set', 'time': 'time'},
              'W': {'lon': 'longitude_f', 'lat': 'latitude_f', 'depth': 'not_yet_set', 'time': 'time'},
              'depth_w':{ 'lon': 'longitude_f', 'lat': 'latitude_f', 'depth': 'not_yet_set', 'time': 'time'}}

fieldset = FieldSet.from_c_grid_dataset(filenames, variables,dimensions,allow_time_extrapolation=True)
fieldset.U.set_depth_from_field(fieldset.depth_w)
fieldset.V.set_depth_from_field(fieldset.depth_w)
fieldset.W.set_depth_from_field(fieldset.depth_w)

I work in an atoll, with shallow depths (1 to 70m) and a rough bathymetry.

We observe that a significant number of particles stop during the simulation, especially in shallow water or near bathymetric changes.
To explore this problem, we made a simple test by removing the vertical advection and imposing :
particle.depth = prof * 0.5
Where "prof" is the total depth at the particle position.

After simulation, we represent herewith : 
- the total depth at the position of the particle (in black)
- the z of the particle (in red) (=50% of the total depth)
- the sigma level at the particle position (in blue)
The sigma level should roughly follow the z; but we observe that it sometimes deviates strongly, by several meters, which we do not understand. This could be the cause of the particles stopping.
![Parcels_local100_50pc_20sec_new_beachplot](https://user-images.githubusercontent.com/82551244/126445691-2c864c79-a26a-4b58-991f-7381d2e326e1.png)

Do you have any ideas about this? 
Maybe it comes from the creation of the fieldset?

Do you know if parcels can take into account time-varying sigma levels, and if so how?

Thanks a lot in advance,
best regards,
Mathilde

**Comment by erikvansebille** [comment]
Hi @mathildecha, thanks for your question. TO answer the last bit: yes, Parcels does support time-varying sigma levels. See [this tutorial](https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/tutorial_timevaryingdepthdimensions.ipynb) for how to use these. Does this help?
