### ISSUE TITLE
First location delayed particles does not repeat original location

### ISSUE THREAD

**Issue by axnsantana** [OceanParcels/parcels#1083]
Hi,

I have tried to use both `repeatdt` and `time` array to release particles periodically from a specific location.  
Initially, they seem to work correctly, but then I notice that for the new particles, their first position does not coincide with the original position. The first position of the new particles is already one dt step ahead.  

For example, I release one particle each hour from location (2, 39) and I set dt = outputdt = 1h.  
So, in the output file, I get the particle P0 starting at (2, 39), but P1...Pn does not start at (2, 39).  
The first value of these delay particles is already in a different position.

I prepare a notebook showing this behaviour([here](https://gist.github.com/axnsantana/7fc47b6bfb3df35862ccafef8fd82c78)). I used a constant velocity field and It confirmed that the first position of P1...Pn is after the first advection. It is worthy to notice that this difference will increase proportionally the dt size. 

Also for some applications (e.g.: sampling fields, age...) the location and the variable will not be consistent. The first record of the variables has the initial value while the location is already one advection ahead (no matter the kernel order).

I put the version on the notebook, but I let it here:
Python 3.8.5
parcels                   2.2.2            py38h578d9bd_0    conda-forge

Am I missing something? is that correct?

thanks for the attention.

Just a figure summarizes the problem, particles are released at a 2dt frequency, starting from 0,0 coordinate and travelling 1 degree/s in each direction. I expect new particles to be 2 degrees behind the previous one, but what I get is 1 degree behind. (outputdt = dt).  

![issue_parcels](https://user-images.githubusercontent.com/17858249/135473583-fdcad000-bee3-4ddd-993e-e84ddb2a67fa.png)

**Comment by erikvansebille** [comment]
Thanks for reporting, @axnsantana. This is indeed a bug, and after a bit of digging I also found its source (a copy-by-reference instead of copy-by-value mistake). I'll create a Pull Request to fix this asap

**Comment by erikvansebille** [comment]
Can you check whether the fix in #1085 works and solves this issue, @axnsantana?

**Comment by axnsantana** [comment]
Hi @erikvansebille, yes it solved the problem. 
I had no time to set up a new environment with this branch, but applying the changes fixed the problem.  
Thank you!
