### ISSUE TITLE
Unexpected behavior of abs() in kernel

### ISSUE THREAD

**Issue by mikaelk** [OceanParcels/parcels#1097]
Using the abs() function in parcels kernels leads to unexpected behavior for me. It does not work for floats, I made a small notebook to reproduce the problem:
https://github.com/OceanParcels/Global_Analysis_Mikael/blob/main/MOi_test_biofouling_abs.ipynb

It seems like it is converted to the integer version of the abs() function in the parcels backend, while normally abs() works with floats in python as well. The math.fabs function does work correctly though.

**Comment by erikvansebille** [comment]
Fixed in #1098
