### ISSUE TITLE
Newlines generating errors when installing latest parcels build

### ISSUE THREAD

**Issue by nvogtvincent** [OceanParcels/parcels#1106]
**Steps to reproduce problem:**

```
conda create -n parcels_test -c conda-forge parcels jupyter cartopy ffmpeg
conda activate parcels_test 
conda remove --force parcels
pip install git+https://github.com/OceanParcels/parcels.git@master
```

**Error message:**

```
...

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-_hk1hnuh/setup.py", line 8, in <module>
      setup(name='parcels',

...

    File "/home/noam/anaconda3/envs/parcels_test/lib/python3.9/site-packages/setuptools/dist.py", line 151, in single_line
      raise ValueError('Newlines are not allowed')
  ValueError: Newlines are not allowed
```

**Fix:**
Remove the multiline description in `setup.py`. 

I've reproduced this error (and fix) on two machines, but I don't understand why this error would suddenly be appearing now since I did the same thing without an error around a week ago. Could somebody else see if they can also reproduce this error?

**Comment by erikvansebille** [comment]
Thanks for reporting, @nvogtvincent. Indeed, this seems to now also pop up on Github Actions, see https://github.com/OceanParcels/parcels/runs/4235078708?check_suite_focus=true#step:3:961. 

@CKehl, I've created a PR #1107 to fix this; you may want to also implement this change in #1034 to fix the red-crosses for CI there

**Comment by erikvansebille** [comment]
By the way, here is the documentation fro setuptools itself: https://github.com/pypa/setuptools/pull/2870
