### ISSUE TITLE
Save initial area name for each particles?

### ISSUE THREAD

**Issue by hraapoto** [OceanParcels/parcels#1114]
Hi everyone,

I was wondering if there was a way to save the initial location names of my particles. In my case, I'm generating particles around several islands and I would like to save the name of each associated islands.

I tried to add a new variable in my particle class with a dtype=np.dtype(str) but I have the error: ValueError: unable to map dtype '<U0'

So for the moment, I'm saving integers (one index for each island) instead of string but it would be easier if I could use a string variable. Anyone already tried that?

Thanks and Happy holidays

**Comment by erikvansebille** [comment]
Hi @hraapoto. Thanks for your message. But unfortunately, we indeed do not support strings as `dtype` in `Variables`. This would require a major overhaul of the code, which is beyond scope at the moment. Much easier to just use a dictionary or lookup-table in your analysis. 

Note that you can [add metadata to the netcdf output file](https://oceanparcels.org/gh-pages/html/#parcels.particlefile.baseparticlefile.BaseParticleFile.add_metadata), so you could store the mapping between island name and island integer in the file itself

**Comment by hraapoto** [comment]
Thanks @erikvansebille for the answer.
Indeed, the metadata might be very useful!
Thanks a lot
