### ISSUE TITLE
'ParticleFile' object has no attribute 'export'

### ISSUE THREAD

**Issue by gacuervol** [OceanParcels/parcels#1134]
I am running oceanparcels from google colab.

Using:
!pip install parcels
!pip install cgen
!pip install pymbolic
!wget --no-parent -r https://oceanparcels.org/examples-data/

I am following the notebook tutorials posted in the web page https://oceanparcels.org/#tutorials

But always when  I run the line:
output_file.export()

I get this error:
 'ParticleFile' object has no attribute 'export'

If export is no more a atribute of parcels.particlefile.ParticleFile class How can I export to NetCDF the particle file?

**Comment by erikvansebille** [comment]
Thanks for reporting, @gacuervol. Can I ask which version of parcels you're running? And on which operating system? It seems you're using `pip` to install parcels, but we don't support that. It may be that you have an older version. We recommend using [`conda`](https://anaconda.org/conda-forge/parcels) to install parcels

**Comment by gacuervol** [comment]
> Thanks for reporting, @gacuervol. Can I ask which version of parcels you're running? And on which operating system? It seems you're using `pip` to install parcels, but we don't support that. It may be that you have an older version. We recommend using [`conda`](https://anaconda.org/conda-forge/parcels) to install parcels

Thanks for your fast replay, 
The parcels.__version__ is 2.0.0 
I am running the package in colab who is a linux OS. 

It is not possible to use the package in colab? because I want to use it there.

The Particle File object have the really have attribute export() in the latest version of the package?

**Comment by erikvansebille** [comment]
Thanks @gacuervol. Parcels v2.0.0 is more than 2.5 years old, so I would not recommend using it. The pip version seems to have been packaged by someone who we don't know (https://pypi.org/project/parcels/). To keep maintainability manageable with a small team, we do not support parcels installing via pip; only via conda as I mentioned above.

Of course, you can always `git clone` and install parcels yourself from scratch

**Comment by gacuervol** [comment]
> Thanks @gacuervol. Parcels v2.0.0 is more than 2.5 years old, so I would not recommend using it. The pip version seems to have been packaged by someone who we don't know (https://pypi.org/project/parcels/). To keep maintainability manageable with a small team, we do not support parcels installing via pip; only via conda as I mentioned above.
> 
> Of course, you can always `git clone` and install parcels yourself from scratch

Thank you so much for your suggestion I will try with the `git clone` approach
