### ISSUE TITLE
Persistent OutofBoundsError

### ISSUE THREAD

**Issue by rrcarlson** [OceanParcels/parcels#1136]
Thanks so much for producing OceanParcels! It's a wonderful tool.

I have been receiving a persistent OutofBoundsError, and I'm not sure why. I use a 'DeleteParticle' command to delete my particles when they are out of bounds, and all particles are always deleted before the first timestep. When I remove the 'DeleteParticle' function, advection still fails, as expected, due to an OutofBoundsError.

I have tried several different fixes to identify why particles are out of bounds:

- Used different current data (a nest of a ROMS model rather than MITgcm) for my study region; both lead to the same error.
- Tried different options for loading currents, by first loading data into an xarray and, alternatively, using `FieldSet.from_netcdf`, but this doesn't matter. All fieldsets look good in map visualizations, with particles showing up where they should at the release sites (see screenshot at bottom), and fieldsets have the correct times listed (using `fieldset.U.grid.time`).
- Currents are not large enough to advect particles out of bounds right away. I've also tried moving particles offshore in case they're too close to land, but receive the same error.
- I removed diffusivity to simplify things, but same error.
- Finally, I tried to change the release locations to 360 degrees (instead of -180), but same error.

Do you have any ideas on what could be going wrong? Thank you so much for any help you can provide!

```
from parcels import FieldSet, ParticleSet, JITParticle, ErrorCode, plotTrajectoriesFile, Variable, ParcelsRandom, Field, AdvectionRK4, DiffusionUniformKh
import numpy as np
import pandas as pd
import xarray as xr
from datetime import timedelta, datetime
import math

# Delete particles if they exit the dispersal domain (later removed, to no effect)
def DeleteParticle(particle, fieldset, time):
    print('particle has been deleted')
    particle.delete()

# Read in MITgcm data as xarray dataset. `fp` represents one .nc file spanning 100 days in 2012
fp = "XXXX"
mitgcm = xr.open_dataset(fp)

# Define variables and dimensions for fieldset. There are different lat/lon ids for both U and V in this dataset, so I defined them separately.
variables = {'U':'U', 'V':'V'}
dimensions = {}
dimensions['U'] = {'lat': 'LATITUDE_T126_376', 'lon': 'LONGITUDE_U382_732', 'depth': 'DEPTH_T1_35', 'time': 'TIME1'}
dimensions['V'] = {'lat': 'LATITUDE_V126_376', 'lon': 'LONGITUDE_T381_731', 'depth': 'DEPTH_T1_35', 'time': 'TIME1'}

# Make fieldset (also tried FieldSet.from_netcdf, but didn't change anything)
fieldset = FieldSet.from_xarray_dataset(mitgcm, variables, dimensions)

# Visualize fieldsets: all appears normal
fieldset.U.show()
fieldset.V.show()

# Add diffusivity. Testing tiny diffusivity to prevent from advecting out of bounds.
kh = 0.002
fieldset.add_constant_field("Kh_zonal", kh, mesh = "spherical")
fieldset.add_constant_field('Kh_meridional', kh, mesh='spherical')

# Set particle release locations
fp_points = "XXXX" # a csv containing coordinates in columns
infile = pd.read_csv(fp_points, header = None) 
nrepeat = 5 # Each site releases 5 particles

habilon = np.repeat(infile[1], nrepeat)
habilat = np.repeat(infile[0], nrepeat)

# Define the pset
pset = ParticleSet.from_list(fieldset=fieldset, pclass=JITParticle, lon=habilon, lat=habilat)
print(pset)
pset.show(field=fieldset.U) # All looks good here (screenshot below)

# Define kernels and execute simulation
kernels = pset.Kernel(AdvectionRK4) + pset.Kernel(DiffusionUniformKh)
outputfile = pset.ParticleFile(name = "XXXX", outputdt = timedelta(hours = 6))
pset.execute(kernels,
             runtime=timedelta(days=4),
             dt=timedelta(minutes=5),
             recovery={ErrorCode.ErrorOutOfBounds: DeleteParticle},
             output_file=outputfile)
```
Result is the error message:

```
WARNING: ParticleSet is empty on writing as array at time 21600
WARNING: ParticleSet is empty on writing as array at time 43200

OR if `ParticleDelete` (delete particles when out of bounds) is disabled:

OutofBoundsError: 0
Particle P[1](lon=-156.000000, lat=19.213438, depth=2.500000, time=0.00000
Time: 2012-01-26T12:00:00.000000000,	timestep dt: 300.000000
Out-of-bounds sampling by particle at (-156.000000, 19.213438, 2.500000)
```

Particles have correct release locations:

![Screen Shot 2022-02-08 at 1 07 06 PM](https://user-images.githubusercontent.com/36307756/153490840-460574af-b469-4ae2-b8ea-bc1ea2ce4f4c.png)

**Comment by erikvansebille** [comment]
Thanks for reporting, @rrcarlson. These OutOfBounds errors most often happen because of the 360 longitude wrapping, so I'm somewhat surprised that you tried to change the release locations to 360 degrees (instead of -180), but got the same error. 
Can you print the `fieldset.U.grid.lon[0]` and `fieldset.U.grid.lon[-1]`? What values do they have? And what values does `habilon` have? Make sure that your `habilon` longitudes fall within the range of the `fieldset.U.grid.lon`

**Comment by rrcarlson** [comment]
Thanks for your quick response @erikvansebille! You're right; I had tried changing release locations to 360 degrees but perhaps converted or called the result incorrectly, because my points were not within range of `fieldset.U.grid.lon` (I had previously just relied only on the map to verify).

The advection appears to work now--thank you so much!

**Comment by erikvansebille** [comment]
Glad that this worked for you. Good luck with Parcels!
