### ISSUE TITLE
AssertionError even though ordered .nc file list with FieldSet.from_netcdf

### ISSUE THREAD

**Issue by HandmannP** [OceanParcels/parcels#1139]
Hey everybody, I am trying to set up experiments with the cmems output and import the files in a load fields function. Even though I am ordering the files according to their date parcels does not load them accordingly and gives an AssertionError. Please find the script attached here. Do you have any Idea how this could be resolved?
[Micor_plastic_Indian_ocean_backward_trajectories.md](https://github.com/OceanParcels/parcels/files/8114579/Micor_plastic_Indian_ocean_backward_trajectories.md)

**Comment by erikvansebille** [comment]
Hmm, how sure are you that the list of input files is really sorted? What if you add `sorted(glob())` to each of the filename lists?

```python
fname_U = sorted(glob('uo/cmems_mod_glo_phy_my_0.083_P1D-m_uo_????-??-??_????-??-??.nc'))
fname_V = sorted(glob('vo/cmems_mod_glo_phy_my_0.083_P1D-m_vo_????-??-??_????-??-??.nc'))
fname_T = sorted(glob('thetao/cmems_mod_glo_phy_my_0.083_P1D-m_thetao_????-??-??_????-??-??.nc' ))
fname_S = sorted(glob('so/cmems_mod_glo_phy_my_0.083_P1D-m_so_????-??-??_????-??-??.nc'))
fname_MLD = sorted(glob('mlotst/cmems_mod_glo_phy_my_0.083_P1D-m_mlotst_????-??-??_????-??-??.nc' ))
```

**Comment by HandmannP** [comment]
I do this in the load_allfiles function as follows:
files_T = [file for file in sorted([f for f in glob.glob(data_path + fname_T)])
              if int(file.split('_')[-1].split('-')[0]) in range(f_year_first, f_year_last + 1)]

**Comment by erikvansebille** [comment]
OK, and are you absolutely sure that the list of filenames is in order? Are the timestamps in the files themselves the same as the strings in the filenames? Because I really think that this Error is thrown for a reason, so I'd recommend you carefully verify that the timestamps in the files are indeed consecutively ordered

**Comment by HandmannP** [comment]
Thanks Eric apparently something went wrong during downloading the files from the Copernicus system - I am checking all time stamps in relation to the date in the file name now and will get back as soon as this error is resolved.

**Comment by HandmannP** [comment]
Hey Erik, thanks for pointing the timestamps out - I had to reload some files since they apparently hat the wrong timestamp - I can not imagine how something like this can happen during download but it happened. so the issue is solved now.

**Comment by erikvansebille** [comment]
OK, great that this is sorted then
