### ISSUE TITLE
interpolation problem on nemo based conf

### ISSUE THREAD

**Issue by quai20** [OceanParcels/parcels#1143]
Hello,
I'm facing an issue with my fieldset. Following the nemo 3d notebook tutorial, I managed to create my fieldset for this configuration
![index](https://user-images.githubusercontent.com/17851004/157216474-20be96cf-7716-433b-8ec6-b118d27064cc.png)

The problem is that the particles are automatically outOfBounds, even if they are indeed within the limits of the domain. 
If I test some values to interpolate, it always return `0.0` : 
```
>> fieldset.computeTimeChunk(fieldset.U.grid.time[0], 1)
>> fieldset.U[0,1,60,-30]
0.0
```
as long as this warning : 
```
[...]/miniconda3/envs/nemoparcels/lib/python3.9/site-packages/parcels/field.py:822: RuntimeWarning: invalid value encountered in double_scalars
  eta = -cc / bb
```
I checked and the value of `aa,bb,cc` are `0.0`
Example of larger interpolation test on my domain, everything is at 0.0 : 
![index2](https://user-images.githubusercontent.com/17851004/157207992-da3f9c8d-98a4-423c-a2f1-be4acc5bdc95.png)

This is my first time with parcels and c-grid, so maybe I miss something, or maybe there's something wrong with my input dataset. 
If you have any lead to help me investigate, I would be grateful. I'm in `parcels v2.3.0`

Thanks,

**Comment by erikvansebille** [comment]
Thanks for reporting, @quai20 (and nice maps!). May it be that your grid extends from 0 to 360 degrees, but your particles are defined between -180 and 180 degrees? In other words, what happens if you do `fieldset.U[0, 1, 60, 330]`?

**Comment by quai20** [comment]
Hi @erikvansebille 
My dataset is defined on -180/180 :
![Capture du 2022-03-08 10-44-50](https://user-images.githubusercontent.com/17851004/157210891-06189302-b16d-40ea-b690-f6b9c147bdd4.png)
and `fieldset.U[0, 1, 60, 330]` returns 0.0 as well. Shouldn't it return `outOfBounds` ?

**Comment by erikvansebille** [comment]
Ah, but your longitudinal grid is not monotonous; Parcels can have big trouble with that. Can you manually change your `fieldset.U.grid.lon` to make sure that it is always monotonous?

**Comment by quai20** [comment]
How would you advice to do this ?

**Comment by erikvansebille** [comment]
Well, you can change the values of `fieldset.U.grid.lon` after you've created the object (it's a simple numpy-array). So you may be able do something like (not tested; because I don't have your grid data)
```python
fieldset.U.grid.lon[fieldset.U.grid.lon<0] += 360
```

Note however that it's somewhat strange that your longitudes in the plot above seem to _decrease_ (so the grid runs east to west). To be honest I'm not sure if Parcels can handle this; it's surely something I've never seen in NEMO output...

**Comment by quai20** [comment]
I tried `fieldset.U.grid.lon[fieldset.U.grid.lon<0] += 360` but I still get a 0.0 result for any interpolation

**Comment by erikvansebille** [comment]
And does the plot of `fieldset.U.grid.lon[1500, :]` change then? If you still only get zeros, it may very well be because the Parcels code can't handle longitudes ordered from east to west (as opposed to from west to east). Can you try to 'swap' your longitudes (and you will then also need to swap the data itself?) outside of Parcels?

**Comment by quai20** [comment]
Yes the plot changed, and we have a continuous longitude : 
![Capture du 2022-03-08 13-03-19](https://user-images.githubusercontent.com/17851004/157234712-8a9aa5d1-0a94-4ef7-ba63-20342720c606.png)

**Comment by erikvansebille** [comment]
Indeed, this plot clearly shows that the gradient in longitude is everywhere negative (and note also the zeros on either side!), so my guess it that this non-positive monotonic nature of lon causes your interpolation problems. There's nothing that we can do in Parcels; you will have to use another tool to flip the data

**Comment by quai20** [comment]
Ok I'll try to do that. But I'm not sure it's possible, I'm gonna have the same problem for latitude. 
Here are lon and lat :
![latlon](https://user-images.githubusercontent.com/17851004/157408476-92d60b86-2f6c-4320-bba6-752c4e9e11e3.png)

Since it's not parcels related, I close the issue. Thank you for your quick answer to my question @erikvansebille

**Comment by lvankampenhout** [comment]
hi @quai20 , I'm interested in following this up. At the minimum Parcels could issue a warning message when a coordinate is not monotonous. Could you be so kind and upload your grid data somewhere, so I can use that as a test case?

**Comment by quai20** [comment]
Hi @lvankampenhout , 
I sent you an email.

**Comment by quai20** [comment]
Interesting. 
If I use the non-masked coordinate file instead (instead of zero values you mentionned @erikvansebille, lat & lon are full) it seems to be working better. I need to check the interpolations but it interpolates. That's a big step.
