### ISSUE TITLE
Are free slip and partial slip boundary interpolations supported with B-grids?

### ISSUE THREAD

**Issue by hrsdawson** [OceanParcels/parcels#1161]
I'm trying to use the free slip boundary condition documented in the **[](https://nbviewer.org/github/OceanParcels/parcels/blob/master/parcels/examples/documentation_unstuck_Agrid.ipynb#Tutorial-on-implementing-boundary-conditions-in-an-A-grid)Tutorial on implementing boundary conditions in an A grid** (thanks for this by the way, very useful!) with velocity fields from an Arakawa B-grid model, but I'm getting an `interp_method` error when trying to create the fieldset (see code and traceback below). I'm only running 2D advection, so I thought this boundary interpolation might still work with the `FieldSet.from_b_grid_dataset()` method. It works if I use `FieldSet.from_netcdf()`, but the documentation says that only nemo or mitgcm gridindexing is supported with this method. 

So, I guess my question is twofold: 1) Are the free-slip and partial-slip boundary conditions supported with B-grids? And if not, 2) will the `FieldSet.from_netcdf()` method correctly interpolate U and V from a B-grid model given the nemo/mitgcm gridindexing and that I can't also specify the `interp_method` to be `bgrid_velocity` when using the free slip / partial slip boundary interpolation?
                          
![Screenshot from 2022-04-12 15-14-33](https://user-images.githubusercontent.com/62230733/162885789-3669e404-014f-425a-97b8-76be8cd2f69e.png)

Thanks in advance for any guidance you have.

**Comment by erikvansebille** [comment]
Thanks for raising this Issue, @hrsdawson. Indeed, you can't use`freeslip` on Arakawa B-grids, this is not implemented. Note that there is a subtle difference between A-grids and B-grids, even if you don't consider W or tracers like temperature: where U and V are on the corners in A-grids, they are in the Centre for B-grids (see e.g. [wikipedia](https://en.wikipedia.org/wiki/Arakawa_grids). So you can't simply assume that the free slip implementation works for B-grids too. 

Developing this would be beyond scope for my own group right now, as we hardly ever use B-grid-models. But perhaps you can try yourself to implement this? The relevant code is in https://github.com/OceanParcels/parcels/blob/master/parcels/include/parcels.h#L917-L985

**Comment by hrsdawson** [comment]
Thanks for your response @erikvansebille. Yes, understandable re the development - perhaps I can look into this. However, in the case of the B-grid model I'm using, U and V are defined at the north-east corner of the tracer cell. The Parcels documentation for B-grids notes that  "_In 2D: U and V nodes are on the cell vertices and interpolated bilinearly as a A-grid._". It seems to me that if I'm only running 2D advection (and not loading any tracer fields which are offset from U,V), it should be okay to use the freeslip and partial slip schemes as for an Arakawa A-grid model? 

![Screenshot from 2022-04-12 20-15-09](https://user-images.githubusercontent.com/62230733/162938386-0c2bd189-dc44-413a-afc5-dbd9f6046010.png)

**Comment by erikvansebille** [comment]
Ah, good point; I forgot about that. Yes, in 2D a Arakawa A- and B-grid are equivalent for Parcels, if only velocities are considered. So in that case you could simply use `from_netcdf()` with `interp_method=freeslip`? But I guess that the proof is in eating the pudding?

**Comment by hrsdawson** [comment]
Thanks @erikvansebille. I'll run some test cases to check it's working as expected on the trajectories. If I end up needing to implement this for B-grids in 3D (or if I need to read in tracer fields in 2D), then I'll re-open a case and work on the code.  Thanks!
