### ISSUE TITLE
Compilation fails because indexing variable is set to float

### ISSUE THREAD

**Issue by quai20** [OceanParcels/parcels#1169]
Hello ! 
In my custom JIT kernel, I try to index an array with an index `i=0` but the compilation of the generated C code fails because `i` is set to a float. Is there any way to force the variable to an integer when generating the C code of my kernel ? 
Thanks,

**Comment by erikvansebille** [comment]
Hi @quai20. I don't think that we support type-conversion in JIT mode, or at least I've never tried it. More in general, we don't really support arrays in JIT; or at least not for variables. How are you using arrays? Can you share (a snippet of) your Kernel?

**Comment by quai20** [comment]
Hi @erikvansebille 
```
isa_drange = [10.,12.,14.,16.,18.,20.,22.,24.,26.,28.,30.]
    temp_isa = [0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.]
    i=0
    while (i<len(isa_drange)):        
        temp_isa[i] = fieldset.T[time,isa_drange[i], particle.lat, particle.lon]
        i = i+1    
```      
The compilation fails because of the `temp_isa[i]` & `isa_drange[i]` : 
`/tmp/parcels-500721/fcc5206e5ae24b8a52b39111423d907d_0.c:150:90: error: array subscript is not an integer`
So maybe the issue is not really the array itself but just the index.

In this case I want to calculate a median within the JIT kernel. I'll probably have to try to decompose the calculation without using arrays.

**Comment by quai20** [comment]
What I did is probably not the best solution but I modified `compilation/codegenerator.py` to : 

- always add "reserved indexing" int variables : **i**,**j** & **k**
- remove any detected **i**,**j**,**k** from `funcvars`

With that, my above example works.

**Comment by quai20** [comment]
"a bit of a hack" is a polite way to say it yes :smile: 
Building directly a small part of my C kernel would be better indeed, I'll look into your solution. 
I close the issue, thanks for your help !
