### ISSUE TITLE
Dependency on matplotlib-base rather than matplotlib

### ISSUE THREAD

**Issue by scottyhq** [OceanParcels/parcels#1173]
We're trying to include parcels in a docker image used on binders and jupyterhubs, but the dependency on matplotlib brings in 'Qt' and uses 100's of MB of disk space. https://github.com/pangeo-data/pangeo-docker-images/issues/329

If Qt is not strictly necessary, you can depend on 'matplotlib-base', which does not bring along 'Qt' by default, making that matplotlib backend instead optional. See conda-forge docs https://conda-forge.org/docs/maintainer/knowledge_base.html#matplotlib

The parcels conda-forge recipe would need updating here: 
https://github.com/conda-forge/parcels-feedstock/blob/09b9df24933feb9073670045152d9af18864c0b4/recipe/meta.yaml#L38

**Comment by rabernat** [comment]
Thanks for digging into this @scottyhq! :+1: to changing the dependency, which would allow us to make the pangeo docker image significantly smaller.
