### ISSUE TITLE
Noncontinuous grids

### ISSUE THREAD

**Issue by hblumberg** [OceanPARCELS/parcels#1184]
My team has noticed that if we construct a `Fieldset` using NetCDF data in which longitudes are in the range [0, 360), we see out of bounds errors when a particle tries to move across the Prime Meridian. This is the case even when the longitudes are ordered "correctly" (e.g. `[358, 359, 0, 1, 2]`).

We could change our longitudes to be in the range [-180, 180), but then we'd have the problem along the International Date Line.

Our questions are:
1. Is this the intended behavior for noncontinous grids?
2. If so, how do folks usually work around this when working with longitudes?

Thanks in advance!

**Comment by erikvansebille** [comment]
Thanks for your question, @hblumberg. Indeed, Parcels expects longitudes to be monotonously increasing. In your example about, you would use `[358, 359, 360, 361, 362]`. This can be done by changing the longitude vector before (or after) the FieldSet creation, but certainly before the particles execution. Does that work?

Note that for dealing with periodic boundaries, you may then also need to add a halo. See for example the tutorial at https://nbviewer.org/github/OceanParcels/parcels/blob/master/parcels/examples/tutorial_periodic_boundaries.ipynb

An alternative to using a halo is to change the kernels themselves, and add modulo statements to for example a custom Advection Kernel.
