### ISSUE TITLE
Question - data from ocean gif tutorial 

### ISSUE THREAD

**Issue by graceebc9** [OceanParcels/parcels#1217]
Hello - please could you elaborate on medusarun the data used in this tutorial? Where did you source it? https://nbviewer.org/github/OceanParcels/parcels/blob/master/parcels/examples/documentation_homepage_animation.ipynb

I'm trying to model the trajectories of particles released from the mouth of the Missisipi into the gulf of Mexico. I understand I need an ocean current netcdf of some form. 

Thanks,
Grace

**Comment by erikvansebille** [comment]
Dear @graceebc9, the data from the medusa run comes from http://opendap4gws.jasmin.ac.uk/thredds/nemo/root/catalog.html, but that link is often down. 

You could also have a look at the data at https://www.mercator-ocean.eu/en/solutions-expertise/accessing-digital-data/product-details/?offer=4217979b-2662-329a-907c-602fdc69c3a3&system=d35404e4-40d3-59d6-3608-581c9495d86a (with [documentation here](https://www.mercator-ocean.eu/wp-content/uploads/products_pdf/MOI_GLO12.pdf)), which is the 'workhorse model' we now use in our group. The advantage is that it's on an original C-grid, so no interpolation
