### ISSUE TITLE
Bug in field object time concatenation

### ISSUE THREAD

**Issue by Jacketless** [OceanPARCELS/parcels#123]
I believe I've found a bug in the time concatenation from multiple files when initialising a `Field` objects from `Field.from_netcdf()`.

When individual netcdf files contain single time slices (i.e. the time dimension is of length one) the code works, but when each netcdf contains multiple time-slices (e.g. perhaps one month of data), the line 
`data[tidx:, 0, :, :] = filebuffer.data[:, :, :]` 
throws an error when attempting to allocate the array from the time-slice to the full array for the entire time-series. I'm not quite sure why it works in the case of single time indices, but it does!

I have a working example, and a fix, but it requires some example netCDF files. What is the best way to demonstrate this bug?

**Comment by erikvansebille** [comment]
That indeed sounds like a bug. Can you paste the patch here and send the example data directly to me, and I'll look into it?

**Comment by Jacketless** [comment]
I have sent some example data through to you Erik.

I believe the issue arises in `Field.from_netcdf()` from each `tslice` in `timeslices` not having a `.size` attribute when of length greater than one (not sure why this is!). My quick patch is to therefor explicitly increment the `tidx` counter object by the length of each tslice.

```
tidx = 0
for tslice, fname in zip(timeslices, filenames):
    with FileBuffer(fname, dimensions) as filebuffer:
        data[tidx:, 0, :, :] = filebuffer.data[:, :, :]
    tidx += tslice.size
``` 

can be changed to

```
tidx = 0
for tslice, fname in zip(timeslices, filenames):
    with FileBuffer(fname, dimensions) as filebuffer:
        data[tidx:(tidx+len(tslice)), 0, :, :] = filebuffer.data[:, :, :]
    tidx += len(tslice)
```

and this fixes the error in my example script

**Comment by erikvansebille** [comment]
Yes, I can confirm that this fix works. @Jacketless could you create a branch with this fix and then a Pull Request? I'll then merge it into `master` once all travis tests are passed

**Comment by Jacketless** [comment]
Now done, in PR #124
