### ISSUE TITLE
Particles not moving and out-of-bound

### ISSUE THREAD

**Issue by jporobicg** [OceanParcels/parcels#1235]
Hello,
I have a problem seeding in some specific regions of the model. When running the model, the particles don't  move from the seeding position, and I'm getting the following result:

```
WARNING: ParticleSet is empty on writing as array at time 3600
WARNING: ParticleSet is empty on writing as array at time 7200
```

I tried to check if I have values of U and V in those specific locations using the code below, 

`fieldset.UV[7200, 0, lat_part[0], lon_part[0]]`

I am getting the following error. 
```
Correct cell not found after 1000000 iterations
FieldOutOfBoundError: U sampled out-of-bound, at (145.535066, -14.859701, 0.000000)
```

When I look at the hydro model outside Oceanparcels, I have U and V at those positions(see figure). Do you have any idea where the problem could be?
![Seeding_location](https://user-images.githubusercontent.com/7935204/189483561-4b578550-60a3-403f-90ae-3edfee0465da.png)

**Comment by erikvansebille** [comment]
Thanks for reporting @jporobicg. I don't immediately see what the problem could be here. When you say 
> I have a problem seeding in some specific regions of the model
does that mean that you don't have this problem in other parts of the domain?

Could you also provide the code that you use to create your `FieldSet`, and your `ParticleSet`? That code may also provide useful hints!

**Comment by jporobicg** [comment]
Hi @erikvansebille ,

> When you say
>> I have a problem seeding in some specific regions of the model.

> does that mean that you don't have this problem in other parts of the domain?

Yes, I don't have this problem in other areas of the model domain. 
FielSet:
```
data_path = '/home/por07g/Documents/Projects/GBR_modeling/GBR_oceanparcels/GBR_main/Data/'
files = sorted(glob(data_path+'gbr1_simple_*.nc'))
mesh_mask = data_path + 'coordinates.nc'
filenames = {'U': {'lon': mesh_mask, 'lat': mesh_mask, 'depth': files[0], 'data': files},
             'V': {'lon': mesh_mask, 'lat': mesh_mask, 'depth': files[0], 'data': files}}
variables = {'U': 'u',
             'V': 'v'}
dimensions = {'U': {'lon': 'longitude', 'lat': 'latitude', 'depth': 'zc', 'time': 'time'},
              'V': {'lon': 'longitude', 'lat': 'latitude', 'depth': 'zc', 'time': 'time'}}

fieldset = FieldSet.from_netcdf(filenames, variables, dimensions, allow_time_extrapolation = True)
```
ParticleSet + execution
```
lon_part = [145.53506554786637, 145.51936068493657, 145.5356358863923, 145.53145637880326, 145.52736346809914]
lat_part = [-14.859701485520151, -14.85834488238424, -14.86892276514238, -14.849033419881252, -14.862993266736664]
## Depth tried -5.35; -2; -1
depth_part = [0]*len(lat_part)
pset = ParticleSet.from_list(fieldset, pclass=JITParticle,
                                 lon = lon_part,
                                 lat = lat_part,
                                 depth = depth_part)    
# setting the Kernel
kernels = pset.Kernel(AdvectionRK4) 
output_file = "/home/por07g/Documents/Projects/GBR_modeling/GBR_oceanparcels/GBR_main/MRE"
pfile = pset.ParticleFile(output_file, outputdt = delta(hours=1))
pset.execute(kernels, runtime = delta(days = 1), dt = delta(hours = 1),
             output_file = pfile, recovery = {ErrorCode.ErrorOutOfBounds: DeleteParticle})

pfile.export()  # export the trajectory data to a netcdf file
plotTrajectoriesFile(output_file+".nc");
```
You can find the entire code for the MRE [here](https://github.com/jporobicg/MRE_OceanParcels/blob/7bba375a24ef71fa91531407c92dfdd3c245f31a/MRE_and_Map_polygons.ipynb)

**Comment by erikvansebille** [comment]
Hmm, one possibility is that it could be that it takes more than 1000000 iterations to find the cell where the particles are located in, especially in the centre of the domain; although that then suggests that the search method is highly inefficient on your rotated, elongated domain. 

Could you try increase the value of `intMax` in the `index_search.h` file? 
https://github.com/OceanParcels/parcels/blob/7f6610417c948e85d65d98704db36e55e505b5a7/parcels/include/index_search.h#L251
Does that help?

Alternatively, you could try to write a code yourself where you assign the number of the grid cell in the `I` and `j` direction to each Particle's `xi` and `yi`. That will help the algorithm find the initial positions sooner.

**Comment by jporobicg** [comment]
Hi @erikvansebille 
Thanks for your suggestion. I tried increasing itMax up to 1e9. I also tried increasing [maxIterSearch](https://github.com/OceanParcels/parcels/blob/7f6610417c948e85d65d98704db36e55e505b5a7/parcels/include/index_search.h#L353), but I got the same results.

**Comment by erikvansebille** [comment]
Thanks for checking, @jporobicg. The search algorithm may be stuck in a loop, because of your rotated grid. In that case, I recommend to set the Particle's `xi` and `yi` (i.e. in which grid cell each particle is located) by end, after you defined the ParticleSet but before you run a `.execute()`). If you write your own code for finding the `xi` of a particle, you can assign it with the following loop:
```python
    for p in pset:
        xi =   # code to find grid cell number where particle is
        p.xi = np.array([xi], dtype=np.int32)
``` 
And similar for `yi`

**Comment by jporobicg** [comment]
Hi @erikvansebille 
I followed your suggestion, and the seeding works perfectly now. I'm posting the code if anyone needs it. Cheers and thanks. 


Function to locate the seeding grid cell:

```Python
def find_particle_index(latitudes, longitudes, part_lat, part_lon):
    """"This function looks for the indexes of each particle looking for in which grid cell each particle is located.
    Use this function after setting the particles and before executing the run
    latitude: latitude grid
    longitude: longitude grid
    part_lat: particle latitude at seeding
    part_lon: particle longitude at seeding"""
    diff_grid = np.abs(part_lat - latitudes) + np.abs(part_lon - longitudes)
    XiYi = np.where(diff_grid == diff_grid.min())
    indexes = [XiYi[0].item(), XiYi[1].item()]
    return(indexes)
```

- After setting the particles "pset"

```python
for p in pset:
    yi, xi = find_particle_index(grd_lat, grd_lon, p.lat, p.lon)
    p.xi = np.array([xi], dtype=np.int32)
    p.yi = np.array([yi], dtype=np.int32)
```

Then execute "pset.execute(kernels, ... )"

Cheers,
Javier

**Comment by erikvansebille** [comment]
Great that this worked, I'll close the issue then
