### ISSUE TITLE
issue with parcels execution on HPC

### ISSUE THREAD

**Issue by selipot** [OceanParcels/parcels#1260]
I have some parcels code that run fine within a notebook on a jupyter server running on the HPC system at my university (with CentOS 7.6 and bash shell). Yet the same code does not run on a login node or computing node of the same HPC system. A test version of the same code runs fine on my macOS laptop. When executing the parcels kernel, some temporary `.so` files are not found. I have read issue #487 and I am able to change the location of the temporary files to my scratch space on the HPC (instead of the default `/tmp`) yet this does not solve the issue. I am copying the relevant error output below. I am wondering if it has to do with some different environment variables between the interactive node running the jupyter server and the computing node? In both cases I am printing out the paths and the (very long) list of environment variables. Is there a specific environment variable I should be looking out for that is used by parcels processes? Something to do with permissions perhaps?

```
INFO: Compiled ArraySampleParticleInitZeroSample ==> /scratch/tidaldrift/parcels-3477/lib52c065219fa2a3bbd21461bbfd44b8a6_0.so
Traceback (most recent call last):
  File "/home/selipot/pra-drifters/particles_na.py", line 109, in <module>
    pset.execute(sample_kernel, dt=0) 
File "/home/selipot/miniconda3/envs/py3_parcels/lib/python3.8/site-packages/parcels-2.3.1.dev129+g65e5d595-py3.8.egg/parcels/particleset/baseparticleset.py", line 341, in execute
    self.kernel.load_lib()
  File "/home/selipot/miniconda3/envs/py3_parcels/lib/python3.8/site-packages/parcels-2.3.1.dev129+g65e5d595-py3.8.egg/parcels/kernel/basekernel.py", line 260, in load_lib
    self._lib = npct.load_library(self.lib_file, '.')
  File "/home/selipot/miniconda3/envs/py3_parcels/lib/python3.8/site-packages/numpy/ctypeslib.py", line 148, in load_library
    return ctypes.cdll[libpath]
  File "/home/selipot/miniconda3/envs/py3_parcels/lib/python3.8/ctypes/__init__.py", line 448, in __getitem__
    return getattr(self, name)
  File "/home/selipot/miniconda3/envs/py3_parcels/lib/python3.8/ctypes/__init__.py", line 443, in __getattr__
    dll = self._dlltype(name)
  File "/home/selipot/miniconda3/envs/py3_parcels/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
```
```
    OSError: /scratch/tidaldrift/parcels-3477/lib52c065219fa2a3bbd21461bbfd44b8a6_0.so: cannot open shared object file: No such file or directory
```

(ed: add one more backtick)

**Comment by erikvansebille** [comment]
Hmm, I don't know how to fix this I'm afraid. Perhaps @willirath (or @ckehl?), who have more experience with HPC, have an idea?

**Comment by willirath** [comment]
Not sure. Sounds like a permission error to me. Guesses:

- Is `/scratch/tidaldrift/` the right location to point to? As `tidaldrift` sounds like either a group name or a name of a compute cluster, I'd guess there might be a subdirectory either belonging to your user or related to a job id or something? For further diagnosis, I'd probably run an `env | grep -i scratch` and `env | grep -i tmp` and look for how paths under `/scratch` are handled in the job.

- If it's not the above: Does `/scratch/tidaldrift/parcels-3477/` exist? (The last dir is generated by Parcels and I'd expect any permission error to show up here first.) If it does not exist, can you create it on the command line? (`mkdir -p /scratch/tidaldrift/parcels-3477/`)

- The path `/scratch/tidaldrift/parcels-3477/` should have been created here: https://github.com/OceanParcels/parcels/blob/ecda521bf34645742a0762d781c95bf25641aa51/parcels/tools/global_statics.py#L33 I guess if this didn't throw an error yet, write permissions might not be an issue. But maybe, @selipot, you can try and check if the desired tmp dir location in `/scratch/tidaldrift` actually is followed by `tempfile.gettempdir()`? A shell one-liner like `python -c "from tempfile import gettempdir; print(gettempdir());"` could help revealing if your shell env is leading to the intended behaviour.

**Comment by willirath** [comment]
Possibly related (@CKehl) I'm a little confused about this line
https://github.com/OceanParcels/parcels/blob/ecda521bf34645742a0762d781c95bf25641aa51/parcels/kernel/basekernel.py#L260
It tries loading the library from the current dir `.` but then uses a full path which is in `self.lib_file`.

**Comment by selipot** [comment]
> Not sure. Sounds like a permission error to me. Guesses:
> 
> * Is `/scratch/tidaldrift/` the right location to point to? As `tidaldrift` sounds like either a group name or a name of a compute cluster, I'd guess there might be a subdirectory either belonging to your user or related to a job id or something? For further diagnosis, I'd probably run an `env | grep -i scratch` and `env | grep -i tmp` and look for how paths under `/scratch` are handled in the job.

`/scratch/tidaldrift/` is my personal scratch space for my *tidaldrift* project. I had specified to use this folder by setting the tempdir folder in an attempt to understand if this was indeed a permission issue. The same issue exist when I use the default `/tmp` folder for temporary files.

> * If it's not the above: Does `/scratch/tidaldrift/parcels-3477/` exist? (The last dir is generated by Parcels and I'd expect any permission error to show up here first.) If it does not exist, can you create it on the command line? (`mkdir -p /scratch/tidaldrift/parcels-3477/`)

Yes, `/scratch/tidaldrift/parcels-3477/` does exist but after the attempted execution I can see that this folder is empty. The `.so` files are not present there.

> * The path `/scratch/tidaldrift/parcels-3477/` should have been created here: https://github.com/OceanParcels/parcels/blob/ecda521bf34645742a0762d781c95bf25641aa51/parcels/tools/global_statics.py#L33
>    I guess if this didn't throw an error yet, write permissions might not be an issue. But maybe, @selipot, you can try and check if the desired tmp dir location in `/scratch/tidaldrift` actually is followed by `tempfile.gettempdir()`? A shell one-liner like `python -c "from tempfile import gettempdir; print(gettempdir());"` could help revealing if your shell env is leading to the intended behaviour.

I don't think it's an issue with the creation of that folder. What process writes the `.so` files?

**Comment by selipot** [comment]
In summary, if I let parcels does its thing and do not change the temporary folder location I get the same issue. The `/tmp/parcels-3477/` folder is created but not populated and creates the error that the `.so` file is not found. I am wondering if I might need to load a compiler module that is needed by parcels?

**Comment by willirath** [comment]
> I don't think it's an issue with the creation of that folder. What process writes the .so files?

This should be
https://github.com/OceanParcels/parcels/blob/ecda521bf34645742a0762d781c95bf25641aa51/parcels/kernel/basekernel.py#L237
which is called from here
https://github.com/OceanParcels/parcels/blob/ecda521bf34645742a0762d781c95bf25641aa51/parcels/particleset/baseparticleset.py#L340

The behaviour of the compiler should be in here: https://github.com/OceanParcels/parcels/blob/ecda521bf34645742a0762d781c95bf25641aa51/parcels/particleset/baseparticleset.py#L340

**Comment by willirath** [comment]
> I am wondering if I might need to load a compiler module that is needed by parcels?

In principle, the dependencies of the Conda package should be self sufficient. The logic of overriding compiler configs with environment vars in Linux is, however, very confusing.

If I'm not mistaken, we've narrowed down the problem to the `.so` files not being created or (less likely IMO) not being created in the desired place. This could be due to a non-functional compiler config, which in turn might come from an improper activation of the conda environment. Conda's activation process is sometimes buggy on non-interactive shells.

If the env works in an interactive session but not in a non-interactive shell, you can try and explicitly activate with:
```shell
. /home/selipot/miniconda3/bin/activate base
conda activate py3_parcels
```

**Comment by willirath** [comment]
Ah. Means we’re almost there. Here’s what we do on our university cluster for running jupyterlab on compute nodes: 

https://git.geomar.de/python/jupyter_on_HPC_setup_guide/-/blob/master/job-scripts/jupyterlab-slurm.sh#L88

The comment below the linked line could work:
source "${HOME}"/miniconda3/etc/profile.d/conda.sh

---

Dr. Willi Rath
Ozeandynamik
GEOMAR
Helmholtz-Zentrum für Ozeanforschung Kiel
Duesternbrooker Weg 20, Raum 425
24105 Kiel, Germany
------------------------------------------------------------
Tel. +49-431-600-4010
***@***.***
www.geomar.de
-----------------------
Pers. Meeting Room: https://geomar-de.zoom.us/j/2378402733?pwd=NFBaNnRIMVdoS3F1WDVBV01ZcmU2QT09
-----------------------

**Comment by selipot** [comment]
I have tried again to do things properly: 1) from the native anaconda software of my HPC, I have re-created a parcels environment from the environment file for linux, and 2) I am properly activating this environment with the job file sent to the scheduler (as advised by the helpdesk) before executing my code.

Despite this, I am getting the same error (`.so` file missing). I am noting that I **do** need to change the temporary directory from the default `/tmp` to my scratch space, otherwise the temporary folder (`parcels-3477` above) does not even get written, despite what I said earlier (it must have been a remnant from running the code in jupyter hub).

Not sure where to go from here? I am wondering if the package dependencies in the linux environment file for parcels are adequate for my HPC (like `gcc_linux-64`?). I'll try to investigate.

**Comment by selipot** [comment]
I think I have succeeded! My steps were:

1) git clone the parcels repo
2) load the native anaconda software module for my HPC
2) using conda, proceed to conduct the developer installation of parcels using the linux environment file but without the `gcc_linux-64` package (conda install parcels fails because it does not seem to be available for the HPC architecture.)
3) load the native gcc compiler module for my HPC
4) run the `python setup.py install` for parcels
5) make sure to include in my job script the loading of the HPC anaconda and gcc module

And that worked! But since I had to git clone the latest repo I had to modify my code for the zarr output instead of netcdf ... But I can't read the zarr output with xarray! Arg, what do I need to change???

**Comment by JamiePringle** [comment]
For zarr, try the following https://nbviewer.org/github/OceanParcels/parcels/blob/master/parcels/examples/documentation_MPI.ipynb

**Comment by selipot** [comment]
ok crisis averted I needed to install zarr in my environments for analysis. So in the end a shorter test worked! Thank you so much @willirath and @erikvansebille for helping me through this issue! So how does one read the output before the full completion of the execution? We used to be able to generate the netcdf file from the output before the complete execution.
