### ISSUE TITLE
Problem with adding wind field

### ISSUE THREAD

**Issue by Novaoceans** [OceanParcels/parcels#1267]
Hi, I tried to add a wind field to a current field to implement the windage.
But the results are not good. some particles run on the land. What should I do
to fix this issue? Thanks!

These are part of the code:
# the current 
filenames   = {'U': {'lon': mesh_mask, 'lat': mesh_mask, 'depth': wfiles[0], 'data': ufiles},
               'V': {'lon': mesh_mask, 'lat': mesh_mask, 'depth': wfiles[0], 'data': vfiles}}

variables   = {'U': 'uo',
               'V': 'vo'}

dimensions  = {'U': {'lon': 'glamf', 'lat': 'gphif', 'depth': 'depthu', 'time': 'time_counter'},
               'V': {'lon': 'glamf', 'lat': 'gphif', 'depth': 'depthu', 'time': 'time_counter'}}

indices     = {
'U': {'depth': [0]},
'V': {'depth': [0]}
}

fieldset_ocean = FieldSet.from_nemo(filenames, variables, dimensions,indices=indices, allow_time_extrapolation=True)
# the wind 
filenames = {
 'U': {'lon': filepath_coord, 'lat': filepath_coord, 'data': filepath_wind},
 'V': {'lon': filepath_coord, 'lat': filepath_coord, 'data': filepath_wind}
 }

variables = {
'U': 'u_wind',
'V': 'v_wind'
}

dimensions = {
'lat': 'nav_lat',
'lon': 'nav_lon',
'time': 'time_counter'
}

fieldset_wind = FieldSet.from_netcdf(
    filenames,
    variables,
    dimensions,
    chunksize=False,
    allow_time_extrapolation=True)
percentage_wind = 0.5
fieldset_wind.U.set_scaling_factor(percentage_wind/100)
fieldset_wind.V.set_scaling_factor(percentage_wind/100)

# Add the two together, wind and ocean
fieldset_sum = FieldSet(
U=fieldset_wind.U+fieldset_ocean.U,
V=fieldset_wind.V+fieldset_ocean.V)

pset        = ParticleSet.from_list(fieldset=fieldset_sum, pclass=JITParticle,
                lon=lons,
                lat=lats,
                depth=np.zeros_like(lons),
                time=OP_start+repeat_time)

![Figure_musquash_count_30days](https://user-images.githubusercontent.com/116027397/200612916-3680d284-5b90-48f1-8acf-cac95f01232c.png)

**Comment by erikvansebille** [comment]
Dear @Novaoceans; this is of course expected if your wind fields also have values over land. Remember that Parcels does not have a concept of 'land' out-of-the-box.

You could write custom kernels to avoid this, see for example the code for our paper at https://doi.org/10.5194/gmd-12-3571-2019, which you can find at https://github.com/OceanParcels/Parcelsv2.0PaperNorthSeaScripts
