### ISSUE TITLE
Failing test "test_randomvonmises" on master

### ISSUE THREAD

**Issue by VeckoTheGecko** [OceanParcels/parcels#1274]
The `test_randomvonmises` test is failing in the build process on master (as seen in the workflow output of #1273 ).

https://github.com/OceanParcels/parcels/blob/56e988ae0f627ec8994c656f5f4bab71154a2e47/tests/test_diffusion.py#L120-L148

**Comment by VeckoTheGecko** [comment]
I think it might be to do with this line, and potentially a change in Scipy (since no change in `parcels` seems to have triggered the test failing).

https://github.com/OceanParcels/parcels/blob/56e988ae0f627ec8994c656f5f4bab71154a2e47/tests/test_diffusion.py#L146

**Comment by erikvansebille** [comment]
Thanks for reporting this, @VeckoTheGecko! Very strange that the von mises now fails. Seems indeed to be related to the line you mention above. Where before the average of this `scipy_mises` list was `mu` (`=np.pi`), it is now closer to `0`. I have no idea why this doesn't work on the scipy version used in the Github Actions??

I'm not in favour of simply disabling the unit test; better to check what is going on and fix it where/how we can. I'll dig a bit deeper
