### ISSUE TITLE
Pre-commit hooks

### ISSUE THREAD

**Issue by VeckoTheGecko** [OceanParcels/parcels#1285]
Pre-commit allows for the automated running of linting workflows before a commit is finalised, even applying automatic fixes. This is particularly useful for linting, so that linting errors can be corrected before a commit is even made (hence reduced reliance on the linting action to pickup linting errors).

I propose the following hooks as a baseline (a list of popular hooks are available [here](https://github.com/pre-commit/pre-commit-hooks)):
- check-yaml (verify yaml syntax)
- end-of-file-fixer (adds newline to end of files)
- trailing-whitespace (trims trailing whitespace)
- black (autoformats python files, related to #1284)

**Comment by VeckoTheGecko** [comment]
Pre-commit is "opt-in" by default, meaning that code quality errors can slip through if someone isn't using pre-commit. [Pre-commit CI](https://pre-commit.ci/) prevents this by using the pre-commit config to run CI on the codebase. Precommit runs on pull requests, and will automatically make commits to fix issues.

**Comment by erikvansebille** [comment]
Good idea, @VeckoTheGecko. Some of these are already implemented in my own IDE (I use PyCharm). 

But I don't entirely understand why you open an Issue about this. What is broken in Parcels itself and/or what do we need to change?
