### ISSUE TITLE
Codecoverage misses some lines (e.g. in plotting.py)

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/parcels#1302]
The [new codecov.io integration](https://github.com/OceanParcels/parcels/pull/1287) is very nice, but the reporting does not always seem correct. 

For example, the `plotting.py` function does not appear to covered at all on [codecov](https://app.codecov.io/gh/OceanParcels/parcels/blob/increasing_codecoverage/parcels/plotting.py) (except for loading of the functions), even though [the unittest on Ubuntu does report that test_script.py has passed](https://github.com/OceanParcels/parcels/actions/runs/4087919649/jobs/7054526234#step:4:2731) (and even throws the [warning for missing cartopy](https://github.com/OceanParcels/parcels/blob/4f161810eb77b9013e450cb64b7cf0aaaa13d10f/parcels/plotting.py#L278)). 

I really don't understand why this is not reported oncodecov.io then. @VeckoTheGecko, do you have any ideas?

**Comment by VeckoTheGecko** [comment]
I'll take a look this weekend and see if it's a quick fix. Unfortunately I can't give too much time to this if the fix is allusive (due to other commitments, and other priorities of mine in the codebase)

**Comment by erikvansebille** [comment]
Now fixed in the new `test_plotting.py` file (see e.g. https://github.com/OceanParcels/parcels/pull/1296/commits/651d2423c542242b46e03bf2616fa1a167ffab14, https://github.com/OceanParcels/parcels/pull/1296/commits/d85e6599e3b6c46ee797d14473c1ccf573cb85e4 and https://github.com/OceanParcels/parcels/pull/1296/commits/01c362b1f9fbf27f11c5fa3ed0538becdd428006)
