### ISSUE TITLE
Formatting with `black`

### ISSUE THREAD

**Issue by VeckoTheGecko** [OceanParcels/parcels#1326]
I suggest formally adopting [`black`](https://black.readthedocs.io/en/stable) as the code formatter for the codebase. An outline of the `black` code style is available [here](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html).

Adopting `black` has several benefits:
- a more homogenous code style across the codebase
- docstring processing (fixing indentation, and removing trailing whitespace)
- automated handling of many `flake8` issues
- processing line lengths to be <88 characters (allowing for greater visibility in IDEs, and for consistency)
- reducing git diffs
- uncompromising (no thought about configuration needed)

`black` is a widely accepted tool in the scientific Python community, and would bring this package more in line with Python best practice.

## Overriding `black`
> Black reformats entire files in place. It doesn’t reformat lines that end with `# fmt: skip` or blocks that start with `# fmt: off` and end with `# fmt: on`. `# fmt: on/off` must be on the same level of indentation and in the same block, meaning no unindents beyond the initial indentation level between them.

## Ignoring formatting changes in git blame
As the formatter will make bulk changes to the codebase, it can impact "git blame" tooling. Having a `.git-blame-ignore-revs` file ignores these changes in blame, instead pointing to the commit when line functionality was last changed. Commits that are solely composed of formatting changes can have their commit hashes added to this file.

You can then add this to your git config to use automatically during git blame:
`git config blame.ignoreRevsFile .git-blame-ignore-revs`
or use it manually in git blame
`git blame --ignore-revs-file .git-blame-ignore-revs parcels/field.py`

The GitHub UI [supports `.git-blame-ignore-revs` out the box](https://github.blog/changelog/2022-03-24-ignore-commits-in-the-blame-view-beta/).

## Adoption process
There are two ways that `black` can be introduced. All at once (formatting the whole codebase in one commit) or incrementally.

I would suggest an incremental adoption. The codebase has many spots with line length is greater than 88 characters. `black` would format these across multiple lines in such a way that impacts readability. An incremental adoption would allow for more attention to this readability, and allow for manual refactoring to improve readability again in a manageable way less likely to introduce bugs.

Now:
- [ ] Add `black` as dependency and create `.git-blame-ignore-revs`
- Incrementally update modules to use `black`

Later:
- [ ] Add black to `pre-commit` workflow for automated formatting

---
## Example (of black for minimising git diffs)
I've been working on type hints for the `fieldset.py` file, and came across this method formatted with (I assume) some pre-existing formatter. 

```py
def from_netcdf(cls, filenames, variables, dimensions, indices=None, fieldtype=None,
                mesh='spherical', timestamps=None, allow_time_extrapolation=None, time_periodic=False,
                deferred_load=True, chunksize=None, **kwargs):
```
Although this looks good, adding typehints would force the method arguments to be rewrapped. Just adding a typehint to `filenames` could force a diff of 3-4 lines, where using black would just cause a diff of one line (allowing for a cleaner git history).

```diff
 def from_netcdf(
     cls,
-    filenames,
+    filenames: <type annotation>,
     variables,
     dimensions,
     indices=None,
     fieldtype=None,
     mesh: Union[Literal["spherical"], Literal["flat"]] = "spherical",
     timestamps=None,
     allow_time_extrapolation=None,
     time_periodic=False,
     deferred_load=True,
     chunksize=None,
     **kwargs
 ):
```

**Comment by VeckoTheGecko** [comment]
No, this hasn't been implemented. I was avoiding it as it would slap a large diff across the entire codebase and spread some statements across multiple lines (which could impact readability if not also refactored). Thought it could be more effort than its worth in the pursuit of "standardization" (which is subjective anyway).

The main benefit of this would be for the tutorial notebooks which are public facing, and shorter line lengths would be helpful for displaying in the website without horizontal scrolling.

Do you want me to whip up a PR for this for you to check out and decide? Do you think I should apply to `.py` and `.ipynb`, or just `.ipynb`?

I would 100% recommend `black` for new projects though. I love it 😄

**Comment by erikvansebille** [comment]
OK thanks for the clarification, @VeckoTheGecko. I can certainly see the case for using black on all the `.ipynb` notebooks, so that they display better on the docs. Would you indeed want to try implement that?

**Comment by VeckoTheGecko** [comment]
Can do. I'll likely have an implementation up by the end of the week
