### ISSUE TITLE
Particles interaction with land-mask 

### ISSUE THREAD

**Issue by JSoto-Nav** [OceanParcels/parcels#1338]
Hello,
I’m using a very simple implementation of parcels to analyze particle dispersion around the Balearic Islands. I use the `AdvectionRK4` kernel. It works, but some particles show strange behavior when interacting with the land points of the velocity field:
-	Some particles enter the land regions of the domain, or move across small islands. 
-	Other particles arrive to a land point and then stop moving. 

I’ve been looking but could not find documentation in the website about how exactly `AdvectionRK4` define the interaction between particles and land points. Should the particles bounce when they find a land point? I understand that beaching has to be explicitly included, which is not the case in my simulation, so why do some particles stop moving when they reach a land point? 

I would really appreciate if you could indicate me where can I find information about this issue.

Thanks in advance for your help.

**Comment by JamiePringle** [comment]
Where are you getting your flow field? If it specifies flow across land boundaries, this will cause the behavior you see. In particular, we found that if you use data from a C grid model that has been converted to an A grid, all sorts of bad boundary behavior occurs. 

Jamie

**Comment by erikvansebille** [comment]
Indeed, I second @JamiePringle's comment. See also the Delandmeter and VS paper, which discusses these boundary issues at length: https://doi.org/10.5194/gmd-12-3571-2019

Note that Parcels by itself doesn't have a concept 'land'; if you want land, you'll have to add a custom Kernel that deals with land treatment yourself
