### ISSUE TITLE
CalledProcessError with RuntimeError on a PC

### ISSUE THREAD

**Issue by EASurovic** [OceanParcels/parcels#1343]
Hello OceanParcels Team!

My name is Elizabeth Surovic, and I've run into a CalledProcessError with a RuntimeError. I'm a new PhD student at UNSW, and I've been using parcels for about six months to model some larval dispersal patterns over a period of a few months in consecutive years. Lately, I have been receiving this error only when I'm executing the code: 
```
pset.execute(kernels, 
             recovery={ErrorCode.ErrorOutOfBounds: DeleteParticle},
             dt=delta(minutes=5), #time forwards
             output_file=output_file, 
             verbose_progress=False,
             endtime=end_time)
Traceback (most recent call last):

  File ~\Miniconda3\envs\py3_parcels\lib\site-packages\parcels\compilation\codecompiler.py:228 in _create_compile_process_
    subprocess.check_call(cmd, stdout=logfile, stderr=logfile)

  File ~\Miniconda3\envs\py3_parcels\lib\subprocess.py:369 in check_call
    raise CalledProcessError(retcode, cmd)

CalledProcessError: Command '['gcc', '-Wall', '-fPIC', '-std=gnu11', '-IC:\\Users\\z5380297\\Miniconda3\\envs\\py3_parcels\\lib\\site-packages\\parcels\\include', '-I.', '-g', '-O3', '-DDOUBLE_COORD_VARIABLES', '-m64', '-o', 'C:\\Users\\z5380297\\AppData\\Local\\Temp\\parcels-tmp\\lib72554b68e526929d6d4891d155cf9404_0.dll', 'C:\\Users\\z5380297\\AppData\\Local\\Temp\\parcels-tmp\\72554b68e526929d6d4891d155cf9404_0.c', '-shared', '-lm', '-m64']' returned non-zero exit status 1.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  Cell In[66], line 1
    pset.execute(kernels,

  File ~\Miniconda3\envs\py3_parcels\lib\site-packages\parcels\particleset\baseparticleset.py:340 in execute
    self.kernel.compile(compiler=GNUCompiler(cppargs=cppargs, incdirs=[path.join(get_package_dir(), 'include'), "."]))

  File ~\Miniconda3\envs\py3_parcels\lib\site-packages\parcels\kernel\basekernel.py:253 in compile
    compiler.compile(self.src_file, self.lib_file, self.log_file)

  File ~\Miniconda3\envs\py3_parcels\lib\site-packages\parcels\compilation\codecompiler.py:292 in compile
    super(GNUCompiler_SS, self).compile(src, obj, log)

  File ~\Miniconda3\envs\py3_parcels\lib\site-packages\parcels\compilation\codecompiler.py:270 in compile
    self._create_compile_process_(cc, src, log)

  File ~\Miniconda3\envs\py3_parcels\lib\site-packages\parcels\compilation\codecompiler.py:244 in _create_compile_process_
    raise RuntimeError(err)

RuntimeError: Error during compilation:
Compilation command: gcc -Wall -fPIC -std=gnu11 -IC:\Users\z5380297\Miniconda3\envs\py3_parcels\lib\site-packages\parcels\include -I. -g -O3 -DDOUBLE_COORD_VARIABLES -m64 -o C:\Users\z5380297\AppData\Local\Temp\parcels-tmp\lib72554b68e526929d6d4891d155cf9404_0.dll C:\Users\z5380297\AppData\Local\Temp\parcels-tmp\72554b68e526929d6d4891d155cf9404_0.c -shared -lm -m64
Source/Destination file: C:\Users\z5380297\AppData\Local\Temp\parcels-tmp\72554b68e526929d6d4891d155cf9404_0.c
Log file: C:\Users\z5380297\AppData\Local\Temp\parcels-tmp\72554b68e526929d6d4891d155cf9404_0.log

Log output: C:\Users\z5380297\AppData\Local\Temp\parcels-tmp\72554b68e526929d6d4891d155cf9404_0.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 #include "parcels.h"
 ^
C:\Users\z5380297\AppData\Local\Temp\parcels-tmp\72554b68e526929d6d4891d155cf9404_0.c: In function 'AdvectionRK4SampleAgeSampleDistance':
C:\Users\z5380297\AppData\Local\Temp\parcels-tmp\72554b68e526929d6d4891d155cf9404_0.c:149:55: error: 'delta' undeclared (first use in this function)
   particles->age[pnum] = (particles->age[pnum] + fabs(delta));
                                                       ^
C:\Users\z5380297\AppData\Local\Temp\parcels-tmp\72554b68e526929d6d4891d155cf9404_0.c:149:55: note: each undeclared identifier is reported only once for each function it appears in

If you are on macOS, it might help to type 'export CC=gcc'
```
I'm not sure what to do as I'm using a Dell Laptop for this and not a macOS. I've tried reading other threads here for help and checking my packages to see if it's an updating issue. Nothing is working so far. These errors only happen when I try to run the "pset.execute" part of my code, but there are no error messages in the code itself. 

The version of Parcels I have is: 2.4.1

If any more information is needed, I'm happy to supply it. 

Finally, any help with this issue would be greatly appreciated. Thank you all for your time and support!

Kind Regards, 
Elizabeth Surovic

**Comment by VeckoTheGecko** [comment]
Hi Elizabeth,
I think this could be an issue with your kernels (and how they're translated to C code in the compiler).

Would you be able to provide your code/notebook that encounters this error? You're welcome to trim it down if you want to just leave the parcels parts. If you zip up the files you can attach the zip to your reply here.

**Comment by EASurovic** [comment]
Hi Vecko, 

Thank you for your quick response. These are the lines of code that give me this error. 
```
pset.execute(kernels, 
             recovery={ErrorCode.ErrorOutOfBounds: DeleteParticle},
             dt=delta(minutes=5), #time forwards
             output_file=output_file, 
             verbose_progress=False,
             endtime=end_time)
```
I'm not sure that's enough of it to be helpful, but this is the part of my code that gives me those errors when I run it. 

Here are the kernels I create/define in case this is useful for understanding the above. 
```
fieldset.add_constant('maxage', 40.*86400)

random.seed(123456) # Set random seed

class SampleParticle(JITParticle):         # Define a new particle class
    age = Variable('age', dtype=np.float32, initial=0.) # initialise age
    distance = Variable('distance', initial=0., dtype=np.float32)  # the distance travelled
    prev_lon = Variable('prev_lon', dtype=np.float32, to_write=False,
                        initial=attrgetter('lon'))  # the previous longitude
    prev_lat = Variable('prev_lat', dtype=np.float32, to_write=False,
                        initial=attrgetter('lat'))  # the previous latitude.

def SampleDistance(particle, fieldset, time):
    lat_dist = (particle.lat - particle.prev_lat) * 1.11e2  # Calculate the distance in latitudinal direction (using 1.11e2 kilometer per degree latitude)
    lon_dist = (particle.lon - particle.prev_lon) * 1.11e2 * math.cos(particle.lat * math.pi / 180)  # Calculate the distance in longitudinal direction, using cosine(latitude) - spherical earth
    particle.distance = math.sqrt(math.pow(lon_dist, 2) + math.pow(lat_dist, 2)) # Calculate the total Euclidean distance travelled by the particle
    particle.prev_lon = particle.lon  # Set the stored values for next iteration.
    particle.prev_lat = particle.lat

def SampleAge(particle, fieldset, time):
    particle.age = particle.age + math.fabs(delta)
    if particle.age > fieldset.maxage:
        particle.delete()

start_time = np.repeat(start_time,len(lon))

## NEXT DEFINE THE PARTICLES AND WHERE YOU WANT THEM
pset = ParticleSet.from_list(fieldset, 
                             pclass=SampleParticle,
                             lon=lon,
                             lat=lat,
                             time=start_time,
                             repeatdt=repeatdt)

## FINALLY, SET UP THE OUTPUT SO YOU CAN CREATE A NEW FILE WITH YOUR PARTICLES RUNNING IN IT 
output_file = pset.ParticleFile(name = "oscar_vel15yr_Rar90d.zarr", outputdt=delta(days = 1))

kernels = pset.Kernel(AdvectionRK4) + SampleAge + SampleDistance #BrownianMotion2D 


# the "CalledProcessError" and "RuntimeError" happen at the actual execution.
pset.execute(kernels, 
             recovery={ErrorCode.ErrorOutOfBounds: DeleteParticle},
             dt=delta(minutes=5), #time forwards
             output_file=output_file, 
             verbose_progress=False,
             endtime=end_time)
```

The data I've been using is OSCAR data. If you need some of that, I can try to add it, but that will be pretty difficult.

**Comment by VeckoTheGecko** [comment]
The error is in
```py
def SampleAge(particle, fieldset, time):
    particle.age = particle.age + math.fabs(delta)
    if particle.age > fieldset.maxage:
        particle.delete()
```
as `delta` is not undefined here. I think you want `particle.dt` instead which gives the delta in seconds (as shown in section `3. Kernels` in the [Parcels Structure tutorial](https://nbviewer.org/github/OceanParcels/parcels/blob/master/parcels/examples/tutorial_parcels_structure.ipynb).

Hope that helps!

**Comment by EASurovic** [comment]
Hi Vecko, 

Thank you for your suggestion. I tried your suggestion, but that doesn't fix the issue. I've defined `delta` from `from datetime import timedelta as delta`. So changing `delta` in the `SampleAge` doesn't work. I get an error that I haven't defined `dt`. There must be something else wrong. I can add more of my code if that will help.

Kind Regards, 
Elizabeth Surovic

**Comment by erikvansebille** [comment]
Hi Elizabeth, note that within the Kernel, you can't access functions that you imported in python. See the list of what you can and can't use in kernels under the header `Kernels` in the [General Parcels tutorial](https://nbviewer.org/github/OceanParcels/parcels/blob/master/parcels/examples/tutorial_parcels_structure.ipynb)

It's strange that there's now a compilation error with `dt`, because your SampleAge kernel above doesn't have a `dt`. Could that come from another kernel?

**Comment by VeckoTheGecko** [comment]
> I get an error that I haven't defined `dt`.

Just reiterating that the correction is to add `particle.dt` (not just `dt`). The `.dt` attribute for particles is available for all particles (along with attributes `particle.lon`, `particle.lat`, `particle.fieldset`, `particle.time`, and any other custom variables you define for that particle (e.g. `particle.age`)). This is shown in the [documentation for JITParticle](https://parcels.readthedocs.io/en/latest/#parcels.particle.JITParticle).

The updated code would be
```diff
def SampleAge(particle, fieldset, time):
-   particle.age = particle.age + math.fabs(delta)
+   particle.age = particle.age + math.fabs(particle.dt)
    if particle.age > fieldset.maxage:
        particle.delete()
```

Generally, as mentioned by Erik, kernel functions are somewhat basic in what they accept (as the code needs to be translated to C code). A good rule of thumb is that in your kernel function if you want pass data into the kernel, it has to be passed by adding the data to the particle or the fieldset. In this case, the delta you're looking for is already an attribute of the particle (`particle.dt`). *Importing `delta`, although would make the keyword available to Python functions, it does not make it available for parcels kernels.*

Also note that `delta` (as defined by `from datetime import timedelta as delta`) is not a value but a function. Its a function that returns a Python object allowing to work with time intervals in a human friendly way.

- typing `delta` by itself is improper use of the function and does nothing
- typing `delta(days=1, hours=2, minutes=20)` creates a `datetime.timedelta` object in Python
- typing `delta(days=1, hours=2, minutes=20).total_seconds()` returns a `float` with the number of seconds in the interval

---

If you're still experiencing difficulty, please provide error logs as well as code as that allows us to help more.
