### ISSUE TITLE
Create kernels from list of Python functions

### ISSUE THREAD

**Issue by VeckoTheGecko** [OceanPARCELS/parcels#1347]
Programmatically combining kernels is useful for those who are interested in running various simulations with different particle behaviour.

Currently kernels can be combined by hardcoding:
```py
# Define your kernel functions
# ...

# Combine kernels
combined_kernel = pset.Kernel(kernel_1) + pset.Kernel(kernel_2) + pset.Kernel(kernel_3)
```

If you want to create a combined kernel from a list, you can do:
```py
import functools

# Define your kernel functions
# ...

def get_combined_kernel(pset, kernel_lst):
    """
    Returns a combined kernel given a list of kernels.
    """
    kernels = (pset.Kernel(i) for i in kernel_lst)
    return functools.reduce(lambda x, y: x+y, kernels)

kernel_lst = [kernel_1, kernel_2, kernel_3]
combined_kernel = get_combined_kernel(pset, kernel_lst)
```

Although this second method is much nicer and much more extensible (not requiring things to be hardcoded, and allowing for the programmatic creation of the list by appending the functions as needed), its not accesible for those who are not as familiar with Python (and the `functools` package). Adding native parcels support for creating kernels from a list of functions would be nice, especially since I imagine this isn't an uncommon usecase.

**solution:**  
```py
combined_kernel = pset.Kernel.from_list(
    [kernel_1, kernel_2, kernel_3]
)
```

---
Anecdotally, I used this in my work when investigating beaching strategies of plastic particles.

I'm happy to work on this (just wanting to check if this is a good feature, get feedback, and whether its congruent with the API design).

**Comment by VeckoTheGecko** [comment]
cc @mheen this was what I was talking about. Keen to know if you have any suggestions here 😄

**Comment by VeckoTheGecko** [comment]
hmmm. Giving a quick look at the codebase I'm not sure how feasible the `combined_kernel = pset.Kernel.from_list([kernel_1, kernel_2, kernel_3])` solution is. Will need to give this a think about how it will fit into the api...

**Comment by erikvansebille** [comment]
I think this is a great idea! Having a way to more easily merge lists of Kernels would really benefit workflows. It could be via a `pset.Kernel.from_list()` method, or it could even be the default behaviour when the first argument of `pset.Kernel()` is a list. 

And I actually don't think it should be too difficult to implement. Have a look add how `pset.Kernel().__add__` is implemented:
https://github.com/OceanParcels/parcels/blob/28f231fab4b35dfc8df697fee23cc9a2658f379b/parcels/kernel/basekernel.py#L277-L280
Which simply calls `pset.Kernel().merge()`
https://github.com/OceanParcels/parcels/blob/28f231fab4b35dfc8df697fee23cc9a2658f379b/parcels/kernel/basekernel.py#L264-L275

An implementation for lists could therefore iteratively call `pset.Kernel().merge()` for each item in the list?

Do you want to give it a try, @VeckoTheGecko, or do you want me to have a stab at this implementation?

**Comment by VeckoTheGecko** [comment]
I definitely think this will be an easy feature to patch in.

`pset.Kernel()` itself is a method as shown here
https://github.com/OceanParcels/parcels/blob/28f231fab4b35dfc8df697fee23cc9a2658f379b/parcels/particleset/particlesetaos.py#L659-L665

So it won't be possible to do `pset.Kernel.from_list()` as I initially thought. Having it be the behaviour of `pset.Kernel` when the first argument is a list is a good solution instead (I don't love how its implicit, but lacking a better solution it should be good).

Happy to work on this once you confirm API design 😄
