### ISSUE TITLE
Parcels within eReefs GBR

### ISSUE THREAD

**Issue by Dinga1990** [OceanParcels/parcels#1354]
Hi, 

I'm a student and new to GitHub. I'm looking at drifters in the Great Barrier Reef. I have been using this tutorial https://tristansalles.github.io/EnviReef/6-addson/parcels.html however I want to use the raw data with hourly output from here: https://dapds00.nci.org.au/thredds/dodsC/fx3/gbr1_2.0/gbr1_simple_2022-05-14.nc.html

This raw data uses a C-grid however I'm struggling to get it to work after using the NEMO C-grid tutorials. I was wondering if someone can help me out, as I haven't been able to crack this in a week.
Ereef details are here: https://research.csiro.au/ereefs/models/ 

I’m trying not to re-grid the data as has been done previously. I have some MATLAB code to re-grid, which I would need to convert to python. However, the end goal is to have a single notebook that would be able to run anywhere within the eReefs domain so it can be used by other students and researchers.

Other notes: 
- Using parcels 2.4.1 in a Conda environment. 
- 
Matt

**Comment by Dinga1990** [comment]
[Ereef_parcels-daily - GITHUB.pdf](https://github.com/OceanParcels/parcels/files/11358491/Ereef_parcels-daily.-.GITHUB.pdf)

**Comment by VeckoTheGecko** [comment]
Hello, greetings from WA 😄 . I think building in compatability for parcels to act natively with model output is a great idea. 

A few things:
* Would you mind uploading a NetCDF file to [WeTransfer](https://wetransfer.com/)? I'm not familiar with subsetting data from OPeNDAP, and the UI wasn't intuitive to me.
* Would you mind providing a reproducible code sample, and your full error log? See [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) for how you can include code in GitHub with or without syntax highlighting.

Having the data + code + full error log will allow us to replicate the issue, and better help.

Just a heads up, I don't really have time to give this a proper look this weekend. I'll see if I can take a closer look Mon/Tues.

**Comment by Dinga1990** [comment]
@VeckoTheGecko Thanks! I didn't expect answers on the weekend so any help is better than me going in spirals. 

The native file is 7GB, so WeTransfer will not work. Here is the direct data link: 
https://dapds00.nci.org.au/thredds/fileServer/fx3/gbr1_2.0/gbr1_simple_2022-05-01.nc

I will work on the second part tonight.

**Comment by Dinga1990** [comment]
Parcels with eReef simple.ipynb

**Comment by Dinga1990** [comment]
https://github.com/Dinga1990/Drifter_eReefs/blob/main/Parcels%20with%20eReef%20simple.ipynb

**Comment by Dinga1990** [comment]
After discussion with the CSIRO regarding the grid, it was discovered that the data was re-grid from C-grid to A-grid already as raw output. There are working with the dimensions, I was able to get the code running.  Code is here: 
https://github.com/Dinga1990/Drifter_eReefs/blob/main/Parcels%20with%20eReef%20simple.ipynb

**Comment by JamiePringle** [comment]
One word of warning -- using C-grid model data that has been re-gridded to A-grid will lead to problems near all solid boundaries, as the flow field boundary condition of no-flow through the bottom is not generally captured by the A-grid data. At a minimum, this will cause problems with particles moving through land or bottom boundaries. It is MUCH, MUCH better to use the original C-grid data.  Happy to chat more about this. 

You will see this as a problem if you see particles going into the bottom or onto land...
