### ISSUE TITLE
`parcels_get_examples` deprecation notice

### ISSUE THREAD

**Issue by VeckoTheGecko** [OceanParcels/parcels#1376]
I only realised post release that replacing `parcels_get_examples` with a deprecation notice would probably be a better user experience than outright removing the command. Something like:

```
$ parcels_get_examples parcels_examples
The parcels_get_examples command has been deprecated since parcels v2.4.2. Notebooks are now
standalone as they download data on the fly. Please see the latest Parcels documentation for the
updated notebooks and instructions on how to download them.

https://docs.oceanparcels.org/en/latest/documentation.html

```
Thoughts?

**Comment by erikvansebille** [comment]
This is an interesting idea @VeckoTheGecko, but I don't think that many users regularly call this command. Only upon installation, but then they will follow the installation guide, where reference to `parcels_get_examples` is now gone. Also, providing this message would require yet another release before users would see it?
