### ISSUE TITLE
Auto-update CITATION.cff file

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/parcels#1386]
The CITATION.cff file should be updated after every new release (see also #1385). I've looked around a bit ([there's a list here](https://github.com/citation-file-format/citation-file-format#tools-to-work-with-citationcff-files-wrench)), but didn't find an easy way to automate this using e.g. GitHu Actions?

@VeckoTheGecko, have you seen tools to automate this?

**Comment by VeckoTheGecko** [comment]
I'm not familiar with tooling to edit `.cff` files (the most I've worked with citations is using `doi2bib`, but that's unrelated).

Looking at `pandas`, `matplotlib`, `xarray`, and `seaborn`, neither of them have entries for `version` in their `CITATION.cff`/`CITATION.bib` files. On the [citing page of the Pandas website](https://pandas.pydata.org/about/citing.html) (different to citing in GitHub), they list the version as `latest`. Is maintaining the version in the file important in a research context?

If you'd like to update the version, I think doing it manually would be less effort (especially given infrequent releases) and less complex than automating it. Perhaps adding it to a checklist of tasks to do in a release.

**Comment by erikvansebille** [comment]
OK, thanks for chipping in, @VeckoTheGecko. I do think it's important to have the latest version in the CITATION, but we can then update it manually
