### ISSUE TITLE
Running notebooks in RTD CI

### ISSUE THREAD

**Issue by VeckoTheGecko** [OceanParcels/parcels#1391]
Just saw
![image](https://github.com/OceanParcels/parcels/assets/36369090/76ab75e5-f574-4780-860c-cb5895dd6612)
in #1389.

Now that notebooks are standalone (#1355), should I now explore the possibility of running all notebooks as part of RTD CI?

Pros:
- Never need to worry about re-running outputs manually
- Minimal diffs (and small notebook size)

Cons:
- RTD build process will take a while (meaning that PRs won't have a quick preview of the docs available)
- Notebooks downloaded as ZIPs won't have outputs visible
- Requires maintaining a list of additional dependencies for notebooks, instead of the current dependencies (just `environment_py3_linux.yml`)
https://github.com/OceanParcels/parcels/blob/0dcbfe35645dafd0cdc9aedb53c6420b465d2c62/.readthedocs.yaml#L13-L14
- Loss of distinction between `tutorial` and `documentation` notebooks (as all will need to be run)

**Comment by VeckoTheGecko** [comment]
We can also add the [`nb-ensure-clean`](https://gitlab.com/iamlikeme/nbhooks/-/blob/master/.pre-commit-hooks.yaml) pre-commit hook to the repo.

**Comment by VeckoTheGecko** [comment]
Was just looking at [a part of the RTD documentation](https://docs.readthedocs.io/en/stable/builds.html), and this might not even be possible due to build time limits:

![image](https://github.com/OceanParcels/parcels/assets/36369090/6db57b5c-85d8-48dc-9f11-afb505795c43)

Happy to give it a stab, but I only see this working using the RTD build process if that part of their docs is out of date, or I'm somehow misinterpretting it 😅

**Comment by VeckoTheGecko** [comment]
I don't think that this issue is viable unless huge changes are made to speedup notebook execution to below 15 mins (realistically, about <7 mins due to the time taken to install the environment). Closing.

**Comment by erikvansebille** [comment]
Thanks for checking this, @VeckoTheGecko. I agree that it will be very challenging to get the build time under 15 minutes. 

Also, I would be hesitant to publish notebook figures without having checked them ourselves; it would mean that we would every time have to double-check the docs after making a change to the notebooks. 

So let's leave the current workflow in place
