### ISSUE TITLE
Create explicit test script which ensures the installed package works as intended?

### ISSUE THREAD

**Issue by willirath** [OceanParcels/parcels#1395]
In https://github.com/conda-forge/parcels-feedstock/pull/98, we're discussing how to ensure that the installed Parcels package and all dependencies work as intended (especially in the JITParticle case which is the one requiring careful setup of the environment).

Currently, the package is tested by running the peninsula example. This test can, however, complete successfully even if the compilers installed as a dependency of the parcels conda package are not working, if parcels falls back to compilers provided by the operating system.

Maybe we can add a script (not sure where) which sets up the compiler and logs path, version, etc. of the compiler which it found and fails if there's no compiler found? Having this as part of the Parcels repository rather than in the Conda-Forge feedstock feels more natural as here also would be the place where any future changes of the way JIT compilation is done would happen.

**Comment by erikvansebille** [comment]
I think this is a very good idea, @willirath. We could make a `tests/test_compliation.py` script and run that with `pytest` on conda-forge? Could you make a proposal what it exactly needs to test then?

**Comment by willirath** [comment]
> @erikvansebille and @willirath, we could also try to run more of your test suite (unless it takes forever) on the conda-forge side. Would you like me to enable that in [conda-forge/parcels-feedstock#98](https://github.com/conda-forge/parcels-feedstock/pull/98)?

Not sure this is necessary. The run of the one example script in https://github.com/ngam/parcels-feedstock/blob/aarches/recipe/meta.yaml#L60 already includes the one critical dependency as it triggers the just-in-time compilation part of the logic of Parcels.

**Comment by erikvansebille** [comment]
I think this is fixed in https://github.com/conda-forge/parcels-feedstock/blob/50ab3a48c31416a926185101cfbb339de49940d5/recipe/meta.yaml#L59-L60
