### ISSUE TITLE
Vector plotting issue for C-grid data

### ISSUE THREAD

**Issue by RicCrocker** [OceanParcels/parcels#1398]
This is something which I think only affects the plotting of vectors when using c-grid data.
(and I appreciate that the plotting is not the focus of the package)

I was looking at the quiver plots for some c-grid data and noticed that the vectors appeared to be significantly diagonal (something that doesn't occur when working through e.g the GlobCurrent exmple).

pset.show(field="vector",domain={"N": 20, "S": 0, "E": 100, "W": 80})

   
![FIXTESTORIG](https://github.com/OceanParcels/parcels/assets/36732502/bbdf04b2-e37a-4e70-9317-58ea2f672d26)

Digging into plotting.py, it looks like the U component of the field is being used as the V component (for vectors and subsequently to calculate the speed for the underlying field) when the data is transformed to an A-grid from C-grid.

I think the fix is simply to change the regrid of V to use data[1] instead of data[0] 
e.g             
d[:, :-1] = (data[1][:, :-1] + data[1][:, 1:]) / 2.
d[:, -1] = data[1][:, -1]

This gives me something which appears more realistic e.g

![FIXTESTWITHFIX](https://github.com/OceanParcels/parcels/assets/36732502/e0b3a746-27a8-4066-8ce3-6492222df3d8)

Thanks for developing Parcels

Ric

**Comment by erikvansebille** [comment]
Thanks for reporting this, @RicCrocker! I think you're right about the bug. If you want, feel free to create a Pull Request that fixes this (and get recognised for the contribution)

However, do note that we are currently _removing_ all the plotting methods from Parcels (in #1397), so from the next version there will be no more `pest.show()` method. Up to you whether you still want to fix the bug; but you'll have to be quick 😉

**Comment by erikvansebille** [comment]
Since `Field.show()` is now deprecated in #1397, this issue is not relevant anymore; so closing
