### ISSUE TITLE
Broken anchor `http://oceanparcels.org/#parallel_install`

### ISSUE THREAD

**Issue by VeckoTheGecko** [OceanParcels/parcels#1418]
Has the location of the instructions changed now? http://oceanparcels.org/#parallel_install

https://github.com/OceanParcels/parcels/blob/fb7be59c8ce19d72120727dd766f0a50a70456a7/docs/examples/documentation_MPI.ipynb#L16
https://github.com/OceanParcels/parcels/blob/fb7be59c8ce19d72120727dd766f0a50a70456a7/parcels/collection/collectionaos.py#L28
https://github.com/OceanParcels/parcels/blob/fb7be59c8ce19d72120727dd766f0a50a70456a7/parcels/collection/collectionsoa.py#L81

**Comment by erikvansebille** [comment]
Thanks @VeckoTheGecko, for sorting this out. #1419 fixed this!
