### ISSUE TITLE
Parcels Tutorial Issue: RuntimeError: Error during compilation

### ISSUE THREAD

**Issue by kbhawes** [OceanParcels/parcels#1425]
Hi, I'm trying to work through the parcels quickstart tutorial and when I get to executing the particleset, I'm getting this error. I'm not really sure what's going on. 

---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
File ~\Anaconda3\envs\parcels\Lib\site-packages\parcels\compilation\codecompiler.py:234, in CCompiler._create_compile_process_(self, cmd, src, log)
    233 try:
--> 234     subprocess.check_call(cmd, stdout=logfile, stderr=logfile)
    235 except OSError:

File ~\Anaconda3\envs\parcels\Lib\subprocess.py:413, in check_call(*popenargs, **kwargs)
    412         cmd = popenargs[0]
--> 413     raise CalledProcessError(retcode, cmd)
    414 return 0

CalledProcessError: Command '['cl.exe', '-Wall', '-fPIC', '-std=gnu11', '-IC:\\Users\\21515867\\Anaconda3\\envs\\parcels\\Lib\\site-packages\\parcels\\include', '-I.', '-g', '-O3', '-DDOUBLE_COORD_VARIABLES', '-m64', '-o', 'C:\\Users\\21515867\\AppData\\Local\\Temp\\parcels-tmp\\lib94358014a7e7cfbf773978a351b334e3_0.dll', 'C:\\Users\\21515867\\AppData\\Local\\Temp\\parcels-tmp\\94358014a7e7cfbf773978a351b334e3_0.c', '-shared', '-lm', '-m64']' returned non-zero exit status 4.

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
Cell In[8], line 5
      1 output_file = pset.ParticleFile(
      2     name="EddyParticles.zarr",  # the file name
      3     outputdt=timedelta(hours=1),  # the time step of the outputs
      4 )
----> 5 pset.execute(
      6     AdvectionRK4,  # the kernel (which defines how particles move)
      7     runtime=timedelta(days=6),  # the total length of the run
      8     dt=timedelta(minutes=5),  # the timestep of the kernel
      9     output_file=output_file,
     10 )

File ~\Anaconda3\envs\parcels\Lib\site-packages\parcels\particleset\baseparticleset.py:438, in BaseParticleSet.execute(self, pyfunc, pyfunc_inter, endtime, runtime, dt, moviedt, recovery, output_file, movie_background_field, verbose_progress, postIterationCallbacks, callbackdt)
    436         self.kernel.remove_lib()
    437         cppargs = ['-DDOUBLE_COORD_VARIABLES'] if self.collection.lonlatdepth_dtype else None
--> 438         self.kernel.compile(compiler=GNUCompiler(cppargs=cppargs, incdirs=[path.join(get_package_dir(), 'include'), "."]))
    439         self.kernel.load_lib()
    441 # Set up the interaction kernel(s) if not set and given.

File ~\Anaconda3\envs\parcels\Lib\site-packages\parcels\kernel\basekernel.py:262, in BaseKernel.compile(self, compiler)
    260         if self.src_file is not None:
    261             all_files_array.append(self.src_file)
--> 262         compiler.compile(self.src_file, self.lib_file, self.log_file)
    263 if len(all_files_array) > 0:
    264     logger.info(f"Compiled {self.name} ==> {self.lib_file}")

File ~\Anaconda3\envs\parcels\Lib\site-packages\parcels\compilation\codecompiler.py:298, in GNUCompiler_SS.compile(self, src, obj, log)
    295 lib_pathdir = os.path.dirname(obj)
    296 obj = os.path.join(lib_pathdir, lib_pathfile)
--> 298 super().compile(src, obj, log)

File ~\Anaconda3\envs\parcels\Lib\site-packages\parcels\compilation\codecompiler.py:270, in CCompiler_SS.compile(self, src, obj, log)
    268 with open(log, 'w') as logfile:
    269     logfile.write(f"Compiling: {cc}\n")
--> 270 self._create_compile_process_(cc, src, log)

File ~\Anaconda3\envs\parcels\Lib\site-packages\parcels\compilation\codecompiler.py:239, in CCompiler._create_compile_process_(self, cmd, src, log)
    237     except subprocess.CalledProcessError:
    238         with open(log) as logfile2:
--> 239             raise RuntimeError(f"Error during compilation:\n"
    240                                f"Compilation command: {cmd}\n"
    241                                f"Source/Destination file: {src}\n"
    242                                f"Log file: {logfile.name}\n"
    243                                f"Log output: {logfile2.read()}\n"
    244                                f"\n"
    245                                f"If you are on macOS, it might help to type 'export CC=gcc'")
    246 return True

RuntimeError: Error during compilation:
Compilation command: ['cl.exe', '-Wall', '-fPIC', '-std=gnu11', '-IC:\\Users\\21515867\\Anaconda3\\envs\\parcels\\Lib\\site-packages\\parcels\\include', '-I.', '-g', '-O3', '-DDOUBLE_COORD_VARIABLES', '-m64', '-o', 'C:\\Users\\21515867\\AppData\\Local\\Temp\\parcels-tmp\\lib94358014a7e7cfbf773978a351b334e3_0.dll', 'C:\\Users\\21515867\\AppData\\Local\\Temp\\parcels-tmp\\94358014a7e7cfbf773978a351b334e3_0.c', '-shared', '-lm', '-m64']
Source/Destination file: C:\Users\21515867\AppData\Local\Temp\parcels-tmp\94358014a7e7cfbf773978a351b334e3_0.c
Log file: C:\Users\21515867\AppData\Local\Temp\parcels-tmp\94358014a7e7cfbf773978a351b334e3_0.log
Log output: fatal error C1510: Cannot load language resource clui.dll.

If you are on macOS, it might help to type 'export CC=gcc'

**Comment by erikvansebille** [comment]
Thanks for reporting @kbhawes. On which operating system are you?

**Comment by kbhawes** [comment]
Hi erik, I'm on Windows 10

**Comment by erikvansebille** [comment]
Hmm I don't run Windows myself, so can't help much. I can't remember having seen this error with other windows users before. Perhaps you can do a google search for the error: `Cannot load language resource clui.dll`

**Comment by kbhawes** [comment]
Oh I didn't even see that line in the error code! Thank you. For anyone else who comes across this error, the issue was that the paths parcels was using to try and find cl.exe, clui.dll, and mvpdb140.dll were wrong. My solution was just to copy those files to a location parcels would look.

**Comment by apatlpo** [comment]
> My solution was just to copy those files to a location parcels would look.

Hi Kelly ;)
You may want to specify which location that is
