### ISSUE TITLE
Overlapping time values while creating a FieldSet

### ISSUE THREAD

**Issue by martoconnh** [OceanParcels/parcels#1440]
I'm having an issue while creating a fieldset from my own netCDF files, some time values might be overlapping. 

`fieldset = FieldSet.from_netcdf(nc_files_list, variables, dimensions)`

And I'm given the following error:

```
Traceback (most recent call last):

  File ~\anaconda3\Lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\marto\documents\universidade\tfg\proba parcels\parcels_arousa1.py:32
    fieldset = FieldSet.from_netcdf(archivos_nc4, variables, dimensions)

  File ~\anaconda3\Lib\site-packages\parcels\fieldset.py:470 in from_netcdf
    fields[var] = Field.from_netcdf(paths, (var, name), dims, inds, grid=grid, mesh=mesh, timestamps=timestamps,

  File ~\anaconda3\Lib\site-packages\parcels\field.py:443 in from_netcdf
    time, time_origin, timeslices, dataFiles = cls.collect_timeslices(timestamps, data_filenames,

  File ~\anaconda3\Lib\site-packages\parcels\field.py:288 in collect_timeslices
    raise AssertionError(f'Please make sure your netCDF files are ordered in time. First pair of non-ordered files: {dataFiles[id_not_ordered]}, {dataFiles[id_not_ordered + 1]}')

AssertionError: Please make sure your netCDF files are ordered in time. First pair of non-ordered files: C:\Users\Marto\Documents\UNIVERSIDADE\TFG\FICHEIROS_AROUSA\hidrodinamicos\MOHID_Hydrodynamic_Arousa_20170901_0000.nc4, C:\Users\Marto\Documents\UNIVERSIDADE\TFG\FICHEIROS_AROUSA\hidrodinamicos\MOHID_Hydrodynamic_Arousa_20170902_0000.nc4
```

Is there any way I can run my fieldset over overlapping time values? Or shall I modify my netCDF files in order to erase the overlapped values?

**Comment by michaeldenes** [comment]
Hi @martoconnh, I'm not sure what you mean by overlapping time values. Is your data simply unordered? Or, somehow, your data specifies a range of time values for your velocities? If the former, you could simply load your netcdf files with xarray, perform a sort by time, and then construct the fieldset using the from_xarray_dataset function. If the latter, I've no idea (never seen that before!) but maybe discretise your data? Let me know how you go!

**Comment by martoconnh** [comment]
Hi! I will definetely try that, thank you!

Anyway, I'll try to explain better what I was trying to say earlier. I am using a list of netcdf files, each one has dimensions (lat,lon,time) and variables u,v (zonal and meridional velocities). In each file, both latitude and longitude dimensions are the same, but time is variable.

Every day, some real data are collected in order to generate some simulated data for the following 49 hours. In consequence, each file has 49 time values. For instance, file1 has 24h from day 1, 24h from day 2 and 1h from day 3. Then file2 starts with some new data for day 2, so it counts 49 hours since day 2 starts (same with file3 and so on). 

Data from day 2 is more precise in file2 than the simulated data from file1 (as the simulation in file2 is based on more recent real data), so I was wondering if there's any way that I can just read data for the first 24 time values (24 hours) in each file.

If not, the only way I can think of to solve this, is to erase the data from the last 25 time values in each file. I'm sorry, it was way more complex than I actually thought in the first place, I should have explained it better earlier.
