### ISSUE TITLE
Requirement to run `pull_data.py` is undocumented.

### ISSUE THREAD

**Issue by dham** [OceanPARCELS/parcels#149]
The install instructions don't actually tell the user to run `pull_data.py`. The only place this seems to be mentioned is in .travis.yml

**Comment by erikvansebille** [comment]
This is also discussed in Issue #104. Will fix soon

**Comment by fischcheng** [comment]
I cloned the repo and tried to follow the tutorials and run the test files but realized that I didn't have the velocity fields. Thx for mentioning that there is a `pull_data.py`. And yes, it needs to be included in the README.md or the tutorials, or others will just be clueless like me. (unless it will be automatically triggerd as in #104 )

**Comment by fischcheng** [comment]
I cloned the repo and tried to follow the tutorials and run the test files but realized that I didn't have the velocity fields. Thx for mentioning that there is a `pull_data.py`. And yes, it needs to be included in the README.md or the tutorials, or others will just be clueless like me. (unless it's automatically triggerd as discussed in #104 )

**Comment by erikvansebille** [comment]
Temporarily fixed in #168 as we wait for the fix for #104 to land
