### ISSUE TITLE
RunTimeErrorWarning in output files

### ISSUE THREAD

**Issue by imariaguiar** [OceanParcels/parcels#1491]
Hello, I have a set of particle release output files for each year of data (from 2008 to 2022). In the midst of running the code for particle release, I usually encounter this warning/error: 'C:\Users\55859\anaconda3\envs\py3_parcels\lib\site-packages\xarray\coding\times.py:251: RuntimeWarning: invalid value encountered in cast flat_num_dates_ns_int = (flat_num_dates * _NS_PER_TIME_DELTA[delta]).astype'. 

However, this error has never been a problem for plotting the trajectory results.

The issue is that I'm currently trying to create probability maps using my current grid of the global circulation model data along with trajectory data. When attempting to plot the probability maps, it seems that in some years of the trajectory, there are no positions that align with the original grid (which doesn't make sense).

I'm releasing particles in the same location for all years, but when trying to calculate the probability map, the only years that align with the original grid are the ones that, during execution, show the warning/error described above. The ones that don't show the error always yield zero in the position count.

However, I've checked all the trajectory files, and none of them are empty; all contain positions that match the original grid. But within this script, only a few years can be computed.

I've always used this same Python script for probability calculations, and it has always worked. In this case, I don't understand what might be happening. I'm not entirely sure if this is related to the warning/error during execution or if it's just a coincidence that the code is only working for the years when the error occurs.

The following Python script for calculating the probability:

data = xr.open_dataset('D:/dados/moi_glo12/daily_mean/psy4v3r1-U-2007-01-01.nc')

glo_lat = data['nav_lat'][:,0]
glo_lon = data['nav_lon'][0,:]

def carregar_dados_particulas(arquivo_zarr):
    particulas = xr.open_dataset(arquivo_zarr, engine='zarr')
    return particulas['lat'].values, particulas['lon'].values

visitados = {}

count_djf = np.zeros((240, 959), dtype=int)

years = range(2008,2022)
for ano in years:
    arquivo_zarr = f'/Users/55859/Documents/USP/Mestrado/parcels/outputs/currents/nbc/DJF/nbc_DJF_{ano}.zarr'  # .zarr de cada ano
    lat, lon = carregar_dados_particulas(arquivo_zarr)   
    visitados_ano = np.zeros((240, 959), dtype=int)
   
    for trajetoria in range(lat.shape[0]):  # iterando sobre todas as trajetórias (dimension 'trajectory')
        for ponto_obs in range(lat.shape[1]):  # iterando sobre todos os pontos de observação (dimension 'obs')
            lat_idx = np.argmin(np.abs(glo_lat.values - lat[trajetoria, ponto_obs]))
            lon_idx = np.argmin(np.abs(glo_lon.values - lon[trajetoria, ponto_obs]))
                
            # marcando o ponto de grade como visitado na matriz de visitados
            visitados_ano[lat_idx, lon_idx] = 1
    
    # armazenando a matriz de visitados para o ano atual no dicionário
    visitados[f'visitados_{ano}'] = visitados_ano
    
    count_djf += visitados[f'visitados_{ano}'] # rodar uma de cada vez para cada estação

count_djf = (count_djf / 14) * 100

**Comment by erikvansebille** [comment]
Dear @imariaguiar, thanks for reporting this issue. However, I'm not sure I can help. What do you mean with the sentence below? What is in the files/ What if you simply plot the lons and lats?
> none of them are empty

The `RuntimeWarning` you get is related to `xarray`, not Parcels. The fact that you only get it for some of your hydrodynamic files and not others, suggests that there are differences in the way the dates are stored in these files. You could check out more carefully (using `xarray.open_dataset()`) what the differences are between the files? That might give you a clue?
