### ISSUE TITLE
Continue .execute when pset is empty

### ISSUE THREAD

**Issue by erikvansebille** [OceanPARCELS/parcels#156]
Currently, Parcels fails with an error `IndexError: index 0 is out of bounds for axis 0 with size 0` when the `pset` is empty during `.execute` (e.g. when all particles have been deleted)

Since in principle `Particles` could be added later on again, I think default behaviour should be that `.execute` keeps going, even there's no particles to execute. We could add a warning/print statement

**Comment by erikvansebille** [comment]
Actually, turns out this was not a bug, but simply an error thrown when I called `pset.execute` with `starttime=pset[0].time`. Obviously, this won't work if `pset` is empty.

So not a bug after all; Parcels does work for empty `psets`

**Comment by jma360** [comment]
Hi, I am new at Parcels and I find  this same mistake "IndexError: index o is out of bounds for….".
I have got assigned a value for pset with latitude and longitude but the error remains the same. 
Could it be an error when calling the .nc? If I load a single nc fie and run it for only one day there is no problema but more than one day gives me error
