### ISSUE TITLE
Changing Parcels -> parcels and importing all of parcels throughout

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/parcels#1581]
Most python packages are all-lowercase ([as suggested by pep8](https://peps.python.org/pep-0008/#package-and-module-names)), so we should also change the writing of `parcels` to lowercase throughout in the examples, documentation, docstrings and website. 

While we're at it, we could also change the notebooks in the examples to refer to the classes as `parcels.ClassName`, to better highlight that these are specific to `parcels`. So e.g. change
```python
from parcels import FieldSet

fset = FieldSet(...)
```
to
```python
import parcels

fset = parcels.FieldSet(...)
```

**Comment by VeckoTheGecko** [comment]
Before I go ahead on this, just confirming that I should only change the code to say `parcels.ClassName` and not the markdown cells themselves? I think it would be clear from the code itself, and saying `parcels.FieldSet` every time would be a bit too verbose

**Comment by erikvansebille** [comment]
> Before I go ahead on this, just confirming that I should only change the code to say `parcels.ClassName` and not the markdown cells? I think it would be clear from the code cells, and saying `parcels.FieldSet` every time would be a bit too verbose

Yes indeed; only the code-cells. Like how it's done in the NumPy documentation (see screenshot below)
<img width="637" alt="Screenshot 2024-07-18 at 17 14 02" src="https://github.com/user-attachments/assets/bf256b10-92f9-44ad-a346-5d041b5c366a">


> Also, the lowercase nature of the package names (from my understanding) is only for the code itself. I think calling the package "Parcels" or "OceanParcels" in documentation is fine. Even numpy [uses NumPy for their project documentation](https://numpy.org/doc/2.0/user/whatisnumpy.html).

Ah, I didn't realise that! In that case, we can keep calling it Parcels in the non-codeblocks :-)
