### ISSUE TITLE
Readding performance benchmark capability

### ISSUE THREAD

**Issue by CKehl** [OceanParcels/parcels#1599]
In reference  to e-mail exchange with @erikvansebille  and Laurin Steidle, I have located my old code used to do the performance benchmark. Yet, this code (i.e. this branch) has been removed. Thus, you can't do the runtime benchmarks we have performed in papers.

In order to allow for result replication and benchmarking again, I am re-adding this code one last time to the repository, in an attempt to this time keep it in. It is also important for my own students in order to do performance comparisons, e.g. with Parcels.

**Comment by CKehl** [comment]
I'd appreciate if someone could create a new PR for me, so I can submit the patch. Thanks in advance.

**Comment by erikvansebille** [comment]
Hi @ckehl, can't you create a branch yourself? Don't you have the rights? Or otherwise from a fork?

Note that there's also https://github.com/OceanParcels/parcels/tree/benchmark_integration; that might contain useful (old) material?

**Comment by CKehl** [comment]
Hi @erikvansebille 

Thanks for your response! 
On point 1: I have created a local branch, but I don't have the access rights anymore to commit a new branch to the parcels github indeed. I have a very old personal fork - don't know how easy it is to get that fork to the new master branch status.

Thanks for pointing to the old branch. I have also considered that indeed, though this branch is incompatible with the master (due to the interaction kernel, the discontinuation of alternative particle-set structures etc.). That is why I just grabbed the current main and implemented it into there - that's the least time-intensive approach from my perspective.

Can you create a development branch from this issue, please ? Then I can easily check that issue-related branch with the updated code and we can wrap this up soon.

Kind regards, Christian

**Comment by CKehl** [comment]
Thanks Erik!

**Comment by CKehl** [comment]
Somehow, I cannot push to the parcels repository anymore. Then, there's likely only the possibility with the local fork that may work. That may take a bit longer.
Here a bit of an excerpt from what **git** says:

```
christian@PROMETHEUS:/media/christian/DATA/git/parcels-main$ git checkout performance_benchmark 
Branch 'performance_benchmark' set up to track remote branch 'performance_benchmark' from 'origin'.
Switched to a new branch 'performance_benchmark'
christian@PROMETHEUS:/media/christian/DATA/git/parcels-main$ git merge ab345adaf646c1103b6d8243599970b8cadd3f89
Merge made by the 'recursive' strategy.
 parcels/kernel.py                   | 163 +++++++++++++++++++++-
 parcels/particleset.py              | 487 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-
 parcels/tools/performance_logger.py | 321 +++++++++++++++++++++++++++++++++++++++++++
 3 files changed, 968 insertions(+), 3 deletions(-)
 create mode 100644 parcels/tools/performance_logger.py
christian@PROMETHEUS:/media/christian/DATA/git/parcels-main$ git status
On branch performance_benchmark
Your branch is ahead of 'origin/performance_benchmark' by 2 commits.
  (use "git push" to publish your local commits)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	parcels/tools/perlin2d.py
	parcels/tools/perlin3d.py

nothing added to commit but untracked files present (use "git add" to track)
christian@PROMETHEUS:/media/christian/DATA/git/parcels-main$ git push --force-with-lease 
X11 forwarding request failed on channel 0
ERROR: Permission to OceanParcels/parcels.git denied to CKehl.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
