### ISSUE TITLE
Better control of warnings for users

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/Parcels#1600]
The warnings/logger implementation in parcels is a bit clunky; it would be nice to refactor this with a more advanced(?) library. It would especially be nice if users could control which messages they turn on and off. 

For example, for some cases where it is expected that particle sets are empty for some time during the simulation, users may want to silence the `ParticleSet is empty on writing as array at time XXXX` warning

**Comment by andrew-s28** [comment]
I'd be able to take this one on, motivated by my recent experiences with the `ParticleSet is empty` message. I wanted to check in before rewriting it to see if you all had an opinion on what a refactor/rewriting of this would look like.

Currently, the warnings in Parcels are implemented through the [logging library](https://github.com/OceanParcels/Parcels/blob/master/parcels/tools/loggers.py). I was curious if there is any interest in transitioning to using the [warnings library](https://docs.python.org/3/library/warnings.html). This has several advantages, in my opinion:
- Using the warning library will enable users to set their own level of warning using the [warnings context manager](https://docs.python.org/3/library/warnings.html#available-context-managers), which has the advantage of being consistent with other libraries, such as [numpy.exceptions](https://github.com/numpy/numpy/blob/v2.0.0/numpy/exceptions.py), [pandas.errors](https://github.com/pandas-dev/pandas/blob/v2.2.2/pandas/errors/__init__.py), and [astropy.utils.exceptions](https://github.com/astropy/astropy/blob/main/astropy/utils/exceptions.py). 
- Users explicitly managing their own warnings using standard library functionality is better than including another kwarg as input to functions that would manage silencing internally and might go missed by many users. When I tried to suppress Parcels warning in some recent runs where I expected empty ParticleSets, I was surprised that my usual way of handling warnings wasn't working.
- Warnings could then also be included in documentation with some hints on how to solve them, e.g., a `ChunkWarning` is issued when chunks are not set optimally, encouraging the user to check the chunking on I/O files.

The reason I wanted to check first is that there is one thing that could be seen as a negative if this is implemented, depending on the goals of the existing logger implementation. The default behavior of the warning library is to only show warnings once, so for the case of the empty `ParticleSet` warning, the default behavior would change from showing on every iteration to only showing once.

I think this could be mitigated with an example in the tutorials showing how to use the warnings context manager if you desire old behavior (e.g., `warnings.simplefilter('always', category=EmptyParticleSetWarning)`), and that the overall positives of an updated warnings implementation outweigh the negatives, but I'm curious to see if anyone disagrees before I get working on it.

**Comment by erikvansebille** [comment]
Thanks for your willingness to pick this up, @andrew-s28! I agree with @VeckoTheGecko that your strategy makes sense; so please go ahead and propose some changes. Note that it doesn't need to be a fully functional PR; even a start would already be great. We're here to help :-)

**Comment by VeckoTheGecko** [comment]
@andrew-s28 just a note we've installed formatting across the codebase in the last couple days (#1655). I recommend merging with latest master to avoid conflicts

**Comment by andrew-s28** [comment]
Thanks for the heads up @VeckoTheGecko. Just synced my fork, so should be good to go! I'll keep an eye on it going forward, since it seems there's lots of great developments happening quickly. 

PS thank you and @erikvansebille for all the work that is going into the project. I found the new projects tab really helpful for seeing where I could contribute (and the overall direction of the package development), so I think it is working well.

**Comment by VeckoTheGecko** [comment]
Related to this is the parameter `netcdf_decode_warning` used in the codebase.

```
netcdf_decodewarning : bool
            Whether to show a warning id there is a problem decoding the netcdf files.
            Default is True, but in some cases where these warnings are expected, it may be useful to silence them
            by setting netcdf_decodewarning=False.
```

No action required at the moment. I'll discuss and have a think about how we can deprecate this transparently with users.

**Comment by andrew-s28** [comment]
@VeckoTheGecko sounds good.

I should have a draft PR ready in the next couple of days, since I am assuming there will be some feedback in how I structure the new warnings classes and we can discuss from there.
