### ISSUE TITLE
[Errno 28] No space left on device

### ISSUE THREAD

**Issue by cristinarumi** [OceanParcels/parcels#1622]
### Discussed in https://github.com/OceanParcels/parcels/discussions/1621

<div type='discussions-op-text'>

<sup>Originally posted by **cristinarumi** July 27, 2024</sup>
Hi,

I've encountered the "[Errno 28] No space left on device" error while running OceanParcels, indicating insufficient disk space. However, I have over 14 TB of free space available.
<img width="742" alt="Screenshot 2024-07-27 at 10 18 22" src="https://github.com/user-attachments/assets/b1a49ea2-0cde-4e75-bc2d-3319330eb7dc">

Do you have any suggestions on how to resolve this issue? I would really appreciate your help.

Thank you,
Cristina</div>

**Comment by cristinarumi** [comment]
<img width="738" alt="image002" src="https://github.com/user-attachments/assets/d857338e-6eb5-461a-b730-ce42cbf87b05">

**Comment by VeckoTheGecko** [comment]
Duplicate of #1621
