### ISSUE TITLE
Consider using flake8-pyproject to combine .flake8 and pyproject.toml info

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/parcels#1628]
In https://github.com/OceanParcels/Virtual_ship_classroom/blob/development/codetools.sh, @surgura wrote a script to quickly check valid code

One of the dependencies is https://github.com/john-hen/Flake8-pyproject, which seems as a nice way to combine the duplicate info on flake8 in our `.flake8` and `pyproject.toml` files. Consider using this for Parcels too?

**Comment by VeckoTheGecko** [comment]
Migrating to Ruff (#1609) will merge the linting configs into `pyproject.toml`
