### ISSUE TITLE
Removing `delta` alias for `timedelta`

### ISSUE THREAD

**Issue by VeckoTheGecko** [OceanParcels/parcels#1636]
The codebase uses `delta` as an alias for `datetime.timedelta` through the codebase and through the notebooks. This is a bit unique to `parcels`, and can lead to confusion to those famliar with Python wanting to use parcels for simulation.

It would be good to remove this in favour of using `timedelta`.

**Comment by erikvansebille** [comment]
Good idea, fully agree!
