### ISSUE TITLE
Invalid call of `VectorFieldEvalNode`

### ISSUE THREAD

**Issue by VeckoTheGecko** [OceanParcels/Parcels#1662]
I came across this code:

https://github.com/OceanParcels/Parcels/blob/595b7a94cdf97182df53c88fa99cf05646f07346/parcels/compilation/codegenerator.py#L63-L71

For ref:

https://github.com/OceanParcels/Parcels/blob/595b7a94cdf97182df53c88fa99cf05646f07346/parcels/compilation/codegenerator.py#L81-L88

Function signatures don't match, this is a bug. Requires investigation into intended purpose.

**Comment by erikvansebille** [comment]
I don't think this is a bug (it certainly works as intended; we use it a lot in all of the kernels!), but just a very confusing way of coding it. The `var`, `var2`, `var3` are the _output_ of the C-function (as pointers), not the input of the python function. 

I must admit it's also a bit magical to me; but rest assured it's not a bug! Happy to discuss further in person ;-)

**Comment by VeckoTheGecko** [comment]
just a note that that line 71 with the (maybe) bug also isn't covered by our test suite:
![image](https://github.com/user-attachments/assets/e349819a-0527-4382-94e1-bc7685573db2)
