### ISSUE TITLE
Binder tag broken?

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/Parcels#1669]
### Parcels version

v3.0.4

### Description

When clicking the [`launch binder`](https://mybinder.org/v2/gh/OceanParcels/parcels/master?labpath=docs%2Fexamples%2Fparcels_tutorial.ipynb) tag on README.md, the binder launches but fails with
```
Channels:
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... bash: line 1:     8 Killed                  ${MAMBA_EXE} env update -p ${NB_PYTHON_PREFIX} --file ".binder/environment.yml"
time: 53.349
 ---> Removed intermediate container d44d69b86d02
The command '/bin/sh -c TIMEFORMAT='time: %3R' bash -c 'time ${MAMBA_EXE} env update -p ${NB_PYTHON_PREFIX} --file ".binder/environment.yml" && time ${MAMBA_EXE} clean --all -f -y && ${MAMBA_EXE} list -p ${NB_PYTHON_PREFIX} '' returned a non-zero code: 137Error in event stream: Error
```

Seems to be an issue with the .binder/environment.yml file?

### Code sample

```python
# Paste your code within this block
```

```text
# Paste your error message within this block
```

**Comment by VeckoTheGecko** [comment]
I don't think this is an error with our code. I built locally using `repo2docker` with no issues. I think its a limit that mybinder.org puts on containers in terms of resource consumption (which explains the 137 error code, which some posts mention is a memory error code).

We aren't the only ones https://github.com/jupyterlab/jupyterlab/issues/16344 .

**Comment by VeckoTheGecko** [comment]
[Made a post](https://discourse.jupyter.org/t/encountering-resource-limits-when-building-binder-from-repo-returned-a-non-zero-code-137/28284)
