### ISSUE TITLE
Consider using KMeans from scipy instead of sklearn

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/Parcels#1670]
Following also #1616 where we moved to using the `KDTree` implementation from Scipy, we could also consider using [`kmeans` from Scipy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.vq.kmeans.html), thereby removing dependency on `sklearn` in  particle data.py
https://github.com/OceanParcels/Parcels/blob/997e3f86399cf319341a3d3f4fb1c5dc339e2580/parcels/particledata.py#L15

We need to check/investigate though whether the behaviour of `scipy.cluster.vq.kmeans` is the same as that of `sklearn.cluster.KMeans`

**Comment by VeckoTheGecko** [comment]
Ooo, didn't know scipy also did kmeans.

Briefly looking into it, it seems we'd get a performance hit by moving to scipy's implementation. This is noted in the [notes section of their API on this](https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.vq.kmeans.html), and there's a [dedicated comparison here](https://hdbscan.readthedocs.io/en/latest/performance_and_scalability.html#comparison-of-high-performance-implementations).
