### ISSUE TITLE
Read only values in `Field`

### ISSUE THREAD

**Issue by VeckoTheGecko** [OceanParcels/Parcels#1686]
Lets make the following read only (so that users don't try to edit it expecting it to propagate to the grid

https://github.com/OceanParcels/Parcels/blob/93cc635b82397a826e4e0869f2db4ecc7b3bfb19/parcels/field.py#L192-L197

cc: @sruehs

**Comment by erikvansebille** [comment]
In fact, we could even deprecate the `field.lon`, `field.lat` and `field.depth` attributes; I left them in for backward compatibility when we moved to a GridSet structure back in v2.0. So it's really old, redundant code that's there just for convenience.

**Comment by VeckoTheGecko** [comment]
Yes, thats also a possibility. Let's save this particular discussion for down the line where I review all attributes/methods and suggest actions to take (deprecate to make private, make read only, etc)

**Comment by VeckoTheGecko** [comment]
Done in #1709
