### ISSUE TITLE
Maintainer documentation 

### ISSUE THREAD

**Issue by VeckoTheGecko** [OceanParcels/Parcels#1688]
@erikvansebille would it be beneficial to have some simple maintainer documentation? Currently I thought it would be good for a release checklist (so we don't forget to update our citation file). Perhaps it could also include other useful links for people working in the codebase (e.g., linking to the [Scientific Python Development Guide](https://learn.scientific-python.org/development/) which is a good resource) or software carpentry stuff.

I think having a bulleted list linking resources for oceanographic Python would be helpful (links to xarray tutorials, setting up conda, setting up vscode) though that would be beyond the scope of Parcels, and I don't know where the home of that could be.

**Comment by erikvansebille** [comment]
Yep, very good idea to create maintainer documentation for Parcels. Where would that document live? A markdown file somewhere here in the repository? Or on docs.oceanparcels.org?

And indeed, it should at least have a check-list for releases (also re-build and check the binder environment!), and perhaps also our workflow for merging PRs (at least one maintainer should approve a PR; if the person opening a PR is a maintainer, that same person will also merge it; etc)

And sure, a curated list of useful links could be good too, but are less important IMO. Such a list tends to get outdated if not maintained. But at least we could link to https://pangeo.io as a starting point for Big Data geoscience

@VeckoTheGecko, if you create such a maintainer document somewhere, I can help populate it
