### ISSUE TITLE
Parallel execution

### ISSUE THREAD

**Issue by mlange05** [OceanParcels/parcels#17]
Now that we are homing in on what Parcels will be and how one uses it we should start considering parallel execution. I propose that we should aim to add automatically MPI parallelism the key ideas outlined in the workshop. Ultimately the user should only be required to execute `mpiexec -n num_proc python my_parcels_script.py`. The key ingredients for this would be:
- Grids need to compute a parallel partitioning in parallel.
- Particle serialisation is required to send small particle groups to neighbouring partitions via MPI.
- We need to detect once a particle enters a "halo" region to trigger sending. This avoids global communications, which otherwise would impede scalability.

Ideally we would implement this for both modes equally, but depending on feasibility I would prioritise C/JIT. A pre-requisite for the particle serialisation would be more dynamic data structures for the particle sets, since we would need to add and remove particles frequently on local processes.

**Comment by jianzhou722** [comment]
Hi all - any timeline for the parallel version of PARCELS?

**Comment by erikvansebille** [comment]
Discussions on Parallelisation in this very old Issue is now being continued in #553, so closing here
