### ISSUE TITLE
DOC: Viewing and editing metadata dict

### ISSUE THREAD

**Issue by VeckoTheGecko** [OceanParcels/Parcels#1701]
The metadata for the simulation is stored in a dictionary (`ParticleFile.metadata`) which is passed to xarray during writing.

https://github.com/OceanParcels/Parcels/blob/b007dcf0ee189ca85735d78c97f0fabf0ad485de/parcels/particlefile.py#L78-L84

Currently users can modify and add items to this dictionary, however this isn't mentioned in documentation. Showing how users can view and modify these attributes would be helpful as a quick aside in a tutorial.

NOTE: When documenting this, please use normal dictionary methods for modifying the metadata (the `ParticleFile.add_metadata()` method is over-engineered and will be marked for deprecation)

@erikvansebille in which tutorial would be a good place to mention this?

**Comment by erikvansebille** [comment]
Good point to better document this feature. Places to do that could be
1. The [Working with Parcels Output tutorial](https://docs.oceanparcels.org/en/latest/examples/tutorial_output.html)
2. The [Executing and Output section](https://docs.oceanparcels.org/en/latest/examples/tutorial_parcels_structure.html#4.-Execution-and-output) of the Parcels structure overview tutorial

If we add it in option 1, we could link it in option 2.
