### ISSUE TITLE
Hurricane Helene broke the Parcels docs.

### ISSUE THREAD

**Issue by willirath** [OceanParcels/Parcels#1724]
### Parcels version

v3.0.6

### Description

Currently, <https://www.ncei.noaa.gov/data/oceans/ncei/formats/netcdf/v2.0/trajectoryIncomplete.cdl>, which is referred to in https://github.com/OceanParcels/Parcels/blob/a814d7f66a3d344b5068196139f4dc922712682c/docs/examples/tutorial_output.ipynb returns a 404 error and indicates that 
> NCEI in Asheville has been significantly impacted by Hurricane Helene. We are working to resolve these issues as soon as possible. We apologize for any inconvenience.

As a result, the link checking phase of the sphinx build defined in https://github.com/OceanParcels/Parcels/blob/a814d7f66a3d344b5068196139f4dc922712682c/.readthedocs.yaml#L8 fails.

However, <https://docs.oceanparcels.org> already redirects to <https://docs.oceanparcels.org/en/v3.0.6/>

**Comment by VeckoTheGecko** [comment]
Thanks for the report! I've updated the default to `latest` instead so the docs site is up

**Comment by willirath** [comment]
Looks good. Thanks!
