### ISSUE TITLE
Using ParticleSet execute show_movie function

### ISSUE THREAD

**Issue by sw5413** [OceanPARCELS/parcels#177]
I tried using the above function, but obtained an unexpected keyword argument 't' error relating to the following line of code: self.show(field=show_movie, t=leaptime), line 274. Removing t=leaptime worked, but I am not sure of what the aim of that part of code is.

**Comment by erikvansebille** [comment]
Thanks for reporting, but this has been fixed a while ago in #152. Please `git pull` to update to the latest version of `master`
