### ISSUE TITLE
Decoupling K-Means Cluster Initialization from Number of MPI Processes

### ISSUE THREAD

**Issue by AlexT97** [OceanParcels/Parcels#1790]
### Parcels version

3.0.6, 3.1.0

### Description

Hello, I'm an HPC Applications specialist and I've been working recently with one of the researchers at my university on a weird problem they've been getting when running OceanParcels in MPI mode.

In a number of cases, MPI will simply freeze with no errors or anything.  This problem has happened with both the latest version of OceanParcels and older versions as well.  In short, it will simply stop at whatever the last thing it was doing was and refuse to continue.  The only warnings we've been able to find have come sporadically.  These seem to indicate a Convergence issue with the K-Means clustering algorithm used for chunking data:

```
ConvergenceWarning: Number of distinct clusters (7) found smaller than n_clusters (16). Possibly due to duplicate points in X.
```

Both numbers would change.  We noticed, however, that if the number of MPI processes is reduced far enough, this can mitigate the problem.

My question is this, and I apologize in advance if this is a lot to ask:

Would it be possible to decouple the number of K-Means clusters requested on initialization from the number of MPI processes the user requests?  If that's possible, it would certainly help speed up processing for users on HPC clusters.

If that's not possible, would it be possible to turn that Convergence Warning into an error and report that to the user so we can adjust the number of MPI processes accordingly?

### Code sample

```bash
sbatch -n 16 <my_slurm_script>.sh ## Job contains a python code using OceanParcels MPI GOM model
```

```text
ConvergenceWarning: Number of distinct clusters (7) found smaller than n_clusters (16). Possibly due to duplicate points in X.
```

**Comment by VeckoTheGecko** [comment]
You can provide a custom partitioning function to the ParticleSet constructor so that you have control of this behaviour. This is documented in the [Parallelisation with MPI and Field chunking with dask](https://docs.oceanparcels.org/en/latest/examples/documentation_MPI.html) tutorial. So you can specify 6 clusters for KMeans, and then distribute them across the different processes.

Does that help with your problem?

**Comment by VeckoTheGecko** [comment]
(to be clear, I think that this problem is due to the initialisation positions of the particles. The default partitioning function is one that is a 'sensible choice' but not something that would work on all initialisation setups)
