### ISSUE TITLE
Generalize the plotting interface

### ISSUE THREAD

**Issue by guidov** [OceanParcels/parcels#221]
The standard basemap Mercator projection when working with a global grid might be improved. A feature enhancement will involve a more adaptive plotting interface.
The ability to pass different basemap or cartopy projections to ParticleSet.show() could be useful. I can make an attempt to enhance the plotting interface. 

Another plotting feature might include changing an (x,y,z) particle trajectory color to indicated depth in a 2-D plot.

**Comment by erikvansebille** [comment]
Plotting (both through `ParticleSet.show()` and through the `plotParticleTrajectory` function) is indeed very rudimentary at the moment. However, would be great if it can be extended yes! So please feel free to propose enhancements @guidov!

**Comment by erikvansebille** [comment]
Note that we will also need to fix an issue with versions of matplotlib > 2.0.2 not supporting `plt.pause()` method anymore. When we do the reworking of plotting, we will need to implement an alternative way to generate animations

**Comment by erikvansebille** [comment]
I just came across this post on the `Basemap` website: https://matplotlib.org/basemap/users/intro.html#cartopy-new-management-and-eol-announcement

> Starting in 2016, Basemap came under new management. The Cartopy project will replace Basemap, but it hasn’t yet implemented all of Basemap’s features. All new software development should try to use Cartopy whenever possible, and existing software should start the process of switching over to use Cartopy. All maintenance and development efforts should be focused on Cartopy.

So I guess that Parcels should also switch over to `Cartopy` at some point
