### ISSUE TITLE
Field set put an inaccurate message when loading data with nan values

### ISSUE THREAD

**Issue by delandmeterp** [OceanParcels/parcels#224]
When loading a netcdf file containing nan values, the code writes the following warning

/home/staff/delan007/sources/parcels/parcels/field.py:613: RuntimeWarning: invalid value encountered in greater
  data = self.dataset[self.name][:, self.indsdepth, self.indslat, self.indslon]

It should say it found nan values, and in which field.

**Comment by erikvansebille** [comment]
With the change to xarray in #311, this seems to have been fixed? However, we still get warnings  like
```
particleset.py:315: RuntimeWarning: invalid value encountered in multiply next_output = time + outputdt * np.sign(dt)
```
but this only happens in Python3 (not Python2)

**Comment by erikvansebille** [comment]
This seems to have been fixed by one of the recent changes to `Field` reading
