### ISSUE TITLE
Swapping pytest-ipynb for nbval

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/parcels#226]
We're now using `pytest-ipynb` plugin to auto-test the tutorial notebooks. However, there seems to be a newer (better?) plugin at https://github.com/computationalmodelling/nbval that might be more appropriate for what we need. For one, it seems the restrictions on file naming are loosened in `nbval`. I suggest looking into whether we want to change to this new plugin

**Comment by mlange05** [comment]
:+1:

**Comment by erikvansebille** [comment]
Fixed in #228
