### ISSUE TITLE
Is Parcels ready for a conda-forge package?

### ISSUE THREAD

**Issue by willirath** [OceanParcels/parcels#234]
I've thought about <https://github.com/OceanParcels/parcels/issues/104#issuecomment-341236516> where I argued that a conda-forge package for Parcels might not make a lot of sense, yet. And I don't think, I should put it this way.

To the contrary, making it as easy as possible to try Parcels might make a lot of sense at this stage. Especially as there already are tutorials which invite for playing with it. And I think that it is possible to get people to interact with the tutorials in only a few lines of code:

1. Install Parcels: `conda install -c conda-forge parcels`

2. Get the tutorials: `parcels_get_examples $HOME/parcels_first_steps/`

3. Run them: `cd $HOME/parcels_first_steps/; jupyter notebook`

Step 1 needs a conda-forge package. Building a conda-forge package from a repository that has a working setup.py and knowing all the dependencies is relatively easy. (Well, things always take longer than estimated.  But it's at least straightforward.) And maintaining one is really easy: Whenever there's a new release, update a few lines in a yaml-file and wait for the magic to happen.

Conda-forge packages build on release-files like <https://github.com/OceanParcels/parcels/archive/v0.9.tar.gz>. That means, there's a few more steps for the developers of Parcels whenever they want to get a new feature or bug-fix to the users. But that's not necessarily a disadvantage: From a user’s perspective, having a release to refer to when communicating about any specifics of a tool is a lot nicer than referring to an evolving branch name or a Git commit hash.

Step 2 needs a command installed along with Parcels that fetches the example data, and puts the tutorials and the example data into some target directory. This is what #233 is about.

Step 3 is obvious, I think.

**Comment by willirath** [comment]
As soon as #235 is done, one could try and build a conda-forge package. For this, we'd need a release or at least a tag to build against. From <https://github.com/OceanParcels/parcels/projects/1> I gather, that this would not be a `v.1.0.0`. With the added `time_periodic` functionality, incrementing to `v0.10.0` could be in order, though.

**Comment by erikvansebille** [comment]
Yes, I agree. @delandmeterp is preparing a big PR on the way we deal with `grids` under the hood. Ones that gets merged into master, I will tag as `v0.9.1`

We're not yet at v1.0 I fear. For that we need at least non-Cartesian grid support, and ideally also a start on efficient I/O and/or parallelisation. See also the project timeline at https://github.com/OceanParcels/parcels/projects/1

**Comment by willirath** [comment]
How to you decide about version increments? In my opinion, the easiest would be to stick to [semantic versioning](http://semver.org/#summary) where `v0.9.0` to `v0.10.0` indicates added features (non-cartesian grids) that don't break existing behaviour and `v0.9.0` to `v0.9.1` would mean a minor fix not doing anything with the API (apart from restoring expected behaviour in, e.g., a bug fix.)

**Comment by willirath** [comment]
With `v1.0` released, I drafted a conda-forge package here: <https://github.com/willirath/staged-recipes/commit/09648828ddbfd6b23f09a36846605f9f573b5901>

I've included @erikvansebille, @delandmeterp and myself as package maintainers.  ([Details on what this means are here.](https://github.com/conda-forge/staged-recipes#9-what-does-being-a-conda-forge-feedstock-maintainer-entail))

The next step would be a PR to <https://github.com/conda-forge/staged-recipes> and probably about a week of waiting for the conda-forge people to trigger the actual build.  Then, the installation process would just be:

1. Install Anaconda or Miniconda
2. `conda install -c conda-forge parcels`

What do you think?

**Comment by erikvansebille** [comment]
Thanks @willirath for setting this up. Sounds like a great idea! So please go ahead and do the PR on conda-forge. Look forrward to being able to conda install parcels ;-)

**Comment by willirath** [comment]
Build seems to run fine now: <https://github.com/conda-forge/staged-recipes/pull/4831>

But I had to tweak the setup procedure to make this work: <https://github.com/willirath/staged-recipes/blob/674562afb5ddc5e0cda1097f6e2d78b960ebf48b/recipes/parcels/remove_setuptools-scm_dependency.patch>  I'll file an issue as soon as I understand what exactly went wrong.

**Comment by erikvansebille** [comment]
Thanks again @willirath for organising the conda-forge! They have merged our PR now, but if I do
`conda create -n py2_parcels_conda -c conda-forge parcels` I get
```
Fetching package metadata .............

PackageNotFoundError: Packages missing in current channels:
            
  - parcels

We have searched for the packages in the following channels:
            
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.continuum.io/pkgs/main/osx-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/osx-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/osx-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/osx-64
  - https://repo.continuum.io/pkgs/pro/noarch
```

I'm assuming it will take time before parcels is updated in their repos? Or am I doing something wrong?

Also, you said you changed `setup.py`? Can you file a PR? That can then also contain the updated installation instructions..

**Comment by willirath** [comment]
Now that the feedstock is fully created, this should be working now.  But there are a few issues:

1) No OSX package yet:  Travis has a severe backlog of OSX builds.  So I've disabled OSX builds to get the feedstock up and running.  I'll re-enable them as soon as Travis has recovered.

2) Scipy 1.0.0 from the conda-forge channel has been marked broken for at least some platforms.  Currently, this results in Scipy from the default channels and some inconsistencies that break the Parcels installation.

I'll handle both problems in the feedstock.

**Comment by willirath** [comment]
> Also, you said you changed setup.py? Can you file a PR?

I'll do that first.

> That can then also contain the updated installation instructions.

And I'll add a suggestion for a simplified installation instruction as soon as the conda-forge issues mentioned above are fixed.

**Comment by willirath** [comment]
We're getting there...  It's not quite ready for an update of the how-to-install section in the Parcels docs, but on Linux and with a fresh Miniconda root env activated, I get a fully working env with:
```bash
conda create -n parcels_conda -c conda-forge parcels blas=*=openblas jupyter
```

The `blas=*=openblas` stuff is necessary to make sure that conda-forge scipy and numpy are picked.  (They have a problem with re-building scipy and the default-channel scipy does not like Anaconda's gcc ...)

Windows builds are queued now, OSX is still waiting for Travis to come back.

**Comment by willirath** [comment]
I've tried (and failed ... for now) to find a full set of requirements that result in a fully functional conda package.  A few takeaways:

## Generalize GCC call

_This one's likely to cause problems even with the current 5-step installation procedure soon._

The main issue is the gcc dependency which relies on an Anaconda package that has been [deprecated in favor of a new and more modern stack](https://github.com/ContinuumIO/anaconda-issues/issues/7284#issuecomment-344209142). While this deprecated gcc works fine for JIT in Parcels, it collides with recent builds of scipy and numpy that have been built with a more recent compiler version.

From what I have seen during the last few days, it is a mere coincidence, that the current [environment.yml](https://github.com/OceanParcels/parcels/blob/master/environment.yml) is working.

Mitigation is probably easy:  [`parcels.compiler.GNUCompiler`](https://github.com/OceanParcels/parcels/blob/master/parcels/compiler.py#L62-L74) should avoid a hard coded `"gcc"`. There, first checking for a keyword argument passed to `__init__()`, then checking for an environment variable `$GCC` and / or `$CC`, and only as a last resort falling back to `"gcc"` would allow for swapping the `gcc` package for [the new compiler packages](https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html#compiler-packages).

## Aim at Py2 and Py3 support (again?)

As the only really platform specific dependency of Parcels is the compiler, I was considering a [noarch package](https://conda-forge.org/docs/meta.html#building-noarch-packages) instead of building for Linux, OSX and Windows separately. The benefit is much faster builds (things like the the Travis outage that currently prevents any updates on OSX packages would not hit Parcels at all).

One requirement for building noarch packages that Parcels currently does not meed is that, both, Python 2 and 3 are supported. This seems to be relatively easy.  To get an idea of the necessary effort, I've played with [`python-modernize`](https://pypi.python.org/pypi/modernize) and could get Parcels to install with, both, Python 2 and Pyton 3 and run the first tutorial.

## Streamline `setup.py`

Using [this patch](https://github.com/conda-forge/parcels-feedstock/blob/b983b809beb4b0bb596a57c4913a813ebc8081b9/recipe/tweak_setup-py.patch) against the `v1.0` `setup.py` results in a version that installs fine during conda builds, via pip, and by explicitly running `python setup.py install`, includes the example and header files in all cases and does not require `setuptools_scm` any more.

## Moving forward

I'll plan to create a PR for the GCC issue and for the `setup.py` in the coming days. I'll probably also add one that at least documents how close Parcels actually is to being fully Py2 and Py3 compatible.

**Comment by erikvansebille** [comment]
Thanks heaps again for all this effort, @willirath! Really great that you're helping out so intensively with this Issue!

Yes, I agree that we should (again) aim for both Python2 and Python3 support. I'd be happy to lead that; will file a new Issue soon. 

If you can take care of the `gcc` issue, which you probably have much more experience with than us, that would eb great. Hopefully we can make `conda install parcels` work very soon then :-)

**Comment by willirath** [comment]
#283 will take care of GCC and #282 adapts the `setup.py`.

**Comment by willirath** [comment]
I have a fully working conda package for linux (windows and osx are queued):

```bash
conda create -n py2_parcels_cf -c conda-forge parcels
```

Note that I (somewhat intentionally) did not include `jupyter`, `basemap` etc. in the requirements. So to run all the tutorials, a user would have to run:
```bash
conda install jupyter basemap
```

Let's wait and see if the windows and osx packages turn out to be fine as well and then go on from there.
