### ISSUE TITLE
Allow for executing Kernels without advancing time

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/parcels#240]
There may be cases where users want to run Kernels, but not actually do a time-step. Examples include e.g. for sampling a field

Currently, Parcels crashes when either `dt=0`, and also when `runtime=0` (or, equivalently, if `starttime`=`endtime`). 

Should we write a special case in `pset.execute()` when either `dt=0` or `runtime=0`, to execute the kernels without actually advancing time? Perhaps including a `logger.info` that time has actually not advanced?

**Comment by delandmeterp** [comment]
Yes, this is actually important. We were discussing such necessity with David no earlier than yesterday, even if we found another solution at the end.
I'll change this.

**Comment by erikvansebille** [comment]
Fixed in #247
