### ISSUE TITLE
Creation of large particle sets is slow in jit mode

### ISSUE THREAD

**Issue by davidwichmann** [OceanParcels/parcels#263]
I have worked with large particle sets (several 100 000 particles) and noticed that creating large particle sets is very slow in jit mode, but not in scipy mode. 

python example_stommel.py scipy -p 200000

needs around 50 seconds to set up the pset. In jit mode, for 100 000 particles

python example_stommel.py -p 100000

it takes more than 3 minutes to set it up. In addition, we also noticed that the increase in required time to set up the pset is not linear in jit mode, while it is linear in scipy mode. Setting up a pset for 400 000 particles in jit mode took more than an hour, before I interrupted it.

**Comment by erikvansebille** [comment]
Fixed in #324
