### ISSUE TITLE
reference to peninsula case needs updating

### ISSUE THREAD

**Issue by erikvansebille** [OceanPARCELS/parcels#3]
The reference to the original peninsula testcase (in the comments op peninsula.py) should be 

    """Grid representing the flow field around an idealised peninsula.

    The original test description can be found in Fig. 2.2.3 in:
    North, E. W., Gallego, A., Petitgas, P. (Eds). 2009. Manual of recommended practices 
    for modelling physical - biological interactions during fish early life. 
    ICES Cooperative Research Report No. 295. 111 pp.
    http://archimer.ifremer.fr/doc/00157/26792/24888.pdf"""

**Comment by mlange05** [comment]
Addressed now in example-peninsula branch.
