### ISSUE TITLE
particle_val attributes not handled correctly in `ParticleSet.density()`

### ISSUE THREAD

**Issue by Jacketless** [OceanParcels/parcels#302]
Upgrading to the latest version of parcels I notice that the new version of `ParticleSet.density()` does not correctly handle the `particle_val` argument. The purpose of this argument is to provide the *string name of a particle object attribute* to be used in place of simple density of particles themselves. At present, the code assumes that `particle_val` is a list of the these values for each particle.

Changing line
`particle_val = particle_val if particle_val else np.ones(len(self.particles))`
to
`particle_val = [getattr(p, particle_val) for p in self.particles] if particle_val else np.ones(len(self.particles))`
should fix this

I can do this once I'm done upgrading to the latest master

**Comment by erikvansebille** [comment]
Good point @Jacketless. Happy for you to create a PR that does this. Perhaps giving users the option of either a string name argument *or* a vector of values?

**Comment by erikvansebille** [comment]
Fixed in #307
