### ISSUE TITLE
Fieldset.advancetime through NEMO curvilinear grids

### ISSUE THREAD

**Issue by rm1911** [OceanParcels/parcels#306]
I am trying to run Parcels over NEMO ORCA025 model output - the velocity fields are curvilinear and there are many files for a given year. So, to do this, I am trying to combine the Fieldset.advancetime tutorial with the NEMO curvilinear grids tutorial.

I have defined a loadNEMOfile function which calls the u,v grids and default mesh settings; I wish to loop through a year of 5-day velocity grid files. However, upon attempting fieldset.advancetime, the following error messaged is returned:

RuntimeError: Time of field_new in Field.advancetime() overlaps with times in old Field

Does the mesh_mask.nc4 file need to have updated 'time' variable too? If so, how best to do this?

[advancetime_curvilinear.docx](https://github.com/OceanParcels/parcels/files/1767739/advancetime_curvilinear.docx)

**Comment by erikvansebille** [comment]
Hi @rm1911, I ran into this issue too, a while ago. Then, I implemented a function along the following lines:
```
def set_nemo_fieldset(ufiles, vfiles, meshset=None):

    filenames = {'U': ufiles, 'V': vfiles}
    if meshset is None:
        mname = ddir + 'domain/coordinates.nc'
        filenames['mesh_mask'] = mname
        meshnames = {'gU': mname, 'gV': mname, 'gT': mname}
        meshvars = {'gU': 'glamu', 'gV': 'glamv', 'gT': 'glamt'}
        meshdims = {'gU': {'lon': 'glamu', 'lat': 'gphiu'},
                    'gV': {'lon': 'glamv', 'lat': 'gphiv'},
                    'gT': {'lon': 'glamt', 'lat': 'gphit'}}
        meshset = FieldSet.from_netcdf(meshnames, meshvars, meshdims, indices)
        from_nemo = True
    else:
        from_nemo = False

    variables = {'U': 'uo', 'V': 'vo'}
    dimensions = {'U': {'lon': 'nav_lon', 'lat': 'nav_lat', 'depth': 'depthu', 'time': 'time_counter'},
                  'V': {'lon': 'nav_lon', 'lat': 'nav_lat', 'depth': 'depthv', 'time': 'time_counter'}}

    if from_nemo:
        fieldset = FieldSet.from_nemo(filenames, variables, dimensions, indices, allow_time_extrapolation=False)
    else:
        fieldset = FieldSet.from_netcdf(filenames, variables, dimensions, indices, allow_time_extrapolation=False)

    return fieldset, meshset 
```
And then the first time I would call the function with `meshset=None` and then during the `.advancetime()` with `meshset=meshset`. Does that work for you?

Note that we are working on having Parcels do advance_time under the hood, so that users don't need to worry about it anymore (e.g. #216); once that new feature lands, this should all be much easier
