### ISSUE TITLE
Source code in oceanparcels.org/_modules is outdated

### ISSUE THREAD

**Issue by willirath** [OceanParcels/parcels#320]
The source code for `FieldSet.from_nemo` on <http://oceanparcels.org/_modules/parcels/fieldset.html> does not match <https://github.com/OceanParcels/parcels/blob/master/parcels/fieldset.py#L158>.

It looks like the HTML files in oceanparcels.org/_modules are outdated.

**Comment by erikvansebille** [comment]
Fixed now, thanks for noting that these files in _modules were indeed outdated
