### ISSUE TITLE
Using parcels with MITgcm

### ISSUE THREAD

**Issue by edoddridge** [OceanParcels/parcels#321]
Hello,

We're revamping the [MITgcm documentation](http://mitgcm.readthedocs.io/en/latest/), and as part of that project I'm putting a list of [related projects](https://github.com/MITgcm/MITgcm/pull/47) into the documentation. Our intention is to list projects which can be used in conjunction with MITgcm and provide additional functionality.

It looks like parcel's ability to load in [netCDF velocity fields](http://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/parcels_tutorial.ipynb#Reading-in-data-from-arbritrary-NetCDF-files) would allow parcels to be run using MITgcm output. Has anyone tried that?

Would you be happy for parcels to be listed, and if so, any suggestions for a blurb?

Cheers,
Ed

**Comment by erikvansebille** [comment]
Hi @edoddridge! Yes, Parcels can work with MITgcm, and it would be great to have it highlighted on the related projects page of MITgcm. I've just created a PR at https://github.com/edoddridge/MITgcm/pull/1
