### ISSUE TITLE
Handling data before 1678 or after 2262 likely requires generalization of `timedelta`

### ISSUE THREAD

**Issue by willirath** [OceanParcels/parcels#323]
[Xarray handles dates before the year 1678 or after year 2262 differently.](http://xarray.pydata.org/en/stable/time-series.html) For years beyond these limits, the time coordinate of a data array will fall back to `netcdftime`.

I can see two problems that will probably arise if you try processing data from before 1678 or after 2262 with Parcels

1. As far as I see, Parcels currently assumes that _all_ time data are `np.datetime64`. This assumption will not be met for periods not withing the "native" date range of xarray and Pandas.

2. As Parcels opens each single data file as a separate xarray dataset, there will be inconsistencies if the data cover periods that only paritally overlap with the date range given above.

I'm not sure what's the best way to solve this. Always falling back to [netcdftime](https://github.com/Unidata/netcdftime) could be a good idea. 

Another (more complicated) possibility would be to let Xarray do whatever it does and check for the type of `time` whenever it matters.

**Comment by delandmeterp** [comment]
Yes, so we should use a different time object.
`datetime.datetime` was nice, but it is not returned by xarrays.
And while a `datetime.datetime` can be easily transformed to a 'np.datetime64`, the opposite is not true. I will check what is this netcdftime object.

I think we have to be able to deal with user's `datetime.datetime` objects, and internally we have to transform everything to one single type of object.

**Comment by erikvansebille** [comment]
This is now explicitly dealt with through PR #353; Parcels indeed only supports `time_origins` between 1678 and 2262, and throws an error if time_origin is outside. Closing this issue and #220 for now, until we hear about a actual use-case for extending this date range (which would be a lot of work!)

**Comment by willirath** [comment]
>  (which would be a lot of work!)

There's a lot going on on the xarray and netcdftime side of this problem.  We'll probably get xarray Datasets that have time axes which behave like `datetime` objects in the near future.  So I agree:  Let's close here and wait for this to be solved upstream.

**Comment by delandmeterp** [comment]
It is already the case!
When date is out of bound, xarray throw a warning and gives you `datetime.datetime` objects. Actually, our test simply throws an error if the date given by xarray is a `datetime.datetime` because we don't want (currently) to check later on if dates are `datetime.datetime` or `np.datetime64`

**Comment by willirath** [comment]
Currently, xarray can return _inconsistent_ time axes with `datetime.datetime` for those steps that are not in `[1678, 2262]` and `np.datetime64[ns]` for everything else.  In the next (?) release of xarray, this will probably be fixed and adapting currently problematic time axes will be much more straightforward.
