### ISSUE TITLE
NEMO Curvilinear grid discontinuity

### ISSUE THREAD

**Issue by rm1911** [OceanParcels/parcels#347]
When running particles on a curvilinear ORCA025 grid ([available here](http://gws-access.ceda.ac.uk/public/nemo/runs/ORCA025-N102/means/2001/)), the particles do not cross the edge of the velocity grid (at roughly 72.25E).  Code attached.

Instead, there appears to be a discontinuity which artificially accumulates or deletes particles. 
Note that the edges of the ORCA025 grid contain nan values, which corresponds to this meridian line. 

![surface_particle_destination](https://user-images.githubusercontent.com/8235558/38871866-df29b6e8-4249-11e8-80be-ffbf3117050d.png)

[test_release.docx](https://github.com/OceanParcels/parcels/files/1919794/test_release.docx)

**Comment by delandmeterp** [comment]
Hi,
The line you talk corresponds to the boundary of your grid (see how ORCA grids are defined)
I think your problems occurs because you set a fieldset.add_periodic_halo() while your grid does already contains a periodic halo (two cells are repeated).
You cannot add a periodic halo to a grid that does already contain it, it messes up the full grid.
Could you confirm me that removing that fixes your problem?

We'll add a comment like this to the doc and tutorials to warn about this potential error.

**Comment by rm1911** [comment]
Removing the periodic halo does fix the problem - thank you.

![surface_particle_destination](https://user-images.githubusercontent.com/8235558/38926106-74b971da-42f9-11e8-97a3-c76ea7b0ac14.png)

**Comment by rm1911** [comment]
While this has been solved for surface fields, the problem of spurious deletion persists for velocities interpolated to isopycnals.

I have used the template, changing the input fields (which have the same shape and boundary) and including extra variables.

![figure_1](https://user-images.githubusercontent.com/8235558/39209561-03a63186-47fe-11e8-9bfd-8f0077e155a1.png)

[iso27.1_res025_1yr_global.docx](https://github.com/OceanParcels/parcels/files/1944355/iso27.1_res025_1yr_global.docx)

**Comment by rm1911** [comment]
UPDATE: Solution as follows...

ORCA025 velocity fields begin at 72.75E and end at 73E and therefore contain two repeat/overlapping cells. The edges of the fields are filled with zero values (presumably for reasons to do with the mesh singularities). However, parcels read these zero-value cells, which led to particles being trapped there.

The solution was to set the edges of ORCA025 velocity fields equal to their corresponding repeat cells (which can be found by studying the longitude arrays). When repeat cells are being used, a periodic halo is not required (see @delandmeterp message above).
