### ISSUE TITLE
Written particle files enormously large due to two 'unlimited' dimensions

### ISSUE THREAD

**Issue by pdnooteboom** [OceanParcels/parcels#357]
Currently I am writing extremely small files (say 'file.nc') (11 particles at 11 time steps). Nevertheless, the written files are 45 Mb each. 

I can create a file with fixed dimensions, with a size of 55 Kb with: 'ncecat file.nc filefixed.nc.' 

How can I write a file with lower size in first instance?

**Comment by erikvansebille** [comment]
I've looked into this a bit today, and it appears to be an issue with the 'chunk-size' of netcdf files. See e.g. the blog piece at https://www.unidata.ucar.edu/blogs/developer/entry/chunking_data_choosing_shapes

I've now added an option `chunksizes` to `ParticleFile.__init__` in https://github.com/OceanParcels/parcels/commit/0770eb74b5fa8da166e0d4c2d9b195b8c386b156

Indeed, the test file reduces from approx 24MB before controlling to <60KB for `chunksizes = [1, 1]`

However, this will likely lead to much slower I/O... @pdnooteboom, can you test this and see whether 1) this reduces file sizes for you and 2) doesn't lead to much increased time spent on file writing?

If all good, then we'll need to think about the best default values for the `chunksizes` argument. Perhaps `[len(pset), 1]`?

**Comment by pdnooteboom** [comment]
I checked the time and the file size when "chunksizes = [1, 1]" and "chunksizes = None" @erikvansebille. Interestingly, in both cases the written file sizes I found are now the same (both 105 Kb which is reasonably low). The "chunksizes = [1, 1]" is slightly faster even.

**Comment by erikvansebille** [comment]
Fixed in #366
