### ISSUE TITLE
Efficient code for computing particle densities

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/parcels#40]
One thing PARCELS will need to be able to do is efficiently compute particle densities, given the positions of N particles. As we don't want to solve an N-body problem, we'll need to have some smart data structure

I chatted to @pwolfram today, and he suggested k-d trees: https://en.wikipedia.org/wiki/K-d_tree
This seems indeed what we might need

No huge rush, and perhaps we don't even need this for the GMD milestone. But I wanted to open an issue on it anyway, so that we know this might be the way forward

**Comment by mlange05** [comment]
Ok, I believe this is similar to the diagnostic fields that @Jacketless requires to model predator-prey interactions. The idea here is to generate a field (numpy array) that sums the total amount of a variable quantity stored on the particles in each cell and then normalises this by cell volume. To get a particle density the value each particle "deposits" is then 1, but for a "prey" particle this might be some measure of biomass, which in turn allows the "predator" particle to sample the local population and adjust its behaviour accordingly. 

In terms of implementation it is important to note that no tree is required here, since our particles always know where they are in the grid. The syntax I would propose for the "depositing" action would probably be something like `grid.DiagFieldA << particle.varA`, which would be interpreted in parcels.Kernels accordingly.

**Comment by pwolfram** [comment]
The benefit to the tree is aggregation of particles for computational
efficiency.  This essentially helps with problems requiring accounting for
lumped effects of particles far away, especially for problems like
gravitation. I agree, @mlange05, you can probably do something like binning
based on position instead for densities, but may find trees useful for
other applications.

On Wed, Feb 24, 2016, 4:26 AM Michael Lange <notifications@github.com>
wrote:

> Ok, I believe this is similar to the diagnostic fields that @Jacketless
> <https://github.com/Jacketless> requires to model predator-prey
> interactions. The idea here is to generate a field (numpy array) that sums
> the total amount of a variable quantity stored on the particles in each
> cell and then normalises this by cell volume. To get a particle density the
> value each particle "deposits" is then 1, but for a "prey" particle this
> might be some measure of biomass, which in turn allows the "predator"
> particle to sample the local population and adjust its behaviour
> accordingly.
>
> In terms of implementation it is important to note that no tree is
> required here, since our particles always know where they are in the grid.
> The syntax I would propose for the "depositing" action would probably be
> something like grid.DiagFieldA << particle.varA, which would be
> interpreted in parcels.Kernels accordingly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OceanPARCELS/parcels/issues/40#issuecomment-188181424>
> .
>
-- 

Phil

--------------------

Phillip J. Wolfram

**Comment by Jacketless** [comment]
I'm now at the point where I would soon like to begin comparing particle densities at certain points with corresponding variables from a Eulerian model.
This is something I can do "offline" from the particle output .nc file in the manner @mlange05 suggests (binning and counting), but do we want to open a branch that does these calculations and writes to a field as a first step to on-the-fly particle density calculation?

**Comment by erikvansebille** [comment]
Did PR #81 fix this issue now? Or do we still need to keep it open?

**Comment by mlange05** [comment]
No, PR #81 was orthogonal to this.

**Comment by Jacketless** [comment]
PR #67 has made an attempt at density calculation within the main execution loop, but is not passing tests. A more considered design of adaptive execution loops was mentioned in #78 and so I have held off any further development on this issue. #67 contains enough functionality for me at the moment, but happy to discuss how to fix and get it into the master branch.

This is really the last piece of PARCELS functionality I require for the initial tuna milestones.

**Comment by erikvansebille** [comment]
Two points on this old Issue:
- Related to calculating densities is also the computation of **streamfunctions** (like what Ariane does). This would be a great feature to have, as it is one of the most-used diagnostics in Ariane. We could look at their implementation and mimic that
- An additional difficulty in computing fields of particle densities (or streamfunctions) during runtime is that in C we can presently not write to `Fields` (we can only read `Fields`). So there is no easy way to change values of a field within the JIT-execution. Not sure how to easily fix this

**Comment by erikvansebille** [comment]
Fixed in #255

**Comment by mathildejutras** [comment]
Hi, I was wondering if there was any development on the computation of **streamfunctions**, as mentioned above. Thanks!

**Comment by erikvansebille** [comment]
We haven't developed code for this in Utrecht yet, but I think that @ignasivalles may have previously computed streamfunctions from particles. Maybe he can help?
