### ISSUE TITLE
Depth-less netCDF fields

### ISSUE THREAD

**Issue by Jacketless** [OceanPARCELS/parcels#41]
Hi gang,
As I'm now importing fields from more new ocean/ecosystem models, I'm coming across the issue of fields that have no depth dimension, i.e. just represent some variable that has been integrated through the water column at a lat/long position. I suspect that we will use these kinds of fields more and more going forward- habitat maps, fields that give the starting densities of particles (another feature I'd like to try and code up), and perhaps even our own internal particle density field that we have discussed using to simulate local interactions.

Correct me if I'm wrong, from what I can tell at the moment, field.py expects four-dimensional datasets (even though we only advect in 2d) structured [time, depth, lat, lon]
From field.py:
`# Pre-allocate grid data before reading files into buffer
        data = np.empty((time.size, 1, lat.size, lon.size), dtype=np.float32)
        tidx = 0
        for tslice, dset in zip(timeslices, datasets):
            data[tidx:, 0, :, :] = dset[dimensions['data']][:, 0, :, :]
            tidx += tslice.size`
it appears that we expect four dimensions but only take the top depth slice anyway. 

A quick fix for me is to try and add a depth dimension of length 1 to these "2d" netCDFs, but perhaps we want to be able to allow PARCELS to deal with such fields explicitly?

**Comment by erikvansebille** [comment]
Good point, @Jacketless 

Similarly, at some point we will probably also encounter time-less netCDF files (think spatial maps of diffusivity).

This needs some thinking about how general we want our netcdf files to be.

**Comment by mlange05** [comment]
Ok, I think ultimately we want a hierarchy of specialised `Field` sub-classes to encapsulate our internal data layout, similar to the set of grid classes discussed in issue #39. I would think something along the lines of `Field2D`, `Field2DVertical`, `Field2DTime` and `Field2DVerticalTime` with a constructor hierarchy, appropriate `from_netcdf()` initialisers and cached interpolator routines should be sufficient. Once we have that we can even write smart wrapper functions that detect data layout from file, but let's first get the data structures right.

**Comment by erikvansebille** [comment]
Yes, I totally agree. For completeness, don't forget the `Field0DVertical` class of column models.

Also, we would ideally also accomodate time-evolving grids. The adaptive horizontal meshes are one type, but there are also quite few ocean models that have temporally-varying vertical grids (i.e. horizontal surfaces go up and down over time). Something to remember as we're defining these classes?

**Comment by Jacketless** [comment]
Ok, that sounds like a fairly intuitive way to build in this functionality.

To get things working in the short window I have in France, I've hacked my
netCDFs using NCO to have the appropriate form, but I'll try and write some
of these example subclasses as I go and you adjust.

@erikvansebille now you describe it in that way, I realise that I am
already trying to use time-less fields with tuna biomass densities that I'm
using as 'initial conditions' for the distribution of particles. In this
case, there is an arbitrary time dimension of length one.

**Comment by Thomas-95** [comment]
I have created a new kernel, `landmass_kernel`, related to this topic. I was hoping to create a kernel capable of determining a particle's distance from the coast, for which I would require a grid of values that are 'land'. Such a grid doesn't have a time dimension, whereas `field.py` dictates that this must be that case.

**Comment by erikvansebille** [comment]
Completed implementation in #184
