### ISSUE TITLE
Time differences 

### ISSUE THREAD

**Issue by hart-davis** [OceanParcels/parcels#413]
I found an issue between using`fieldset.from_data` and `fieldset.from_netcdf`. 

If I call data using `from_data` like this:

`data = {'U': U, 'V': V}
dimensions = {'U': {'time':time,'lon': lon, 'lat': lat},
              'V': {'time':time,'lon': lon, 'lat': lat}}
fieldset = FieldSet.from_data(data, dimensions)`

and then print fieldset.U.time, I get:

[  1.45311839e+18   1.45320484e+18   1.45329115e+18   1.45337760e+18
   1.45346391e+18]

But if I call the data using `from_netcdf` like this: 

`filenames = {'U': fname,
             'V': fname}
variables = {'U': 'uo',
             'V': 'vo'}
dimensions = {'U': {'time':'time',
                    'lon': 'longitude', 
                    'lat': 'latitude'},
              'V': {'time':'time',
                    'lon': 'longitude', 
                    'lat': 'latitude'}}
fieldset = FieldSet.from_netcdf(filenames, variables, dimensions)`

and then print fieldset.U.time, I get:
[      0.           86449.10173389  172760.7645143   259209.86624819
  345521.52902861]

This arises, I think, because the 'time' data is in a format similar to '2018-08-16'  and the conversion takes place resulting in extremely large time values in the `from_data` run [1.45311839e+18]. This issue has caused me issues when adding a separate field [e.g. wind or spatial diffusion], as depending on which method I use the times do not match up.

**Comment by delandmeterp** [comment]
`FieldSet.from_data()` should only take as input time values which are numbers.
We should check at the creation of the grid (where we convert time to float64), that time is a number and raise an error otherwise.

Currently, the conversion to float64 returns whatever value.

**Comment by erikvansebille** [comment]
Fixed in #416
