### ISSUE TITLE
Re-organise tests and examples

### ISSUE THREAD

**Issue by mlange05** [OceanPARCELS/parcels#44]
Now that we have a separate `examples` sub-repo we should start caring about the way we test internal functionality and how we demonstrate it by separating low-level feature and unit tests from full-scale example setups. The current test setups are all small examples and should thus be migrated to the examples repo eventually. In their place we require a whole range of additional low-level feature tests that cover the basic functionalities individually, for example:
* Grid and field initialisation from file using different formats
* Internally provided kernels, such as `AdvectionRK4/EE` should be tested against known solutions
* Various constructs of our internal JIT kernel language
* Particle trajectory and data output

As we add more and more features and cover a wider range of formats, this list should grow, while the `examples` repo will be used to maintain a useful set of setups that demonstrate complete scenarios.

**Comment by erikvansebille** [comment]
So the idea now is to host all the netcdf data on a separate server (ideally oceanparcels.org, http://plasticadrift.org/parcelsdata/ for now). There will then be a script to download this data if users want it.

Following from some initial investigation by @Thomas-95, I've had a further look into pydap, and it seems that it doesn't play nice with hdf5. It gives strange error messages (also detailed in the old email thread [here](https://groups.google.com/forum/#!topic/pydap/Drswq52UveM))

However, I'm not sure we actually need pydap; might it not be overkill? Since we simply want to download the entire set of files anyway, can't we use something much simpler like `wget`, or a python version of that (see [here](https://pypi.python.org/pypi/wget))?

**Comment by mlange05** [comment]
Ok, I don't think we want a script to "bulk download" all test on install. Instead I would thing we integrate `pydap` into our `Grid` objects to allow users to access and cache their own remote files via OpenDAP and put the according addresses in the `test_xxx.py` files, ie.: `grid=Grid.from_nemo("http://plasticadrift.org/parcelsdata/GlobCurrent_xxx.nc", ...)`). In this scenario we need to make sure `pydap` buffers the files, so the download is only triggered the first time the test is run.

However, if `pydap` really doesn't work, the bulk download can be used as a temporary fix. Have you tried it yourself though (the bug report you link looks old)?

**Comment by erikvansebille** [comment]
Sorry for not being clear that the `pydap` indeed fails.

The code
`from pydap.client import open_url`
`dataset = open_url('http://test.opendap.org/dap/data/nc/coads_climatology.nc')`
`print 'read coads'`
`OAFM_simple_U = open_url('http://plasticadrift.org/parcelsdata/OFAM_example_data/OFAM_simple_U.nc')`
`print 'read ofam'`

Returns
`read coads`
`Traceback (most recent call last):
  File "/Users/erik/Downloads/pull_data.py", line 6, in <module>
    OAFM_simple_U = open_url('http://plasticadrift.org/parcelsdata/OFAM_example_data/OFAM_simple_U.nc')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pydap/client.py", line 60, in open_url
    dataset = response(url)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pydap/client.py", line 210, in _ddsdas
    dataset = DDSParser(dds).parse()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pydap/parsers/dds.py", line 26, in _dataset
    self.consume('dataset')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pydap/parsers/dds.py", line 19, in consume
    token = SimpleParser.consume(self, regexp)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pydap/parsers/__init__.py", line 25, in consume
    raise Exception("Unable to parse token: %s" % self.buffer[:10])
Exception: Unable to parse token: <!DOCTYPE `

So the example they provide seems to work; our file doesn't work. Not sure if it's HDF5, but that's what this old post seems to suggest, and their error message was quite similar...

I'm suggesting going for bulk download as a temporary fix yes

**Comment by mlange05** [comment]
Ah ok, in that case, yes, let's go for a bulk download. We might still be able to use  the OpenDAP feature in `netCDF4`, or maybe even fix `pydap` in the future, but for now let's go with `pycurl` or `wget`.

**Comment by erikvansebille** [comment]
Fixed by @Thomas-95 in PR #92 (which was based on branch `examples_test_update`)
