### ISSUE TITLE
Time extrapolation not working for fieldset?

### ISSUE THREAD

**Issue by MiriamFrauke** [OceanParcels/parcels#446]
I encountered a problem in a very basic run of two particles in a velocity field:

`fieldset = FieldSet.from_parcels("MovingEddies_data/moving_eddies", allow_time_extrapolation = True)`
`pset = ParticleSet.from_list(fieldset=fieldset, pclass=JITParticle, lon=[3.3e5, 3.3e5], lat=[1e5, 2.8e5])`
`pset.execute(AdvectionRK4,
            runtime=timedelta(days=10),
            dt=timedelta(minutes=5),
            output_file=pset.ParticleFile(name="EddyParticlesTest.nc", outputdt=timedelta(hours=1)))`
`print(pset)`
`pset.show(field=fieldset.U)`

The problem here is in the last line. When the runtime is less than 7 days, it works just fine. However, if the runtime is more, an error occurs and it seems that the velocity field can not be plotted. The command `pset.show()` without the `fieldset` works just fine, and shows where the particles are after a number of days.

Another interesting remark is that it works if I choose a negative `timedelta`. The U-field can be shown together with the particles just fine after -20 days, but not after +20 days.

**Comment by erikvansebille** [comment]
Fixed in #449
