### ISSUE TITLE
time format bound to datetime with unit

### ISSUE THREAD

**Issue by cjongedijk** [OceanParcels/parcels#454]
Parcels at the moment seems to only accept 'datetime' format time fields. time fields without units or in the wrong format are not accepted. Would it be possible to create more freedom in the format of time values for example when imported in fieldset from netcdf or when automatically setting the start time of a simulation or particle (via time[0] in grid.py) and possibly in other situations depending on the project. It would be nice if a 'plain' format would be accepted i.e. a numpy array or single float value.

**Comment by erikvansebille** [comment]
Yes, very good point. In fact, we're currently developing this with a new `TimeConverter` class, following Issue #425 
There is an almost complete branch `cftime_noleap_calendar` (see also https://github.com/OceanParcels/parcels/compare/cftime_noleap_calendar). This will probably become a PR very soon (just needs some work on documentation and code-cleanup, mostly). 

Feel free to give it a try already and see if this works for you. if not, please report here what kind of `time` fields you have, so we can add that calendar to the TimeConverter class

**Comment by delandmeterp** [comment]
@cjongedijk , could you check that #455 solves your bug?

It is on the sample you've sent me (was not a unit but an array problem it seems)

**Comment by erikvansebille** [comment]
Fixed in #455
