### ISSUE TITLE
Performance of IO-Loop

### ISSUE THREAD

**Issue by willirath** [OceanParcels/parcels#473]
Parcels spends a lot of time in <https://github.com/OceanParcels/parcels/blob/master/parcels/particlefile.py#L161_L170>.

For 12-hourly output and a 5-minute time step, the Agulhas example spends 95% of the time in this loop. [(See this gist for details.)](https://gist.github.com/willirath/dbdd1ee9578fb42718e96de7597caeb4)

To me, the root of the problem seems to be the fact that this loop supports the most general case (particles being killed / created at runtime) in an explicit way.

**Comment by willirath** [comment]
(cc: @ohlmann and @phandmann This is the IO-bottleneck I was referring to.)

**Comment by willirath** [comment]
(cc: @handmannp)

**Comment by delandmeterp** [comment]
This should be fixed in the near future. We haven't attacked that bottleneck since two students are working on it for a project. Outcomes should come within two weeks.

**Comment by willirath** [comment]
That's great to hear.  Then as a next step, we can talk about OpenMP parallelization of the particle loop. :)

**Comment by erikvansebille** [comment]
This has been fixed now in #486 and #497
