### ISSUE TITLE
Problem Installing Parcels

### ISSUE THREAD

**Issue by ana-machado** [OceanParcels/parcels#489]
Hi
I followed the instructions to install Parcels. Apparently everything worked out, but  when I try to import parcels I get:
"ImportError: No module named parcels"
I am using anaconda2, the directory py2_parcels was created inside ~/anaconda2/envs/py2_parcels
Do you know what can be missing?
Thank you
Ana

**Comment by willirath** [comment]
Did you activate the environment? Step 3 from http://oceanparcels.org/#installing is always necessary, before using parcels as installed following the guide.

**Comment by ana-machado** [comment]
I did... 
$ source ~/anaconda2/bin/activate py2_parcels
I get no error message.
But still:
In [2]: from parcels import FieldSet
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-870c5cb80a78> in <module>()
----> 1 from parcels import FieldSet

ImportError: No module named parcels

Any ideas?

**Comment by willirath** [comment]
What does `conda list -n py2_parcels` say?

**Comment by willirath** [comment]
Another possibility: Do you happen to use ipython although it is not installed in the py2_parcels env?

**Comment by ana-machado** [comment]
# packages in environment at /home/ana/anaconda2/envs/py2_parcels:
#
blas                      1.1                    openblas    conda-forge
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2018.10.15           ha4d7672_0    conda-forge
cloog                     0.18.0                        0  
dbus                      1.13.0               h3a4f0e9_0    conda-forge
expat                     2.2.5                hfc679d8_2    conda-forge
ffmpeg                    3.2.4                hf82bc7d_4    conda-forge
fontconfig                2.11.1                        6  
freetype                  2.5.5                         2  
gcc                       4.8.5                         7  
geos                      3.6.2                hfc679d8_3    conda-forge
gettext                   0.19.8.1             h5e8e0c9_1    conda-forge
glib                      2.56.2               h464dc38_1    conda-forge
gmp                       6.1.2                         0    conda-forge
gst-plugins-base          1.12.5               hde13a9d_0    conda-forge
gstreamer                 1.12.5               h5856ed1_0    conda-forge
hdf4                      4.2.12                        0  
hdf5                      1.10.1                        2    conda-forge
icu                       54.1                          0  
isl                       0.12.2                        0  
jbig                      2.1               h470a237_1001    conda-forge
jpeg                      8d                            2  
krb5                      1.16.2               hbb41f41_0    conda-forge
libcurl                   7.62.0               hbdb9355_0    conda-forge
libedit                   3.1.20170329         haf1bffa_1    conda-forge
libffi                    3.2.1                hfc679d8_5    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 7.2.0                hdf63c60_3    conda-forge
libgfortran               3.0.0                         1    conda-forge
libiconv                  1.15                 h470a237_3    conda-forge
libpng                    1.6.35               ha92aebf_2    conda-forge
libsodium                 1.0.16               h470a237_1    conda-forge
libssh2                   1.8.0                         2    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    conda-forge
libtiff                   4.0.6                         2  
libxcb                    1.13                 h470a237_2    conda-forge
libxml2                   2.9.4                         0  
libxslt                   1.1.29                        4    conda-forge
mpc                       1.1.0                         4    conda-forge
mpfr                      3.1.5                         0    conda-forge
ncurses                   6.1                  hfc679d8_1    conda-forge
openblas                  0.2.19                        2    conda-forge
openssl                   1.0.2p               h470a237_1    conda-forge
pandoc                    2.3.1                         0    conda-forge
pcre                      8.41                 hfc679d8_3    conda-forge
pixman                    0.32.6                        0    conda-forge
proj4                     4.9.3                h470a237_8    conda-forge
pthread-stubs             0.4                  h470a237_1    conda-forge
python                    2.7.15               h33da82c_4    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
sqlite                    3.25.3               hb1c47c0_0    conda-forge
tk                        8.6.8                         0    conda-forge
x264                      1!152.20180717       h470a237_1    conda-forge
xorg-libxau               1.0.8                h470a237_6    conda-forge
xorg-libxdmcp             1.1.2                h470a237_7    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
zeromq                    4.2.5                hfc679d8_6    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge

**Comment by ana-machado** [comment]
I am using ipython. But if I run "python example_peninsula.py --fieldset 100 100"
I have the same problem:
Traceback (most recent call last):
  File "example_peninsula.py", line 1, in <module>
    from parcels import FieldSet, ParticleSet, ScipyParticle, JITParticle, Variable
ImportError: No module named parcels

**Comment by delandmeterp** [comment]
Could you, within the conda prompt do the following:
- source ~/anaconda2/bin/activate py2_parcels
- python
(You're now in a python terminal)
- import parcels

Does that work? If so, it means that the other program when you run parcels does not use the conda python.

**Comment by willirath** [comment]
Hardly any of the requirements seem to be there. Can you rerun this by first deleting the env

conda env remove -n py2_parcels

And then run the installation again?

**Comment by ana-machado** [comment]
Still get the same problem:
Python 2.7.15 | packaged by conda-forge | (default, Oct 12 2018, 14:10:50) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import parcels
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named parcels
>>>

**Comment by ana-machado** [comment]
conda env remove -n py2_parcels
I get:
CondaEnvironmentError: Environment error: cannot remove current environment. deactivate and run conda remove again

**Comment by willirath** [comment]
Then first

```
source activate base
```

And then remove and recreate.

**Comment by willirath** [comment]
> PS: I've edited your above comment to list code as code. Check "Edit" to see how this is done.

**Comment by willirath** [comment]
Why reinstall? -- It looks like only part of the installation has actually been done. Ffmpeg is in the env. Jupyter, cartopy, and parcels itself aren't. Either because sth went wrong with conda or because you did not copy the whole installation line.

Let's see if this solves it.

**Comment by ana-machado** [comment]
thank you very much for your help. Its reinstalling ("Solving package specifications: ....."). I have to leave now, but will tell you later if it solved the problem.

**Comment by ana-machado** [comment]
Thank you for your help. This problem is solved, there was a problem with the installation due to the version of anaconda. I had to update it and now it seems parcels is working (with a lot of warnings).

**Comment by willirath** [comment]
That is good to know.

What kind of warnings do you get? (There's a bunch of warnings that are not critical. But it would be good to know if there's sth new.)

**Comment by ana-machado** [comment]
When I run python example_peninsula.py --fieldset 100 100
I get the warnings listed bellow, but it creates an output, so it seems to be working:

/home/ana/anaconda2/envs/py2_parcels/lib/python2.7/site-packages/pandas/_libs/__init__.py:4: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
/home/ana/anaconda2/envs/py2_parcels/lib/python2.7/site-packages/pandas/__init__.py:26: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (hashtable as _hashtable,
/home/ana/anaconda2/envs/py2_parcels/lib/python2.7/site-packages/pandas/core/dtypes/common.py:6: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos, lib
/home/ana/anaconda2/envs/py2_parcels/lib/python2.7/site-packages/pandas/core/util/hashing.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import hashing, tslib
/home/ana/anaconda2/envs/py2_parcels/lib/python2.7/site-packages/pandas/core/indexes/base.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (lib, index as libindex, tslib as libts,
/home/ana/anaconda2/envs/py2_parcels/lib/python2.7/site-packages/pandas/tseries/offsets.py:21: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.tslibs.offsets as liboffsets
/home/ana/anaconda2/envs/py2_parcels/lib/python2.7/site-packages/pandas/core/ops.py:16: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos as libalgos, ops as libops
/home/ana/anaconda2/envs/py2_parcels/lib/python2.7/site-packages/pandas/core/indexes/interval.py:32: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs.interval import (
/home/ana/anaconda2/envs/py2_parcels/lib/python2.7/site-packages/pandas/core/internals.py:14: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import internals as libinternals
/home/ana/anaconda2/envs/py2_parcels/lib/python2.7/site-packages/pandas/core/sparse/array.py:33: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.sparse as splib
/home/ana/anaconda2/envs/py2_parcels/lib/python2.7/site-packages/pandas/core/window.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.window as _window
/home/ana/anaconda2/envs/py2_parcels/lib/python2.7/site-packages/pandas/core/groupby/groupby.py:68: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (lib, reduction,
/home/ana/anaconda2/envs/py2_parcels/lib/python2.7/site-packages/pandas/core/reshape/reshape.py:30: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos as _algos, reshape as _reshape
/home/ana/anaconda2/envs/py2_parcels/lib/python2.7/site-packages/pandas/io/parsers.py:45: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.parsers as parsers
/home/ana/anaconda2/envs/py2_parcels/lib/python2.7/site-packages/pandas/io/pytables.py:50: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos, lib, writers as libwriters
INFO: Generating NEMO FieldSet output with basename: peninsula
Peninsula: Advecting 20 particles for 1 day, 0:00:00

**Comment by ana-machado** [comment]
But now I was trying to follow the tutorials and wasn't finding the directories with the input data. I suppose I have to create them with create_testfields.py, right? but this doesn't seem to be working.
The output I have for  "python create_testfields.py" is below. Any ideas?


/home/ana/anaconda2/envs/py2_parcels/lib/python2.7/site-packages/pandas/_libs/__init__.py:4: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
/home/ana/anaconda2/envs/py2_parcels/lib/python2.7/site-packages/pandas/__init__.py:26: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (hashtable as _hashtable,
/home/ana/anaconda2/envs/py2_parcels/lib/python2.7/site-packages/pandas/core/dtypes/common.py:6: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos, lib
/home/ana/anaconda2/envs/py2_parcels/lib/python2.7/site-packages/pandas/core/util/hashing.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import hashing, tslib
/home/ana/anaconda2/envs/py2_parcels/lib/python2.7/site-packages/pandas/core/indexes/base.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (lib, index as libindex, tslib as libts,
/home/ana/anaconda2/envs/py2_parcels/lib/python2.7/site-packages/pandas/tseries/offsets.py:21: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.tslibs.offsets as liboffsets
/home/ana/anaconda2/envs/py2_parcels/lib/python2.7/site-packages/pandas/core/ops.py:16: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos as libalgos, ops as libops
/home/ana/anaconda2/envs/py2_parcels/lib/python2.7/site-packages/pandas/core/indexes/interval.py:32: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs.interval import (
/home/ana/anaconda2/envs/py2_parcels/lib/python2.7/site-packages/pandas/core/internals.py:14: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import internals as libinternals
/home/ana/anaconda2/envs/py2_parcels/lib/python2.7/site-packages/pandas/core/sparse/array.py:33: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.sparse as splib
/home/ana/anaconda2/envs/py2_parcels/lib/python2.7/site-packages/pandas/core/window.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.window as _window
/home/ana/anaconda2/envs/py2_parcels/lib/python2.7/site-packages/pandas/core/groupby/groupby.py:68: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (lib, reduction,
/home/ana/anaconda2/envs/py2_parcels/lib/python2.7/site-packages/pandas/core/reshape/reshape.py:30: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos as _algos, reshape as _reshape
/home/ana/anaconda2/envs/py2_parcels/lib/python2.7/site-packages/pandas/io/parsers.py:45: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.parsers as parsers
/home/ana/anaconda2/envs/py2_parcels/lib/python2.7/site-packages/pandas/io/pytables.py:50: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos, lib, writers as libwriters
Traceback (most recent call last):
  File "create_testfields.py", line 20, in <module>
    generate_testfieldset(xdim=5, ydim=3, zdim=2, tdim=15)
  File "create_testfields.py", line 15, in generate_testfieldset
    fieldset = FieldSet.from_data(data, dimensions)
  File "/home/ana/anaconda2/envs/py2_parcels/lib/python2.7/site-packages/parcels/fieldset.py", line 84, in from_data
    allow_time_extrapolation=allow_time_extrapolation, time_periodic=time_periodic, **kwargs)
  File "/home/ana/anaconda2/envs/py2_parcels/lib/python2.7/site-packages/parcels/field.py", line 103, in __init__
    self.data = self.reshape(self.data, transpose)
  File "/home/ana/anaconda2/envs/py2_parcels/lib/python2.7/site-packages/parcels/field.py", line 288, in reshape
    ('Field %s expecting a data shape of a [ydim, xdim], [zdim, ydim, xdim], [tdim, ydim, xdim] or [tdim, zdim, ydim, xdim]. Flag transpose=True could help to reorder the data.')
AssertionError: Field %s expecting a data shape of a [ydim, xdim], [zdim, ydim, xdim], [tdim, ydim, xdim] or [tdim, zdim, ydim, xdim]. Flag transpose=True could help to reorder the data.

**Comment by willirath** [comment]
That's what Step 4 here http://oceanparcels.org/#installing is for:  Run `parcels_get_examples <path_to_the_desired_example_dir> to get all examples.

**Comment by ana-machado** [comment]
Ops, I had just copied the directory. Great, it seems to be working now. I've been able to complete the first tutorial "Running particles in an idealised field". I will continue to the next ones :)
Thank you very much for your help

**Comment by El-Rayes** [comment]
I followed the steps in  http://oceanparcels.org/#installing
I kept receiving the same error 'No module named parcels'
until I separated it as follows, then it ran smoothly:
from parcels import FieldSet
from parcels import ParticleSet
from parcels import Variable
from parcels import ScipyParticle, ScipyInteractionParticle
from parcels import DiffusionUniformKh
from parcels import NearestNeighborWithinRange, MergeWithNearestNeighbor

Also you may need to install xarray if you did not install it already.
