### ISSUE TITLE
Moving eddies test velocity field looks different depending on grid size

### ISSUE THREAD

**Issue by Abobie** [OceanPARCELS/parcels#50]
I noticed a while ago that the moving eddies test works well for its default grid size, but when you change the grid size the entire fields change, see pictures below. I thought I'd just fix it myself, but still haven't, so I thought I might as well post an issue in case anyone else wants to have a look at it before I get around to. Or maybe someone already knows what's causing this?
![eddiesu1](https://cloud.githubusercontent.com/assets/13031587/13848563/55096b18-ec4a-11e5-8565-fba68e1ec0db.png)
U field with default grid size, (200, 350)
![eddiesu2](https://cloud.githubusercontent.com/assets/13031587/13848564/550a2738-ec4a-11e5-87b7-84bde290712f.png)
U field with different grid size, (100, 200)

**Comment by erikvansebille** [comment]
I just rewrote bits of moving_eddies, and should be good now. I'll do a PR

**Comment by erikvansebille** [comment]
Should be fixed with latest PR
