### ISSUE TITLE
Documentation about units

### ISSUE THREAD

**Issue by jetesdal** [OceanParcels/parcels#506]
This is mostly a question. I just started looking into using parcels. Going over the examples, I wondered how the reading functions in parcels know what units the velocities (U, V, W) have. Does `FieldSet.from_netcdf()` read the metadata of the netcdf files (e.g., "units: m s-1") or is it assumed that the velocities are given in m/s? I couldn't find any info about required units in the documentation, so I wanted to check if velocities (U, V, W) should always be in m/s?

**Comment by delandmeterp** [comment]
No, we do not read the units of the fields such that we don't do any automated rescaling. If your data is not in m/s, you can use the function `Field.set_scaling_factor()`

It is noteworthy that we do the scaling between m/s and °/s, such that it is important that you set if your mesh is `spherical` or `flat`. You can check it by printing `field.grid.mesh`
When you use `Field.from_netcdf`, the default value is `spherical`

**Comment by erikvansebille** [comment]
Thanks @jetesdal, for this question. I've now added a [tutorial](https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/tutorial_unitconverters.ipynb) that further explains how UnitConverter objects are used 'under the hood' in Parcels; see also #515. Hope that this clarifies your question further
