### ISSUE TITLE
Any interest in a parallel example using joblib or an example with interacting particles using Scipy's cKDTree?

### ISSUE THREAD

**Issue by ali-ramadhan** [OceanParcels/parcels#509]
Hi everyone,

Thanks so much for developing Ocean Parcels! It's super easy to use and has quickly let me produce really beautiful movies of many interacting particles moving around. I've been using it to code up an agent-based model of interacting marine microbes.

My only concern was being able to advect millions of interacting particles. I don't think I know enough about MPI to contribute a solution so to do this I split up my particle set into _N_ equally sized particle sets (_N_ being the number of cores I am utilizing) and ran _N_ instances of parcels using [`joblib`](https://joblib.readthedocs.io/en/latest/parallel.html), using [`joblib.dump`](https://joblib.readthedocs.io/en/latest/generated/joblib.dump.html) to write the lat, lon data to disk from each worker. For some reason, using parcels' built-in output writer did not play nice with joblib. This worked very well with _N=28_ cores.

Figuring out which of the _N(N-1)/2_ particle pairs should interact given an interaction length scale (~1 km in my case) took a while to figure out as I wasn't familiar with this problem but I ended up storing the particle positions in a _k_-d tree (using SciPy's excellent [`cKDTree`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.cKDTree.html)) and using [`cKDTree.query_pairs`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.cKDTree.query_pairs.html#scipy.spatial.cKDTree.query_pairs) to very quickly create a set of particle pairs to interact. For 490,000 particles building the tree typically takes <0.5 seconds and the querying typically takes <0.5 seconds as well (all this on a single core).

I've put up my ugly code (+ some snapshots and a link to a movie) on a GitHub repo: [mixing-induced-ecological-warfare](https://github.com/ali-ramadhan/mixing-induced-ecological-warfare)

The reason I'm creating this issue (please let me know if this is the wrong place for this) is because I've been talking to people and I've been getting questions about how I coded up my agent-based model so I thought maybe I could chisel my code down into a minimal example or two if you guys think it would be useful for parcels. Maybe you don't want an example using parcels + joblib if parcels will run in parallel with MPI soon but maybe an example showing many interacting particles using a _k_-d tree might be useful?

Please let me know if I can contribute useful examples or figures/movies.

**Comment by erikvansebille** [comment]
Thanks @ali-ramadhan, for this plug of your mixing-induced-ecological-warfare repo; it certainly looks very cool! It would be awesome to put such microbial interactions into a Parcels Kernel ;-)

And yes, the cKDTree might be a good option for parallelisation of Parcels; which is our oldest open Issue (#17) and which is the main development aim for ur next version now that we've just released v2.0.0beta with updated interpolation schemes. 

A minimal example would certainly be very useful and welcomed warmly. See also @willirath's notebook at https://nbviewer.jupyter.org/gist/willirath/6b5c4654ca6be3774fa76acf4a266b96

**Comment by erikvansebille** [comment]
We are now closing this, because it is somewhat similar to #599. Yet, as we develop better index search, this is still a very good idea to keep in mind. @ali-ramadhan, let us know if you have any updates!
