### ISSUE TITLE
Parcels is slow with v1.4.2 of netCDF4 on python3

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/parcels#513]
We've recently seen that Parcels can sometimes be _very_ slow on python3. After some digging around, we think that this is related to a recent upgrade of the `netCDF4` package. We therefore suggest to avoid using v1.4.2 of the netCDF4 package, especially if you're using python3.

The plan now is to wait for a future update of `netCDF4`, and see if that fixes the slowness.

**Comment by willirath** [comment]
Related: https://github.com/Unidata/netcdf4-python/issues/809

**Comment by HandmannP** [comment]
Does one has to limit the netcdf version of the environment ? like a downgrade via conda-forge? or is this a parcels intern issue - if the case how can I downgrade the netcdf version there? Thanks in advance!

**Comment by HandmannP** [comment]
I now downgraded the netcdf version via conda install -n env_name -c conda-forge netcdf4=1.4.1 works fine :D

**Comment by erikvansebille** [comment]
This has now been fixed in #597
