### ISSUE TITLE
c-code generator for if-statements inside custom kernels

### ISSUE THREAD

**Issue by mikaelk** [OceanParcels/parcels#538]
Hi all,

There seems to be a bug in the c-code generator when using if-statements inside a custom kernel. I'll attach a sample script based on the stommel example and the corresponding c-code.

When I put an if-statement inside of another if-statement, the code inside of the if-statement (see l. 134-136 c-code) seems to get executed before the if-statement itself is checked (l. 137). The corresponding if-statement in the python code can be found on l. 91-92.

Best,
Mikael

[0d46b78f1f104285b3dc199479ae9038.c.txt](https://github.com/OceanParcels/parcels/files/2884289/0d46b78f1f104285b3dc199479ae9038.c.txt)

[Stommel.py.txt](https://github.com/OceanParcels/parcels/files/2884293/Stommel.py.txt)

**Comment by erikvansebille** [comment]
Thanks for flagging this, @mikaelk. However, the test you added is rather wieldy and obfuscated. I've created a very minimal unit test at a new branch  https://github.com/OceanParcels/parcels/tree/issue_nested_if_kernels

The key code is below
```
def fieldset(xdim=20, ydim=20):
    """ Standard unit mesh fieldset """
    lon = np.linspace(0., 1., xdim, dtype=np.float32)
    lat = np.linspace(0., 1., ydim, dtype=np.float32)
    U, V = np.meshgrid(lat, lon)
    data = {'U': np.array(U, dtype=np.float32), 'V': np.array(V, dtype=np.float32)}
    dimensions = {'lat': lat, 'lon': lon}
    return FieldSet.from_data(data, dimensions, mesh='flat', transpose=True)

def test_nested_if(fieldset, mode):
    """Test nested if commands"""
    class TestParticle(ptype[mode]):
        p1 = Variable('p1', dtype=np.int32, initial=1)
        p2 = Variable('p2', dtype=np.int32, initial=0)
    pset = ParticleSet(fieldset, pclass=TestParticle, lon=0, lat=0)

    def kernel(particle, fieldset, time):
        if particle.p1 >= particle.p2:
            particle.p2 = 1
            if particle.p2 == particle.p1:
                particle.p1 = 5

    pset.execute(kernel, endtime=10, dt=1.)
    assert np.allclose([pset[0].p1, pset[0].p2], [5, 1])

test_nested_if(fieldset(), 'jit')
```

However, that seems to work fine with nested if-statements. Or am I missing something and is the problem not with nested if-statements? Could you adapt the unit test so that it breaks; that will allow us to dig deeper

**Comment by mikaelk** [comment]
This code seems to break, hope it's clear enough now:
`def fieldset(xdim=20, ydim=20):
    """ Standard unit mesh fieldset """
    lon = np.linspace(0., 1., xdim, dtype=np.float32)
    lat = np.linspace(0., 1., ydim, dtype=np.float32)
    U, V = np.meshgrid(lat, lon)
    data = {'U': np.array(U, dtype=np.float32), 'V': np.array(V, dtype=np.float32)}
    dimensions = {'lat': lat, 'lon': lon}
    return FieldSet.from_data(data, dimensions, mesh='flat', transpose=True)

ptype = {'scipy': ScipyParticle, 'jit': JITParticle}

def test_nested_if(fieldset, mode):
    """Test nested if commands"""
    class TestParticle(ptype[mode]):
        p1 = Variable('p1', dtype=np.int32, initial=1)
        p2 = Variable('p2', dtype=np.int32, initial=0)
    pset = ParticleSet(fieldset, pclass=TestParticle, lon=0, lat=0)

    def kernel(particle, fieldset, time):
        a = 0.
        if particle.p1 > particle.p2: #should be true
            tmp_a = particle.p1  
            if tmp_a > particle.p2: #should be the same statement so also true
                a = 5
        particle.p2 = a
        
    pset.execute(kernel, endtime=10, dt=1.)
    assert np.allclose([pset[0].p1, pset[0].p2], [1, 5])

test_nested_if(fieldset(), 'jit')

`
