### ISSUE TITLE
particle.xi in scipy mode

### ISSUE THREAD

**Issue by delandmeterp** [OceanParcels/parcels#556]
While in JIT mode, we store `particle.xi[]`, `particle.yi[]` and `particle.zi[]` that keeps track of the cell in which the particle is located, we don't do it in Scipy mode.
Even if scipy mode is not meant to be as efficient as possible but rather an easy development configuration, unstored particle.xi are a serious drawback largely affecting the efficiency.
We should store them as it is done in JIT mode

**Comment by philippemiron** [comment]
Sorry, could you help me with this, where are the indices (particle.xi[]) use only in the JIT case? I can't seem to find it...

**Comment by erikvansebille** [comment]
In the new SOA implementation of the ParticleSet, ScipyParticles also have `xi` etc (see [here](https://github.com/OceanParcels/parcels/blob/master/parcels/particle.py#L177-L180)). However, these are not used and/or updated in the Field interpolation. I am working on also implementing them in ScipyParticle, but it's not simple to do

**Comment by erikvansebille** [comment]
This is now fixed in #940
