### ISSUE TITLE
ctypes and pointers

### ISSUE THREAD

**Issue by delandmeterp** [OceanParcels/parcels#560]
Every pointer to memory should be set as late as possible. This will help parallelising the code (see #553 and https://github.com/willirath/pangeo_parcels)

Could everything be set at pset.execute() ?
By everything I mean, pointers in fieldset and pset.

**Comment by willirath** [comment]
Minimal code to test if we can serialize a `ParticleSet`:

```python
import pickle
copied_pset = pickle.loads(pickle.dumps(pset))
```

**Comment by erikvansebille** [comment]
Closing this very old Issue for now.
