### ISSUE TITLE
How to add the Brownian motion to the field

### ISSUE THREAD

**Issue by cicciodevoto** [OceanParcels/parcels#570]
Hello,
this more than an issue is a question, sorry if this is not the right place where to ask for.

I am using OceanParcels for my project and I can track my objects backward and forward-in-time using AdvectionRK4. Now I want to add the Brownian diffusion, but I didn't figure out how to do it.

I saw the issue #515, the example_brownian.py and tests/test_diffusion.py, but I don't understand how the Brownian info are linked to the original field.

Do I have to execute BrownianMotion2D before AdvectionRK4 and in someway connect the results?
And  how can I save the final trajectory in just one file?
Is there any tutorial about it?

Thanks a lot!

**Comment by erikvansebille** [comment]
Hi Francesco,

You can add different kernels together by using the `+` operator, see for example cell [28] at [the Parcels tutorial](https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/parcels_tutorial.ipynb#Sampling-a-Field-with-Particles). 

A more worked-out code where we've done this is in [the code](https://github.com/OceanParcels/AntarcticPeninsulaPlastic/blob/master/plastic_antarcticpeninsula_run.py) for our recent [Lacerda et al (2019)](https://doi.org/10.1038/s41598-019-40311-4) paper, where the diffusion fields are created on [lines 59-61](https://github.com/OceanParcels/AntarcticPeninsulaPlastic/blob/master/plastic_antarcticpeninsula_run.py#L59-L61) and then concatenated on [line 83](https://github.com/OceanParcels/AntarcticPeninsulaPlastic/blob/master/plastic_antarcticpeninsula_run.py#L83). 

*Note by the way that that code was for Parcels v1.1.1, so to get it to work for Parcels v2.0, you will have to remove the `dt` arguments from the Kernel definitions (lines 31, 38 and 45), and swap the order of field-interpolation (line 39&40) to `[0, particle.depth, particle.lat, particle.lon]`*

Hope this helps. I'm closing the issue now but feel free to reopen if it's still unclear
