### ISSUE TITLE
Field.show() does not correctly determine the domain for curvilinear grids

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/parcels#580]
As reported by @phand on https://gitter.im/OceanPARCELS/parcels_running, `Field.show()` does not always correctly determine the extent of the domain for curvilinear grids. This was kind of known, as this extent is set manually at https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/tutorial_nemo_3D.ipynb

We should either fix this or if that is too complicated (remember; plotting in Parcels is intentionally very rudimentary!) at least issue a warning that the domain may not be plotted correctly for Curvilinear grids

**Comment by willirath** [comment]
cc: @HandmannP
