### ISSUE TITLE
Issue with adding a field to the fieldset

### ISSUE THREAD

**Issue by VictorOnink** [OceanParcels/parcels#589]
I have been trying to add a field to the fieldset from a file that I have used before (the one to implement an anti-beaching current) but parcels seems to have an issue with loading in the field, since when I examine the fieldset with fieldset.borU.show(), it appears that only a few of the datapoints have been included in the field. It could of course be an issue with the file, but it appears the issue lies with parcels because a) I have used this exact file before for the antibeaching current and then there was no issue (admittedly with an older version of parcels) and b) the last thing I tried was to first load the field as an array and then add it to the fieldset. The field looked fine as an array, but when I try to add it to the fieldset with fieldset.add_field the field is once again incomplete like before.
I've added the code in below.

```python
from parcels import FieldSet, ParticleSet, Geographic,GeographicPolar, JITParticle, AdvectionRK4,ErrorCode, plotTrajectoriesFile,Variable, Field
from parcels import rng as random
from datetime import timedelta, datetime
import numpy as np
from operator import attrgetter
import math
from netCDF4 import Dataset

filenames1 = {"U": "/alphadata04/onink/lagrangian_sim/GlobCurrentDailyData/GlobCurrent_Daily_Zonal_2002-01*",
             "V": "/alphadata04/onink/lagrangian_sim/GlobCurrentDailyData/GlobCurrent_Daily_Meridional_2002-01*"}

variables1 = {'U': "uo",
             'V': 'vo'}

dimensions1 = {'U':{'lat': 'latitude', 'lon':'longitude', 'time':'time'},
              'V':{'lat': 'latitude', 'lon':'longitude', 'time':'time'}}

fieldset = FieldSet.from_netcdf(filenames1, variables1, dimensions1, allow_time_extrapolation=True)

**#Now I try to add the field for the border current**
Ubor=np.array(Dataset('/alphadata04/onink/lagrangian_sim/Merlin/boundary_velocities_MERLIN.nc').variables['MaskUvel'][0,:,:])
Vbor=np.array(Dataset('/alphadata04/onink/lagrangian_sim/Merlin/boundary_velocities_MERLIN.nc').variables['MaskVvel'][0,:,:])
lonBor=np.array(Dataset('/alphadata04/onink/lagrangian_sim/Merlin/boundary_velocities_MERLIN.nc').variables['lon'][:])
latBor=np.array(Dataset('/alphadata04/onink/lagrangian_sim/Merlin/boundary_velocities_MERLIN.nc').variables['lat'][:])
**#So up to this point the arrays appear as they should, but when I then include them in the fieldset...**
fieldset.add_field(Field('borU',Ubor,lon=lonBor,lat=latBor,mesh='spherical'))
fieldset.borU.units=GeographicPolar()
fieldset.add_field(Field('borV',Vbor,lon=lonBor,lat=latBor,mesh='spherical'))
fieldset.borV.units=Geographic()
fieldset.add_periodic_halo(zonal=True)
```

**Comment by delandmeterp** [comment]
A few comments:
* You shouldn't open 4 times your nc file but only once (when you create Ubor, Vbor, ...)
* Remove in a first time spherical, periodic_helo and units to see what is happening
* Instead of showing the file, you can also show your own data Ubor with imshow. Do you face the same issue there?
* The idea is also to figure out if it's a plotting or more fundamental issue

**Comment by erikvansebille** [comment]
Thanks Victor, for reporting. I've just updated your comment with [python-flavoured markdown](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) so that the code looks better.

However, it'll be very hard for us to debug this. Can you add some info on what you expected to be a result, and what you got? Perhaps add a Figure? 

Note also that the plotting routines shipped with Parcels are extremely rudimentary, and should not always be trusted. If the plots looks weird, it's likely the plotting routines rather than the FieldSet itself

**Comment by VictorOnink** [comment]
Thank you Philippe and Erik for the feedback. Here I have more detail exactly what the issue is. 
So the anti beaching current field ought to be non-zero only in cells at the coast. Below you can see the example for when I zoom in on the UK. You can then see the outline of the british coast.
![Anti Beaching Current from File UK](https://user-images.githubusercontent.com/31734765/57133294-9dbc3e80-6da2-11e9-8368-feda3d67afd3.png)
Now the next figure is again a close up of the UK, but this time it is plotted with fieldset.borU.show(). As you can see, around the UK coastline we now only have a couple cells where we have non-zero values for the anti beaching current. I originally thought/hoped that this was just a plotting issue, but this doesn't appear to be the case since when I do the simulation, I find many of my particles beach. I have also changed the code so that it tracks the border current along the trajectory of the particle. Even if I see that the particles have beached at the coast, the along-trajectory values of the border current for all the particles are 0, indicating that the border current values have never been properly loaded.
![Anti Beaching Fieldset UK](https://user-images.githubusercontent.com/31734765/57133274-9137e600-6da2-11e9-884e-5091175570ab.png)
As for Philippe suggestions, I have indeed tried to see if removing the spherical, periodic_halo and units commands solves the issues, but this is not the case (opening the nc file 4 times was because I had quickly copied that part of the code from somewhere else, but you are right that coding it like this is unnessary. Unfortunately it also doesn't solve the issue). I have tried plotting the nc file field in several different ways and they all turn out exactly as expected. So this again indicates an issue with the fieldset, and not the plotting tools. 
I hope this clarifies the issue, but please let me know if there is anything else you need.

**Comment by erikvansebille** [comment]
This is very difficult for us to debug from here, without access to your files. 

I fear you'll have to dig into this yourself a bit. Note that you can access the data in a Field itself, so one thing you can do is compare your `Ubor` array to the values in `fieldset.borU.data`. They should be the same. If not, report back here and tell us how they are different

**Comment by delandmeterp** [comment]
The problem must be with the plotting.
To efficiently debug, you want a simple code. See

```
from parcels import FieldSet, ParticleSet, Geographic,GeographicPolar, JITParticle, AdvectionRK4,ErrorCode, plotTrajectoriesFile,Variable, Field
from parcels import rng as random
from datetime import timedelta, datetime
import numpy as np
from operator import attrgetter
import math
from netCDF4 import Dataset

def generate_fieldset(xdim, ydim, zdim=1, tdim=1):
    lon = np.linspace(0., 10., xdim, dtype=np.float32)
    lat = np.linspace(0., 10., ydim, dtype=np.float32)
    depth = np.zeros(zdim, dtype=np.float32)
    time = np.zeros(tdim, dtype=np.float64)
    if zdim == 1 and tdim == 1:
        U, V = np.meshgrid(lon, lat)
        dimensions = {'lat': lat, 'lon': lon}
    else:
        U = np.ones((tdim, zdim, ydim, xdim))
        V = np.ones((tdim, zdim, ydim, xdim))
        dimensions = {'lat': lat, 'lon': lon, 'depth': depth, 'time': time}
    data = {'U': np.array(U, dtype=np.float32), 'V': np.array(V, dtype=np.float32)}

    return (data, dimensions)

data, dimensions = generate_fieldset(xdim=10, ydim=10)
fieldset = FieldSet.from_data(data, dimensions)

#Now I try to add the field for the border current
Ubor=np.array(Dataset('./boundary_velocities_MERLIN.nc').variables['MaskUvel'][0,:,:])
Vbor=np.array(Dataset('./boundary_velocities_MERLIN.nc').variables['MaskVvel'][0,:,:])
lonBor=np.array(Dataset('./boundary_velocities_MERLIN.nc').variables['lon'][:])
latBor=np.array(Dataset('./boundary_velocities_MERLIN.nc').variables['lat'][:])
#So up to this point the arrays appear as they should, but when I then include them in the fieldset...
fieldset.add_field(Field('borU',Ubor,lon=lonBor,lat=latBor,mesh='spherical'))
fieldset.borU.units=GeographicPolar()
fieldset.add_field(Field('borV',Vbor,lon=lonBor,lat=latBor,mesh='spherical'))
fieldset.borV.units=Geographic()
#fieldset.add_periodic_halo(zonal=True)

print(np.max(fieldset.borU.data[0,:] - Ubor))
print(np.min(fieldset.borU.data[0,:] - Ubor))

import matplotlib.pyplot as plt
#plt.imshow(Ubor)
#plt.show()

fieldset.borU.show(domain={'N':60,'S':50,'W':-10,'E':10})
#plt.imshow(fieldset.borU.data[0,510:550,670:730])
#plt.show()
```

**Comment by VictorOnink** [comment]
Thanks, I'll see I can do. I didn't know that I could see the data itself, and when I compared that to the input from the nc file they matched. So therefore it might be a problem with the plotting after all, but there is still the issue that the particles don't seem to find border current field within the fieldset. So I'll see if there is a problem somewhere else in the code and I'll let you know once I find the issue

**Comment by delandmeterp** [comment]
Problem is in the A-grid plotting (plotting.py:204)
```
        else:  # if A-grid
            d = (data[0][:-1, :-1] + data[0][1:, :-1] + data[0][:-1, 1:] + data[0][1:, 1:])/4.
            d = np.where(data[0][:-1, :-1] == 0, 0, d)
            d = np.where(data[0][1:, :-1] == 0, 0, d)
            d = np.where(data[0][1:, 1:] == 0, 0, d)
            d = np.where(data[0][:-1, 1:] == 0, 0, d)
```

Since we use pcolormesh that plots in each cell the lowleft corner value (and this is not what we want),
we rewrite the data to put in the low left corner the average value of the velocity in the cell,
AND we put the cell value to 0 if one of the corners is 0. Maybe we shouldn't do that last stage.
Also, the best would be to not use pcolormesh but rather contourf for A grid plotting

**Comment by VictorOnink** [comment]
The issue was found and solved. While the plotting tool of parcels did not show the border current field correctly, as shown above, the field was loaded correctly. 
The reason why the border current didn't work was because of an issue with how I included it in the numerics of the advection. Adding the border current with a forward Euler scheme (while the advection with the surface currents U and V was done with 4th order Runge-Kutta) doesn't work. Instead, I included the border current in the Runge Kutta scheme, which works exactly as expected (and hoped for). In case it is of interest for other users, the 4th order Runge-Kutta kernel including beaching is added in below:

```
def advectionRK4border(particle, fieldset, time): 
        """Advection of particles using fourth-order Runge-Kutta integration. 
        This includes a border current, which must be loaded into the fieldset
        as borU and borV.
        Function needs to be converted to Kernel object before execution""" 
        (u1, v1) = fieldset.UV[time, particle.depth, particle.lat, particle.lon] 
        u1bor=fieldset.borU[time,particle.depth,particle.lat,particle.lon] 
        v1bor=fieldset.borV[time,particle.depth,particle.lat,particle.lon] 
        lon1, lat1 = (particle.lon + (u1-u1bor)*.5*particle.dt, particle.lat + (v1-v1bor)*.5*particle.dt) 
        (u2, v2) = fieldset.UV[time + .5 * particle.dt, particle.depth, lat1, lon1] 
        u2bor=fieldset.borU[time+.5*particle.dt,particle.depth,lat1,lon1] 
        v2bor=fieldset.borV[time+.5*particle.dt,particle.depth,lat1,lon1] 
        lon2, lat2 = (particle.lon + (u2-u2bor)*.5*particle.dt, particle.lat + (v2-v2bor)*.5*particle.dt) 
        (u3, v3) = fieldset.UV[time + .5 * particle.dt, particle.depth, lat2, lon2] 
        u3bor=fieldset.borU[time+.5*particle.dt,particle.depth,lat2,lon2] 
        v3bor=fieldset.borV[time+.5*particle.dt,particle.depth,lat2,lon2] 
        lon3, lat3 = (particle.lon + (u3-u3bor)*particle.dt, particle.lat + (v3-v3bor)*particle.dt) 
        (u4, v4) = fieldset.UV[time + particle.dt, particle.depth, lat3, lon3] 
        u4bor=fieldset.borU[time+particle.dt,particle.depth,lat3,lon3] 
        v4bor=fieldset.borV[time+particle.dt,particle.depth,lat3,lon3] 
        particle.lon += (u1 + 2*u2 + 2*u3 + (u4-u4bor)) / 6. * particle.dt 
        particle.lat += (v1 + 2*v2 + 2*v3 + (v4-u4bor)) / 6. * particle.dt
```
