### ISSUE TITLE
gcc compiler on linux

### ISSUE THREAD

**Issue by delandmeterp** [OceanParcels/parcels#591]
It seems many conda installations are currently struggling with gcc on linux.

So far in parcels, we were using the system gcc (I think it wasn't the case i the past), but if we want to have more control over the compilation options (openmp, mpi, ...) we need to control gcc version as well.

This is currently done in PR #583, but it breaks on linux. The issue message was 
```
version `GLIBCXX_3.4.20' not found 
```
This error can be fixed adding `libgcc=5.2.0` (see for example [here](https://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error) ).

But I couldn't add this link in the env.yml file successfully. (See 1672c89)
I work around I've found on a linux machine is to install libgcc=5.2.0 afterwards, not at environment creation (This is really weird, no?)

But as strange as it looks, it also works on travis. If I don't put libgcc in the env.yml but in the .travis.yml (see 04ebc04 and 615e43f)

Anyone having an explanation to that?

**Comment by willirath** [comment]
I guess the fact that you activate before installing might lead to a different set of env vars.

**Comment by delandmeterp** [comment]
I'll have a look at that.
But then what about the following point I observed?

```
env.yml (with gcc and libgcc=5.2.0)
activate
-> does not work
```

```
env.yml (with gcc)
activate
conda install libgcc=5.2.0
-> work
```

as explained above, but:
```
env.yml
activate
conda install gcc
conda install libgcc=5.2.0
-> work
```

```
env.yml
activate
conda install gcc libgcc=5.2.0
-> does not work
```

I'll create the different conda environments again, and see what are the diffs in env vars (`printenv`) before and after, to see if I can locate the strange behaviour..

**Comment by erikvansebille** [comment]
This is circumvented by using `mpicc` instead of `gcc` in #openmp,
