### ISSUE TITLE
Robust and efficient index search in Parcels

### ISSUE THREAD

**Issue by delandmeterp** [OceanParcels/parcels#599]
The search of the particle index within a grid is neither robust nor efficient.
To improve it, we will need to make use of trees.
In this [example](https://gist.github.com/fbriol/026f9cbe38a60ecceeefa8fe899368ca), fbriol uses its pyindex module that suits our needs.

An example of using pyindex in the context of Parcels is implemented in this [notebook](https://github.com/OceanParcels/bare-bones-parcels/blob/master/find_cell_curvi_mesh/find_index.ipynb).

To follow pyindex development, see this [issue](https://github.com/pangeo-data/pangeo/issues/629).

**Comment by erikvansebille** [comment]
This has now been implemented by @angus-g in #954
