### ISSUE TITLE
NetCDF file with time overlap

### ISSUE THREAD

**Issue by cicciodevoto** [OceanParcels/parcels#603]
Hello,

I have two netCDF files with a time overlap. 
E.g. the file A cover the time from the 00:30 to 23:30 of the 01/06/2019 (just 24h), and the file B from the 00:30 of the 01/06/2019 to 23:30 of the 05/06/2019 (5 days) always with the same time step of 1h.
So the two files share the first 24h, but just in time not in velocity!

I would like to track objects for 5 day, but using for the first 24h the data from file A and for the other days the data from file B. Is there a way to do this in Parcels without manipulate the files by hand?

Thanks!
Francesco

**Comment by willirath** [comment]
Depending on how you want to ingest the data in Parcels, from_xarray_dataset might be an option. This would enable you to stitch together those parts of the two netcdf files that you want to use to drive the experiment.

**Comment by cicciodevoto** [comment]
Usually I use from_netcdf, so I give to Parcels the files and everything works fine, but now I have this problem.

If I understand correctly,  with from_xarray_dataset, I have to manipulate the array so to substitute the overlapping data with the right one and then give it to Parcels. Am I right?

**Comment by willirath** [comment]
Yes. You'll probably have to use the `isel` method to select the relevant parts of both datasets and then the `concatenate` function to stitch them together.

**Comment by cicciodevoto** [comment]
Sorry for the delay. Thanks I will try it, for now I close this issue.
