### ISSUE TITLE
Objects linking to each other

### ISSUE THREAD

**Issue by delandmeterp** [OceanParcels/parcels#607]
It seems we have a problem in Parcels with many object linking to each other.
This is observed in PR #605

if `fieldset.U = U` and `U.fieldset = fieldset`, both object are linking each other. 
The consequence of this is that objects are not correctly destroyed.

I have observed such bug in `py.test example_peninsula.py`:

Now that we use dask, it seems (I'm not sure) that because of this issue, the netcdf file are kept locked since the objects pointing to them still exist.
It wasn't the case before since the np.array was taken from the file and the file was closed.
In dask, even if we close the file, it is still accessible.

All this is illustrated in the example below:
option 1: crashes (except if the mirror links are killed uncommenting two lines.
               Also, it only crashes if a dask.compute() function is called
option 2: no mirror links, all is fine
option 3: A parcels independent example of this issue
option 4: If we repeat option 3 many times, link to file 0 stays, but others are killed. Don't ask me why...

```
from parcels import FieldSet, Field
import xarray as xr
import numpy as np
import dask.array as da

def peninsula_fieldset():
    lon = np.linspace(0,1,10)
    lat = np.linspace(0,1,10)
    U = np.zeros((10,10))
    V = np.zeros((10,10))

    data = {'U': U, 'V': V}
    dimensions = {'lon': lon, 'lat': lat}
    return FieldSet.from_data(data, dimensions, mesh='flat')

def fieldsetfile(it=None):
    filename = 'peninsula' if it is None else 'peninsula_%d' % it
    fieldset = peninsula_fieldset()
    fieldset.write(filename)
    return filename

class O1():
    def __init__(self):
        pass
class O2():
    def __init__(self):
        pass

def func(option):
    if option == 1:
        fieldset = FieldSet.from_parcels(fieldsetfile())
        fieldset.U.data.compute()
        print(fieldset)
        print(fieldset.U.fieldset)
        #fieldset.U.fieldset = None
        #fieldset.V.fieldset = None

    elif option == 2:
        fieldsetfile()
        dims = {'lon': 'nav_lon', 'lat': 'nav_lat'}
        u = Field.from_netcdf(filenames='peninsulaU.nc', variable='vozocrtx', dimensions=dims)
        u.data.compute()

    elif option == 3:
        fname = fieldsetfile()
        ds = xr.open_dataset(fname+'U.nc')
        u = da.from_array(ds.vozocrtx, chunks='auto')
        u.compute()
  
        o1 = O1()
        o2 = O2()
        o1.u = u
        o1.o2 = o2
        o2.o1 = o1

    else:
        for it in range(4):
            fname = fieldsetfile(it)
            ds = xr.open_dataset(fname+'U.nc')
            u = da.from_array(ds.vozocrtx, chunks='auto')
            u.compute()
  
            o1 = O1()
            o2 = O2()
            o1.u = u
            o1.o2 = o2
            o2.o1 = o1


func(3)
dset = xr.Dataset()
dset.to_netcdf('peninsulaU.nc')
dset.to_netcdf('peninsula_1U.nc')
```

**Comment by delandmeterp** [comment]
In a simple example, I manage to fix some issue by manually destroying the fields.fieldset pointer
This should simply be stated in the field destructor,

BUT

I still have problems when a particle is initialised from a field. I think it is the same issue that this Parcels independent problem (same as option 3 yesterday, but without all the links, and with two dask.compute() calls (this is crucial to make it crash):

```
def func():
    fname = fieldsetfile()
    ds = xr.open_dataset(fname+'U.nc')
    u = da.from_array(ds.vozocrtx, chunks='auto')
    u.compute()
    u.compute()
 
func()
dset = xr.Dataset()
dset.to_netcdf('peninsulaU.nc')
```

If we compute twice the array, then `ds` is locked. Why??

**Comment by delandmeterp** [comment]
See issue reported in [dask](https://github.com/dask/dask/issues/4966)

**Comment by delandmeterp** [comment]
Note that `gc.collect()` can also remove object even if they are locked in a linking loop. But it is not advisable to run it during code execution.

Proper way would be to define __del__ method for our different classes.
-> Defining a __del__ method might disturb the gc.collect calls (see https://pymotw.com/2/gc/), but it seems it's not a problem anymore (I've just tested it)

**Comment by CKehl** [comment]
As a closure: we are able to integrate the GC on command, but setting the `postIterationCallbacks` and the `callbackdt` for `ParticleSet.execute()`, where `postIterationCallbacks` is a Python list `[]` of function handlers, that are called during execution. This allows in-run garbage collection.

The problem itself has been reasonably resolved in recent patches, so that memory leaks from parcels internally shall not occur. If one still runs into accumulating memory errors, integrating a function call like:
```
def clean_memory():
    gc.collect()
```
as callback for the `ParticleSet` would resolve this issue.
