### ISSUE TITLE
`Field.from_netcdf()` requires lists in `variables` dict, while `FieldSet.from_netcdf()` does not

### ISSUE THREAD

**Issue by daanreijnders** [OceanParcels/parcels#608]
**Problem description:**
I want to use `Field.from_netcdf()` to add a field to an existing fieldset. The mesh arrays for the `lat` and `lon` dimensions are saved in a separate file than the `data` and I would like to pass a dictionary with the locations to these files as follows:

```
filenames = {'lon': path_to_mesh,
             'lat': path_to_mesh,
             'data': path_to_field}
variable = ('variable_name_in_parcels', 'variable_name_in_netcdf')
dimensions = {'time': 'time',
              'lat': 'TLAT',
              'lon': 'TLON'}
field = Field.from_netcdf(filenames, variable, dimensions)
```
While this is allowed in `FieldSet.from_netcdf()`, `Field.from_netcdf()` throws an assertion error because it requires `filenames['lon'] == 1`, likely checking that this is a list of length one. 

**Current workaround:** put paths in list (took some time and help from @delandmeterp to figure this out)

**Suggestion:** allow `filenames['lon']` to be a string, as is allowed when using `FieldSet.from_netcdf()`.

**Comment by delandmeterp** [comment]
Hi Daan,

Can you have a look if PR #609 solves the issue? It should.

**Comment by daanreijnders** [comment]
Yes, it solves the issue. Thanks!
