### ISSUE TITLE
How to create a frozen binary

### ISSUE THREAD

**Issue by cicciodevoto** [OceanParcels/parcels#611]
Hello,

I am working in Windows 10 and I created a frozen binary of my script.
But when I run it I obtain this error:

`INFO: Compiled random ==> c:\users\fdevoto\appdata\local\temp\parcels-tmp\parcels_random_5300ff60-5a01-47e2-bdb0-10185260fe4a.
so
Traceback (most recent call last):
  File "src\modules\test.py", line 131, in <module>
  File "site-packages\parcels\particleset.py", line 497, in Kernel
  File "site-packages\parcels\kernel.py", line 76, in __init__
  File "inspect.py", line 700, in getsource
  File "inspect.py", line 689, in getsourcelines
  File "inspect.py", line 528, in findsource
IOError: source code not available
[2836] Failed to execute script test`

If I understand correctly how Parcels works, it read the .py file and create a .c file which is compiled by the gcc compiler into a dll.
Because I created the frozen binary, the .py file doesn't exist anymore, I have the .exe one and, of course, Parcels doesn't find the source code.

Is there a way to obtain a working frozen binary?
And is it also possible to create the dll just once so to avoid the presence of the gcc compiler on the pc?

Thanks,
Francesco

**Comment by erikvansebille** [comment]
Dear Francesco,

Thanks for raising this issue, and sorry for the slow response. However, none of us here work on Windows, and we have no experience with dll libraries. However, if it's a matter of hardcoding the library location, you could look into editing the `Kernel.load_lib()` function at https://github.com/OceanParcels/parcels/blob/master/parcels/kernel.py#L178-L180. No idea if this would work, but you could try?

Best wishes,
Erik and Philippe

**Comment by cicciodevoto** [comment]
Dear Erik,

thank you very much for the answer and sorry for my extremely slow response.

I solved the error in PyInstaller just adding these lines to the spec file:

```
coll = COLLECT(exe,
                         a.binaries, Tree('C:\\Users\\fdevoto\\AppData\\Local\\Continuum\\miniconda2\\envs\\py2_parcels\\Lib\\site-packages\\parcels', prefix='Lib\\site-packages\\parcels\\'),
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='test')
```

It will copy the parcels folder in the executable one.

About the library location, I moved to ScipyParticle so to avoid, at least for now, the problem. 

If I will find a better solution for both the questions, I will update this post.

Thank you very much!
Francesco
