### ISSUE TITLE
Fieldset time from_netcdf

### ISSUE THREAD

**Issue by Nixonst** [OceanParcels/parcels#612]
When running the following script I am getting this error.  I am on the current version of parcels and have tried with and without netcdf_engine = 'scipy'. Any advice would be much appreciated.

`
from IPython import get_ipython
from parcels import FieldSet, ParticleSet, JITParticle, AdvectionRK4, plotTrajectoriesFile, Variable
#import numpy as np
#import math
from datetime import timedelta

filenames = {'U':'GLORY_1999.nc',
             'V':'GLORY_1999.nc',
             'evap':'core/1999.nc',
             'prec':'core/1999.nc'}

variables = {'U': 'uo',
             'V': 'vo',
             'evap':'F_evap',
             'prec':'F_prec'}

dimensions = {'U':{'lat': 'latitude','lon': 'longitude','time': 'time'},
              'V':{'lat': 'latitude','lon': 'longitude','time': 'time'},
              'evap':{'lat': 'lat','lon': 'lon','time': 'time'},
              'prec':{'lat': 'lat','lon': 'lon','time': 'time'}}

fieldset = FieldSet.from_netcdf(filenames ,variables, dimensions, netcdf_engine = 'scipy')`

<img width="779" alt="Screenshot 2019-06-25 at 16 04 47" src="https://user-images.githubusercontent.com/50363369/60073186-17e5bf80-9763-11e9-8f4f-3c3233ca0035.png">

**Comment by erikvansebille** [comment]
Hi Stefan,

Not sure why this bug is occurring. Could you send me your input files, so I can do some debugging? Use my email address e.vansebille@uu.nl

**Comment by Nixonst** [comment]
Glory_1999.nc
<https://drive.google.com/file/d/1e0Pl6qnoJ1pktvoyfoOlpgf0u44ZJffF/view?usp=drive_web>
Dear Erik,

Please find attached the input file that's causing the problem, the glory
data works fine advecting particles by itself so I presume it is this one.

Also could you let me know how you debug it as I have 20 years worth of
this data that are all showing the same problem.

Regards,
Stefan Nixon.
 1999.nc
<https://drive.google.com/file/d/1EzqeE9odTuSnZ3O6qfdwbaT5ZmlEKIyp/view?usp=drive_web>

**Comment by erikvansebille** [comment]
We've just released version 2.0 yesterday, and it's now available on conda. Can you confirm for us that the issue is also present in this new version 2.0?

**Comment by Nixonst** [comment]
Dear Erik, 

Sorry about the time it took me to reply, the issue now is an issue opening the netcdf where I need to set decode to false. Is this possible by editing the source code?

Regards,
Stefan Nixon

**Comment by erikvansebille** [comment]
Hi Stefan,

First of all, sorry for the slow response.

I had a look at your data, and it may be that the data is read in if you change https://github.com/OceanParcels/parcels/blob/master/parcels/field.py#L1531 to
```python
try:
    ds = xr.decode_cf(ds)
except:
    pass
```
Could you check if this works for you?

**Comment by erikvansebille** [comment]
Hi Stefan,

I just wanted to follow up on this Issue about your problem with calendars in Parcels. We now have a new tutorial (see https://github.com/OceanParcels/parcels/blob/master/parcels/examples/tutorial_timestamps.ipynb) that explains how you can use the `timestamps` argument in your `FieldSet` creation to circumvent any issues with calendars. Does that work for you Issue too?
