### ISSUE TITLE
Order output file backward simulations

### ISSUE THREAD

**Issue by OlivelliAri** [OceanParcels/parcels#616]
The order of the netcdf output file of a backward simulation is not consistent with the order in which particles are defined. Releasing four particles [1,2,3,4] at location and time (sharing same month and year):

`lats_orig = [-33.66477, -33.51575, -33.43135, -33.31850]`
`lons_orig = [18.03866, 15.40349, 13.62885, 11.47783] `
`days_orig = [4, 5, 5, 6]`

The output file is ordered [4,2,3,1]

**Comment by erikvansebille** [comment]
We are very close to merging the brand-new implementation of the `Particlefile` object (#497) to `master`, and I just checked that this is fixed in that new implementation (see a new unit test committed in ab2976a). 

So I suggest to either use the branch of #497 or wait until it lands in `master`
