### ISSUE TITLE
Time periodic fields

### ISSUE THREAD

**Issue by delandmeterp** [OceanParcels/parcels#642]
In the current version of Parcels, if users provide a periodic field, they need to provide the first and last time steps of the time series (i.e. [0, 1, 2, ..., 24] for a daily cycle, [Jan 1st, ..., Jan 1st ] for a yearly cycle, ...

There is some redundancy in this system, since some data needs to be provided once.

This should be fixed in the future such that users only provide the series as [0, ..., 23] or [Jan 1st, ..., Dec 31st]

But because of this, it will be necessary to provide also the period of the time series, since all time steps are not necessarily equal (e.g. [Jan 1st, Feb 1st, ..., Dec 1st].
Unlike what is currently implemented, the fact that Dec has 31 days is lost, such that period is necessary.

**Comment by erikvansebille** [comment]
Fixed in #641
