### ISSUE TITLE
`FieldSet.from_netcdf()` timestamps for one NetCDF file containing multiple timesteps

### ISSUE THREAD

**Issue by daanreijnders** [OceanParcels/parcels#648]
NetCDF files don't always have a time axis that is formatted in a way that Parcels can read them. In some cases, the time axis is just an index. Parcels already has the `timestamps` parameter built into `Fieldset.from_netcdf()`, which allows users to pass arrays with `np.datetime64` corresponding to the actual date-times of a snapshot. However, it is currently implemented in such a way that each array element corresponds to one field file which contains a single timestep. Therefore, this does not work for NetCDF files containing multiple timesteps.

Proposed solution: ability to pass a nested arrays with `np.datetime64` objects. Outer index corresponds to individual field files, while the inner index corresponds to time indices within a file. 

It is also useful to implement this for `FieldSet.from_pop`, `FieldSet.from_nemo` etc.

**Comment by erikvansebille** [comment]
This has been fixed in #653, thanks @daanreijnders for finding this bug _and_ suggesting a fix!
