### ISSUE TITLE
Renaming grid.time and grid.time_full

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/parcels#651]
The naming of `grid.time` and `grid.time_full` is now somehwat confusing, because users would typically use `grid.time` when they need `grid.time_full` (see also https://github.com/OceanParcels/parcels/pull/650#discussion_r326561584)

Suggestion is to change the naming of `time` to e.g. `_defer_time` (signalling that it's a private attribute) and of `time_full` to `time`

**Comment by CKehl** [comment]
Agreed - this may be subject to change in the soon future.
