### ISSUE TITLE
Parcels crashes if too many files open

### ISSUE THREAD

**Issue by erikvansebille** [OceanPARCELS/parcels#66]
The code doesn't seem to work with too many files open, at the moment. 

Do a `git pull` on the latest parcels-examples code, and then run `python examples/test_globcurrent.py`. This will give the netcdf error message `RuntimeError: Too many open files`

The problem is that we currently read in _all_ data before we start running particles; this can become an enormous amount of data very quickly (the total size of the GlobCurrent data set is > 200GB)

Ideal is to read in data 'on the fly', I guess. But this might require (yet again) a large rewrite of the code?

A simpler fix that might go a long way for now is to close files after we're done with them?

**Comment by mlange05** [comment]
Ok, I just pushed a fix for this to the `adding_globcurrent_support` branch. The fix introduces a new class `FileBuffer` that we can later extend to do on-the-fly data reads and even grid partitioning.
