### ISSUE TITLE
its possible to change particle mass, size and weight ?

### ISSUE THREAD

**Issue by mehrezboulares** [OceanParcels/parcels#675]

**Comment by erikvansebille** [comment]
Dear @mehrezboulares. You can assigna  particle mass, size and weight if you want by adding custom Variables (see https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/parcels_tutorial.ipynb#Calculating-distance-travelled)

However, note that these sizes etc won't change the dynamics of the particles; i.e. their trajectories won't change unless you write kernels that do something to the particles based on their mass, size etc. That is for you as a user to do

Good luck!
