### ISSUE TITLE
Unable to decode by xarray for netcdf from hycom

### ISSUE THREAD

**Issue by ryohekono** [OceanParcels/parcels#679]
Dear anyone,

I am a very beginner of python and working on the very beginning of the first tutorial now.
My issue is when I use hycom netCDF files at the section of "Reading in data from arbritrary NetCDF files" in the first tutorial, FieldSet.from_netcdf() gives me back warnings of "File hycom---uv3z.nc could not be decoded properly by xarray (version 0.13.0) ".
I've been stuck on here and no clue how to solve this issue.
Probably because of this issue, I cannot create the right output_file of particleset.

![issue](https://user-images.githubusercontent.com/56178123/67485521-1f11d100-f662-11e9-9e84-d700e3cabb1b.png)

I've already tried to modify the netcdf_engine='xarray' to 'scipy' in the Field.py file, but it didn't work.
This might be a very easy and stupid question, but I really need any solutions.
Thank you.

Link: HYCOM data files I use mainly (ones ending with ut3z.nc)
ftp://ftp.hycom.org/datasets/GLBu0.08/expt_91.1/data/hindcasts/2016/

**Comment by erikvansebille** [comment]
Dear @ryohekono. This may have to do with the calendar in the files. Have a look at the tutorial at https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/tutorial_timestamps.ipynb that explains how you can use the `timestamps` argument to circumvent the decoding of calendars.

**Comment by ryohekono** [comment]
Hello @erikvansebille, and thank you very much for the answer.
I tried timestampts and it still gives me back a message of undecoding.
I am so sorry to keep asking you, but I hope you could have a look at my issue.

![issue1](https://user-images.githubusercontent.com/56178123/67571276-7a5bc600-f72b-11e9-80ed-b54e1df733d7.png)

**Comment by erikvansebille** [comment]
Dear @ryohekono. Looking at your screenshots again, I'm not sure what exactly the problem is. You see Warnings, but these may not have to be a problem. They are thrown by xarray, and we've seen them before in our own experiments too. Still, the particle execution is fine

Can you check that the particle execution is really wrong? Do you get any errors? Otherwise, I think you can just ignore these warnings

**Comment by ryohekono** [comment]
Hi @erikvansebille , thank you so much for your response back!
If i can simply ignore the warning messages, that's good to hear. But I still keep receiving the same error when i attempt to execute to create the output. (Please have a look at the photo below)
Is there any possibly plausible ideas to solve this? I've been stuck here over a week...

![issue2](https://user-images.githubusercontent.com/56178123/67589541-8908a400-f750-11e9-96b5-df229ebb29b1.png)
![issue3](https://user-images.githubusercontent.com/56178123/67589542-89a13a80-f750-11e9-9d76-b100173d4c63.PNG)

**Comment by erikvansebille** [comment]
I've just check the issue, and it seems to be a problem with the way land values are stored in the hycom data. 

The solution is to add `vmin=-2000` when you create the `FieldSet.from_netcdf`

**Comment by ryohekono** [comment]
Hi, @erikvansebille 
Thank you so much!
It's finally worked successfully!
I really appreciate your support. Thank you!

**Comment by erikvansebille** [comment]
I think you've solved it now in https://github.com/OceanParcels/parcels/issues/865? 

Indeed, 
```python
fieldset = FieldSet.from_netcdf(filenames, variables, dimensions, vmin=-2000)
``` 
is the way to add `vmin`
