### ISSUE TITLE
Lagrangian Diffusion

### ISSUE THREAD

**Issue by Jacketless** [OceanParcels/parcels#68]
While a random walk approximates Eulerian diffusion in a discretised framework when diffusivity is uniform, things are not so trivial when the diffusion field is spatially variable. Getting these kernels right are critical part of the tuna project milestone (and any other application that wishes to diffuse particles), so I've been working away on this (which is why I've been quiet for the last week or so!)

Will be finishing up a PR soon that uses the gradient and density additions from #67 and #62

**Comment by erikvansebille** [comment]
As we now have both Uniform Brownian Diffusion (#269)  and Non-uniform Brownian diffusion (#340)  kernels, as well as expovariate random functionality (#333), closing this Issue for the moment
