### ISSUE TITLE
Adding a swimming velocity to particles

### ISSUE THREAD

**Issue by pierrick-giffard** [OceanParcels/parcels#680]
Hello @erikvansebille and @delandmeterp,

I would like to implement active movements to particles, i.e. I would particles to move at velocity V_tot = V_current + V_swim. V_swim should be calculated at each time step and for each particle (it depends on the water temperature at the particle location and on the particle age). Is there any way to add a swimming velocity at each time step and for each particle ?

Thanks a lot for your help,
Pierrick

**Comment by erikvansebille** [comment]
Hi @pierrick-giffard 

Two options:
1) create a custom kernel where you compute the swimming velocity yourself and add it to the particle positions. See the [parcels tutorial](https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/parcels_tutorial.ipynb) for how to create a custom kernel
2) Create a Field object that has `V_swim` everywhere and then use SummedFields to move your particles with the sum of the currents and swimming. See the [SummedFields kernel](https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/tutorial_SummedFields.ipynb)

It depends on your situation (size of fields, number of particles) which is more efficient. The advantage of 2) is that it is easy to use RK4-integration, in 1) you will have to write that yourself

Good luck!
