### ISSUE TITLE
Question about pre-computed velocity fields

### ISSUE THREAD

**Issue by ArnoiZ** [OceanParcels/parcels#681]
Hi,

I am trying to run a particle tracking simulation for a relatively small ocean area. I downloaded data from GlobCurrent but found that the size of the subset for the area I selected was only  8*8, which is not very accurate.
Is there any method that I could calculate the velocity field for a specific area?

Best regards,

Ming

**Comment by erikvansebille** [comment]
Dear Ming

Sorry, but this really does not appear to be a question/issue about Parcels, so we can't help you here on github. If you want velocity fields, I suggest you go to other places on the internet where these are provided. As you may understand, we are a small team and have only limited capacity to provide support, which we focus on dealing with bugs and issues about the Parcels code itself

Good luck
Erik

**Comment by ArnoiZ** [comment]
Sorry for the interruption, thank you very much!
