### ISSUE TITLE
errors when I try to use the tools

### ISSUE THREAD

**Issue by wongchieh** [OceanParcels/parcels#686]
hello！  I am new to use these tools to do the parcels.  But I met a lot of problems when I use it.

the first is :
  when I use the "conda create -n py3_parcels -c conda-forge python=3 parcels jupyter cartopy ffmpeg" to create an environment, the matplotlib is always not working, though I install a new one after I unstall the last one.  and also the command "pset.execute(AdvectionRK4, runtime=14000, dt=10, output_file= pset.ParticleFile(name='practise3.nc', outputdt=50))"  didn't out_put a file in the directory"'practise3.nc'", on the contary, it will be saved in a new direcrory such as "out-atoanbgy",and there are many ".npy" files in it, I don'know what's going wrong.

and the second is:
  I tried to install all the packages doing the parcels need, but this will go into another problem, 

**### FileNotFoundError                         Traceback (most recent call last)
E:\ProgramData\Anaconda3\envs\parcels\lib\site-packages\parcels\compiler.py in compile(self, src, obj, log)
     48             try:
---> 49                 subprocess.check_call(cc, stdout=logfile, stderr=logfile)
     50             except OSError:

E:\ProgramData\Anaconda3\envs\parcels\lib\subprocess.py in check_call(*popenargs, **kwargs)
    341     """
--> 342     retcode = call(*popenargs, **kwargs)
    343     if retcode:

E:\ProgramData\Anaconda3\envs\parcels\lib\subprocess.py in call(timeout, *popenargs, **kwargs)
    322     """
--> 323     with Popen(*popenargs, **kwargs) as p:
    324         try:

E:\ProgramData\Anaconda3\envs\parcels\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    774                                 errread, errwrite,
--> 775                                 restore_signals, start_new_session)
    776         except:

E:\ProgramData\Anaconda3\envs\parcels\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
   1177                                          os.fspath(cwd) if cwd is not None else None,
-> 1178                                          startupinfo)
   1179             finally:

FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
<ipython-input-34-b30311bb32f4> in <module>
      1 pset = ParticleSet(fieldset, pclass=JITParticle, lon=[0], lat=[1000])
      2 output_file = pset.ParticleFile(name='NestedFieldParticle1.nc', outputdt=50)
----> 3 pset.execute(AdvectionRK4, runtime=14000, dt=10, output_file=output_file)

E:\ProgramData\Anaconda3\envs\parcels\lib\site-packages\parcels\particleset.py in execute(self, pyfunc, endtime, runtime, dt, moviedt, recovery, output_file, movie_background_field, verbose_progress)
    329                 self.kernel.remove_lib()
    330                 cppargs = ['-DDOUBLE_COORD_VARIABLES'] if self.lonlatdepth_dtype == np.float64 else None
--> 331                 self.kernel.compile(compiler=GNUCompiler(cppargs=cppargs))
    332                 self.kernel.load_lib()
    333 

E:\ProgramData\Anaconda3\envs\parcels\lib\site-packages\parcels\kernel.py in compile(self, compiler)
    173         with open(self.src_file, 'w') as f:
    174             f.write(self.ccode)
--> 175         compiler.compile(self.src_file, self.lib_file, self.log_file)
    176         logger.info("Compiled %s ==> %s" % (self.name, self.lib_file))
    177 

E:\ProgramData\Anaconda3\envs\parcels\lib\site-packages\parcels\compiler.py in compile(self, src, obj, log)
     51                 err = """OSError during compilation
     52 Please check if compiler exists: %s""" % self._cc
---> 53                 raise RuntimeError(err)
     54             except subprocess.CalledProcessError:
     55                 with open(log, 'r') as logfile2:

RuntimeError: OSError during compilation
Please check if compiler exists: gcc**

I am so confused how to solve these problems.

**Comment by erikvansebille** [comment]
Dear @wongchieh. I'm not sure what went wrong in your first error, but please note that it is expected that during the run, the output will be saved in a temporary file. Only at the end of the run are these temporary files converted to a netcdf file. This makes Parcels much more efficient. You can always convert the files at the end of the run using the `parcels_convert_npydir_to_netcdf` tool.

For your second error, I don't think we can help. This seems to be a windows error (something with the c-compiler?), but we don't run windows computers ourselves. Perhaps your system administrator can help?

**Comment by wongchieh** [comment]
dear erik,
&nbsp; &nbsp;thanks for your help, I've solved the problems and run it successfully, it is very useful.&nbsp; &nbsp;
best wishes
wong



---Original---
