### ISSUE TITLE
RemoteDisconnected   when showing the map where the fieldset is set by ‘from_netcdf’

### ISSUE THREAD

**Issue by wongchieh** [OceanParcels/parcels#689]
hello,
  the tools are very useful and fast. But I have a problem which seems to  exist only in windows users or chinese users.  the problem is:
   first I set the field using`fieldset = FieldSet.from_netcdf(filenames, variables, dimensions)`,  and the erro rose when I want to show the field using the command `fieldset.U.show(land=True)`.  and it will warm me that ` warnings.warn('Downloading: {}'.format(url), DownloadWarning)`    and I guess if this is because I am a Chinese user so I have no right to download the coastline.  `Remote end closed connection without response` this is the end of the error.

**Comment by willirath** [comment]
The download is triggered by cartopy which needs to obtain shape files from <http://www.naturalearthdata.com/>.  Can you access this website directly?  (Might also be a local firewall issue I've often seen when working on large scientific-computing clusters.)

**Comment by erikvansebille** [comment]
If you can't download the cartopy data, I suggest you write your own plotting routines. This in general is recommended, as Parcels only provides _very_ rudimentary plotting

**Comment by wongchieh** [comment]
can't I download the costline data directly, and set a path for drawing the costline to avoid to connect with the website?
