### ISSUE TITLE
Validation of particle tracking across nested grids

### ISSUE THREAD

**Issue by Plagioclase** [OceanParcels/parcels#697]
Apologies if this is too off-topic, but whilst I'm very impressed that OceanParcels allows you to use nested grids, I wanted to ask if particle tracking across nested grids has been tested/validated before (in particular I wonder what happens at the domain interfaces)? I ask because I've not managed to find any examples of this being done in the literature, and I'd rather avoid re-inventing the wheel before I launch into an investigation myself!

**Comment by erikvansebille** [comment]
Thanks @Plagioclase! For Parcels, we've tested/validated the `NestedFields` capability both in the [tutorial](https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/tutorial_NestedFields.ipynb) and in the [paper in GMD](https://www.geosci-model-dev.net/10/4175/2017/), but not much more than that. 

I know that the nested approach has been used much more extensively in [CMS](https://www.sciencedirect.com/science/article/pii/S136481521200312X?via%3Dihub), but not sure which articles would be the most relevant..
