### ISSUE TITLE
Using 2D fields for a behaviour kernel associated with a 3D fieldset

### ISSUE THREAD

**Issue by ElizaJayne11** [OceanParcels/parcels#698]
I want to first thank you for having produced such a powerful computational tool. It is clearly amenable to all sorts of transport-related questions that the ocean community wants to address.
I should also preface my "issue" with the acknowledgement that not only am I new to Parcels, but also to Python, having been trained in MATLAB/Fortran, so please forgive me if my problems are naive.

I am trying to use Parcels to simulate 3D Adv + 2D Dif of plankton, which are initialized at a depth of 25m or the midpoint of the water column, whichever is shallower, and which weakly swim toward the local pycnocline as they are transported around. 

Both the bathymetry and the mixed-layer depth fields are 2D, whereas my velocity fieldset is 3D. I was unable to find any examples you had that incorporated sampling of 2D variables associated with a 3D fieldset. So instead, I defined a second fieldset (2D) that enabled me to interpolate the bathymetry field to the initial particle location (please see below). However when I tried to use that second fieldset in my  behavioral kernel, I got the error that "NotImplementedError: Cannot convert 'fieldset2' used in kernel to C-code". 

One workaround that I see is to simply create 3D fields out of my 2D variables by repeating the values at every depth. But that seems klugey and I am assuming there is a more elegant way of doing this. Any advice is much appreciated.

#Lines from main code relating to bathymetry
a = np.loadtxt('ICs2_noland.txt')
lonp = a[:,0] 
latp = a[:,1]
depthp = 25*np.ones(len(lonp));

bathy = loadmat(data_path + 'lonlat_bathy.mat')['Bathymetry']
bathy_lon = loadmat(data_path + 'lonlat_bathy.mat')['lon']
bathy_lat = loadmat(data_path + 'lonlat_bathy.mat')['lat']
data2D = {'Bathy': bathy}
bathy_dimensions = {'Bathy': {'lon': bathy_lon, 'lat': bathy_lat}}
fieldset2 = FieldSet.from_data(data2D, bathy_dimensions, extra_fields={'Bathy': 'Bathy'})

bathyp = np.zeros(len(lonp))
for i in range(0,len(lonp)):
    bathyp[i] = fieldset2.Bathy[0,0,latp[i], lonp[i]]  

depthp[bathyp <50]= bathyp[bathyp <50]/2
depthp[depthp<.51]=.51  

#Lines for defining behavioral kernel. Note here for simplicity, I am using the preferred depth as the midpoint of the water column  and not the mixed layer depth (i.e. ultimately it will be a second 2D variable that needs to get interpolated to the particle location
def VertVel(particle, fieldset2, time):
    bathyp = fieldset2.Bathy[time,5,particle.lat, particle.lon]
    prefdep = min(25,bathyp/2)
    if prefdep < .51:
      prefdep = .51 
    range = min(5,bathyp/2)
    if particle.depth < prefdep - range:
      wbehave = .001
    elif particle.depth > prefdep + range:
      wbehave = -0.001
    particle.depth += wbehave * particle.dt

**Comment by erikvansebille** [comment]
Hi @ElizaJayne11, thanks for the nice words and for starting to use Parcels!

You're getting this error because in a kernel definition, the fieldset _has_ to be called `fieldset`. So calling it `fieldset2` is not allowed

The idea is that you always have only one fieldset in parcels. But a fieldset can have multiple fields, on different grids. So you could very well combine 2D and 3D grids into the same fieldset. 

Either do it all in one call to `FieldSet.from_data()` or `FieldSet.from_netcdf()` or similar, or, if that's easier, add individual Fields to a Fieldset using `fieldset.add_field()`

Does that help? Good luck!

Erik

**Comment by ElizaJayne11** [comment]
I hadn't realized that it needed to be named "fieldset" because I had seen the example here: https://github.com/OceanParcels/parcels/blob/master/tests/test_advection.py
which defines both a "fieldset2D" (line 45) and a "fieldset3D" (line 55). Is the issue of fieldset names specific to custom kernels?

Unfortunately, I can't define my fieldset all in one call, because some of the fields' files are in netcdf format and others are straight data. I am struggling with getting the fieldset.add_field syntax correct when I have to simultaneously define a new 2D grid for the new field. Could you possibly point me to an example of some code that does this?

**Comment by erikvansebille** [comment]
The script at https://github.com/OceanParcels/PumiceEvent/blob/master/pumiceevent_forecast.py actually has two different ways to combine Fields to a Fieldset:
1) via creation of a new fieldset ([line 41](https://github.com/OceanParcels/PumiceEvent/blob/master/pumiceevent_forecast.py#L41))
2) via `add_field()` ([line 49-51](https://github.com/OceanParcels/PumiceEvent/blob/master/pumiceevent_forecast.py#L49-L51)) 

Does that help?

**Comment by ElizaJayne11** [comment]
Yes that was very helpful. Thank you. I am now able to add my Bathymetry and MLD to the fieldset, and my behavior kernel appears to be working.
