### ISSUE TITLE
Py3.8 breaks parcels on a Mac?

### ISSUE THREAD

**Issue by willirath** [OceanParcels/parcels#700]
I've run into compilation errors just specifying `python=3` upon installation. Falling back to `python=3.6` seems to have solved this for now.

Should the installation instructions be adapted until this is figured out?

(Related: #691)

**Comment by erikvansebille** [comment]
OK, I've now added python=3.6 to the installation instructions at http://oceanparcels.org/#installing

Do we also need to change the `environment_py*.xml` files?

**Comment by erikvansebille** [comment]
This seems to have fixed for now by specifically forcing `python=3.6` on http://oceanparcels.org/#installing
