### ISSUE TITLE
Problem with time extrapolation

### ISSUE THREAD

**Issue by ArnoiZ** [OceanParcels/parcels#701]
Hi, I am trying to run a particle transportation simulation with a 5-minute time step.

I first computed the velocity fields with a 5-minute time step and stored them in netCDF file, and added a calendar with the following code: 
```
f = nc4.Dataset(filename,'w',format='NETCDF4')
time_var = f.createVariable('time','f8','time')
calendar = 'standard'
units = 'days since 1900-01-01'
time_var[0] = nc4.date2num(simu_time, units=units, calendar=calendar)
f.close()
```

Then I tried to use the computed velocity field to run the simulation with the following code.
```
filenames = {'U': "current_velocity/20*.nc",
             'V': "current_velocity/20*.nc"}
variables = {'U': 'eastward_eulerian_current_velocity',
             'V': 'northward_eulerian_current_velocity'}
dimensions = {'lat': 'lat',
              'lon': 'lon',
              'time': 'time'}
fieldset = FieldSet.from_netcdf(filenames, variables, dimensions)
pset = ParticleSet.from_line(fieldset=fieldset, pclass=JITParticle,
                             size=5,            # releasing 5 particles
                             start=(132.25, 34),   # releasing on a line: the start longitude and latitude
                             finish=(132.7, 34))
pset.execute(AdvectionRK4, runtime=timedelta(hours=1), dt=timedelta(minutes=5))
```
Then I run into the time extrapolation problem:
```
OutOfTimeError: 0
Particle P[0](lon=132.250000, lat=34.000000, depth=0.000000, time=0.000000)
Time: 43342.375,	timestep dt: 0.006944
Field sampled outside time domain at time 43342.375. Try setting allow_time_extrapolation to True```
```
Then I set `allow_time_extrapolation=True`, and run the simulation again. However, this time the particles does not move until 8 hours later. 
To be more specific, I first run `pset.execute(AdvectionRK4, runtime=timedelta(hours=8), dt=timedelta(minutes=5))`, the particle set does not move. Then I execute simulation again with runtime = 1 hour and the particle starts to move.

So I have two questions: 
the first is why is the time extrapolation problem happening and what could I do to solve it.
The second is that why the particles doesn't move until the simulation has ran for 8 hours when I set `allow_time_extrapolation=True`? 
One possible reason that I could think of is because the start of my current velocity simulation starts at 9 am, when `allow_time_extrapolation=Ture`, the start time of simulation is set to 0 am, which means there is no current velocity data between 0 to 8 am and cause the particles to stay in the same position. 

I attached first ten time steps of my computed current velocity field data, I hope it could help with identifying the problem.
[current_velocity.zip](https://github.com/OceanParcels/parcels/files/3954025/current_velocity.zip)

**Comment by erikvansebille** [comment]
Dear @ArnoiZ, thanks for reporting! I have looked into this Issue, but it seems that your netcdf files do not actually have any metadata on the calendar. Therefore, Parcels interprets the `time` dimension as seconds, and you get this problem. Something must have gone wrong in your saving of the NetCDF file

Alternatively, you could also use the [timestamps](https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/tutorial_timestamps.ipynb) argument to overload the calendar in your netcdf.

Good luck!

**Comment by ArnoiZ** [comment]
Hi, I tried to use timestamps argument as you suggested. But Parcels seems to choose 'time' dimension in netCDF file over given timestamps.

Here's my code:
```
timestamps = np.expand_dims(np.arange('2018-07-01T09:00:00', '2018-07-01T17:05:00', dtype='datetime64[5m]'),axis=1)

fieldset = FieldSet.from_netcdf(filenames, variables, dimensions,timestamps=timestamps)
```
The output is 
`WARNING: Time already provided, defaulting to dimensions['time'] over timestamps.`

Is there a way to work around this problem?

**Comment by erikvansebille** [comment]
Yes, remove the `time` from the `dimensions` dictionary

**Comment by TessMW** [comment]
I have a question related to the problem above. I am trying to add timestamps to my fieldset as follows:

![image](https://user-images.githubusercontent.com/88772167/129005272-fd4e3f58-760b-4bfc-8d2a-c2d00682966c.png)

This raises a UFuncTypeError (see below). What datatime dtypes does the FieldSet.from_netcdf take?

![image](https://user-images.githubusercontent.com/88772167/129005756-cc6afa9d-397d-4ae4-8fc3-c86f26b89fcd.png)

**Comment by erikvansebille** [comment]
Hi @TessMW. This is not a problem of Parcels, but of your numpy function. For example, try the code snippet below 
```python
import numpy as np
timestamps_new = np.expand_dims(np.arange('2014-09-07 00:00:00', '2014-10-01 00:20:00', dtype='datetime64[120s]'), axis=1)
np.all((timestamps_new[1:]-timestamps_new[:-1]) > 0)
```
which throws exactly the same error; but has nothing to do with parcels. So I suggest you first fix this

(By the way, next time it would be helpful if you put code in your Issue text, instead of a screenshot. I now had to type in your lines as I couldn't copy-paste them 😉)
