### ISSUE TITLE
Two issues with Netcdf output files

### ISSUE THREAD

**Issue by ElizaJayne11** [OceanParcels/parcels#704]
Hi

I have encountered two separate issues related to writing the output NetCDF file, for which I was unable to find any mention of Github issues. I am hoping you will be able to diagnose what is going on. I've pared down my actual code to a very simple one that illustrates the problems (please see below). FYI -- I am running parcels version 2.1.2 installed with python 3.6.

1) Temporary files "out-XXX" are not collated into a single NetCDF file. When running the code, no error is given, however the npy files are left in the out-XXX/o/ directory. If I uncomment Line 41 (pfile.close=(True), and rerun the code, the NetCDF file is produced. If I then re-comment like 41, delete the NetCDF file, and run it again, I get no error the first time, but subsequently get 
Exception ignored in: <bound method ParticleFile.__del__ of <parcels.particlefile.ParticleFile object at 0x1193f25f8>>
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/parcels/particlefile.py", line 195, in __del__
    self.close(True)
  File "/Applications/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/parcels/particlefile.py", line 200, in close
    self.export()
  File "/Applications/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/parcels/particlefile.py", line 352, in export
    raise RuntimeError("No npy files found in %s" % self.tempwritedir_base)
RuntimeError: No npy files found in out-DNYKZMWL
If I run it again, I get no error, and a NetCDF output is created, but an out-XXX folder is also created and remains. 

2) When I run the code with Line 41 uncommented so I do get an output file: for the situation where particles on "land" (i.e. velocity = 0) have their depth reset to 1 (Line 15), the netCDF file correctly stores the particle locations, such that the depth of particle 1 is reset to 1m at the first output time. However, if I instead *delete* land particles (i.e. uncomment line 9), the output file doesn't show the delete until the second output time. This happens even when the output file deltat is greater than the particle dt. If I restrict the simulation to the single particle that gets deleted, I get a warning that the Particle set is empty at the first output time. So the code recognizes the deletion at the correc time, but it doesn't write the file that way.

Any advise you can give would be very welcome.

*********************Parcels simple code below****************************
from parcels import ParticleFile, JITParticle, ParticleSet, FieldSet, Field
from datetime import timedelta as delta
import numpy as np

def CheckLand(particle, fieldset, time):
    (up, vp, wp) = fieldset.UVW[time, particle.depth, particle.lat, particle.lon] 
    if fabs(up) < 1e-8 and fabs(vp) < 1e-8 and fabs(wp)<1e-8:   
        particle.depth = 1
        #particle.delete()

xdim = ydim = 3
zdim = 3

uu = np.zeros((xdim, ydim, zdim))
uu[2,:,:] = 1

dimensions = {'lon': np.linspace(0., 2, xdim, dtype=np.float32),
              'lat': np.linspace(0., 2, ydim, dtype=np.float32),
              'depth': np.linspace(0., 2, zdim, dtype=np.float32)}
data = {'U': uu, 
        'V': np.zeros((xdim, ydim, zdim), dtype=np.float32),
        'W': np.zeros((xdim, ydim, zdim), dtype=np.float32)}

fieldset = FieldSet.from_data(data, dimensions, mesh='flat')

#Define ICs so one particle has zero velocity (land) and one has non-zero velocity
lonp=[1, 0.5]
latp=[1, 1.5]
depthp=[.5, 1.5]

pset = ParticleSet.from_list(fieldset=fieldset, pclass=JITParticle, lon=lonp, lat=latp, depth=depthp)
                    
pfile = ParticleFile("Testing", pset, outputdt=delta(hours=1))

kernels =  pset.Kernel(CheckLand) 

pset.execute(kernels, runtime=delta(hours=2), 
                      dt=delta(hours=1),   
                      output_file=pfile,)

#pfile.close(True)

**Comment by erikvansebille** [comment]
Hi @ElizaJayne11, thanks for reporting these issues, and also for providing such a nice minimal code! That really helps us with debugging!

Re your point 1: This is because of how python closes files upon exit of the script. The easiest way to work around this is to define the `ParticleFile` object _within_ the `pset.execute`, so 
```python
pset.execute(kernels, runtime=delta(hours=2), dt=delta(hours=1),
             output_file=ParticleFile("Testing", pset, outputdt=delta(hours=1)))
```
 
Re your point 2: I fear that this is not easy to fix. The way that writing files is implemented in Parcels, is that all the deleted particles are written only every `outputdt`, mostly for efficiency and speed. This also means that deleted particles are written at the next `outputdt`. Changing this will be a massive rewrite of the code, something that I don't expect we'll do in the near future. Is this a problem for you?

**Comment by ElizaJayne11** [comment]
Hi Erik

Thanks for your informative feedback. I really appreciate you taking the time to help.

Specifying the ParticleFile in the execute statement worked (good to know it is just a Parcels thing, and not something I was doing wrong).

With regard to the writing of deleted particles: It is not a real problem, as worst-case I can always write output files at double the frequency. I am confused however, because it sounds like if a particle is deleted between the initial conditions and first outputdt, it should appear as deleted in the second output file. That is different than what I am seeing in my code, where it only appears deleted at third outputdt file.

**Comment by erikvansebille** [comment]
Hi @ElizaJayne11, sorry for the slow response. The two writings is because the ParticleSet is written at time 0 _before_ any kernels are applied, so only at time 3600 is the particle deleted, and hence it is again written then as last deleted. Makes sense?
