### ISSUE TITLE
Create a test to check and verify memory behaviour and containment with different Field() structures

### ISSUE THREAD

**Issue by CKehl** [OceanParcels/parcels#722]
Many issues recently experienced severe bugs in terms of memory leakage, which required significant fixes. In order to avoid, prevent or mitigate future memory leaks, we should develop and include a test that checks the memory behaviour and containment of the following things:

- [ ] different pre-defined chunk sizes: auto, False, tuple-definition, dict-definition

- [ ] check usage of Dask parameters: field_chunksize='auto' *with* and *without* `dask.yaml`

- [ ] deferred loading vs. direct loading

- [ ] time extrapolation: None, time_extrapolate, time_periodic

- [ ] MPI vs. non-MPI (if possible)

- [ ] time-forward vs. time-backward computing

**Comment by erikvansebille** [comment]
Very good idea! This can go into a new `performance` folder on the parcels repo? We could then automate testing/analysis on our own HPC systems, without burdening the github actions CI (which wouldn't have access to the large netcdf files anyways). Would that work?
