### ISSUE TITLE
GCC cross compiler error while activating parcels environment

### ISSUE THREAD

**Issue by pierrick-giffard** [OceanParcels/parcels#732]
When I activate my parcels 2.1.3 environment, the following errors appear:

_ERROR: This cross-compiler package contains no program /homelocal/pgiffard/SRC/miniconda3/envs/parcels21/bin/addr2line
ERROR: activate-binutils_linux-64.sh failed, see above for details
ERROR: This cross-compiler package contains no program /homelocal/pgiffard/SRC/miniconda3/envs/parcels21/bin/cc
ERROR: activate-gcc_linux-64.sh failed, see above for details_

I just removed miniconda and reinstalled it and I still get these errors. However, with the last version of parcels I'm now able to execute in JIT mode (with version 2.1.1 it was switching automatically to Scipy mode). Any idea of why these errors appear?

**Comment by CKehl** [comment]
Hi @pierrick-giffard ,
Be aware to always install `gcc_linux-64` and `py` as packages from conda, and **not** the `gcc` package (which is not working well in conda environments and with packages like `pandas`). If `gcc` package is already installed, please remove the package from your conda environment with the related `conda` command.
Best,
Christian

**Comment by pierrick-giffard** [comment]
Hi @CKehl,
Here is my package list : 
[My_environment.txt](https://github.com/OceanParcels/parcels/files/4621117/My_environment.txt)
I have `gcc_impl_linux-64` and `gcc_linux-64` but I haven't `gcc `package. I still get the same message when I activate my environment but I haven't got any problem afterwards to run simulations.

**Comment by CKehl** [comment]
Hm - this will need a bit more time to investigate, Pierrick

**Comment by erikvansebille** [comment]
Hi @pierrick-giffard. Are you still experiencing this problem? If so: we've recently refactored the `Compiler` class, so would be good to see if the new #914 PR fixes this issue. Could you check?

**Comment by pierrick-giffard** [comment]
Hi Erik,
Actually, I have no _ERROR_ message with my "developer installation" with git clone but only with my classic installation. I noticed that with the developer installation I've no package 'gcc_impl_linux-64' and 'gcc_linux-64', packages I have with the classic installation. Nevertheless, it doesn't seem to impact parcels execution.

**Comment by pierrick-giffard** [comment]
Hi Erik,
Actually, I have no _ERROR_ message with my "developer installation" with git clone but only with my classic installation. I noticed that with the developer installation I've no package 'gcc_impl_linux-64' and 'gcc_linux-64', packages I have with the classic installation. Nevertheless, it doesn't seem to impact parcels execution.

**Comment by pierrick-giffard** [comment]
Hi Erik,
Actually, I have no _ERROR_ message with my "developer installation" with git clone but only with my classic installation. I noticed that with the developer installation I've no package 'gcc_impl_linux-64' and 'gcc_linux-64', packages I have with the classic installation. Nevertheless, it doesn't seem to impact parcels execution.

**Comment by pierrick-giffard** [comment]
Hi Erik,
Actually, I have no _ERROR_ message with my "developer installation" with git clone but only with my classic installation. I noticed that with the developer installation I've no package 'gcc_impl_linux-64' and 'gcc_linux-64', packages I have with the classic installation. Nevertheless, it doesn't seem to impact parcels execution.

**Comment by pierrick-giffard** [comment]
Hi Erik,
Actually, I have no _ERROR_ message with my "developer installation" with git clone but only with my classic installation. I noticed that with the developer installation I've no package 'gcc_impl_linux-64' and 'gcc_linux-64', packages I have with the classic installation. Nevertheless, it doesn't seem to impact parcels execution.

**Comment by erikvansebille** [comment]
OK thanks for the clarification. In that case I'll close this Issue
