### ISSUE TITLE
Dask WARNING

### ISSUE THREAD

**Issue by pierrick-giffard** [OceanParcels/parcels#733]
With the last Parcels version I get the following Warning:

_WARNING: Unable to locate chunking hints from dask, thus estimating the max. chunk size heuristically. Please consider defining the 'chunk-size' for 'array' in your local dask configuration file (see https://docs.dask.org)._

Is it normal to have this Warning ?

**Comment by erikvansebille** [comment]
This is new in version 2.1.3. See also http://oceanparcels.org/faq.html#field_chunking_config. Nothing to worry about, although you might get a major speed-up of your code if you tune your dask chunking well, as is explained in the FAQ at the link above.

However, I agree that this might be a bit intimidating/worrying message, so in PR #734 I suggest to change the warning to an info message

**Comment by pierrick-giffard** [comment]
Thank you for the tip, I will try to tune my dask chunking to speed up the code!

**Comment by erikvansebille** [comment]
Fixed in #734
