### ISSUE TITLE
Parallel behaviour & performance 

### ISSUE THREAD

**Issue by ocgabs** [OceanParcels/parcels#737]
Hi, 
I was hoping to be able to use the parallel version of parcels to speed up some experiments. I manage to install it and I can run the examples without problems. However when trying to do my real experiments, exaclty the same that runs in the serial version does not complete when in parallel. Temporary files get created but never convert into netcdfs, when I convert them tracks are a very small fraction of the total requested tracked time. I don't get any error messages. My experiments are with 2D NEMO RK4 advection only. My scripts are the simplest thing, see below. I would appreciate any help. 

from parcels import FieldSet, ParticleSet, ScipyParticle, JITParticle, AdvectionRK4, ParticleFile

from argparse import ArgumentParser
import numpy as np
import pytest
from glob import glob
from datetime import timedelta as delta
from os import path
import time
from netCDF4 import Dataset
import csv
with open('/projectsa/NEMO/gmaya/RECICLE/PARCELS/AMM7s/unifNS.csv') as csvfile:
    file1 = csv.reader(csvfile, delimiter=',')
    LOS = []
    LAS = []
    for row in file1:
        LO = row[0]
        LA = row[1]
        LOS.append(LO)
        LAS.append(LA)
ts=0
tt=[ts]*len(LOS)
data_path = '/projectsa/Recicle/outputs/v2/HadGEM2-ES/'
emem='HadGEM2-ES'
ufiles = sorted(glob(data_path+'HadGEM2-ES_1d_204*U.nc'))
vfiles = sorted(glob(data_path+'HadGEM2-ES_1d_204*V.nc'))
grid_file = '/projectsa/Recicle/gmaya/coordinates.nc'
filenames = {'U': {'lon': grid_file,
                       'lat': grid_file,
                       'data': ufiles},
                 'V': {'lon': grid_file,
                       'lat': grid_file,
                       'data': vfiles}}
variables = {'U': 'uo25h', 'V': 'vo25h'}
dimensions = {'lon': 'glamf', 'lat': 'gphif','time': 'time_counter' }
field_set = FieldSet.from_nemo(filenames, variables, dimensions)
pset = ParticleSet.from_list(field_set, JITParticle, lon=LOS, lat=LAS, time=tt)
pfile = ParticleFile(emem + '2040r.1_test', pset, outputdt=delta(hours=1))
kernels = pset.Kernel(AdvectionRK4)
pset.execute(kernels, runtime=delta(days=90), dt=delta(hours=1),
            output_file=pfile)

**Comment by erikvansebille** [comment]
Thanks @ocgabs, for reaching out. It's hard though for us to debug this without any output. Are there really no error messages or warnings? Any extra information that you can provide is useful

**Comment by ocgabs** [comment]
No errors! so I don't know what to say. It runs very quickly indeed but then stops.
This is are some details of the machine I am using: 
Intel Xeon Gold 6140 CPU 2.30GHz, CentOS7, 144 cores, no queuing system, but no exclusive use... We have a few of this, so I will try on an older one with less trafic. 
I could provide the input files for this if you are willing to test on your side. I am doing a climate change thing with ensemble members, etc... Its a massive endevour, so I was really hopeful for parallel Parcels.

**Comment by ocgabs** [comment]
Hi again, I tried on a different machine, exactly same behaviour...
I have created a temprary public ftp site with all required inputs in case you have a chance to look into this. I will really appreciate your help. livftp.noc.ac.uk/noc/gmayapub/data/parPARCELSinputs/

**Comment by erikvansebille** [comment]
The link to the livftp.noc.ac.uk server does not seem to be working?

**Comment by ocgabs** [comment]
It works for me... in Ecuador... just put ftp:// before the whole the provided path...

**Comment by erikvansebille** [comment]
I have now been able to download the data indeed (it was not obvious that I had to put ftp in front of the url).

What if you add `pfile.close()` to the end of your script? Does it run then? Or, alternatively, create the `pfile` object _inside_ the `pset.execute()`: 
```python
pset.execute(k_adv + k_sample, runtime=delta(days=30), dt=delta(minutes=10), output_file=ParticleFile("recicle_nemo_particles_partest", pset, outputdt=delta(hours=24)))
```
Do you get an output file then?

And have you tried running without MPI? Does that work?

By the way, your simulation crashes because of the `parcels.tools.error.KernelError: 0` error that was also discussed in #712. The good thing is that now I can try debugging this error, as I can run with your script/data

**Comment by erikvansebille** [comment]
OK, I've now found what causes the `parcels.tools.error.KernelError: 0 error`. It's an error in the interpolation scheme, when in your case `xsi = 1.00000 > 1`. This is probably a rounding error. While we discuss here what to do about this, in the meantime it may be easiest to simply delete these particles that exactly hit a grid cell boundary. I've implemented a new ErrorCode for that (also helps with debugging) at #745. But if you don't want to use this new branch, you can also use

```python
def DeleteParticle(particle, fieldset, time):
    particle.delete()

pset.execute(..., recovery={ErrorCode.Error: DeleteParticle})
```

Any particle that receives a `ErrorCode.Error` will then be deleted

**Comment by ocgabs** [comment]
Thanks for looking into this so promptly. Sorry about leavin out ftp:// I didn't want the link to be clickable. Always feel iffy about sharing future oceans without any warnings. For now I will try your latest option and later on look at the new branch.

**Comment by ocgabs** [comment]
In serial mode I was susccessfully using nohup and spawning many jobs from a terminal with the following command that redirects the terminal output:

nohup python TS_AMM7_Parcels.py > /dev/null 2>&1&

The parallel version of this:
nohup mpirun -np 2 python AMM7_Parcels.py > /dev/null 2>&1&

Doesn't work...

Is there a way to omit the terminal output, in order to spawn many jobs from the same terminal?

Has anyone successfully used nohup with the parallel version?

Thanks in advance for your help.

**Comment by CKehl** [comment]
Hi @ocgabs ,
when you run the MPI job, can you track the memory behaviour of it, eg. by using 'top' (a command line system manager under Linux). you should be able to track the process(es) that you spawned. Look at the the column called 'RES' (= 'reserved memory' -> the amount of physical memory consumed). Especially with global, high-res 3D(4D) field data, you may quickly reach the physical limit of available memory, as you don't use field chunking. That is something that may still just work for single-core runs, but without chunking the memory requirement increase by the same factor you increase the number of cores used (i.e. each MPI process will allocate the full field data). That makes even large HPC farms tap out-of-memory quickly, as each of those nodes still has a certain memory limit.
To follow up on that behaviour, some rudimentary statements on memory behaviour, overall computation time (time the process actually runs), etc., are essential to give a better hint on improvements.
Cheers,
Christian
