### ISSUE TITLE
Significant slowdown with to_write="once" particle variables.

### ISSUE THREAD

**Issue by christensen5** [OceanParcels/parcels#739]
When defining a particle class, Parcels offers the option of choosing whether to store a given Variable's value at every outputdt (`to_write=True`) or just at the start of the run (`to_write="once"`).

I noticed that my runs with particle classes involving a `to_write="once"` Variable seemed to run significantly slower than an identical run with the same Variable changed to `to_write=True`. To investigate further I altered `example_stommel.py` to include an additional variable (which I called `diameter`) and ran separate tests with this variable as either `to_write=True` or `to_write="once"`, both on my own laptop and on my university cluster.

![runtimes](https://user-images.githubusercontent.com/14197464/74023312-46817500-4997-11ea-9218-fe8f320ad483.png)

Above is a quick plot of what I found. Solid lines are `to_write="once"` runs, dashed lines are `to_write="True"` runs. Note the log scale on the y-axis. CX1 is the university cluster, the other results are for my laptop. On both systems the `to_write="once"` runs seem to spend significantly longer in `pset.execute()` than the `to_write="True"` runs; at 100,000 particles its about an order of magnitude difference.

The [adapted example scripts are available here](https://github.com/OceanParcels/parcels/files/4170324/write_once_test_scripts.zip).

**Comment by christensen5** [comment]
If it is of any help, I ran a cProfile in pycharm on both scripts with 10000 particles, to see where the "writeonce" script is spending extra time. A snapshot of these results is pictured below:

![cProfile](https://user-images.githubusercontent.com/14197464/74030171-4f2d7780-49a6-11ea-91d6-2592a8515f31.png)

It seems the "writeonce" case causes `pset.execute()` to spend a great deal of time (58.9% of the run in this case) producing list comprehensions. Pycharm points me toward [line 254](https://github.com/OceanParcels/parcels/blob/master/parcels/particlefile.py#L254) in particlefile.py as the source of this repeated call. I'm not sure why this particular listcomp call is taking so long each time but I notice that it's called at every savedt (i.e. 121 times in total). Since line 254 deals with `to_write="once"` variables, perhaps its supposed to only be called once?

**Comment by erikvansebille** [comment]
Thanks for reporting this, @christensen5! This indeed is worrying and should be investigated further!

Would you mind rerunning with #678? There, @angus-g has re-implemented the ParticleSet data, moving from Array-of-Structures data to Structure-of-arrays data. This also means that the line you mention above is not a list-comprehension anymore [line 260](https://github.com/angus-g/parcels/blob/soa-storage/parcels/particlefile.py#L260). So perhaps that speeds everything up again?

**Comment by christensen5** [comment]
I've run a quick test comparing [#678](https://github.com/OceanParcels/parcels/pull/678) with master in a run of just 10,000 particles. Unfortunately, although #678 achieves an impressive speedup over the master branch, the `to_write="once"` run is still very much the slower of the two:

![soa_vs_master](https://user-images.githubusercontent.com/14197464/74040086-e997b600-49ba-11ea-9b2d-7feff601ac4b.png)

Bizarrely, the cProfile output for this new branch still blames `listcomp`, but then points me to [line 259](https://github.com/angus-g/parcels/blob/soa-storage/parcels/particlefile.py#L259) when I select the listcomp call and click on 'navigate to source':

![soa cProfile](https://user-images.githubusercontent.com/14197464/74040891-860e8800-49bc-11ea-8731-ffbb447af2c2.png)

Perhaps it's really blaming the list comprehension at the end of the if-block in [lines 259-263](https://github.com/angus-g/parcels/blob/soa-storage/parcels/particlefile.py#L259-L263)? Either that or I'm misunderstanding the 'navigate to source' feature in PyCharm's cProfile gui.

**Comment by erikvansebille** [comment]
Thanks, really interesting! It could also be the list comprehension in [line 258](https://github.com/angus-g/parcels/blob/soa-storage/parcels/particlefile.py#L258)?
Perhaps we can speed that up with a call to `np.setdiff1d()`? Essentially, we want the indices of all particles whose `id` are not in `self.written_once` yet. @christensen5, would you mind exploring this a bit on your local system?

**Comment by erikvansebille** [comment]
I think the statement you have to use is
```python
first_write = (_to_write_particles(pd, time) & np.isin(pd['id'], self.written_once, invert=True))
```

**Comment by erikvansebille** [comment]
Oh, and note that the list comprehension in [line 263](https://github.com/angus-g/parcels/blob/soa-storage/parcels/particlefile.py#L263) can also be removed easily:

```python
self.written_once.extend(pd['id'][first_write])
```

**Comment by christensen5** [comment]
Happy to give it a try and submit a pull req if it works!

> I think the statement you have to use is
>
>     first_write = (_to_write_particles(pd, time) & np.isin(pd['id'], self.written_once, invert=True))

Here, is `np.isin(..., invert=True)` is a better choice than your first suggestion of np.setdiff1d? Or would you still recommend I use settdiff1d?

**Comment by erikvansebille** [comment]
I've already merged these two suggestions, as I checked that they work against the unit tests. 

`np.setdiff1d()` doesn't work because it doesn't return a list of booleans, as we need. `np.isin()` does work. But if you update the branch then you'll get the latest version without these two list comprehensions

**Comment by erikvansebille** [comment]
So I would be very keen to see whether `to_write=once` works faster with https://github.com/OceanParcels/parcels/pull/678/commits/4b718632bea14bcb385316c30eba40eb31c921eb. Could you test that, @christensen5?

**Comment by christensen5** [comment]
Currently running!

**Comment by christensen5** [comment]
Seems to work; [4b71863](https://github.com/OceanParcels/parcels/commit/4b718632bea14bcb385316c30eba40eb31c921eb) has `to_write=True` runs about as fast as `to_write="once"` runs for 10,000 particles with example_stommel:

![soa_vs_master](https://user-images.githubusercontent.com/14197464/74045406-9296de80-49c4-11ea-8000-0949c9f0d9c0.png)

**Comment by erikvansebille** [comment]
Wow, this is fantastic! Really glad you found this bug, and that we also fixed it!

FYI, #678 is fully functional (thanks to @angus-g!) and we will keep it rebased to master. The reason it's not in master already is that it doesn't work on Windows. So we will first need to fix that before we can merge. For now, I'd say run with #678!

**Comment by christensen5** [comment]
Awesome, #678 is impressively quick so yes, I'll run with it for now!
