### ISSUE TITLE
Ability to specify subset of netcdf data to read in when setting grid

### ISSUE THREAD

**Issue by erikvansebille** [OceanPARCELS/parcels#75]
It would be nice if users could set a subset of the data they want to read in only (e.g. only one depth level) when they specify the grid. NetCDF has ability to read subsets, so we only need way for users to set the limits in `Grid.from_netcdf`

**Comment by mlange05** [comment]
That should be reasonably straightforward to implement. We already pass the naming convention for each field into the `FileBuffer` when reading files, which then simply does `[:, :, ]` for each known dimensions. One way to do this would be to extend the `dimensions` dict to hold nested tuples `(name, shape)`, where `shape = (d0, d1, d2)` for the relevant number of data dimensions. This way we can expose the the shape argument to the user via optional arguments to `Grid.from_netcdf` and `Grid.from_nemo`, for example `dimensions['data'] = ('myvariable', (:, :, 3:5))` for depth layers 3 and 4 only. One thing we then need to do is sanity checking that the passed shape has the right number of dimensions, ie. something like `len(dataset[dimensions[0]]) == len(dimensions['data'][1])`. Does that sound feasible?

**Comment by erikvansebille** [comment]
Yes, this sounds like a very good way forward.

Eventually, in some future version, we might want to add the capacity for users to select the subset based on dimension values, rather than just indices (i.e. selecting depths 0-100m, rather than index 0:5; or latitudes 30N-50N, rather than index 400:500), but that is just sugarcoating that can always be added later

So let's go for this indexing solution first. No high priority, but certainly a nice feature to have

**Comment by erikvansebille** [comment]
Fixed in #136
