### ISSUE TITLE
Update conda documentation for linux

### ISSUE THREAD

**Issue by beroe** [OceanParcels/parcels#756]
In my fresh conda installation (4.7.12), the command to create the environment is:

    create -n py3_parcels -c conda-forge python=3.6 parcels jupyter cartopy ffmpeg

And the command to activate it is

    conda activate py3_parcels

**Comment by erikvansebille** [comment]
Not sure what the Issue is here. Could you elaborate? Why is this different from what's reported on the website?

**Comment by beroe** [comment]
HI Erik. It was a minor thing, but on the web site it says: 

    source $HOME/miniconda3/bin/activate py3_parcels  # Linux / macOS
    activate py3_parcels                              # Windows

And neither of these was the command I used on Ubuntu.
