### ISSUE TITLE
error in pset.show

### ISSUE THREAD

**Issue by ana-machado** [OceanParcels/parcels#757]
Hello,
I am running the following lines,

pset = ParticleSet.from_line(fieldset,size=100,pclass=JITParticle,start=(-13,37),finish=(-13,42),depth=-5)
output_file=pset.ParticleFile(name="DelayParticle_time.nc", outputdt=delta(hours=1))
pset.execute(AdvectionRK4_3D, runtime=100*86400, dt=60, output_file=output_file,recovery={ErrorCode.ErrorOutOfBounds: DeleteParticle})
It all seems to be working, it correctly plots the trajectories with the command: 
plotTrajectoriesFile('DelayParticle_time.nc')
but I get the error below when trying to execure pset.show()
or 
pset.show(field=fieldset.U, time = delta(days=10))

Do you know what am I doing wrong?
Thank you very much
Ana

In [88]: pset.show(field=fieldset.U, time = delta(days=10))  
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-88-09bda312e135> in <module>
----> 1 pset.show(field=fieldset.U, time = delta(days=10))

~/anaconda3/envs/py3_parcels/lib/python3.7/site-packages/parcels/particleset.py in show(self, with_particles, show_time, field, domain, projection, land, vmin, vmax, savefile, animation, **kwargs)
    450         from parcels.plotting import plotparticles
    451         plotparticles(particles=self, with_particles=with_particles, show_time=show_time, field=field, domain=domain,
--> 452                       projection=projection, land=land, vmin=vmin, vmax=vmax, savefile=savefile, animation=animation, **kwargs)
    453 
    454     def density(self, field=None, particle_val=None, relative=False, area_scale=False):

~/anaconda3/envs/py3_parcels/lib/python3.7/site-packages/parcels/plotting.py in plotparticles(particles, with_particles, show_time, field, domain, projection, land, vmin, vmax, savefile, animation, **kwargs)
     72         plt, fig, ax, cartopy = plotfield(field=field, animation=animation, show_time=show_time, domain=domain,
     73                                           projection=projection, land=land, vmin=vmin, vmax=vmax, savefile=None,
---> 74                                           titlestr='Particles and ', depth_level=depth_level)
     75         if plt is None:
     76             return  # creating axes was not possible

~/anaconda3/envs/py3_parcels/lib/python3.7/site-packages/parcels/plotting.py in plotfield(field, show_time, domain, depth_level, projection, land, vmin, vmax, savefile, **kwargs)
    137             raise TimeExtrapolationError(show_time, field=fld, msg='show_time')
    138 
--> 139         latN, latS, lonE, lonW = parsedomain(domain, fld)
    140         if isinstance(fld.grid, CurvilinearGrid):
    141             plotlon[i] = fld.grid.lon[latS:latN, lonW:lonE]

~/anaconda3/envs/py3_parcels/lib/python3.7/site-packages/parcels/plotting.py in parsedomain(domain, field)
    299     else:
    300         if field.grid.gtype in [GridCode.RectilinearSGrid, GridCode.CurvilinearSGrid]:
--> 301             return field.grid.lon.shape[0], 0, field.grid.lon.shape[1], 0
    302         else:
    303             return len(field.grid.lat), 0, len(field.grid.lon), 0

IndexError: tuple index out of range

**Comment by erikvansebille** [comment]
Dear @ana-machado. It is difficult to fix this Issue without access to your netcdf files. However, in general I'd recommend to not rely on the parcels plotting too much. Since you said that your run seemed to work fine, can you not write your own analysis/plotting code? You will need to do that anyway if you want to further analyse the particle output
