### ISSUE TITLE
Nemo/Mercator data with incomplete depth

### ISSUE THREAD

**Issue by JamiePringle** [OceanParcels/parcels#758]
I have a problem running oceanparcels with Mercator 1/12 global data (which is run on the NEMO ocean model) with their tri-polar grid. 

Importantly, we only downloaded the top 36 levels of data. We downloaded U, V and W, so W does not have to be computed from continuity. I can run with AdvectionRK4 when I use indices={'depth':[0]}.  But if I try to use AdvectionRK4_3D and indices={'depth':list(range(0,35))}, the code crashes in field.py line 937 with "IndexError: list assignment index out of range". 

The grid file has the full vertical information, only the U, V and W files are truncated. 

This is a fresh install of version 2.1.4.

If useful, I could upload a test set of data files to a publicly available box folder. 

Attached is a minimal example and the error traceback. The python code has a .py.txt extension so that github accepts it. 

Am I doing something silly, or is this an error in the code? I could truncate the grid file, but that seems a kludge. 

Thanks,
Jamie Pringle

[errorTraceback.txt](https://github.com/OceanParcels/parcels/files/4247050/errorTraceback.txt)
[mercator_try1.py.txt](https://github.com/OceanParcels/parcels/files/4247055/mercator_try1.py.txt)

**Comment by JamiePringle** [comment]
If it is helpful to people, the forcing files referenced in the python script can be found at https://unh.box.com/s/1ohb10r3b2ejzbv11fb2k1mg4ep2fvpv ; I will delete these files once the issue is closed. The paths to the data are defined at the top of the script. 

Thanks again,
Jamie

**Comment by erikvansebille** [comment]
Hi @JamiePringle. Thanks for using Parcels and for contacting us with this Issue. 

Parcels assumes that the grid file and velocity files are fully self-consistent, so it is not a surprise that you get an error if your grid file does not agree with the velocity files. By far the easiest fix here is also remove some layers from your grid files, so that it is consistent again

Good luck!

**Comment by JamiePringle** [comment]
I don't think your diagnosis is correct. Looking at the grid files in the NemoNorthSeaORCA025-N006_data in the parcels_examples directory, there is no vertical information in the coordinates.nc directory. In the data files I had uploaded, there was an inconsistency in the vertical extent of the W and U,V grids as served by Mercator Oceans. I have altered them to be consistent (W was one larger then U,V -- I had not caught that before because it is consistent with ROMS with which I have more experience). But there is still an error.

Before re-opening this issue, I am going to dig deeper into the oceanparcels code. Given the size of these global runs, being able to use a subset of the vertical grid is useful. Will comment again soon. 

Jamie

**Comment by JamiePringle** [comment]
If you are having similar problems, and if either your U,V or W grids have more vertical dimensions then the others, you can fix it with the use of the indices option in creating a fieldSet with from_nemo -- for example 

`indices={'depth':list(range(0,35))}
fset=FieldSet.from_nemo(filenames,variables,dimensions,indices=indices,field_chunksize=(8,3059,4320))`

This does seem to expose an error in the chunking when an explicit field_chunksize is not set. But that is an issue for another issue post. 

Jamie

**Comment by erikvansebille** [comment]
Ok thanks for digging deeper and finding out the true cause of this Issue
