### ISSUE TITLE
s-coordinates

### ISSUE THREAD

**Issue by ana-machado** [OceanParcels/parcels#759]
Hello,

I am doing some tests in order to use parcels with roms outputs. To certify if everything was running as expected, I made two tests:
-keep u,v, and set w=0 (teste2_3rsteps): the files continue moving in the vertical, I was expecting them to stay at the deployment depth and being advected only horizontally.
-set u,v,w=0 (teste3_3rsteps), as expected the particles don't move.
The nc files are in this link, if you think they're useful.
https://meocloud.pt/link/496136f3-00e6-4131-a993-88ebbf77eec8/roms_outputs_3tSteps/
Am I doing something wrong, or is this a bug?

Best regards,
Ana

![teste2_3rsteps](https://user-images.githubusercontent.com/34549357/75203597-6fab4f00-5766-11ea-81ac-9132b9b7bcc6.png)
![teste3_3rsteps](https://user-images.githubusercontent.com/34549357/75203600-720da900-5766-11ea-8594-59cc574d988b.png)

**Comment by erikvansebille** [comment]
Hi @ana-machado, can you also send the scripts that you used to create these simulations?

**Comment by ana-machado** [comment]
Hello. Of course. I added the grid file, the script to run parcels, and the one to plot the previous figures in the same shared folder:
https://meocloud.pt/link/496136f3-00e6-4131-a993-88ebbf77eec8/roms_outputs_3tSteps/
Thank you very much
Ana

**Comment by erikvansebille** [comment]
Hi @ana-machado. I have been looking at your code, but had to change quite a bit in your script, for example because the `out3.nc` file that you provided seems to contain only 0s... I thus now use the `out2.nc` file

Anyway, the main reason it seems why your particles were also moving up and down is because you used the `AdvectionRK4_3D` kernel, instead of the `AdvectionRK4` kernel. As soon as you provide vertical velocity (`W`), then your particles will move up and down...

The following code works for me
```python
from parcels import FieldSet, ParticleSet, JITParticle, AdvectionRK4, ErrorCode
from datetime import timedelta as delta

data_file = 'out2.nc'
outFileName = 'teste3_3tsteps.nc'

def DeleteParticle(particle, fieldset, time):
    particle.delete()

filenames = {'U': data_file, 'V': data_file, 'W': data_file}

variables = {'U': 'u', 'V': 'v', 'W': 'w'}

dimensions = {'lon': 'lon_rho', 'lat': 'lat_rho', 'depth': 'SigmaDepths', 'time': 'scrum_time'}
indices = {'lon': range(0, 367), 'lat': range(0, 480)}

fieldset = FieldSet.from_c_grid_dataset(filenames, variables, dimensions, indices)

pset = ParticleSet.from_line(fieldset, size=100, pclass=JITParticle, start=(-9, 37), finish=(-9, 42), depth=-5)

pset.execute(AdvectionRK4, runtime=delta(days=15), dt=delta(seconds=120),
             output_file=pset.ParticleFile(name=outFileName, outputdt=delta(hours=1)),
             recovery={ErrorCode.ErrorOutOfBounds: DeleteParticle})
print(pset)
```

With output:
```
P[0](lon=-9.010936, lat=37.015213, depth=-5.000000, time=1296000.000000)
P[1](lon=-9.201909, lat=38.215859, depth=-5.000000, time=1296000.000000)
P[2](lon=-9.593782, lat=38.297270, depth=-5.000000, time=1296000.000000)
P[3](lon=-9.000000, lat=38.666667, depth=-5.000000, time=1296000.000000)
P[4](lon=-9.000000, lat=39.222222, depth=-5.000000, time=1296000.000000)
P[5](lon=-9.000000, lat=39.777778, depth=-5.000000, time=1296000.000000)
P[6](lon=-9.036016, lat=40.293679, depth=-5.000000, time=1296000.000000)
P[7](lon=-9.441562, lat=41.624790, depth=-5.000000, time=1296000.000000)
P[8](lon=-9.623545, lat=42.610948, depth=-5.000000, time=1296000.000000)
P[9](lon=-10.280122, lat=43.423971, depth=-5.000000, time=1296000.000000)
```

Note that this code above will only work with the bugfix in #763, if you are running with the latest version of Parcels. However, since you didn't seem to get hindered by this bug before, maybe you're still on an older version?

**Comment by ana-machado** [comment]
Hi Erik! 
Thank you very much for your reply. I am happy the solution is easy, but now I am in trouble. 
Since you noticed I was not running the latest Parcels version, I decided to install it again, but now I am having an error, possible related with the bugfix #763. But since I installed parcels via the easiest way (Parcels Conda-Forge package), I don't know how can I change the file converters.py . 

I also used git to download master branch for a directory, and there I can change converters.py (of course), but I am not discovering how to run it from there... do you have any information about this? I tried what was on the website, (Installation for developers), but have no clue what to do after this (python setup.py install)

Thank you very much
Ana

**Comment by ana-machado** [comment]
I am sorry to insist on this, but, reading your e-mail again, I continue with this doubt. I understand that if I use only 2d advection, it solves this problem, but shouldn't 3d advection leave the particles at the same depth if the vertical velocity is null? The file you said had u,v,w =0 was also a test, and in that case, as expected, the particles don't move in any direction.
