### ISSUE TITLE
strange behaviours with AdvetionRK4_3D in s-coord

### ISSUE THREAD

**Issue by ana-machado** [OceanParcels/parcels#765]
Hello
I am trying to use parcels with some ROMS outputs, I made some simple tests to see if the particles were advected correctly and I think there is some issue going on, especially when particles are crossing regions with steep sigma gradients. They were deployed at 5m depth. See the results in the pdf:
https://meocloud.pt/link/30750091-7e24-47a2-950c-f657c3749073/variousTestsAdvParcels.pdf/
Has anyone used it successfuly with roms outputs? 
Thank you in advance. Hope someone can help :)
Ana

**Comment by erikvansebille** [comment]
Hi @ana-machado 

I think that this is really a matter of what you _expect_ from velocities in a sigma-coordinate. I never use ROMS so I'm not sure how vertical velocity is treated there, but in Parcels we assume that the vertical velocity is with respect to the grid cell (see [the paper](https://www.geosci-model-dev.net/12/3571/2019/gmd-12-3571-2019.html) by @delandmeterp). So if `w=0` in a sigma-coordinate, it means that particles will follow the sigma-layers (and hence move upward/downward in `z` if the sigma-layers do so too).

Now if you don't want this behaviour, then a solution is to use a custom kernel to rewrite the way particles are advected. For example the code below

```python
def AdvectionRK4_3D_alternative(particle, fieldset, time):
    """Advection of particles using fourth-order Runge-Kutta integration with vertical velocity independent of vertical grid distortion.

    Function needs to be converted to Kernel object before execution"""
    (u1, v1) = fieldset.UV[time, particle.depth, particle.lat, particle.lon]
    w1 = fieldset.WA[time, particle.depth, particle.lat, particle.lon]
    lon1 = particle.lon + u1*.5*particle.dt
    lat1 = particle.lat + v1*.5*particle.dt
    dep1 = particle.depth + w1*.5*particle.dt
    (u2, v2) = fieldset.UV[time + .5 * particle.dt, dep1, lat1, lon1]
    w2 = fieldset.WA[time + .5 * particle.dt, dep1, lat1, lon1]
    lon2 = particle.lon + u2*.5*particle.dt
    lat2 = particle.lat + v2*.5*particle.dt
    dep2 = particle.depth + w2*.5*particle.dt
    (u3, v3) = fieldset.UV[time + .5 * particle.dt, dep2, lat2, lon2]
    w3 = fieldset.WA[time + .5 * particle.dt, dep2, lat2, lon2]
    lon3 = particle.lon + u3*particle.dt
    lat3 = particle.lat + v3*particle.dt
    dep3 = particle.depth + w3*particle.dt
    (u4, v4) = fieldset.UV[time + particle.dt, dep3, lat3, lon3]
    w4 = fieldset.WA[time + particle.dt, dep3, lat3, lon3]
    particle.lon += (u1 + 2*u2 + 2*u3 + u4) / 6. * particle.dt
    particle.lat += (v1 + 2*v2 + 2*v3 + v4) / 6. * particle.dt
    particle.depth += (w1 + 2*w2 + 2*w3 + w4) / 6. * particle.dt
```

Compared to the [original AdvectionRK4_3D code](http://oceanparcels.org/gh-pages/html/_modules/parcels/kernels/advection.html#AdvectionRK4_3D), you see that the treatment of vertical velocity has been separated from that of the two horizontal components.

If you use this Kernel  in your `pset.execute()`, make sure that when you create your `FieldSet`, you name your vertical velocity field `WA`.
