### ISSUE TITLE
How to change Particle Size and Color?

### ISSUE THREAD

**Issue by isabelyuyingwu** [OceanParcels/parcels#778]
Hi Erik,

You really did a great work!!! I like your ocean parcels package very much! In recent days, I used your package to track particles in the ocean and it did very well. However, I met problems about **changing the particle's size, density, color**.

(1) First, when I ran your tutorial plotting.py, it successfully launched a set of particles, but the default particle's size was a little bigger if I plotted all of them in my research area. Therefore, I will appreciate it if you remember where to set the particle's size in your python file. 

(2) Second, I plan to launch two sets of particles in the research area, so I want to use two different colors to tag them. I am sorry that I am new to programming (T_T). After reading some of your files carefully, I think the most relevant files are particleset.py & plottrajectory.py, but I feel lost in hundreds of codes...

<img width="959" alt="Screen Shot 2020-03-30 at 9 38 38 AM" src="https://user-images.githubusercontent.com/38671085/77918900-844d9c00-726a-11ea-87d2-37fe3b3cbf8d.png">

I've found two codes to set the particle size & color in plottrajectory.py, but it doesn't work for 'pset..(var....) ' in plotting the particles in gif.

<img width="714" alt="Screen Shot 2020-03-30 at 9 37 47 AM" src="https://user-images.githubusercontent.com/38671085/77919491-3f763500-726b-11ea-8746-80e246c8ba5c.png">

If you know how to change the size & color in your python file, feel free to let me know!!! Thank you so much (^_^). I've noticed that you solved some similar issues, like # 252, #675,  but I still don't find the specific codes to achieve that.

Hope you stay well! Thank you again!!

Best, Isabel

**Comment by erikvansebille** [comment]
Thank you for this kind message, @isabelyuyingwu. Indeed, the plotting routines in Parcels are very rudimentary, and really should not be used for anything more than a quick check of the data. We made the decision for now to focus on the particle computation, not plotting; with the limited resources we have, we can't do it both ;-)

My recommendation is just to write your own plotting routines from scratch, specific for your own experiment and tailored to whatever you need. As a hint, you can write your plotting scripts based on what we do in https://github.com/OceanParcels/parcels/blob/master/parcels/plotting.py. Note of course that you don't even need to use python to plot the particles; since the output files are netcdf you should also be able to plot these in any other data analysis programme that you use

**Comment by isabelyuyingwu** [comment]
WOW. That makes sense! Thanks for your quick response.

Yeah, I forget that we've already saved the NetCDF file as below figure, so we can use it directly for plotting . Thanks for your recommendation. I will read your plotting.py carefully and try later in Matlab or python matplotlib.  

<img width="1063" alt="Screen Shot 2020-03-30 at 11 55 02 AM" src="https://user-images.githubusercontent.com/38671085/77940252-69892080-7286-11ea-9716-2cd7e931e29c.png">



In addition, I have a little question. When we input **pset (parameter.........)**, it will automatically plot the default size (s=20) of particles in black color. Is it because you set the particles' size in particleset.py, or plotting.py? 



<img width="852" alt="Screen Shot 2020-03-30 at 12 12 14 PM" src="https://user-images.githubusercontent.com/38671085/77939121-aa803580-7284-11ea-9abc-9b4e098b1be7.png">

I am sorry for my entry-level programming skills.

Thank you so much!

**Comment by erikvansebille** [comment]
The `size` parameter in `ParticleSet.from_line()` is the size of the particleset, so in the example above there are 5 particles. It is _not_ the size for the plotting. See also the documentation at http://oceanparcels.org/gh-pages/html/#parcels.particleset.ParticleSet.from_line

**Comment by isabelyuyingwu** [comment]
Thank you so much!!! Thanks for your quick response!

I will keep following your research!!! Great! Cheer up!
