### ISSUE TITLE
Option to stop the simulation on demand

### ISSUE THREAD

**Issue by miquelmassot** [OceanParcels/parcels#779]
First of all, thanks for this great software piece!

We are using OceanParcels for simulating underwater objects and we would like to have the ability to stop the simulation when a certain condition is reached. 

For example: how could the argo float example be stopped after drifting 10 km or after returning to the surface for the second time? Is there any other way to stop the simulation than running over the entire simulation time?

**Comment by erikvansebille** [comment]
Very good idea, @miquelmassot; thanks for the suggestion!

I have now implemented an `ErrorCode.StopExecution` in PR #780. If you change to that branch, you can then add the following to your Kernel
```python
if particle.driftdistance > 10e3:
    return ErrorCode.StopExecution
```
This should do what you suggested (assuming of course that you keep track of `driftdistance` for your particle)

**Comment by miquelmassot** [comment]
Thanks @erikvansebille! I will give it a try.
