### ISSUE TITLE
Fluctuating surface elevation

### ISSUE THREAD

**Issue by jianzhou722** [OceanParcels/parcels#788]
Hello - Does Parcels support fluctuating surface elevation? I am using Parcels for some shallower estuaries where horizontal barotropic transport may be important. Would it be possible to include the changing water depth as one of the inputs?

**Comment by erikvansebille** [comment]
Hi @jianzhou722, thanks for the question and your interest in Parcels. In fact, we are currently developing the code to include time-varying depth layers. See #660, where we now implement it for SWASH output.  However, it may also work for your model output?

The key is that you use the `Field.set_depth_from_field()` method, see https://github.com/OceanParcels/parcels/blob/4d_depth_sgrids/parcels/examples/example_dask_chunk_OCMs.py#L102-L104 for an example.

Note that this code is still under development, so let us know whether the code in #660 works for you too!

**Comment by erikvansebille** [comment]
Dear @jianzhou722. We have now merged #660 into `master`, so you could try with the latest master of Parcels. We also created a tutorial at https://github.com/OceanParcels/parcels/blob/master/parcels/examples/tutorial_timevaryingdepthdimensions.ipynb
