### ISSUE TITLE
Exception thrown by kernel finaliser

### ISSUE THREAD

**Issue by angus-g** [OceanParcels/parcels#791]
The `Kernel` class defines a `__del__` finaliser, which is meant to unload the JIT module and delete its files. This seems to work in a lot of cases, but can throw the following exception:

```
Exception ignored in: <bound method Kernel.__del__ of <parcels.kernel.Kernel object at 0x7fc0b0875c50>>
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/parcels/kernel.py", line 172, in __del__
TypeError: 'NoneType' object is not callable
```

From the [CPython documentation](https://docs.python.org/3/reference/datamodel.html#object.__del__):

> `__del__()` can be executed during interpreter shutdown. As a consequence, the global variables it needs to access (including other modules) may already have been deleted or set to `None`. Python guarantees that globals whose name begins with a single underscore are deleted from their module before other globals are deleted; if no other references to such globals exist, this may help in assuring that imported modules are still available at the time when the `__del__()` method is called

In this particular case, `Kernel.__del__()` calls functions from the `_ctypes` module, which is deleted first, according to the snippet above. Maybe it would be possible to qualified-import `_ctypes` to something that doesn't begin with an underscore, but I'm not really sure of the right solution here.

**Comment by erikvansebille** [comment]
Fixed in #794
