### ISSUE TITLE
FieldSet.from_netcdf_tutorial_plotting

### ISSUE THREAD

**Issue by marbi4ever** [OceanParcels/parcels#801]
I am trying to read the ocean currents from the ncdf file like the ones in the examples. I made my ncdf files like those in the tutorial, ( lan,lat,time,u and v) as this 
filenames = {'U': "GlobCurrent_example_data/myfile135.nc",
             'V': "GlobCurrent_example_data/myfile135.nc"}
variables = {'U': 'u', 'V': 'v'}
dimensions = {'lat': 'lat', 'lon': 'lon','time': 'time'}
fieldset = FieldSet.from_netcdf(filenames, variables, dimensions). However, when I create a particles set by:
pset = ParticleSet.from_line(fieldset=fieldset, size=5, pclass=JITParticle,
                             start=(24, 73), finish=(25, 73),time=datetime(1993, 5, 15))) 
it gives me an error due to the time. If I remove the time, it works well, then in the 
pset.show(), the title of the figure is given by "Particles after 0:00:00 hours" although it is supposed to show me the default setting (depending on the time in the ncdf file). 

Any help would be appreciated

**Comment by erikvansebille** [comment]
Thanks @marbi4ever, for reporting this Issue. However, without the actual error that you encountered, it is not possible for us to say anything meaningful about how to fix it

**Comment by marbi4ever** [comment]
Dear @erikvansebille , thank you for your quick support, 
Here is what I write 
**pset = ParticleSet.from_line(fieldset=fieldset, size=5, pclass=JITParticle,
                             start=(24, 73), finish=(25, 73),time=datetime(1993, 5, 16))**

Then, I get this error msg


---------------------------------------------------------------------------
UFuncTypeError                            Traceback (most recent call last)
<ipython-input-15-e8ff36c2296e> in <module>
      1 pset = ParticleSet.from_line(fieldset=fieldset, size=5, pclass=JITParticle,
----> 2                              start=(24, 73), finish=(25, 73),time=datetime(1993, 5, 16))

~\Anaconda3\envs\py3_parcels\lib\site-packages\parcels\particleset.py in from_line(cls, fieldset, pclass, start, finish, size, depth, time, repeatdt, lonlatdepth_dtype)
    227         if type(depth) in [int, float]:
    228             depth = [depth] * size
--> 229         return cls(fieldset=fieldset, pclass=pclass, lon=lon, lat=lat, depth=depth, time=time, repeatdt=repeatdt, lonlatdepth_dtype=lonlatdepth_dtype)
    230 
    231     @classmethod

~\Anaconda3\envs\py3_parcels\lib\site-packages\parcels\particleset.py in __init__(self, fieldset, pclass, lon, lat, depth, time, repeatdt, lonlatdepth_dtype, pid_orig, **kwargs)
     88         if time.size > 0 and isinstance(time[0], np.timedelta64) and not self.time_origin:
     89             raise NotImplementedError('If fieldset.time_origin is not a date, time of a particle must be a double')
---> 90         time = np.array([self.time_origin.reltime(t) if isinstance(t, np.datetime64) else t for t in time])
     91         assert lon.size == time.size, (
     92             'time and positions (lon, lat, depth) don''t have the same lengths.')

~\Anaconda3\envs\py3_parcels\lib\site-packages\parcels\particleset.py in <listcomp>(.0)
     88         if time.size > 0 and isinstance(time[0], np.timedelta64) and not self.time_origin:
     89             raise NotImplementedError('If fieldset.time_origin is not a date, time of a particle must be a double')
---> 90         time = np.array([self.time_origin.reltime(t) if isinstance(t, np.datetime64) else t for t in time])
     91         assert lon.size == time.size, (
     92             'time and positions (lon, lat, depth) don''t have the same lengths.')

~\Anaconda3\envs\py3_parcels\lib\site-packages\parcels\tools\converters.py in reltime(self, time)
     58                 return (time - self.time_origin).total_seconds()
     59         elif self.calendar is None:
---> 60             return time - self.time_origin
     61         else:
     62             raise RuntimeError('Calendar %s not implemented in TimeConverter' % (self.calendar))

UFuncTypeError: ufunc 'subtract' cannot use operands with types dtype('<M8[us]') and dtype('float64')

**Comment by erikvansebille** [comment]
OK, the problem seems to be that `xarray` can't parse a calendar in your nectdf files. You'll need to make sure that the calendar that you specify is readable by `xarray` (i.e. cf-compliant, see http://cfconventions.org/cf-conventions/cf-conventions.html#calendar)
