### ISSUE TITLE
Adding and deleting particles in multigrids

### ISSUE THREAD

**Issue by ursho2552** [OceanParcels/parcels#804]
Hi OceanParcels team,

I seem to have stumbled upon a problem when running parcels using fields with different dimensions ("Mydepth" does not have a time dimension). The fieldset is declared as follows:

```
    data_file = "uvw_pactcs30_10_days.nc"
    depthfiles = "depth_z_pos.nc"
    mesh_file = "pactcs30_grd.nc"    
    
    filenames = {'U': {'lon': mesh_file, 'lat': mesh_file, 'depth': depthfiles, 'data': data_file},
                 'V': {'lon': mesh_file, 'lat': mesh_file, 'depth': depthfiles, 'data': data_file},
                 'W': {'lon': mesh_file, 'lat': mesh_file, 'depth': depthfiles, 'data': data_file},
                 'Mydepth':{'lon': mesh_file, 'lat': mesh_file, 'depth': depthfiles, 'data': depthfiles}}
                         
    variables = {'U': 'u',
                 'V': 'v',
                 'W': 'w',
                 'Mydepth': 'depth_Z_r'}
             
    dimensions = {'U': {'lon': 'lon_psi', 'lat': 'lat_psi', 'depth': 'depth_Z_w', 'time': 'time_counter'},
                  'V': {'lon': 'lon_psi', 'lat': 'lat_psi', 'depth': 'depth_Z_w', 'time': 'time_counter'},
                  'W': {'lon': 'lon_psi', 'lat': 'lat_psi', 'depth': 'depth_Z_w', 'time': 'time_counter'},
                  'Mydepth': {'lon': 'lon_psi', 'lat': 'lat_psi', 'depth': 'depth_Z_w'}}
    
    
    fieldset_simple = FieldSet.from_c_grid_dataset(filenames, variables, dimensions,allow_time_extrapolation=False)
```
Then I run the following code, which executes the kernel AdvectionRK4_3D for 1 day, then 1 particle is deleted, 3 particles are added, and the kernel is executed again with the new particle set. 

```
    lons = [234.46176, 238.53275, 235.88148]
    lats = [38.886448, 33.273415, 33.861694]
    depths = [3.600679,  3.1685855, 0.3420207]
    #JITParticle PteropodParticle
    pset = ParticleSet(fieldset=fieldset_simple, pclass=JITParticle, lon=lons,\
                   lat=lats,depth=depths,\
                   time=0.0,lonlatdepth_dtype=np.float32)
    
    kernel =  pset.Kernel(AdvectionRK4_3D)
    
    for i in range(2):
        
        print('Size of pset before execution: {}'.format(pset.size))
        
        pset.execute(kernel,runtime=delta(days=1),dt=delta(minutes=30.0))
        
        print('Remove particle with index 1')
        pset.remove_indices(np.array([1]))
        
    
        
        print('Add 3 particles ')
        if i == 0:
            lons = [234.66348, 233.14043, 234.66101]
            lats = [46.30859,  33.389473, 40.196228]
            depths = [2.2771595, 2.4657798, 3.2484057]
        elif i == 1:
            lons = [234.1704,  235.04831, 235.97224]
            lats = [37.406612, 42.863438, 39.378765]
            depths = [1.7010666, 1.7238535, 2.6949487]

        pset.add(ParticleSet(fieldset=fieldset_simple, pclass=JITParticle, lon=lons,\
                   lat=lats,depth=depths,\
                   time=delta(days=i+1).total_seconds(),lonlatdepth_dtype=np.float32))
    
        print('Size after execution: {}'.format(pset.size))
```

This code runs if I the field "Mydepth" is not included. However, if I include it then the following error appears after the first iteration of the for loop:

```
Traceback (most recent call last):
  File "Debug_delete_add.py", line 103, in <module>
    pset_ptero.execute(kernel,runtime=delta(days=1),dt=delta(minutes=30.0))
  File "/net/kryo/work/ursho/PhD/Projects/Pteropods/My_parcels/Parcels_master_copy/parcels/parcels/particleset.py", line 661, in execute
    execute_once=execute_once)
  File "/net/kryo/work/ursho/PhD/Projects/Pteropods/My_parcels/Parcels_master_copy/parcels/parcels/kernel.py", line 386, in execute
    remove_deleted(pset)
  File "/net/kryo/work/ursho/PhD/Projects/Pteropods/My_parcels/Parcels_master_copy/parcels/parcels/kernel.py", line 366, in remove_deleted
    pset.remove_booleanvector(indices)
  File "/net/kryo/work/ursho/PhD/Projects/Pteropods/My_parcels/Parcels_master_copy/parcels/parcels/particleset.py", line 502, in remove_booleanvector
    self.particle_data[d] = self.particle_data[d][~indices, ...]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 11 but corresponding boolean dimension is 5
```
The files can be found [here](https://wetransfer.com/downloads/61ead1882e3a96c8231192fdb2f704c520200416091229/0bade677f649b60f98d5b8042eb22c6920200416091259/935c37)

Thank you very much for your help and for the amazing package that is OceanParcels

**Comment by erikvansebille** [comment]
Thanks for reporting, @ursho2552. As you may have seen, @angus-g has just created PR #805 with a fix to this issue. Could you run with this new code and check if it fixes your problem?

**Comment by ursho2552** [comment]
Thank you for the quick answer and action!

 I ran the script with the new code but a new error occurs. After running the kernel, deleting particles, and previous to adding new particles using: 

```
pset.add(ParticleSet(fieldset=fieldset_simple, pclass=JITParticle, lon=lons,\
                   lat=lats,depth=depths,\
                   time=delta(days=i+1).total_seconds(),lonlatdepth_dtype=np.float32))
```
The following error occurs:

```
Traceback (most recent call last):
  File "Debug_delete_add.py", line 122, in <module>
    time=delta(days=i+1).total_seconds(),lonlatdepth_dtype=np.float32))
  File "/net/kryo/work/ursho/PhD/Projects/Pteropods/My_parcels/Parcels_master_copy/parcels/parcels/particleset.py", line 491, in add
    self.particle_data[d] = np.concatenate((self.particle_data[d], particles.particle_data[d]))
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

```
Unlike with the "np.append" the new version does not work even when excluding the field "Mydepth". Additonally, I noticed that I sent the wrong "depth_z_pos.nc" [here's](https://wetransfer.com/downloads/7aeba3993c525bb49a5a9952d7d3473b20200416114549/937769318917ac404d5e2f8acfec791220200416114617/410f55) the correct one.

Again thank you very much

**Comment by ursho2552** [comment]
Hi, 

I was looking for what was happening by using simple print statements. And maybe this can help.
In `particleset.py` `line: 485`  when the particles go through `def add(self, particles)` the shape of `particles.particle_data[d]` is for instance (3,) for time, dt, _next_dt, lon, lat, etc, however the shape of xi (and yi, zi, ti) is (3,1) which then leads to the error mentioned in the comment above.

Are xi, yi, ti, and zi supposed to be like this?

**Comment by ursho2552** [comment]
Hi again,

turn out that when using multigrids, e.g. 3, the shape of the xi, yi, zi, and ti attributes of the particles are the number of particles times the number of multigrids. Thus in `particleset.py' `line 496` the line

`self.particle_data[d] = np.delete(self.particle_data[d], indices)`

deletes objects on the flattened array, which then results in the wrong shape. I changed the line to:

`self.particle_data[d] = np.delete(self.particle_data[d], indices, axis = 0)`

which for the small tests I've done now seem to work

**Comment by angus-g** [comment]
Nice sleuthing @ursho2552! I completely missed that there is a `ParticleSet.remove_indices` method, oops!

**Comment by erikvansebille** [comment]
Thanks @ursho2552 for reporting and investigating, and @angus-g for fixing!
