### ISSUE TITLE
Ageing kernel needs to be changed so only adding when ErrorCode.Evaluate

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/parcels#807]
With #762, computation of particle.age as for example highlighted in the Argo tutorial, needs to be slightly changed to only add `dt` when `particle.state == ErrorCode.Evaluate`. Otherwise, the `dt` might in rare occasions be added multiple times per timestep

**Comment by CKehl** [comment]
Example can look as such:
```
class AgingParticle(JITParticle):
    age = Variable('age', initial=0.)
    life_expectancy = Variable('life_expectancy', dtype=np.float64, initial=np.finfo(np.float64).max)


def Age(particle, fieldset, time):
    if particle.state == ErrorCode.Evaluate:
        particle.age = particle.age + math.fabs(particle.dt)
    if particle.age > particle.life_expectancy:
        particle.delete()
```

then, life_expectancy can be initialised with a constant value, or even dynamically adapted per particle.
