### ISSUE TITLE
support chunking for MITgcm Field dataset

### ISSUE THREAD

**Issue by CKehl** [OceanParcels/parcels#814]
currently, the NetCDF dimensions of fields from MITgcm are not registered in the `_name_map` of `NetcdfFileBuffer`. This needs to be added.

**Comment by angus-g** [comment]
Same thing would be good for MOM data

**Comment by CKehl** [comment]
Hi Angus,
Thanks for the info. I am still re-thinking this process, in some shape or form - we already have the discussion somewhere.
Now, how pressing is the issue for the MOM data ? If you need that support immediately, then it would be nice if you open a PR and add your dimension names for MOM to the name_maps (l. 1660 - l. 1664). Ideally, you would also design a test similar to the ones in `example_dask_chunk_OCMs.py`. Erik and me are right today brainstorming how to ideally cluster those tests and examples where data are not freely distributed, but which still demonstrate data format usage etc. - so we'd be happy to also add that script there.

Otherwise, if it still has a week or two time, then you, Erik and me will have figured out a better way how to do this name mapping more versatile.

Cheers,

Christian

**Comment by CKehl** [comment]
we created a new repository for those user-contributed and not necessarily 'main branch'-scripts at https://github.com/OceanParcels/parcels_contributions, where I put the MITgcm test.
