### ISSUE TITLE
Choose field name when created with netcdf method

### ISSUE THREAD

**Issue by pierrick-giffard** [OceanParcels/parcels#824]
When creating a field with from_netcdf method, the field name is automatically the variable name. Could it be possible to choose a different name that the variable name?

**Comment by erikvansebille** [comment]
If you give the variable in `Field.from_netcdf()` as a tuple, the first entry is the name in Parcels and the second is the name in the NetCDF file. See https://github.com/OceanParcels/parcels/blob/master/parcels/field.py#L214

**Comment by pierrick-giffard** [comment]
Thanks!
