### ISSUE TITLE
Difficulties to run plotTrajectories in 'movie2d' mode

### ISSUE THREAD

**Issue by HugoDENISFR** [OceanParcels/parcels#839]
Hello, 

I am a beginner in ocean parcels so I tried to go through the different tutorials. I am not able to visualize animations created through the 'movie2d' mode. I don't get any error but only a blank graph appears and the animation doesn't start. 

Here is my code (basically a copy from the tutorial). I work in a spyder environment. 

#%%
from IPython import get_ipython
get_ipython().run_line_magic('matplotlib', 'inline')

from parcels import FieldSet, ParticleSet, Variable, JITParticle, AdvectionRK4, plotTrajectoriesFile
import numpy as np
import math
from datetime import timedelta as delta
from operator import attrgetter
#%%

import os
os.getcwd()
os.chdir('C:\\Users\\Hugo')

#%%
fieldset = FieldSet.from_parcels('parcels_examples/Peninsula_data/peninsula', allow_time_extrapolation = True)
#%%

#%%
npart = 10  # number of particles to be released
lon = 3e3 * np.ones(npart)
lat = np.linspace(3e3 , 45e3, npart, dtype=np.float32)
time = np.arange(0, npart) * delta(hours=1).total_seconds()  # release every particle one hour later

pset = ParticleSet(fieldset=fieldset, pclass=JITParticle, lon=lon, lat=lat, time=time)

output_file = pset.ParticleFile(name="DelayParticle_time.nc", outputdt=delta(hours=1))
pset.execute(AdvectionRK4, runtime=delta(hours=24), dt=delta(minutes=5),
             output_file=output_file)
output_file.export()  # export the trajectory data to a netcdf file

plotTrajectoriesFile('DelayParticle_time.nc', mode='movie2d')
#%%

This is why I get 
<img width="495" alt="Capture" src="https://user-images.githubusercontent.com/45329704/82309703-bdc99a80-99c3-11ea-8ce4-2d97184c52b0.PNG">

The animation isn't playing itself, wether I try to use the 'Automatic' or 'Inline' mode of spyder. 

Note that none of the call %maptlotlib inline and %pylab inline worked for me. I got a 'Syntax error' so I changed it by 
from IPython import get_ipython
get_ipython().run_line_magic('matplotlib', 'inline')

The problem may have to do something with it. 

Thanks in advance for your help !

**Comment by erikvansebille** [comment]
Does `plotTrajectoriesFile('DelayParticle_time.nc')` show the trajectories? In other words, is it a problem with the animation? If that's the case, I don't think we can help. I have little experience with Windows. 

Note that Parcels plotting routines are very rudimentary, and only provided for quick-and-dirty visualisation. It's recommended that you write your own plotting/postprocessing scripts to further analyse the output of Parcels

Good luck!

**Comment by HugoDENISFR** [comment]
Hello, Yes plotTrajectoriesFile('DelayParticle_time.nc') works well so it has to do with the animation itself. Thanks anyway, I'll try to write myself the animation function then !
