### ISSUE TITLE
everything is right but it goes error when running

### ISSUE THREAD

**Issue by wongchieh** [OceanParcels/parcels#840]
Cause the grid data and the velocity data are stored in different files, I define the Field by the most primitive way 
`U = Field('U',u,lon = lon , lat =lat,time=time,transpose=False)
V = Field('V',v,lon = lon , lat =lat,time=time,transpose=False)
fieldset = FieldSet(U,V)`
and the sampled the particles at places in the area.
but when running it always goes with the error, out of bounds.
I wonder if there is something important that I have ignored.

**Comment by erikvansebille** [comment]
Dear @wongchieh. We can't help you without more information. Please provide the full error that you get, and also more information on what the files etc are. An ErrorOutOFbounds typically means that you try to compute a particle on a location that is not within the Field
