### ISSUE TITLE
Issue reading in delayed start particles from existing particle file

### ISSUE THREAD

**Issue by hrsdawson** [OceanParcels/parcels#842]
I'm using the `ParticleSet.from_particlefile` function to read in an existing file which contains particles released at different times. However this seems to only read in the particles that were released at `time = 0` and not the particles with a delayed start time. 

As an example, the `tutorial_delaystart.ipynb` notebook initializes 10 particles, each released one hour later:
![image](https://user-images.githubusercontent.com/62230733/83104774-c83f0f00-a0fc-11ea-9a0c-3210b717cb4f.png)

After advection these are the locations of the particles:
![image](https://user-images.githubusercontent.com/62230733/83104832-e73da100-a0fc-11ea-898a-8efaf0eec7e2.png)

If I then read in the output file like below, I only get one particle in the set (the first particle that was released):
![image](https://user-images.githubusercontent.com/62230733/83105188-8c587980-a0fd-11ea-99c8-88b0482bd0d2.png)

Do you have any suggestions on how to deal with this?
Thanks in advance!

**Comment by erikvansebille** [comment]
Thanks for reporting this Issue, it was indeed a bug!

I now fixed it in #844; could you please check if this works for your situation too?

I'll now dig into your other Issue, #843

**Comment by stellema** [comment]
I had similar issues, so thanks for reporting/fixing it! 
Does this fix mean any deleted particles (e.g. by going out of bounds) that have been written to the particle file will start again? 
Also, do the particles continue to be repeated (using `repeatdt`) if they have previously been deleted?

**Comment by erikvansebille** [comment]
Hi @stellema. Thanks for these questions. the `ParticleSet.from_particlefile()` now has a keyword `restarttime` that by default is the maximum time in the netcdf file. So by default, only those particles that were written at the last time will get into the new `pset` (and not particles that had been deleted).

Note that you can also change the `restarttime`, to either be a specific time or a function such as `np.nanmin`. The latter is useful if you run with `dt`<0 (backward-in-time) and you therefore want the restart to start at the _smallest_ time in the netcdf file
