### ISSUE TITLE
decode_cf time error when reading in particle set from file

### ISSUE THREAD

**Issue by hrsdawson** [OceanParcels/parcels#843]
I've come across a decode time error when trying to read in a particle set from an existing file. Not sure if this is known, but I didn't see it in a brief search of previous issues. The error traceback is included below. 

![image](https://user-images.githubusercontent.com/62230733/83107650-fa9f3b00-a101-11ea-93cd-5d4b34ba7e7b.png)
![image](https://user-images.githubusercontent.com/62230733/83107792-320de780-a102-11ea-8fae-88fd515b803a.png)

We've found a work around for this which is to edit the `parcels/particleset.py` file at line 429 from:
`pfile = xr.open_dataset(str(filename), decode_cf=True)`
to:
`pfile = xr.open_dataset(str(filename), decode_cf=False)`
and then to reinstall parcels after this edit is made. 

Is this the right approach, or would you have a different suggestion?

**Comment by erikvansebille** [comment]
This happens because your hydrodynamic data has a `noleap` calendar. Would you be able to share a bit of the data that you used to create the FieldSet with me (e.g. via wetransfer), so I can explore further? I only need three time snapshots and a small domain

**Comment by hrsdawson** [comment]
Thanks for fixing #824! I will send you a snapshot of the hydrodynamic data now.
