### ISSUE TITLE
ImportError when importing the diffusion kernel

### ISSUE THREAD

**Issue by wongchieh** [OceanParcels/parcels#845]
hello,
   it will come out a `importerror` when adding diffusion kernel.
   the code is 
```
from parcels import ( AdvectionDiffusionM1,FieldSet, ParticleSet, JITParticle,
                     DiffusionUniformKh, AdvectionDiffusionEM)
```
   and the error will be :
```
ImportError: cannot import name 'AdvectionDiffusionM1' from 'parcels' (E:\ProgramData\Anaconda3\envs\parcels\lib\site-packages\parcels\__init__.py)
```

   the problem will come out whether in windows or Linux
   I hope you can give some advice on this.

best wishes.

**Comment by erikvansebille** [comment]
This is because you are using an older version of parcels. The new diffusion kernels were only added in v2.2.0. So you will need to update Parcels (using anaconda?) to the latest version
