### ISSUE TITLE
Particle set from particle file doesn't include last values of custom variables

### ISSUE THREAD

**Issue by stellema** [OceanParcels/parcels#846]
Is it possible to include the final values of custom particle variables when using `ParticleSet.from_particlefile`? I noticed that only default particle variables (e.g. time, depth, lat) are carried over to the `ParticleSet`, while custom variables go back to their initial value.
For example, in the [Calculating distance travelled](https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/parcels_tutorial.ipynb#Calculating-distance-travelled) example at the end of `parcels_tutorial.ipynb`, the output of pset is:
```
P[0](lon=27.875189, lat=-33.055775, depth=0.000000, distance=13.197482, time=518400.000000)
P[1](lon=22.721094, lat=-36.037327, depth=0.000000, distance=641.251831, time=518400.000000)
P[2](lon=24.074530, lat=-35.525574, depth=0.000000, distance=543.712524, time=518400.000000)
P[3](lon=28.883598, lat=-34.525509, depth=0.000000, distance=183.668457, time=518400.000000)
P[4](lon=30.882704, lat=-34.146477, depth=0.000000, distance=172.781235, time=518400.000000)`
```

However, the custom "distance" variable goes back to the initial value of 0. in the newly created `ParticleSet`:

`ParticleSet.from_particlefile(fieldset, filename="GlobCurrentParticles_Dist.nc", pclass=DistParticle, restart=True)`
```
P[5](lon=27.875189, lat=-33.055775, depth=0.000000, distance=0.000000, time=518400.000000)
P[6](lon=22.721094, lat=-36.037327, depth=0.000000, distance=0.000000, time=518400.000000)
P[7](lon=24.074530, lat=-35.525574, depth=0.000000, distance=0.000000, time=518400.000000)
P[8](lon=28.883598, lat=-34.525509, depth=0.000000, distance=0.000000, time=518400.000000)
P[9](lon=30.882704, lat=-34.146477, depth=0.000000, distance=0.000000, time=518400.000000)
```

**Comment by erikvansebille** [comment]
Good point, I'll implement asap! Should not be too difficult; stay tuned

**Comment by erikvansebille** [comment]
I've now implemented it in #847. Could you check if this work for you @stellema?

**Comment by stellema** [comment]
Thanks! It works when all variables are written to the output file. 
However, in the [calculating distance travelled](https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/parcels_tutorial.ipynb#Calculating-distance-travelled) example I get this error as there are variables (`prev_lon` and `prev_lat`) with `to_write=False`.
```
Traceback (most recent call last):

  File "C:\Users\Annette\Anaconda3\envs\parcels_test\lib\site-packages\parcels\particleset.py", line 444, in from_particlefile
    raise RuntimeError('Variable %s is in pclass but not in the particlefile' % v.name)

RuntimeError: Variable prev_lon is in pclass but not in the particlefile
```

**Comment by stellema** [comment]
I also found an error when initializing variables that were written with `to_write="once"`:

```
  File "C:\Users\Annette\Anaconda3\envs\parcels_test\lib\site-packages\parcels\particleset.py", line 460, in from_particlefile
    vars[v] = vars[v][inds]
IndexError: too many indices for array
```
The 1D variables could skip this step to avoid being indexed with the tuple `inds = np.where(vars['time'] == restarttime)` on line 458.

**Comment by HugoDENISFR** [comment]
Hi, I am experiencing something that could be related to your issue. It may be trivial but I am not sure about how to use ParticleSet.from_particlefile so any help would be appreciated. 

**I created a nc file : 'parcels_examples/Data_NEMO/indian_drifters.nc' that contains the desired positions of my particules (lon,lat,depth,time) : Time was set as 0.0 for each of them**

`OrderedDict([('lon',
              <class 'netCDF4._netCDF4.Dimension'> (unlimited): name = 'lon', size = 32),
             ('lat',
              <class 'netCDF4._netCDF4.Dimension'> (unlimited): name = 'lat', size = 32),
             ('depth',
              <class 'netCDF4._netCDF4.Dimension'> (unlimited): name = 'depth', size = 32),
             ('time',
              <class 'netCDF4._netCDF4.Dimension'> (unlimited): name = 'time', size = 32)])`
`OrderedDict([('lon',
              <class 'netCDF4._netCDF4.Variable'>
              float32 lon(lon)
              unlimited dimensions: lon
              current shape = (32,)
              filling on, default _FillValue of 9.969209968386869e+36 used),
             ('lat',
              <class 'netCDF4._netCDF4.Variable'>
              float32 lat(lat)
              unlimited dimensions: lat
              current shape = (32,)
              filling on, default _FillValue of 9.969209968386869e+36 used),
             ('depth',
              <class 'netCDF4._netCDF4.Variable'>
              float32 depth(depth)
              unlimited dimensions: depth
              current shape = (32,)
              filling on, default _FillValue of 9.969209968386869e+36 used),
             ('time',
              <class 'netCDF4._netCDF4.Variable'>
              float32 time(time)
              unlimited dimensions: time
              current shape = (32,)
              filling on, default _FillValue of 9.969209968386869e+36 used)])`

Then I just try to set the particles using 

`pset = ParticleSet.from_particlefile(fieldset=fieldset, pclass=JITParticle,filename='parcels_examples/Data_NEMO/indian_drifters.nc')`

And I get the following issue  

` File "<ipython-input-27-025a40b1ae34>", line 1, in <module>
    pset = ParticleSet.from_particlefile(fieldset=fieldset, pclass=JITParticle,filename='parcels_examples/Data_NEMO/indian_drifters.nc')

  File "C:\Users\Hugo\Anaconda3\envs\py3_parcels\lib\site-packages\parcels\particleset.py", line 430, in from_particlefile
    lon = np.ma.filled(pfile.variables['lon'][:, -1], np.nan)

  File "C:\Users\Hugo\Anaconda3\envs\py3_parcels\lib\site-packages\xarray\core\variable.py", line 703, in __getitem__
    dims, indexer, new_order = self._broadcast_indexes(key)

  File "C:\Users\Hugo\Anaconda3\envs\py3_parcels\lib\site-packages\xarray\core\variable.py", line 531, in _broadcast_indexes
    key = indexing.expanded_indexer(key, self.ndim)

  File "C:\Users\Hugo\Anaconda3\envs\py3_parcels\lib\site-packages\xarray\core\indexing.py", line 43, in expanded_indexer
    raise IndexError("too many indices")

IndexError: too many indices`

Which I don't really understand to what it refers to . Is this somehow similar to the issue you hd @stellema ? 

Thanks in advance

**Comment by erikvansebille** [comment]
Indeed @HugoDENISFR, this appears the same bug as reported by @stellema. This should be fixed when #847 is merged into master. Can you confirm?

**Comment by HugoDENISFR** [comment]
Hi, Thanks for your answer ,
I updtated with the latest version, and now I don't have this issue anymore but a new one have appeared :

`RuntimeError: Variable time is in pclass but not in the particlefile`

 I supposed it a completely different issue and it has to do with the way I try to create my particlefile, which may be a bit clumsy. Could you give me advise on how to fix this issue ? I don't know how to specify the right class for my 'time' variable in my file. 

This is the way I tried to create the file ( In particular I am not sure about the dimensions) : init_lon, init_lat and init_depth are arrays that contain the initial coordinates of each of my particles. Then I do : 

`init_pos = netCDF4.Dataset('parcels_examples/Data_NEMO/indian_drifters.nc','w',format="NETCDF4")

init_pos.createDimension('lon',None)
init_pos.createDimension('lat',None)
init_pos.createDimension('depth',None)
init_pos.createDimension('time',None)

i_time = init_pos.createVariable('time', 'f8', dimensions='time')
longitude = init_pos.createVariable('lon', 'f4', dimensions='lon')
latitude = init_pos.createVariable('lat', 'f4', dimensions='lat')
depth = init_pos.createVariable('z', 'f4', dimensions='depth')


longitude[:]=init_lon
latitude[:]=init_lat
depth[:]=init_depth
i_time[:]=np.zeros(len(init_lon))

init_pos.close()`

And I simply call
 `pset = ParticleSet.from_particlefile(fieldset=fieldset, pclass=JITParticle,filename=file_pos)`

Thanks a lot for your help and reactivity, 

Hugo

**Comment by erikvansebille** [comment]
I expect this is because you can't use `time` as the name for a new `Variable`, as it is also the name of a built-in Variable. I have now created a PR ()

I suggest you use another name for this `Variable`.

**Comment by erikvansebille** [comment]
I now see that you created a NetCDF file yourself. I would recommend you use the built-in `ParticleFile.write()` instead, because`ParticleSet.from_particlefile()` only works with files that have been created with `ParticleFile.write()`

**Comment by HugoDENISFR** [comment]
It makes sense then ! Sorry for the mess, still in the beggining of my journey with parcels.
