### ISSUE TITLE
ParticleSet RuntimeError with user defined partitions 

### ISSUE THREAD

**Issue by stellema** [OceanParcels/parcels#850]
I think there is a _very_ small issue in `ParticleSet` [on line 187](https://github.com/OceanParcels/parcels/blob/23166a5fd1903e51480b8e12eb11c769434eb822/parcels/particleset.py#L187). The user given partitions is checked with `np.max(partitions >= mpi_rank)`, but the runtime error it leads to says `'Particle partitions must vary between 0 and the number of mpi procs'`. I think `mpi_rank` should be replaced with `mpi_size`.

**Comment by erikvansebille** [comment]
Good point. Do you want to create a pull request yourself so that we can merge it?
