### ISSUE TITLE
2d longitudes and latitudes

### ISSUE THREAD

**Issue by SaAlrabeei** [OceanParcels/parcels#855]
Hello, 
I have some data whose lon and lat variables are given as matrices not arrays. Whereas the projected_coordinates are arrays (see the picture). 
I am trying to add  field from ncdf but I don't know how to do so, which variables should I consider, ( lon/lat or x/y) !!

![image](https://user-images.githubusercontent.com/42937645/83955417-0520a980-a853-11ea-8d09-82690982d4a4.png)

**Comment by erikvansebille** [comment]
It seems that you are using NEMO data? In that case, please see the tutorial at https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/tutorial_nemo_3D.ipynb for how to load 3D NEMO data, or the tutorial at https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/tutorial_interpolation.ipynb for the more general background on interpolation
