### ISSUE TITLE
POP grid depth units conversion

### ISSUE THREAD

**Issue by Eddebbar** [OceanParcels/parcels#856]
First off, **many thanks** to the entire Parcels team for this intuitive, flexible, and overall excellent tool. 

While using the 3D advection kernel with velocity fields from a POP2 simulation at ~0.1º resolution, I encountered an issue whereby particle vertical advection was ~ 2 order of magnitude smaller than expected, hinting at potentially a vertical velocity or depth unit issue. As nicely documented in ```fieldset.from_pop()```, vertical velocities, which are output in 'cm/s' in POP, are converted in ```fieldset.W.set_scaling_factor(-0.01) ``` to 'm/s' + a direction change, but it's unclear how the depth unit (output in 'cm' in POP) is treated in ```fieldset.from_pop()```.

Attempting a depth unit conversion in parcels from 'cm' to 'm' seemed problematic, while converting depth to 'm' within the original grid files (i.e. in 'meshmask' see example code below) seems to provide realistic vertical trajectories. 

However, I am not sure if this is the appropriate way forward as: i) this is somewhat inconvenient requiring unit conversion upstream in the POP output files, and ii) there might be unknown dependencies or assumptions related to depth unit treatment I may be missing here. 

Thanks in advance for any insights or input on this!
 
```
ufiles = sorted(glob(drc+'g.e11.G.T62_t12.eco.006.pop.h.0005-10*.nc'))
vfiles = sorted(glob(drc+'g.e11.G.T62_t12.eco.006.pop.h.0005-10*.nc'))
wfiles = sorted(glob(drc+'g.e11.G.T62_t12.eco.006.pop.h.0005-10*.nc'))
mesh_mask =drs+'POP_GRID_depth_m.nc'

filenames = {'U': {'lon': mesh_mask, 'lat': mesh_mask, 'depth': mesh_mask, 'data': ufiles},
             'V': {'lon': mesh_mask, 'lat': mesh_mask, 'depth': mesh_mask, 'data': vfiles},
             'W': {'lon': mesh_mask, 'lat': mesh_mask, 'depth': mesh_mask, 'data': wfiles}}

variables = {'U': 'UVEL',
             'V': 'VVEL',
             'W': 'WVEL'}

dimensions = {'U': {'lon': 'ULONG', 'lat': 'ULAT', 'depth': 'z_w', 'time': 'time'},
              'V': {'lon': 'ULONG', 'lat': 'ULAT', 'depth': 'z_w', 'time': 'time'},
              'W':  {'lon': 'ULONG', 'lat': 'ULAT', 'depth': 'z_w', 'time': 'time'}}

fieldset = FieldSet.from_pop(filenames, variables, dimensions)

```

**Comment by erikvansebille** [comment]
Thank you for these nice words, @Eddebbar.

I'm not sure I entirely understand your question, but is it that both the units of W and of depth are in cm? Are the units of depth in the ufiles and vfiles also in cm, or only in the wfiles? Because the POP data we use has depth units in m, right @pdnooteboom? 

If indeed both units are in cm (and cm/s), you could best use  `fieldset.from_pop()` and then immediately after use `fieldset.W.set_scaling_factor(1)` to use a scaling factor of 1.0. Note then that the depth in your output files will also be in cm. Makes sense?

**Comment by pdnooteboom** [comment]
Yes @erikvansebille, the depth has unit m for the POP data that we use.

**Comment by Eddebbar** [comment]
Thanks for the quick reply @erikvansebille! Some clarification and updates:

> is it that both the units of W and of depth are in cm? Are the units of depth in the ufiles and vfiles also in cm, or only in the wfiles? 

Yes, the depth unit is in cm in both W and depth. It is also in cm in the ufiles and vfiles, and is also the case - to my knowledge - for most outputs of CESM/POP model experiments.  

> If indeed both units are in cm (and cm/s), you could best use fieldset.from_pop() and then immediately after use fieldset.W.set_scaling_factor(1) to use a scaling factor of 1.0. Note then that the depth in your output files will also be in cm. Makes sense?

Makes sense, though this raises an issue with the scaling factor already defined in ```Fieldset.from_pop```  See below: 
 
```
fieldset = FieldSet.from_pop(filenames, variables, dimensions)

fieldset.W.set_scaling_factor(1)
```
```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-5-76ba16753f4e> in <module>
----> 1 fieldset.W.set_scaling_factor(1)

~/miniconda3/envs/analysis/lib/python3.7/site-packages/parcels/field.py in set_scaling_factor(self, factor)
    509 
    510         if self._scaling_factor:
--> 511             raise NotImplementedError(('Scaling factor for field %s already defined.' % self.name))
    512         self._scaling_factor = factor
    513         if not self.grid.defer_load:

NotImplementedError: Scaling factor for field W already defined.
```

**Comment by erikvansebille** [comment]
Ah sorry, I forgot that we checked if it was set already

Then a workaround is to set the value directly, i.e.
```python
fieldset.W._scaling_factor = 1.
```
After you've created the `FieldSet`

Note by the way that I'm not entirely sure if this should be 1 or -1. Depends on the direction of vertical velocity. Parcels assumes the direction of positive W to be the same as the direction of increasing depth (so if depth increases downward, then W is assumed positive downward). If it's the other way in Parcels, then use `fieldset.W._scaling_factor = -1.`

**Comment by Eddebbar** [comment]
This works great Erik, and results look the same as when applying the cm_to_m conversion in the original POP output and grid files. 

> Note by the way that I'm not entirely sure if this should be 1 or -1. 

In POP outputs, vertical velocity is positive for upward motion whereas depth increases downward, so a -1 scaling factor is appropriate.

Do you think converting POP depths to 'm' within parcels (e.g. in ```Fieldset.from_pop``` ) is worthwhile (or relatively feasible) for consistency with the broader use of 'm/s' and 'm' units elsewhere in the code? This assumes all - or at least most - POP model outputs have depth units of 'cm', as expected from pop2 documentation <http://www.cesm.ucar.edu/models/cesm1.0/pop2/doc/users/node34.html>

**Comment by erikvansebille** [comment]
OK, good to know that `fieldset.W._scaling_factor = -1.` works for you

I have now created a new PR (#857) that adds a `depth_units` argument in `FieldSet.from_pop()`. For backward compatibility we default to `depth_units='m'`, but give a warning because as you say @Eddebbar, many POP outputs seem to be in cm
