### ISSUE TITLE
Unexpected Particle Motion and Issues with ROMS 3D S-grid Transformations

### ISSUE THREAD

**Issue by BenLimer14** [OceanParcels/parcels#859]
Hello,

First off, we are excited to continue using such an efficient and customizable particle tracking software! We are using 3D advection to simulate coral larval dispersal in a high resolution domain. The hydrodynamics is a ROMS curvilinear S-grid. Each file is 1 hour with 24 time slices 150 seconds each. Here is an example 6-hour 3D output which we are aiming to replicate in PARCELS: (PARCELS will allow for more efficient simulations and enhanced behavioral controls in the particles than in the other software)
![LTRANS_plot](https://user-images.githubusercontent.com/47615818/84408482-cb90cb00-abd1-11ea-88f6-f9ed43e97c22.png)
Here are the issues we are looking forward to resolving:

1) Runs with small internal time steps are not producing smooth output. This image uses 10 second time step, while the first example is 2 seconds. Our better-working examples are limited to 60 seconds at the smallest. Particles are behaving unexpectedly with shorter time steps:
<img width="444" alt="Drop_60_10" src="https://user-images.githubusercontent.com/47615818/84406789-a13e0e00-abcf-11ea-9f11-8d4057b433ac.png">

2) I have been unsuccessful at adapting scripts from other comment threads to obtain depth in meters instead of sigma units. Our bathymetry is in meters but all of the depth dimensions are in sigma units (i.e., s_w for w-velocity; s_rho for u and v-velocities). I'm relatively new to python would definitely appreciate any advice on the grids and how to work with them.

3) Many particles are freezing with only some positions changing between time steps. This can happen without deletion, or they are prematurely deleted by the recovery kernel, when they are in the middle of the ocean. I did not see any "ThroughSurface" errors thrown, so I haven't been able to figure out the cause here. Much of the time, we have depth and latitude change, when longitude doesn't; this can happen in other incomplete combinations of the three as well.

We have used the alternate kernel from Issue #765, which helped greatly, but this is the closest output to the first example plot that we have obtained (This uses a 60 sec time step, 10,000 particles, and 20 hours of run time):
<img width="447" alt="20hr_10000particles_60s" src="https://user-images.githubusercontent.com/47615818/84408997-7608ee00-abd2-11ea-84ab-54e69cd0cab4.png">
The .txt script attached was used to create this output (ran on Jupyter). This is a simple case to get the particles to advect properly with the new kernel, but I have been experimenting with more complicated versions of the script when testing transformations and codes from other comment threads.

[Moorea_New_Kernel.txt](https://github.com/OceanParcels/parcels/files/4766161/Moorea_New_Kernel.txt)

I am currently sharing one of our hydrodynamics files through WeTransfer. Thank you for any help you can provide. I look forward to hearing from you.

Best,
Ben Limer

**Comment by erikvansebille** [comment]
Thanks @BenLimer14, for this very elaborate Issue. I'm not really sure how we can help, though. I was able to run your simulation with the hydrodynamic data you provided (although I had to set `allow_time_extrapolation=True` in the FieldSet creation), and it appeared to run ok.

As you'll understand, I don't have time to deeply dive into your code and application myself; I have my own [team](http://oceanparcels.org/utrechtteam) to support ;-) 

I'd be happy to help if you provide specific bugs/errors: ideally as a [Minimal Working Example](https://en.wikipedia.org/wiki/Minimal_working_example) or even better as a [Unit Test](https://en.wikipedia.org/wiki/Unit_testing) so that we can effectively and efficiently dig into the code to fix any bugs.

**Comment by BenLimer14** [comment]
Hi Erik,

Thanks for looking over the issue. I had specific bugs and errors pop up when I was trying to adapt the grid transformation codes and scripts from the other comment threads, but the issues go beyond that.

For now, I will take some time and see if I can resolve the issues using the software used to create the first example. If that doesn't work, I will return to PARCELS and try and set up a Minimal Working Example.

Best,
Ben
________________________________
