### ISSUE TITLE
Problem in loading HYCOM netcdfs with xarrays

### ISSUE THREAD

**Issue by giospud** [OceanParcels/parcels#865]
Hi everyone
I am trying to load HYCOM netcdf files but I have some problem with xarray:

WARNING: File ./hycom_glb_sfc_u_2020052900_t021.nc could not be decoded properly by xarray (version 0.14.1).
         It will be opened with no decoding. Filling values might be wrongly parsed.
WARNING: Casting lon data to np.float32
WARNING: Casting lat data to np.float32
WARNING: Casting depth data to np.float32
WARNING: Trying to initialize a shared grid with different chunking sizes - action prohibited. Replacing requested field_chunksize with grid's master chunksize.

Any suggestion on how to fix the problem? I am just using the command:
fieldset = FieldSet.from_netcdf(filenames, variables, dimensions,vmin=-2000)

Giovanni

**Comment by erikvansebille** [comment]
These are only Warnings, @giospud. You can probably ignore them.

**Comment by giospud** [comment]
Hi @erikvansebille 
yes, actually I succeeded in running it. Right now I am trying to plot particles at different times
