### ISSUE TITLE
Proper OO-Programming inheritance

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/parcels#866]
While some Parcels classes have ok Object-Oriented behaviour (e.g. the `Particle` class and its associated `JITParticles` and `ScipyParticles`, many others don't. 

It would be good to improve the OO inheritance for at least

- [x] the `ParticleSet` class (e.g. 'build', 'add particle', 'remove particle' as methods)
- [x] the `Kernel` class (with e.g. 'build', 'compile', 'load', 'unload', 'execute' as methods)
- [x] the `ParticleFile` class
- [x] ...

Some of this is already implemented in #862, for example in the `Kernels`, where we have a 'BaseKernel' (in kernelbase.py), from which each kind of 'Kernel' (in 'kernel_node.py' and 'kernel_vectorized.py') is derived from.

This will also help fix #618. Thanks to @CKehl for bringing this up

**Comment by CKehl** [comment]
for `ParticleSet` class, see #913 and follow-ups - issue resolved, progressively.
