### ISSUE TITLE
Error when exporting temp. files to netCDF

### ISSUE THREAD

**Issue by claudiofgcardoso** [OceanParcels/parcels#875]
Hello all,

I just got an error at the end of a simulation, apparently related with the transformation of the temp. files to netCDF (error output below). The simulation was run on Bash, so I lost the "pset". Is there a way of exporting these temporary files into netCDF outside the simulation?

```python
100% (4924800.0 of 4924800.0) |#########| Elapsed Time: 14:25:41 Time: 14:25:41
FINISHED! Execution of simulation took 52035 seconds
Exception ignored in: <function ParticleFile.__del__ at 0x7f9ba2e8b200>
Traceback (most recent call last):
  File "/home/ccardoso/anaconda3/envs/py3_parcels/lib/python3.7/site-packages/parcels/particlefile.py", line 196, in __del__
    self.close()
  File "/home/ccardoso/anaconda3/envs/py3_parcels/lib/python3.7/site-packages/parcels/particlefile.py", line 201, in close
    self.export()
  File "/home/ccardoso/anaconda3/envs/py3_parcels/lib/python3.7/site-packages/parcels/particlefile.py", line 375, in export
    data = self.read_from_npy(global_file_list, len(self.time_written), var)
  File "/home/ccardoso/anaconda3/envs/py3_parcels/lib/python3.7/site-packages/parcels/particlefile.py", line 318, in read_from_npy
    data = np.nan * np.zeros((self.maxid_written+1, time_steps))
MemoryError: ((6444660, 1369), dtype('float64'))
```

**Comment by erikvansebille** [comment]
Hi @claudiofgcardoso. I haven't seen this error before, but it seems that the netcdf file will become so large that it doesn't fit into your memory (`MemoryError`)?

Could you try a system with more memory, or somehow increase your virtual memory? Note that you don't need to rerun the `pset.execute()`, because the files are stored as `npy` dumps, so you can use the [convert_npydir_to_netcdf](https://github.com/OceanParcels/parcels/blob/master/parcels/scripts/convert_npydir_to_netcdf.py) function.

If that doesn't work, then I fear the easiest solution would be to rerun your experiment with a smaller particleset, and then do multiple runs?

**Comment by claudiofgcardoso** [comment]
Hi @erikvansebille,

Thank you for the suggestions. I transferred the .npy files to another system and did the conversion successfully! Only had to edit the pset_info.npy manually in order to update the .npy and final netCDF paths in order to work. 

I will edit my scripts to prevent this from happening following you suggestion of splitting my experiment into two using the `ParticleSet.from_particlefile`, but have some doubts about how it works (also related with issue #842): I am releasing particles at  the rivers outlet taking into account river flow. For that, I create a particle set with the particle release time determined previously to the execution. When running the second part of the simulation, will particles that are expected to be released after this interruption be released?

**Comment by erikvansebille** [comment]
Hi @claudiofgcardoso. The netcdf file does not have any information on particles that have not started yet, so using `ParticleSet.from_particlefile` will also not include particles that have not been released yet

**Comment by claudiofgcardoso** [comment]
Hi @erikvansebille. It would be nice if we could add particles into the particle set after loading it with `ParticleSet.from_particlefile`. I'll find a workaround... Thanks!
