### ISSUE TITLE
Retrieve field values used for interpolation

### ISSUE THREAD

**Issue by HugoDENISFR** [OceanParcels/parcels#878]
Hello, 

For the purpose of understanding dispersal differences obtained between Parcels and another Lagrangian model, I would like to retrieve the different velocity values that parcels uses for its interpolation scheme. 

More precisely, as explained in the reference paper https://gmd.copernicus.org/articles/12/3571/2019/gmd-12-3571-2019.html, I am looking for the values that are read on a C-grid at each time step, to compute the fluxes and interpolate u,v,w at the particle position. 

I tried to look for the appropriate function that does the interpolation in the source code but I am a bit loss between the different files and functions. Could you highlight for me where those values are read in the code ? 

Thanks a lot, 

Hugo

**Comment by erikvansebille** [comment]
You don't need to dig into the source code, you can just use code from the [AdvectionRK4 method](https://github.com/OceanParcels/parcels/blob/master/parcels/kernels/advection.py#L11-L23) (make sure your ParticleType has custom Variables `uvel` and `vvel`.
```python
(u, v) = fieldset.UV[time, particle.depth, particle.lat, particle.lon]
particle.uvel = u
particle.vvel = v
```
If the `interp_method` is set to `cgrid_interpolation`, then this will yield exactly the right values, see also the [interpolation tutorial](https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/tutorial_interpolation.ipynb).

**Comment by HugoDENISFR** [comment]
Yes, I have used this option, the thing is I don't only want the values that are interpolated, but also the values that are read on the grid and used in the computation of the interpolation

**Comment by erikvansebille** [comment]
In that case, have a look at the [AnalyticalAdvection](https://github.com/OceanParcels/parcels/blob/master/parcels/kernels/advection.py#L106) kernel (and its [tutorial here](https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/tutorial_analyticaladvection.ipynb)), where exactly this is done:
- the grid indices are found on lines [127-128](https://github.com/OceanParcels/parcels/blob/master/parcels/kernels/advection.py#L127-L128)
- the velocities (actually fluxes) are computed on lines [187-290](https://github.com/OceanParcels/parcels/blob/master/parcels/kernels/advection.py#L187-L190)

Hope this helps

**Comment by HugoDENISFR** [comment]
Thank you very much !

**Comment by HugoDENISFR** [comment]
How would you manage to print values from a certain kernel to the console or to a file ? 

For instance if I try to retrieve u1 from Advection_RK4, none of print or sys.stdout methods work. I get the type of following error : 

`Cannot convert 'sys' used in kernel to C-code`

From what I see in the documentation, this comes from the fact that kernels are translated into C and therefore, sys or other methods can't work properly. 

Is there an alternative I could use to retrieve values of interest that are computed in a certain kernel, that would be compatible with parcels ? 

Many thanks for your tremendous help, hope you are not too bored of my requests !

Hugo

**Comment by erikvansebille** [comment]
You can use print statements in Kernels directly, see e.g. [these test kernels](https://github.com/OceanParcels/parcels/blob/master/tests/test_kernel_language.py#L222-L244)

Alternatively, you can always use ScipyParticles instead of JITParticles to circumvent running in C. This will allow you to use whatever python code you want
