### ISSUE TITLE
Wherefore art thou parcels

### ISSUE THREAD

**Issue by John-Luick** [OceanParcels/parcels#881]
Just installed miniconda, oceanparcels, etc., and ran through the examples on jupyter notebook. I'm on W10 now but planning to install on both W10 and linux. I assumed that the same examples could be done in pycharm instead of jupyter notebook but have run into trouble getting python 3.8 to find parcels in order to import (or create?) the FieldSet object. It gets matplotlib no problem (import matplotlib.pyplot as plt). But none of the various iterations I have tried of "from parcels import FieldSet..." lead to anything other than "ModuleNotFoundError: No module named 'parcels'". Obviously have tried setting my PATH environment variable and the usual things for helping it find parcel. In summary, the question is... how to get python to find parcels? (Note, I just taught myself to use python in order to use ocean_parcels, so I have about two days python experience - my countless years Matlab experience is of no help with this!)  

Here is one of several different values I tried setting an environmental variable named PYTHONPATH to: 
C:\Users\User\miniconda3\pkgs\parcels-2.2.0-py36h9f0ad1d_0\Lib\site-packages\parcels
That is where I found fieldset.py hiding.

**Comment by erikvansebille** [comment]
Thanks for reporting @John-Luick. However, I don't think we can help much. We don't use Windows ourselves, and I've never heard any other user experience these problems before. Something must have gone wrong on the miniconda install? Can you run other python packages? I fear that the only way to fix this is to trawl the internet for solutions how to set the PYTHONPATH in Windows.
