### ISSUE TITLE
Sampling a 2D variable in 3D fieldset

### ISSUE THREAD

**Issue by NiekK19** [OceanParcels/parcels#883]
Hi all,

Currently I am working on a 3D fieldset made with POP data. Now I wanted to also sample the mixed layer depth along the particle trajectories. This file is just a 2D array with the monthly mixed layer depths. I have constructed this field together with all the other (3D) variables, but leaving out the depth (since there is none). For a single release of particles this is working fine, but when I want to release a new set of particles, say every month, it throws an error at the second month. The error I get: (particleset for every release is 2530 particles.)

`IndexError: boolean index did not match indexed array along dimension 0; dimension is 10120 but corresponding boolean dimension is 5060`

I did not make changes to the way repeatdt is defined (and stopped after 1 year), and this works fine without the mixed layer depth data, so therefor I think that I might have missed something with including the HMXL data to the fieldset. Should something different be done when you include a 2D variable to a 3D fieldset, or does it work the same way as any other variable, which would mean my mistake is in some other part of the code?

The way I have constructed the fieldset now with from_pop(): (only U as example 3D var and HMXL)
```
VEL =  {'U': {'lon':readDir + "bathymetry_POP_lowres_320t384.nc", 
              'lat':readDir + "bathymetry_POP_lowres_320t384.nc",
              'depth':readDir + "w_depfile.nc", 
              'data':readDir + "files_UVEL.nc"},
              'H': {'lon':readDir + "bathymetry_POP_lowres_320t384.nc",
              'lat':readDir + "bathymetry_POP_lowres_320t384.nc",
              'data':readDir + "files_HMXL.nc"}}
```

```
variables = {'U':'UVEL',
'H':'HMXL'}
```

```
dimensions = {'U':{'lon':'ULONG','lat':'ULAT','depth':'moc_z','time':'time'},
'H':{'lon':'ULONG','lat':'ULAT','time':'time'}}
```
Thanks for the help!

**Comment by erikvansebille** [comment]
Hmm, this is strange. Thanks for reporting. Can you also share the code for creating the ParticleSet (including the repeatdt) and the _full_ error message?

**Comment by NiekK19** [comment]
Yes, of course.
For the ParticleSet:
```
class Properties(JITParticle):
    temp = Variable('temp', dtype=np.float32, initial=0.)
    salt = Variable('salt', dtype=np.float32, initial=0.)
    rho = Variable('rho', dtype=np.float64, initial=0.)
    VT = Variable('VT', dtype=np.float32, initial=0.)
    sampled = Variable('sampled', dtype=np.float32, initial=0.)
    HMXL = Variable('HMXL', dtype=np.float32, initial=0.)```

```datas = loadmat("groot55.mat")
lons = datas['Long']
lats = datas['Lat']
deps = datas['Dep']
Times = datas['Time']
repeatdt= timedelta(days=30) #None
pset = ParticleSet.from_list(fieldset=fieldset, 
                             pclass=Properties,
                             lon = lons,
                             lat = lats,
                             depth = deps,
                             time = Times,
                             repeatdt=repeatdt)```
```pset.execute(SampleV + kernel + k_periodic + UpdateP,
             runtime = timedelta(days=330),
             dt=timedelta(hours=-1),
             recovery={ErrorCode.ErrorOutOfBounds: DeleteParticle},
             output_file=output_file)
pset.repeatdt=None#print(pset)
pset.execute(SampleV + kernel + k_periodic + UpdateP,
             runtime = timedelta(days=5145),
             dt=timedelta(hours=-1),
             recovery={ErrorCode.ErrorOutOfBounds: DeleteParticle},
             output_file=output_file)```

And the complete error message:

```
IndexError                                Traceback (most recent call last)
~/Clustertest/Groteset_lat55.py in <module>
    241              dt=timedelta(hours=-6),
    242              recovery={ErrorCode.ErrorOutOfBounds: DeleteParticle},
--> 243              output_file=output_file)
    244 pset.repeatdt=None
    245 #print(pset)

/home/jsayolespana/miniconda3/envs/py3_parcels_mpi/lib/python3.7/site-packages/parcels/particleset.py in execute(self, pyfunc, endtime, runtime, dt, moviedt, recovery, output_file, movie_background_field, verbose_progress, postIterationCallbacks, callbackdt)
    641                 time = max(next_prelease, next_input, next_output, next_movie, next_callback, endtime)
    642             self.kernel.execute(self, endtime=time, dt=dt, recovery=recovery, output_file=output_file,
--> 643                                 execute_once=execute_once)
    644             if abs(time-next_prelease) < tol:
    645                 pset_new = ParticleSet(fieldset=self.fieldset, time=time, lon=self.repeatlon,

/home/jsayolespana/miniconda3/envs/py3_parcels_mpi/lib/python3.7/site-packages/parcels/kernel.py in execute(self, pset, endtime, dt, recovery, output_file, execute_once)
    380
    381         # Remove all particles that signalled deletion
--> 382         remove_deleted(pset)
    383
    384         # Identify particles that threw errors

/home/jsayolespana/miniconda3/envs/py3_parcels_mpi/lib/python3.7/site-packages/parcels/kernel.py in remove_deleted(pset)
    360             if np.count_nonzero(indices) > 0 and output_file is not None:
    361                 output_file.write(pset, endtime, deleted_only=indices)
--> 362             pset.remove_booleanvector(indices)
    363
    364         if recovery is None:

/home/jsayolespana/miniconda3/envs/py3_parcels_mpi/lib/python3.7/site-packages/parcels/particleset.py in remove_booleanvector(self, indices)
    499         """Method to remove particles from the ParticleSet, based on an array of booleans"""
    500         for d in self.particle_data:
--> 501             self.particle_data[d] = self.particle_data[d][~indices, ...]
    502
    503     def execute(self, pyfunc=AdvectionRK4, endtime=None, runtime=None, dt=1.,

IndexError: boolean index did not match indexed array along dimension 0; dimension is 10120 but corresponding boolean dimension is 5060
```

**Comment by erikvansebille** [comment]
OK, the error seems to be with the deletion of Particles (see the error on line 382 of kernel.py

Which version of Parcels are you using? Because I though we had fixed this bug in #751

**Comment by NiekK19** [comment]
I am running version 2.1.5, so it would not be a bad idea at all to update it again. I will try that first.

**Comment by erikvansebille** [comment]
Hi @NiekK19; I'm closing this Issue right now. Feel free to reopen if you still are experiencing this Issue even after updating to the latest code on conda
