### ISSUE TITLE
Release different amount of particles

### ISSUE THREAD

**Issue by SaAlrabeei** [OceanParcels/parcels#885]
I know we can release N number of particles every m days. I am wondering if PARCELS support releasing N_i numbers of particles every M_j date. I.e, day1 release 50k, day2 release 20k particles,etc.

**Comment by erikvansebille** [comment]
The easiest way to accomplish this is to create the whole particle set at once but set different start times for each particle. See e.g. https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/tutorial_delaystart.ipynb#Assigning-each-particle-its-own-time
