### ISSUE TITLE
Crashes when adding a static field to a fieldset

### ISSUE THREAD

**Issue by Plagioclase** [OceanParcels/parcels#888]
I have written a simple kernel to sample a static 2D field from a netcdf. In short, when I add this field to the fieldset separately from the U/V fields, the kernel crashes during compilation. When I add it in the same go as the U/V fields, it works. I do not understand why this is!

I created my fieldset using `FieldSet.from_c_grid_dataset` and then added my static 2D field with `fieldset.coral_psi = Field.from_netcdf` after generating a grid object. Before compiling, Parcels (correctly) interpolates the field through `fieldset.coral_psi.eval(0,0,lat,lon)` (where `coral_psi` is the field name) but when I attempt to record this value in a kernel (regardless of whether it's an unused variable or a particle variable), Parcels crashes during compilation(?) with this error message:

`INFO: Compiled larvaAdvectionRK4Settle ==> /tmp/parcels-1000/xxx.so`
`double free or corruption (out)`
`Aborted (core dumped)`

When I compare my fieldset.coral_psi field object with, for example, the fieldset.U object (which presumably works since advection works fine), there are some differences, namely:

`igrid`: U = 0 / coral_psi = -1
`dimensions:` U = dict object with lon, lat, time / coral_psi = dict object with lon, lat 
`fieldset:` U = fieldset.FieldSet / coral_psi = NoneType
`field_chunksize`: U = 'auto' / coral_psi = NoneType
`data`: U = DeferredArray object / coral_psi = Array with dimensions (1, lat, lon)
`dataFiles`: U = Array with dimensions (time) / coral_psi = Array with dimensions (1)

Clearly something is working because prior to compilation, Parcels can correctly interpolate the field. But it doesn't like it once compiled.

I then tried creating the FieldSet in one go using `FieldSet.from_netcdf` and this does work. However, I am not happy with this because it means I have to have `time_extrapolation = True` when I would rather it wasn't on.

Here is the particle class and basic testing kernel I'm using:

```
class larva(JITParticle):
    # Include new variable to give the sink cell
    # Currently float for testing purposes
    sink_cell = Variable('sink_cell', dtype=np.float32, initial=0)

def Settle(particle, fieldset, time):
    # Currently is just supposed to interpolate coral_psi at particle location
    particle.sink_cell = fieldset.coral_psi[time, particle.depth, particle.lat, particle.lon]
```

This is the code that does NOT work:

```
# For the advective fields
filenames = {'U': {'lon': model_grid_file, 'lat': model_grid_file,
                   'time': model_output_file, 'data': model_output_file},
             'V': {'lon': model_grid_file, 'lat': model_grid_file,
                   'time': model_output_file, 'data': model_output_file}}

variables = {'U': 'u_surf',
             'V': 'v_surf'}

dimensions = {'U': {'lon': 'lon_psi', 'lat': 'lat_psi', 'time': 'time'},
              'V': {'lon': 'lon_psi', 'lat': 'lat_psi', 'time': 'time'}}

# Define the FieldSet
fieldset = FieldSet.from_c_grid_dataset(filenames, variables, dimensions,
                                        allow_time_extrapolation=False)

fieldset.coral_psi = Field.from_netcdf(model_grid_file,
                                  variable='coral_psi',
                                  dimensions={'lon': 'lon_psi',
                                              'lat': 'lat_psi'},
                                  allow_time_extrapolation=True)

pset = ParticleSet.from_list(fieldset=fieldset,
                             pclass=larva,
                             lon=pos[:, 0],
                             lat=pos[:, 1],
                             time=pos[:, 2])

kernels = pset.Kernel(AdvectionRK4) + Settle

output_file = pset.ParticleFile(name='particle_test.nc',
                                outputdt=timedelta(hours=1))

pset.execute(kernels,
             runtime=timedelta(days=sim_time),
             dt=timedelta(minutes=5),
             recovery={ErrorCode.ErrorOutOfBounds: DeleteParticle},
             output_file=output_file)
```
This is the code that DOES work (or at least runs):
```
filenames = {'U': {'lon': model_grid_file, 'lat': model_grid_file,
                   'time': model_output_file, 'data': model_output_file},
             'V': {'lon': model_grid_file, 'lat': model_grid_file,
                   'time': model_output_file, 'data': model_output_file},
             'coral_psi': {'lon': model_grid_file, 'lat': model_grid_file,
                           'data': model_grid_file}}

variables = {'U': 'u_surf',
             'V': 'v_surf',
             'coral_psi': 'coral_psi'}

dimensions = {'U': {'lon': 'lon_psi', 'lat': 'lat_psi', 'time': 'time'},
              'V': {'lon': 'lon_psi', 'lat': 'lat_psi', 'time': 'time'},
              'coral_psi': {'lon': 'lon_psi', 'lat': 'lat_psi'}}

# Define the FieldSet
fieldset = FieldSet.from_netcdf(filenames, variables, dimensions,
                                        allow_time_extrapolation=True)

# Define the ParticleSet
pset = ParticleSet.from_list(fieldset=fieldset,
                             pclass=larva,
                             lon=pos[:, 0],
                             lat=pos[:, 1],
                             time=pos[:, 2])

kernels = pset.Kernel(AdvectionRK4) + Settle

output_file = pset.ParticleFile(name='particle_test.nc',
                                outputdt=timedelta(hours=1))

pset.execute(kernels,
             runtime=timedelta(days=sim_time),
             dt=timedelta(minutes=5),
             recovery={ErrorCode.ErrorOutOfBounds: DeleteParticle},
             output_file=output_file)
output_file.export()
```

Could somebody explain why method 1 does not work and method 2 does? Furthermore, my concerns with method 2 are (1) how does it know that my velocities are on a c-grid and (2) is there a way to turn on time extrapolation for only one of the fields?

Thank you!

**Comment by erikvansebille** [comment]
Hi @Plagioclase. Looking through your code, it might be that the line below is wrong.
```python
fieldset.coral_psi = Field.from_netcdf(model_grid_file, ...)
``` 

You should add Fields as
```python
fieldset.add_field(Field.from_netcdf(model_grid_file, ...))
```

Let us know if it works with this code!

**Comment by Plagioclase** [comment]
Thanks Erik - I didn't realise that this was how you add fields. Works perfectly!

As an aside, I had two quick questions about particle variables. Firstly, is there a non-hacky way to set `to_write=False` for one of the default JITParticle variables (e.g. depth)? Secondly, is there by any chance a way to have `write_ondelete=True` for only certain variables (or alternatively have time-independent variables)? I have a variable where I am only interested in the final state, but still would like the time-varying lat/lon information. Not problem if not, but it would save some space.

**Comment by erikvansebille** [comment]
Glad this worked. We might want to make it more clear in the documentation that `fieldset.add_field()` is how you add `Fields`

As for your other questions, could you please open a new Issue? That way we can track them better and others can also find them. Not a good idea to mix Issues
