### ISSUE TITLE
recent hot fix of field interpolator broke field plotting 

### ISSUE THREAD

**Issue by nathanieltarshish** [OceanPARCELS/parcels#89]
The recent hot fix, designed to address the out of bounds problem #85, modified the interpolator1D() function in field.py.  In particular, the hot fix introduced some new conditionals. In the case that `(x is None and y is None) == True,` the interpolator1D()  attempts to return the variable, `val,` without first assigning it. I assume that the `val = f0 + (f1 - f0) * ((time - t0) / (t1 - t0))` line was just forgotten for this case. Without that line, plotting fields crashes (like e.g. in the ipython tutorial). I submitted a pull request #90 with this fix to the original hot fix.

**Comment by erikvansebille** [comment]
Thanks @nathanieltarshish, this is great! Just pulled into master in #90. Should be good now, thanks again for fixing this
