### ISSUE TITLE
ParticleFile options - removing default variables and time-independent variables?

### ISSUE THREAD

**Issue by Plagioclase** [OceanParcels/parcels#891]
I have two questions about ParticleFile options - firstly, is there a non-hacky way to set `to_write=False` for one of the default JITParticle variables (e.g. depth)? Secondly, is there by any chance a way to have `write_ondelete=True` for only certain variables (or alternatively have time-independent variables)? I have a variable where I am only interested in the final state, but still would like the time-varying lat/lon information. Not problem if not, but it would save some space.

**Comment by erikvansebille** [comment]
Re your first question: I've just created a PR (#892) that implements a method to set the write status of a Variable. Until that is merged into master, you can 'hack' your way around it with
```python
for v in pset.ptype.variables:
            if v.name == 'depth':
                v.to_write = False
```

Re your second question on setting `to_write=False` for only some Variables; that is not possible yet and not as easy to implement. We'll keep it on the backburner for a future feature

**Comment by Plagioclase** [comment]
Thank you Erik, I think this method would be a very useful addition. However, for some reason, that code snippet isn't working for me. It successfully changes `to_write = False` for the depth variable, but Parcels is still writing it to the output netcdf. The status of `to_write` is consistent for all of the other variables. I've tried doing this for other variables using this method and it isn't working either. Could it be because I'm using a custom particle class?

**Comment by erikvansebille** [comment]
That's because you also need to make a change in particlefile.py: https://github.com/OceanParcels/parcels/blob/particleset_set_variable_write_status/parcels/particlefile.py#L174
Otherwise, the file will still be created with a z variable

**Comment by Plagioclase** [comment]
Perfect, thank you!
