### ISSUE TITLE
How to set the color of the land in Agulhas animation by using plotting.py???

### ISSUE THREAD

**Issue by isabelyuyingwu** [OceanParcels/parcels#893]
Hi Erik,

Thanks for your amazing research work and share them in Jupyter Notebook, so that we can learn how to use ocean parcels package. Hereby, I have a question about how to set the land's color in your plotting.py file. 

In your ocean parcels homepage, there is a great animation of moving particles around Agulhas Current, and the land's color is brown (see figure 1). However, when I ran the codes on tutorial_Agulhasparticles.ipynb, I got the figure 2 as below: there are many small black dots in my land, which looks a little dizzying.

**Figure 1**
<img width="1012" alt="Screen Shot 2020-07-30 at 8 58 06 PM" src="https://user-images.githubusercontent.com/38671085/88929980-6f7f2480-d2ad-11ea-8206-7a9005cb6e80.png">
**Figure 2**
<img width="664" alt="Screen Shot 2020-07-30 at 9 19 37 PM" src="https://user-images.githubusercontent.com/38671085/88930000-76a63280-d2ad-11ea-9724-327f71b94a42.png">

I check the codes in plotting.py for a long time, however, unfortunately, I didn't figure it out. I guess it may be related to some codes about `def plotfield(land=True)` , `if land else....`,etc. I would really appreciate it if you can tell me which code to set the color of the land. Thank you very much! (^_^)

``

**Comment by isabelyuyingwu** [comment]
The black ones are our particles, which I can change the particleset's location to make them disappear. But you can see there are many small grey/black dots in land. Do you know how to delete them to set the color of land?? Thanks again!!

**Comment by isabelyuyingwu** [comment]
Here is the tutorial codes showing how to create Parcels in Agulhas animated gif, in the Jupyter Notebook.

`from parcels import FieldSet, ParticleSet, JITParticle, AdvectionRK4, ErrorCode
from datetime import timedelta
import numpy as np`
`filenames = "GlobCurrent_example_data/20*.nc"
variables = {'U': 'eastward_eulerian_current_velocity',
             'V': 'northward_eulerian_current_velocity'}
dimensions = {'lat': 'lat',
              'lon': 'lon',
              'time': 'time'}
fieldset = FieldSet.from_netcdf(filenames, variables, dimensions)`
`lons, lats = np.meshgrid(range(15, 35), range(-40, -30))
pset = ParticleSet(fieldset=fieldset, pclass=JITParticle, lon=lons, lat=lats)`
`def DeleteParticle(particle, fieldset, time):
    particle.delete()`
`for cnt in range(3):
    # First plot the particles
    pset.show(savefile='particles'+str(cnt).zfill(2), field='vector', land=True, vmax=2.0)

    # Then advect the particles for 6 hours
    pset.execute(AdvectionRK4,
                 runtime=timedelta(hours=6),  # runtime controls the interval of the plots
                 dt=timedelta(minutes=5),
                 recovery={ErrorCode.ErrorOutOfBounds: DeleteParticle})  # the recovery kernel`

**Comment by erikvansebille** [comment]
Dear @isabelyuyingwu. Thanks for your interest in Parcels. Note however, that the plotting routines in Parcels are _very_ rudimentary, and really only meant for a quick visualisation of the particles. We also don't really support/develop the plotting, as we do the other codes. I'd strongly recommend that you write your own code for plotting particles, based on the output netcdf file
 
To answer your question about the small grey dots, these are probably the zero-length vectors of the flow, which is zero on land. If you want these to disappear, you could change these to NaN in the plotting function. But again, better to write your own plotting code ;-)

Good luck with running Parcels!
