### ISSUE TITLE
Warning: Deleting particle because of bug in #749 and #737

### ISSUE THREAD

**Issue by Plagioclase** [OceanParcels/parcels#896]
I have a simple kernel that has a chance to delete a particle if it's within a sink cell, which appears to work fine but on the first run, it returns the following warning when the first particle is deleted:

`WARNING: Deleting particle because of bug in #749 and #737`

Parcels continues to run and nothing looks suspicious about the resulting fields, so I'm not sure how big of a problem (if at all) this is. This is my kernel, but the problematic step is `particle.delete()`:

```
def Settle(particle, fieldset, time):
    # Kernel allows particles to settle when over a reef cell.
    # Competency age (s)
    t_comp = 86400.

    # Frequency to check settling (s)
    settle_freq = 1800.

    # Chance to settle if over reef
    settle_chance = 0.1

    # Track particle age
    particle.age += particle.dt

    # Check for reef cells if particle is competent
    if particle.age > t_comp and math.fmod(particle.age, settle_freq) == 0:
        settle_check = random.uniform(0., 1.)
        nearest_cell = fieldset.reef_num[time,
                                         particle.depth,
                                         particle.lat,
                                         particle.lon]

        # If nearest cell is a reef cell, record sink cell, age, and delete
        if nearest_cell > 0 and settle_check < settle_chance:
            particle.sink_cell = nearest_cell
            particle.sink_age = particle.age
            particle.delete()
```
However, `particle.delete()` does not trigger an error when I use it to handle `ErrorCode.ErrorOutOfBounds`:

```
def DeleteParticle(particle, fieldset, time):
    #  Recovery kernel to delete a particle if it leaves the domain
    particle.delete()

pset.execute(kernels,
             runtime=timedelta(days=sim_time),
             dt=timedelta(minutes=5),
             recovery={ErrorCode.ErrorOutOfBounds: DeleteParticle},
             output_file=output_file)
```

Is there a reason why `particle.delete()` is triggering this odd warning within a kernel (but not in a recovery kernel)?

**Comment by erikvansebille** [comment]
Hi @Plagioclase. I wouldn't worry too much about this message, as long as it doesn't appear too often. It may be that a few of your particles are deleted, as the warning message says because of a bug in #749 and #737. 
It happens when the ParticleState at the end of the Kernel is not in the `recovery` dictionary; we've seen it most often occur when the Particle got a `StatusCode.Error` (=5).
