### ISSUE TITLE
Problems with netcdf output file

### ISSUE THREAD

**Issue by giospud** [OceanParcels/parcels#899]
I am running a simulation that is lasting different days and I get an error trying to save the netcdf output file:

Exception ignored in: <function ParticleFile.__del__ at 0x2baa7e34ba70>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/parcels/particlefile.py", line 196, in __del__
  File "/opt/anaconda3/lib/python3.7/site-packages/parcels/particlefile.py", line 201, in close
  File "/opt/anaconda3/lib/python3.7/site-packages/parcels/particlefile.py", line 365, in export
  File "/opt/anaconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 428, in load
NameError: name 'open' is not defined

and this are the settings for the run:
####################################################################################################
ndays=1 # length of the simulation
dtout=1 # output for particles' tracking in hours
outfile=pset.ParticleFile(name="pippo.nc", outputdt=timedelta(hours=dtout))
dtplot=relativedelta(hours=dtout)
t1=tini
tend=tini+relativedelta(hours=ndays*24)
dmn={'N':-32, 'S':-37, 'E':153.0, 'W':149.8}
isv=0
nmf='particles_'+str(isv).zfill(4)
pset.show(field='vector', vmax=3.0, domain=dmn, land=True, savefile=nmf)
isv+=1
while t1<tend:
    print(' ')
    print(t1)
    pset.execute(AdvectionRK4,runtime=timedelta(hours=1),dt=timedelta(minutes=5),output_file=outfile,recovery={ErrorCode.ErrorOutOfBounds: DeleteParticle})
    nmf='particles_'+str(isv).zfill(4)
    pset.show(field='vector', vmax=3.0, show_time=t1, domain=dmn, land=True, savefile=nmf)
    isv+=1
    t1=t1+dtplot

Any idea why it crashes trying to save the netcdf file?

**Comment by Plagioclase** [comment]
I've been getting the same error actually but I've been ignoring it because it seems to be writing to netcdf correctly regardless. I assumed it was related to another warning I've been getting (issue #896) which @erikvansebille said wasn't an issue.

**Comment by erikvansebille** [comment]
Thanks for reporting @giospud. This is a bug that is really hard to fix, but it's harmless. It happens when the ParticleFile is deleted on closing of the python run, but it has been closed/deleted already (so it can't be deleted twice). See e.g. the discussion at https://github.com/OceanParcels/parcels/pull/794#pullrequestreview-390593236

If the netcdf file comes out ok, you can just ignore this error

**Comment by giospud** [comment]
the problem is that the netcdf it is not created so at the end of the run I do not get any nc file

**Comment by erikvansebille** [comment]
Oh I see. What if you add an `outfile.close()` at the end of your script?

**Comment by giospud** [comment]
It is working! thanks a lot for your help!
