### ISSUE TITLE
Is there any way to give particles mass and include inertia calculations?

### ISSUE THREAD

**Issue by MariusWiggert** [OceanParcels/parcels#902]
I'm working on simulating how a floating platform with about 1 ton of mass and a certain depth would float through the ocean.
Hence, I'm wondering if in the existing code there's any possibility to give particles a mass and include inertia calculations for their trajectory?

If not, any ideas where best to implement that functionality? Or maybe someone is already working on it?

**Comment by erikvansebille** [comment]
Hi @MariusWiggert. You would have to provide a [custom Kernel](https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/parcels_tutorial.ipynb#Sampling-a-Field-with-Particles) to simulate this type of behaviour. 

We don't have this one yet, but if you have the equations that you want to simulate, then it shouldn't be too hard to create one yourself?
