### ISSUE TITLE
Example for start_field in ParticleSet.from_field

### ISSUE THREAD

**Issue by giospud** [OceanParcels/parcels#903]
Sorry for the dumb question but there is any example on how to define start_field in the ParticleSet.from_field method? I do not understand how to define it in order to get a random initial seeding

**Comment by erikvansebille** [comment]
There's not really a fully fleshed-out example, but you can see how it works in the unit test at https://github.com/OceanParcels/parcels/blob/master/tests/test_particle_sets.py#L99-L104
