### ISSUE TITLE
Multiply fieldset.U and fieldset.V by a constant

### ISSUE THREAD

**Issue by giospud** [OceanParcels/parcels#907]
Another dumb question: I would like to multiply U and V of a fieldset by a constant. How could I do this operation? Through the definition of a kernel? There is any example available?

Giovanni

**Comment by erikvansebille** [comment]
Each Field has a `set_scaling_factor()` method that you can use to multiply by a constant, see http://oceanparcels.org/gh-pages/html/#parcels.field.Field.set_scaling_factor
