### ISSUE TITLE
Using nested fields with NEMO

### ISSUE THREAD

**Issue by HugoDENISFR** [OceanParcels/parcels#909]
Hello, 

I have 2 fields of different resolution and area coverage that I would like to use in Ocean Parcels, like I saw it was possible on the tutorial available on your website.  I can't manage to get it work, because the tutorial differs slightly from the way I state my NEMO fields. I have been using single NEMO fields for a while and everything works fine, it is just a matter of correct syntax I think. 

I used to set up my configuration as follows : 

`filenames = {'U': {'lon': grid_file, 'lat': grid_file, 'depth': list_data_file, 'data': list_data_file}, 
             'V': {'lon': grid_file, 'lat': grid_file, 'depth': list_data_file, 'data': list_data_file},
             'W': {'lon': grid_file, 'lat': grid_file, 'depth': list_data_file, 'data': list_data_file},
             'Zeta': {'lon': grid_file, 'lat': grid_file, 'data': list_data_file},
             'Bath':{'lon': grid_file, 'lat': grid_file, 'data': list_data_file}}`

`variables = {'U': 'u',
             'V': 'v',
             'W': 'w',
             'Zeta': 'zeta',
             'Bath' : 'h'}`

`dimensions = {'U': {'lon': 'lon_psi', 'lat': 'lat_psi', 'depth': 'sigma_psi', 'time': 'time'},
              'V': {'lon': 'lon_psi', 'lat': 'lat_psi', 'depth': 'sigma_psi', 'time': 'time'},
              'W': {'lon': 'lon_psi', 'lat': 'lat_psi', 'depth': 'sigma_psi', 'time': 'time'},
              'Zeta': {'lon': 'lon_psi', 'lat': 'lat_psi', 'time': 'time'},
              'Bath' : {'lon': 'lon_psi', 'lat': 'lat_psi'}}`
`fieldset = FieldSet.from_c_grid_dataset(filenames, variables, dimensions,allow_time_extrapolation=True)` 

Now I want to do it the same way, the only difference is that my objects `grid_file` and `data_file` or not single strings anymore but a list of 2 strings e.g `data_file=['data_file_1.nc','data_file_2.nc']` . I have tried to use the NestedField function with this but I can't find how to use it properly with fields defined like before, with dictionnaries.... 

Thanks for your help !

**Comment by erikvansebille** [comment]
Hi @HugoDENISFR. I'm assuming you're referring to the [NestedFields tutorial](https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/tutorial_NestedFields.ipynb)?

As detailed there, it works better if you _first_ create the FieldSets for the two nests separately, and only then combine them in a `NestedField`
