### ISSUE TITLE
issues running AdvectionRK4 with JIT particles

### ISSUE THREAD

**Issue by nathanieltarshish** [OceanPARCELS/parcels#91]
In the ipython tutorial, using `JITParticles` with  `AdvectionRK4`  works fine for me with the first NEMO formatted example. At the end of the tutorial, I tried changing the netCDF example's pset from `Particle` datatype to `JITParticle` datatype.  If I try to execute the `AdvectionRK4` method now, the kernel stalls after printing the `Compiled JITParticleAdvectionRK4 ==> ...` output.  I converted the notebook to a python file and repeated the test. My kernel stalled again after printing the compiled line. Any thoughts on what might be going on here? Is this particular to my local setup/installation or perhaps already known to be an issue? Thanks in advance for your help.

**Comment by erikvansebille** [comment]
Yes, this is a known bug indeed. See the comment on PR #83. Unfortunately, this bug isn't fixed yet; it's more difficult than we initially thought. @mlange05 is looking into it

**Comment by nathanieltarshish** [comment]
I see, thanks for pointing that out. I will close this issue because of the redundancy.
