### ISSUE TITLE
netcdf not written untill ipython closes

### ISSUE THREAD

**Issue by JamiePringle** [OceanParcels/parcels#920]
Dear all -- 

I have stumbled into a minor but mysterious issue. When I run ocean parcels, version 2.0.2, with 

    pset.execute(AdvectionRK4,
                 runtime=timedelta(days=durationDays+numDaysRelease),dt=timedelta(minutes=1*60.0),
                 output_file=outFile,verbose_progress=True,
                 recovery={ErrorCode.ErrorOutOfBounds: DeleteParticle})

And it completes successfully, when I look for the output file it is not there, but the out-* directory is present. When I quit ipython, the out-* directory has gone away and the netcdf file is where it should be. This is a bit annoying, because I would like to plot the results as I go on. 

Needless to say, this is easy to work around, but it is a bit mysterious. My full code is attached (as a text file, just to make github happy).

[pointRelease_several_years_3D.txt](https://github.com/OceanParcels/parcels/files/5219429/pointRelease_several_years_3D.txt)

Jamie

**Comment by reint-fischer** [comment]
Hi Jamie,

Are you using v2.0.2 or v2.2.0? As of v2.1.0 the function [`particlefile.close`](https://oceanparcels.org/gh-pages/html/#parcels.particlefile.ParticleFile.close) allows you to export the .npy files from the out-* directory into the netcdf file and remove the out-* directory. Does this answer your question?

Reint

**Comment by JamiePringle** [comment]
Dear Reint -- 

    My bad. I am using 2.2.0, but had a print out of earlier documentation. I hate it when I make an RTFM error, and thank you for your time. 

Jamie
