### ISSUE TITLE
NEMO data access

### ISSUE THREAD

**Issue by cbreasley** [OceanParcels/parcels#924]
I have a windows operating system and don't have access to Linux or a super computer. 
I was wondering if there was an online database or somewhere I could access some NEMO data to be used in my dissertation project. I am looking for 3D data as I am going to be modelling particle release from the sea floor from hydrothermal vents. 

thanks!

**Comment by reint-fischer** [comment]
Hi @cbreasley,

At https://marine.copernicus.eu/ there are many different ocean products available including reanalyses using NEMO data. Note: the velocity data from the NEMO C-Grid is interpolated onto an A-grid for these products (see [here](https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/documentation_indexing.ipynb) for more information)

Cheers,

Reint
