### ISSUE TITLE
custom kernel

### ISSUE THREAD

**Issue by philippemiron** [OceanParcels/parcels#962]
Hi,

I need some help to create a custom kernel.

I have `N ~ 10` known locations `(lon_i, lat_i)` and my problem is I need to find which one is the closest to the `(particle.lon, particle.lat)` at each time step. Once I find the closest one to the particle, I can calculate the `(u', v')` with simple operations.

Anyone has an idea how I could perform this operation inside a custom kernel ?

**Comment by erikvansebille** [comment]
Thanks for reporting, @philippemiron! With @RoelBrouwer and @qubixes, we are working on a way to code particle-particle interactions in the Kernel, which would allow you to do this. It'll probably take a few more months before that is implemented, but please stay tuned for that. 

In the meantime, not that you can use `while`-loops in the kernel (see the [Kernel tutorial here](https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/tutorial_parcels_structure.ipynb#3.-Kernel-execution)), so you could loop over the `N=10` points and calculate the minimum distance each time. The problem may be that, as far as I'm aware, you can't use arrays in Kernels, so you may need to hardcode the points in a separate variable each?

In any way, hope we have particle-particle interaction soon, and then this will be much easier!

**Comment by philippemiron** [comment]
Hi,

I thought about a while loop but without array I'm not sure how I can do this... I ended up doing `N-1` if calls and hardcoded everything. I'll keep an eye out for the future release but in the meanwhile I think I might be able to do what I had in mind.

Thanks,
