### ISSUE TITLE
Index search on skewed grid

### ISSUE THREAD

**Issue by angus-g** [OceanParcels/parcels#968]
We're working with a somewhat skewed grid. For example, the x-coordinates at the x=0 index look like
```
array([113.466435, 113.469376, 113.472318, ..., 122.49621 , 122.499151,
       122.502092])
```
and similarly the y-coordinates at y=0:
```
array([  7.162437,   7.159447,   7.156458, ..., -12.206088, -12.209078,
       -12.212068])
```

The assumption is made that a rectangle bounds all valid points, and this is used e.g. in determining whether an index-search is out of bounds. However, with this skewed grid, a point can be valid according to the bounding rectangle, e.g. (114, -10), yet not lie on the actual grid. For me, this often leads to a segfault due to attempting to access a data value past the end of the array.

**Comment by erikvansebille** [comment]
Hi @angus-g, I see that this Issue has not been picked up in a while. Is it still a problem you're encountering? Have you found a solution/workaround? Something we can help with?
