### ISSUE TITLE
Incorporation of sgrid conventions

### ISSUE THREAD

**Issue by hetland** [OceanParcels/parcels#971]
I would like to propose that parcels accept Arakawa C-grids that follow the [sgrid conventions](https://sgrid.github.io/sgrid/). Currently, curvilinear grids in parcels follow a convention that is used by NEMO. Unfortunately, this is not a common convention in other C-grid based models (ROMS and MITGCM, in particular). This would allow a wider variety of models to be easily used, without cumbersome pre-processing.

**Comment by erikvansebille** [comment]
Hi @hetland, thanks for the question. In fact, from the latest [v2.2.1](https://github.com/OceanParcels/parcels/releases/tag/v2.2.1), Parcels supports MITgcm grid indexing, using `FieldSet.from_mitgcm()`, or by setting `Field.gridindexingtype='mitgcm'`, see also #897.

Is that what you were after?

**Comment by hetland** [comment]
I did not know about the support for MITgcm indexing. This will be very useful.

This specifically is the part that I was after, but generally I still think considering s-grid support would make it so that a wider range of models could be supported. S-grid conventions would let parcels identify the indexing convention from the Dataset attributes. It would also allow for any type of model output. Basically, the node and face configuration can be specified per dimension, for so that arbitrary (though still structured) grids can be used. This removes the requirement to specify the particular grid configuration for each specific model output type.

**Comment by erikvansebille** [comment]
Interesting idea, @hetland! But how would you identify the indexing convention from the Dataset attributes? Is there some CF-convention for indexing that we can query from the attributes? Could you give an example?

**Comment by hetland** [comment]
The S-grid conventions, linked above, describe how this would work: [https://sgrid.github.io/sgrid/](https://sgrid.github.io/sgrid/)

A simple example on that page looks like this:

```
dimensions:
    time = UNLIMITED ;
    inode = 10 ;
    jnode = 20 ;
    icell = 9 ;
    jcell = 19 ;

variables:
    char time(time) ;
        time:standard_name = "time" ;
        time:long_name = "time" ;
        time:units = "seconds since 2015-01-01 00:00:00" ;
    float u(time, jcell, inode) ;
        u:description = "x-velocity" ;
        u:units = "m s-1" ;
        u:grid = "MyGrid" ;
        u:location = "edge1" ;
    float v(time, jnode, icell) ;
        u:description = "y-velocity" ;
        u:units = "m s-1" ;
        u:grid = "MyGrid" ;
        u:location = "edge2" ;
    float c(time, jcell, icell) ;
        c:description = "some concentration" ;
        c:grid = "MyGrid" ;
        c:location = "face" ;
    float node_lat(jnode, inode) ;
        node_lat:standard_name = "latitude" ;
        node_lat:units = "degree_north" ;
    float node_lon(jnode, inode) ;
        node_lon:standard_name = "longitude" ;
        node_lon:units = "degree_east" ;

    int MyGrid ;
        grid:cf_role = grid_topology
        grid:topology_dimension = 2 ;
        grid:node_dimensions = "inode jnode" ;
        grid:face_dimensions = "icell: inode (padding: none) jcell: jnode (padding: none)" ;
        grid:node_coordinates = "node_lon node_lat" ;
```
