### ISSUE TITLE
Use external variable in kernel: initial volume transport

### ISSUE THREAD

**Issue by mathildejutras** [OceanParcels/parcels#977]
Hi,
I am trying to write a kernel to compute the initial volume transport associated with each particle. Perhaps there is already a reference on how to do this somewhere?

I am having trouble as, in the kernel, I would need the area or the different information on the vertical and horizontal spacing. However, this information is not included in the parcels.particle or in the parcels.fieldset "variables".

To be more specific, let's say I have a particle set defined in a square, based on a list of lat/lon/depth as follows:
```
pset = ParticleSet.from_list(fielset=fset, pclass=myclass, lat=Lat, lon=Lon, depth=Depth)
```
, with an area associated with each particle, how can I access this `area` variable in a kernel that would look like this:
```
def VolumeTransport(particle, fieldset, time):

    uv=fieldset.U[0,particle.depth,particle.lat,particle.lon]
    vv=fieldset.V[0,particle.depth,particle.lat,particle.lon]

    particle.volume = np.sqrt(uv**2+vv**2) * area
 ```
Note that the variable would actually not need to be updated at every time step, as I only want the initial volume transport.

Thank you.

**Comment by erikvansebille** [comment]
Hi @mathildejutras, thanks for posing this question. I know that @ignasivalles has created code in the past for calculating initial volume transports of particles, perhaps he can chip in?

Note that, if you know how to calculate the area (on a per particle base), you could always store it in the `myclass` class, as a `Variable`?

**Comment by mathildejutras** [comment]
Hi, thank you, I'll look forward for @ignasivalles' input.

If I define `area` in a `Variable`, I still would not know how to access the depth/spacing variables required to calculate the area.
I calculate the particle position from a function that looks like this:
```
def depthSquare(start, end, steps_hor, steps_vert):
    depthList = np.arange(0,2000,steps_vert)
    lonList = np.linspace(start[1],end[1],steps_hor)
    latList = np.linspace(start[0],end[0],steps_hor)

    Lon = [] ; Lat = [] ; Depth = [] ; area = []
    for i in range(0,len(lonList)):
        c=0
        for d in depthList:
            Depth.append(d)
            Lat.append(latList[i]))
            Lon.append(lonList[i]))
            if c==0 :
                dz = depthList[c] + (depthList[c+1]-depthList[c])/2
            elif c==len(depthList)-1 :
                dz = depthList[c]-depthList[c-1] + (depthList[c]-depthList[c-1])/2
            else :
                dz = (depthList[c+1]-depthList[c])/2 + (depthList[c]-depthList[c-1])/2

            area.append(1./steps_hor*111*1000 * dz)
```
So I would be unsure how to assign either `area` or `depthList`, `lonList` and `latList` to a `Variable` in `myclass`, and then re-obtain which value is associated with which particle.

Thank you.

**Comment by reint-fischer** [comment]
Hi Mathilde,

If you define your ParticleClass as something like this:
```
from parcels import Variable

class myclass(JITParticle):
    area_var = Variable('area_var', initial=0.)
```
Then you can simply initialise the area the same way you do for `Depth`, `Lat` and `Lon`:
```
pset = ParticleSet.from_list(fielset=fset, pclass=myclass, lat=Lat, lon=Lon, depth=Depth, area_var=area)
```

**Comment by mathildejutras** [comment]
That works, thank you very much!

**Comment by ignasivalles** [comment]
Hi @mathildejutras looks like your question has been solved quickly. I've been away from Parcels for a while but I did some work on that. Just to tell you that to compute the mass transport I use the velocity vector perpendicular to the release section, not the magnitude. I think physically is more coherent.

By the way @erikvansebille maybe in the future we can do some piece of code for Parcels that solves mass transport calculation, stream functions and so on, or there is something already done?

**Comment by erikvansebille** [comment]
Thanks for chipping in, @ignasivalles. Yes, it would be great to put some of your code for calculating transports on github. We created a separate repository at https://github.com/OceanParcels/parcels_contributions (still fairly empty), where we plan to be hosting these types of codes. 

If you want, feel free to fork and create a pull request with your code on that repository; I'm sure a lot of users would find it very useful!

**Comment by mathildejutras** [comment]
Maybe another question... Is there a way to use a variable in a kernel without storing it in the Particle class? 
Here, to compute the transport perpendicular to the section, I will need the angle of the section which is just a constant. So it's kind of a waste of space to save it as a variable with every particle.

**Comment by reint-fischer** [comment]
If it is constant across all particles, you can add it to the fieldset using [`add_constant`](https://oceanparcels.org/gh-pages/html/#parcels.fieldset.FieldSet.add_constant). After defining the fieldset you can use:
```
fieldset.add_constant('angle', value)
```
Then in your kernel you can use `fieldset.angle`
