### ISSUE TITLE
Advecting backwards in time 

### ISSUE THREAD

**Issue by BWBlack** [OceanParcels/parcels#986]
Hello everyone,

I have just started using parcels, and I'm currently experimenting with advecting a set of particles backwards in time within an OGCM output. 

I understand that you can simply set the dt to a negative timedelta() object in pset.execute(), but that seems to simply work back from the first file in a dataset ie: of [File_time_start-date.nc ... File_time_end-date.nc], parcels will just take File_time_1.nc and extrapolate back (allow_time_extrapolation=True in my case).

What I would like to do is advect particles from some location starting at File_time_end-date.nc, and compute back towards File_time_start-date.nc (newest to oldest). I have tried just reversing the file order, but that returns an error to order the files sequentially.

I have looked through the tutorials but may have missed something, so apologies if this is fairly trivial! Would anyone be know of a method? 

Thanks very much,
Ben.

**Comment by reint-fischer** [comment]
Hi Ben,

If you do not specify the start-time of particles when creating your `ParticleSet` and your dt is negative, the default releasetime should be at the upper end of your fieldset, i.e. at File_time_end-date.nc: https://github.com/OceanParcels/parcels/blob/master/parcels/particlesets/baseparticleset.py#L376-L379

So what you are looking for should be the default behaviour. If this does not work, you can specify the releasetime yourself:
```
releasetime = datetime.datetime(<date of File_time_end-date.nc>)
pset = ParticleSet(fieldset=fieldset, pclass=JITParticle, lon=lons, lat=lats, time=releasetime)
```
If the problem persists, could you maybe show how you have initialised the `ParticleSet` and what parameters you use in `pset.execute()`?

Hope this helps

**Comment by BWBlack** [comment]
Thanks very much! That's sorted it, I was specifying an additional time for each particle release without stating from what date.
Cheers.
