### ISSUE TITLE
X-axis values of plotTrajectoriesFile('DelayParticle_time.nc', mode='movie2d_notebook')

### ISSUE THREAD

**Issue by prakruthireddy** [OceanParcels/parcels#992]
Hello, 

I am trying to work through the tutorial on how to delay the start of particle advection (https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/tutorial_delaystart.ipynb). When I run plotTrajectoriesFile('DelayParticle_time.nc', mode='movie2d_notebook') I get a graph with x-axis limits of [-150, 150] instead of the correct x-axis limits of [10000, 80000]. I don't see any particles on the graph due to the skewed x-axis values. 

![image](https://user-images.githubusercontent.com/52090459/106371174-42303380-632f-11eb-9705-cafa93f13a53.png)

Do you have any ideas on how I can fix this?

Thank you!

**Comment by reint-fischer** [comment]
Hi @prakruthireddy,

Nice that you are working through the tutorials! I am not sure exactly what goes wrong here.

Parcels development is moving away from supporting included plotting functions, so some of these might become deprecated. Plotting is an important step in the analysis and in quality control, but we recommend users to write their own code for this: to maximise flexibility and allow Parcels to focus on the simulations itself. To help you get started to plot and animate your Parcels output, we have [this tutorial](https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/tutorial_output.ipynb).

I hope this helps,

**Comment by prakruthireddy** [comment]
Thank you so much for taking a look at the plot and suggesting a tutorial! I will attempt to write my own plots.
